import type { Personagem } from "@/lib/tipos";

/** Fichas de conceitos. `pistas` vão da mais difícil para a mais fácil; `curiosidades` não citam o nome. */
export const fichas: Personagem[] = [
  {
    id: "polos-inseparaveis",
    nome: "Polos inseparáveis",
    lugar: "Ímãs · propriedade fundamental",
    quem: "Todo ímã tem um polo norte e um polo sul, e não há como ficar com um só. Ao partir um ímã, cada pedaço volta a ter os dois polos, porque o magnetismo vem de ímãs elementares microscópicos que o corte não separa.",
    gancho: "Ímã é como uma moeda: você pode cortá-la em quantos pedaços quiser, e cada pedaço continua tendo cara e coroa.",
    palavras: ["Monopolo não existe", "Domínios magnéticos", "Linhas fechadas", "Corte"],
    pistas: [
      "Em linguagem de campo, sou a afirmação de que as linhas de campo magnético não têm começo nem fim.",
      "Sou a razão de não existir, no magnetismo, nada parecido com uma carga elétrica isolada.",
      "Por minha causa, serrar uma barra imantada nunca resolve o problema de quem quer um polo só.",
      "Quebre um ímã ao meio e você verá o que eu afirmo: dois ímãs completos.",
    ],
    curiosidades: [
      "Em 1931, Paul Dirac mostrou que a teoria quântica admitiria uma partícula que violasse esta propriedade; ela nunca foi observada.",
      "Experimentos procuram há décadas, em raios cósmicos e em aceleradores, uma exceção a esta regra.",
      "Mesmo reduzindo um ímã a pó, cada grão continua obedecendo a ela.",
    ],
    fato: "Partir um ímã nunca isola um polo",
  },
  {
    id: "linhas-de-campo",
    nome: "Linhas de campo",
    lugar: "Campo magnético · representação",
    quem: "Curvas imaginárias que representam o campo magnético. Em cada ponto, o vetor campo é tangente a elas. Fora do ímã vão do polo norte para o polo sul; dentro, do sul para o norte. São fechadas, nunca se cruzam e ficam mais juntas onde o campo é mais intenso.",
    gancho: "Fora do ímã: Nascem no Norte, Somem no Sul. Onde estão apertadas, o campo é forte; onde estão espalhadas, é fraco.",
    palavras: ["Tangente", "Do N para o S", "Não se cruzam", "Densidade"],
    pistas: [
      "A minha densidade em uma região informa a intensidade do campo ali.",
      "Duas de nós nunca se cruzam, porque em cada ponto o campo tem uma única direção.",
      "Limalha de ferro espalhada sobre um papel, com um ímã embaixo, desenha o nosso formato.",
      "Somos as curvas que saem do polo norte e entram no polo sul de um ímã.",
    ],
    curiosidades: [
      "Foram imaginadas por Michael Faraday, que quase não usava matemática e preferia raciocinar com figuras.",
      "Faraday as chamava de \"linhas de força\".",
      "Em torno de um fio reto com corrente, têm a forma de circunferências.",
      "Em um campo uniforme, são retas paralelas e igualmente espaçadas.",
    ],
    fato: "Saem do norte, entram no sul e nunca se cruzam",
  },
  {
    id: "bussola",
    nome: "Bússola",
    lugar: "Campo da Terra · instrumento",
    quem: "Agulha imantada, livre para girar, que se alinha com o campo magnético local. Seu polo norte aponta aproximadamente para o norte geográfico, onde há um polo sul magnético. O desvio em relação ao norte verdadeiro é a declinação magnética.",
    gancho: "O norte da agulha procura o norte do mapa porque lá mora um polo SUL magnético: opostos se atraem.",
    palavras: ["Agulha imantada", "Declinação", "Norte magnético", "Navegação"],
    pistas: [
      "Sirvo de detector: é a mim que se recorre para definir o sentido do vetor campo magnético em um ponto.",
      "Fui a testemunha da experiência de 1820 que uniu eletricidade e magnetismo.",
      "Quem me usa para navegar precisa corrigir a declinação magnética do lugar.",
      "Tenho uma agulha imantada que aponta para o norte.",
    ],
    curiosidades: [
      "Já era usada na China há cerca de mil anos, antes de chegar à Europa.",
      "As primeiras versões eram uma lasca de magnetita flutuando em água.",
      "Perto dos polos magnéticos torna-se inútil, pois o campo fica quase vertical.",
      "Em 1600, William Gilbert usou-a sobre uma esfera imantada para defender que a Terra é um grande ímã.",
    ],
    fato: "Agulha imantada que se alinha ao campo da Terra",
  },
  {
    id: "ponto-de-curie",
    nome: "Ponto de Curie",
    lugar: "Ímãs · temperatura crítica",
    quem: "Temperatura acima da qual um material ferromagnético perde a imantação, porque a agitação térmica desfaz o alinhamento dos domínios magnéticos. Para o ferro, vale cerca de 770 °C.",
    gancho: "Esquentou demais, a turma dos domínios se dispersa: acima do ponto de Curie não há ímã que resista.",
    palavras: ["770 °C no ferro", "Domínios", "Desmagnetização", "Geodínamo"],
    pistas: [
      "Sou o argumento que derruba a ideia de um ímã permanente no centro da Terra.",
      "Rochas vulcânicas guardam a direção do campo terrestre ao esfriar abaixo de mim.",
      "Para o ferro, valho aproximadamente 770 °C.",
      "Sou a temperatura acima da qual um ímã deixa de ser ímã.",
    ],
    curiosidades: [
      "Leva o nome do físico francês que estudou o magnetismo e a temperatura em sua tese de doutorado, em 1895.",
      "Algumas panelas elétricas de arroz desligam sozinhas graças a este efeito, usando um ímã junto ao fundo.",
      "Para o níquel, fica em torno de 360 °C; para o cobalto, passa de 1100 °C.",
    ],
    fato: "Temperatura em que o ímã perde a imantação",
  },
  {
    id: "oersted",
    nome: "Experiência de Oersted",
    lugar: "Eletromagnetismo · 1820",
    quem: "Observação de que a agulha de uma bússola se desvia quando passa corrente por um fio próximo. Mostrou que cargas elétricas em movimento criam campo magnético, unindo eletricidade e magnetismo.",
    gancho: "Oersted Olhou a agulha: ligou a corrente, ela girou; desligou, ela voltou. Corrente cria campo.",
    palavras: ["1820", "Fio e bússola", "Corrente cria campo", "Eletromagnetismo"],
    pistas: [
      "Para que eu funcione bem, o fio deve ficar paralelo à agulha antes de o circuito ser fechado.",
      "Em mim, inverter a corrente inverte o lado para o qual a agulha se desvia.",
      "Fui realizada em 1820 e acabei com a separação entre eletricidade e magnetismo.",
      "Sou a experiência em que um fio com corrente desvia a agulha de uma bússola.",
    ],
    curiosidades: [
      "Conta-se que a observação aconteceu durante uma aula, em Copenhague.",
      "O resultado foi divulgado em um texto de poucas páginas, escrito em latim.",
      "Poucas semanas depois da notícia, Ampère já havia descoberto a força entre dois fios com corrente.",
      "O autor era dinamarquês e professor de física.",
    ],
    fato: "Mostrou que a corrente elétrica desvia a bússola",
  },
  {
    id: "mao-direita",
    nome: "Regra da mão direita",
    lugar: "Campo das correntes · sentido",
    quem: "Regra prática para achar o sentido do campo magnético criado por uma corrente. No fio reto, o polegar aponta no sentido da corrente e os outros dedos, ao envolver o fio, dão o sentido das linhas de campo. Na espira e no solenoide, os dedos seguem a corrente e o polegar indica o campo no interior.",
    gancho: "Segure o fio como quem segura um corrimão: o polegar vai com a corrente, o abraço dos dedos é o campo.",
    palavras: ["Polegar na corrente", "Dedos envolventes", "Fio, espira e solenoide", "Sentido do campo"],
    pistas: [
      "Aplicada a uma espira, mostro que a face onde a corrente gira no sentido anti-horário é o polo norte.",
      "Com corrente saindo do papel, digo que o campo circula no sentido anti-horário.",
      "Uso o polegar para a corrente e os outros dedos para o campo.",
      "Sou a regra que dá o sentido do campo magnético em torno de um fio.",
    ],
    curiosidades: [
      "Também é conhecida como regra do saca-rolhas: o avanço do saca-rolhas é a corrente e o giro é o campo.",
      "É atribuída a Maxwell e a Ampère, em versões um pouco diferentes.",
      "Não informa a intensidade do campo, apenas a direção e o sentido.",
    ],
    fato: "Polegar na corrente, dedos no sentido do campo",
  },
  {
    id: "solenoide",
    nome: "Solenoide",
    lugar: "Campo das correntes · bobina",
    quem: "Fio enrolado em muitas espiras lado a lado, formando um cilindro. Percorrido por corrente, cria em seu interior um campo praticamente uniforme e paralelo ao eixo, de intensidade B = µ₀·(N/L)·i. Por fora, comporta-se como um ímã em barra.",
    gancho: "Solenoide = ímã em barra com interruptor. O campo depende de espiras por metro e da corrente; o raio não entra.",
    palavras: ["B = µ₀·(N/L)·i", "Campo uniforme", "Eletroímã", "Espiras por metro"],
    pistas: [
      "O meu campo interno não depende do raio das minhas espiras.",
      "Com um núcleo de ferro, torno-me um eletroímã.",
      "Por dentro, o meu campo é uniforme e paralelo ao meu eixo.",
      "Sou uma bobina longa, feita de muitas espiras enfileiradas.",
    ],
    curiosidades: [
      "O nome foi criado por Ampère a partir de uma palavra grega que significa \"tubo\".",
      "Versões feitas com fio supercondutor produzem o campo dos aparelhos de ressonância magnética.",
      "Está por trás das travas elétricas das portas dos carros e das válvulas das máquinas de lavar.",
    ],
    fato: "Bobina longa com campo uniforme no interior",
  },
  {
    id: "tesla",
    nome: "Tesla",
    lugar: "Campo magnético · unidade do SI",
    quem: "Unidade de intensidade do campo magnético no Sistema Internacional. Um tesla é o campo que exerce força de 1 N sobre cada metro de um fio perpendicular a ele, percorrido por 1 A: 1 T = 1 N/(A·m).",
    gancho: "Um tesla é MUITO campo: a Terra tem 0,00005 T, e um aparelho de ressonância magnética, 3 T.",
    palavras: ["1 T = 1 N/(A·m)", "Unidade", "SI", "Gauss"],
    pistas: [
      "Equivalho a um quilograma por ampère por segundo ao quadrado.",
      "Dez mil gauss correspondem a um de mim.",
      "O campo magnético da Terra vale cerca de cinquenta milionésimos de mim.",
      "Sou a unidade de campo magnético no SI.",
    ],
    curiosidades: [
      "Foi adotada em 1960, em homenagem a um inventor nascido na atual Croácia.",
      "O homenageado trabalhou com corrente alternada e com motores de indução.",
      "Na prática do laboratório e da medicina, usam-se muito os submúltiplos mili e micro.",
    ],
    fato: "Unidade de campo magnético no SI",
  },
  {
    id: "forca-magnetica",
    nome: "Força magnética",
    lugar: "Cargas em movimento · F = |q|·v·B·sen θ",
    quem: "Força que um campo magnético exerce sobre uma carga em movimento. Vale |q|·v·B·sen θ, é perpendicular à velocidade e ao campo e, por isso, não realiza trabalho: muda a direção da velocidade, mas não o seu módulo.",
    gancho: "Ela só empurra de lado. Por isso faz curva, mas nunca acelera nem freia.",
    palavras: ["|q|·v·B·sen θ", "Perpendicular a v e a B", "Não realiza trabalho", "Resultante centrípeta"],
    pistas: [
      "No movimento circular de uma carga em um campo uniforme, faço o papel de resultante centrípeta.",
      "Nunca altero a energia cinética da partícula sobre a qual atuo.",
      "Sou nula para cargas em repouso e para cargas que se movem paralelamente ao campo.",
      "Meu módulo é |q|·v·B·sen θ.",
    ],
    curiosidades: [
      "Somada à força elétrica, recebe o nome de um físico holandês, ganhador do Nobel de 1902.",
      "É o que desviava o feixe de elétrons para desenhar a imagem nos televisores de tubo.",
      "É a responsável por prender partículas do vento solar nos cinturões de radiação em torno da Terra.",
    ],
    fato: "Vale |q|·v·B·sen θ e não realiza trabalho",
  },
  {
    id: "regra-do-tapa",
    nome: "Regra do tapa",
    lugar: "Força magnética · sentido",
    quem: "Regra da mão direita espalmada para achar o sentido da força magnética. O polegar aponta no sentido da velocidade (ou da corrente), os outros dedos no sentido do campo, e a força sobre uma carga positiva sai da palma. Para carga negativa, sai das costas da mão.",
    gancho: "Polegar: velocidade. Dedos: campo. Palma: o tapa, que é a força. Carga negativa leva o tapa com as costas da mão.",
    palavras: ["Mão espalmada", "Palma = força", "Carga negativa inverte", "Vale para fios"],
    pistas: [
      "Chego ao mesmo resultado que a regra da mão esquerda de Fleming.",
      "Para cargas negativas, o meu resultado precisa ser invertido.",
      "Em mim, o polegar representa a velocidade e os outros dedos, o campo.",
      "A palma da mão indica a força: é dela que vem o meu nome.",
    ],
    curiosidades: [
      "A versão concorrente, com a outra mão e três dedos perpendiculares, foi criada por um engenheiro inglês para ensinar o funcionamento de motores.",
      "Para fios, usa-se o sentido convencional da corrente no lugar da velocidade.",
      "Só informa o sentido; a intensidade vem da fórmula com o seno do ângulo.",
    ],
    fato: "Polegar em v, dedos em B, a palma dá a força",
  },
  {
    id: "movimento-helicoidal",
    nome: "Movimento helicoidal",
    lugar: "Cargas em movimento · trajetória",
    quem: "Trajetória de uma carga lançada obliquamente em um campo magnético uniforme. A componente da velocidade paralela ao campo se mantém (MRU), enquanto a perpendicular produz um giro (MCU). A composição dos dois é uma hélice de passo constante.",
    gancho: "Oblíquo ao campo: gira E avança, como o arame de uma mola. v·sen θ faz o giro, v·cos θ faz o avanço.",
    palavras: ["Lançamento oblíquo", "MRU + MCU", "Passo da hélice", "v·cos θ avança"],
    pistas: [
      "O meu passo é o produto da componente paralela da velocidade pelo período.",
      "Sou a composição de um movimento retilíneo uniforme com um movimento circular uniforme.",
      "Apareço quando a velocidade não é nem paralela nem perpendicular ao campo.",
      "Tenho a forma de uma mola.",
    ],
    curiosidades: [
      "É assim que as partículas do vento solar descem até as regiões polares e produzem as auroras.",
      "Reatores experimentais de fusão nuclear usam este tipo de trajetória para manter o plasma afastado das paredes.",
      "Se o campo ficar mais intenso ao longo do caminho, as voltas se apertam e a partícula pode ser refletida.",
    ],
    fato: "Trajetória de carga lançada obliquamente ao campo",
  },
  {
    id: "fios-paralelos",
    nome: "Fios paralelos",
    lugar: "Força em condutores · interação",
    quem: "Dois fios paralelos com corrente exercem força um sobre o outro, porque cada um está no campo do outro. A força por unidade de comprimento é µ₀·i₁·i₂/(2π·d). Correntes de mesmo sentido se atraem; de sentidos opostos, se repelem.",
    gancho: "Com correntes é o contrário das cargas: iguais se ATRAEM, opostas se repelem.",
    palavras: ["µ₀·i₁·i₂/(2π·d)", "Mesmo sentido atrai", "Ação e reação", "Definição do ampère"],
    pistas: [
      "A força entre nós cai à metade quando a distância dobra.",
      "As forças que trocamos têm a mesma intensidade, mesmo com correntes diferentes.",
      "Durante décadas, servimos para definir a unidade de corrente elétrica.",
      "Atraímo-nos quando nossas correntes têm o mesmo sentido.",
    ],
    curiosidades: [
      "O fenômeno foi descoberto por Ampère em 1820, poucas semanas depois de ele saber da experiência de Oersted.",
      "A definição de unidade baseada nele só foi abandonada em 2019.",
      "Com 1 A em cada um e 1 m de separação, a força é de apenas 2 × 10⁻⁷ N por metro.",
    ],
    fato: "Atraem-se com correntes de mesmo sentido",
  },
];
