import type { Cadeia, Evento, Intruso } from "@/lib/tipos";
import { cadeia, intruso } from "../criar";

/** Jogo O intruso: três itens pertencem ao grupo e um não. */
export const intrusos: Intruso[] = [
  intruso("imas", "materiais ferromagnéticos", ["Ferro", "Níquel", "Cobalto"], "Cobre",
    "O cobre conduz muito bem a eletricidade, mas praticamente não responde a um ímã. Ferro, níquel e cobalto são os ferromagnéticos clássicos."),
  intruso("imas", "propriedades das linhas de campo magnético", ["São curvas fechadas", "Nunca se cruzam", "Ficam mais próximas onde o campo é mais intenso"], "Terminam no polo sul do ímã",
    "As linhas não terminam em lugar nenhum: entram pelo polo sul, atravessam o ímã por dentro e saem de novo pelo polo norte. É por isso que não existe polo isolado."),
  intruso("imas", "maneiras de enfraquecer um ímã", ["Aquecê-lo acima do ponto de Curie", "Dar marteladas repetidas", "Submetê-lo a um campo alternado que diminui aos poucos"], "Parti-lo ao meio",
    "Partir um ímã só produz dois ímãs menores, cada um com seus dois polos. As outras três ações desalinham os domínios magnéticos."),
  intruso("imas", "fatos sobre o campo magnético da Terra", ["Há um polo sul magnético perto do norte geográfico", "A polaridade já se inverteu muitas vezes", "Desvia as partículas do vento solar"], "Vem de um ímã permanente no centro do planeta",
    "O interior da Terra é quente demais para existir um ímã permanente: está muito acima do ponto de Curie. O campo vem de correntes no núcleo externo líquido."),
  intruso("campo-corrente", "maneiras de aumentar o campo dentro de um solenoide", ["Aumentar a corrente", "Aumentar o número de espiras por metro", "Colocar um núcleo de ferro"], "Aumentar o raio das espiras",
    "O campo de um solenoide longo é B = µ₀·(N/L)·i: o raio das espiras não aparece. Enrolar espiras mais largas não muda o campo interno."),
  intruso("campo-corrente", "grandezas que definem o campo de um fio retilíneo longo", ["Intensidade da corrente", "Distância até o fio", "Permeabilidade magnética do meio"], "Comprimento do fio",
    "Para um fio muito longo, B = µ₀·i/(2π·d). O comprimento não entra: a fórmula já supõe o fio muito maior do que a distância d."),
  intruso("campo-corrente", "aparelhos que usam eletroímã", ["Campainha elétrica", "Guindaste de ferro-velho", "Relé"], "Lâmpada incandescente",
    "A lâmpada incandescente funciona pelo aquecimento do filamento (efeito Joule), e não pelo campo magnético da corrente."),
  intruso("campo-corrente", "observações da experiência de Oersted", ["Com corrente no fio, a agulha se desvia", "Invertendo a corrente, o desvio se inverte", "Desligada a corrente, a agulha volta ao norte-sul"], "Um ímã parado faz surgir corrente no fio",
    "Ímã parado não gera corrente. O caminho inverso (magnetismo criando corrente) exige variação do campo e só foi descoberto por Faraday, em 1831."),
  intruso("forca-carga", "situações em que a força magnética é nula", ["Carga em repouso", "Carga movendo-se paralelamente ao campo", "Nêutron atravessando o campo"], "Elétron movendo-se perpendicularmente ao campo",
    "F = |q|·v·B·sen θ. O elétron tem carga, está em movimento e θ = 90°: é justamente a situação de força máxima."),
  intruso("forca-carga", "grandezas constantes quando uma carga gira em um campo magnético uniforme", ["Módulo da velocidade", "Energia cinética", "Raio da trajetória"], "Direção da velocidade",
    "A força magnética é perpendicular à velocidade: não realiza trabalho, mas muda continuamente a direção do movimento. É por isso que a trajetória é curva."),
  intruso("forca-carga", "grandezas de que depende o período da órbita em um campo magnético", ["Massa da partícula", "Carga da partícula", "Intensidade do campo"], "Velocidade da partícula",
    "T = 2π·m/(|q|·B). Partícula mais rápida faz circunferência maior, mas leva o mesmo tempo para completá-la. É essa propriedade que faz o cíclotron funcionar."),
  intruso("forca-carga", "aparelhos que curvam partículas com campo magnético", ["Espectrômetro de massa", "Cíclotron", "Tubo de imagem das TVs antigas"], "Capacitor de placas paralelas",
    "Entre as placas de um capacitor existe campo elétrico, que desvia cargas em trajetória parabólica e altera a energia delas. Os outros três usam campo magnético."),
  intruso("forca-fio", "mudanças que aumentam a força sobre um fio em um campo magnético", ["Aumentar a corrente", "Aumentar o trecho de fio dentro do campo", "Aumentar a intensidade do campo"], "Alinhar o fio com as linhas de campo",
    "F = B·i·L·sen θ. Com o fio paralelo às linhas de campo, sen θ = 0 e a força desaparece. A força é máxima com o fio perpendicular ao campo."),
  intruso("forca-fio", "afirmações corretas sobre dois fios paralelos com corrente", ["Correntes de mesmo sentido se atraem", "As forças nos dois fios têm a mesma intensidade", "A força cai à metade quando a distância dobra"], "A força é maior no fio de menor corrente",
    "As forças formam um par ação-reação: têm sempre a mesma intensidade, quaisquer que sejam as correntes."),
  intruso("forca-fio", "aparelhos movidos pela força magnética sobre condutores", ["Motor elétrico", "Alto-falante", "Galvanômetro de bobina móvel"], "Chuveiro elétrico",
    "O chuveiro aquece a água pelo efeito Joule em um resistor. Nos outros três, uma bobina com corrente é movida pela força que um ímã exerce sobre ela."),
  intruso("forca-fio", "unidades equivalentes ao tesla", ["N/(A·m)", "N·s/(C·m)", "kg/(A·s²)"], "N·m/A",
    "De F = B·i·L, tesla é N/(A·m). De F = |q|·v·B, é N·s/(C·m). Trocando newton por kg·m/s², chega-se a kg/(A·s²). Já N·m/A é a unidade de fluxo magnético, o weber."),
];

/** Jogo Passo a passo: os passos estão na ordem certa, cada um levando ao seguinte. */
export const cadeias: Cadeia[] = [
  cadeia("imas", "Por que a bússola aponta para o norte",
    ["Metal líquido se move no núcleo externo da Terra", "Esse movimento equivale a correntes elétricas e cria um campo magnético", "As linhas desse campo entram na Terra perto do norte geográfico", "A agulha imantada da bússola se alinha com as linhas de campo", "O polo norte da agulha fica voltado para o norte geográfico"],
    "As linhas entram onde há um polo sul magnético. É por isso que o norte da agulha, atraído por ele, aponta para o norte geográfico."),
  cadeia("imas", "Como um ímã levanta um prego",
    ["Um ímã é aproximado de um prego de ferro comum", "O campo do ímã alinha os domínios magnéticos do prego", "Na ponta mais próxima do prego surge um polo oposto ao do ímã", "Polos opostos se atraem e o prego gruda", "Afastado o ímã, os domínios se desalinham e o prego deixa de atrair"],
    "É a imantação por indução. Ela explica por que o ferro comum é atraído por qualquer polo, e por que o efeito some quando o ímã vai embora."),
  cadeia("campo-corrente", "A experiência de Oersted",
    ["Em repouso, a agulha da bússola aponta na direção norte-sul", "Um fio é estendido paralelamente à agulha, logo acima dela", "Fecha-se o circuito e a corrente percorre o fio", "Surge, na posição da agulha, um campo perpendicular ao fio", "A agulha gira até a direção do campo resultante"],
    "A agulha não fica perpendicular ao fio: ela para na direção da soma do campo da corrente com o campo da Terra."),
  cadeia("campo-corrente", "Do fio ao eletroímã",
    ["Um fio reto com corrente cria um campo fraco ao seu redor", "Enrolado em uma espira, o fio concentra o campo no centro", "Muitas espiras lado a lado formam um solenoide de campo uniforme", "Um núcleo de ferro colocado no solenoide tem seus domínios alinhados", "O campo fica centenas de vezes mais intenso e pode ser ligado e desligado"],
    "Cada passo aproveita melhor a mesma corrente. O ferro doce perde a imantação quando a corrente cessa, e por isso o eletroímã pode ser desligado."),
  cadeia("forca-carga", "De onde vem o raio da órbita",
    ["A carga entra no campo com velocidade perpendicular a ele", "Surge a força magnética |q|·v·B, perpendicular à velocidade", "Essa força faz o papel de resultante centrípeta: |q|·v·B = m·v²/R", "Cancela-se uma velocidade de cada lado da igualdade", "Isola-se o raio: R = m·v/(|q|·B)"],
    "Toda questão de órbita em campo magnético começa na mesma linha: força magnética igual à resultante centrípeta."),
  cadeia("forca-carga", "Por que a trajetória vira uma hélice",
    ["A carga é lançada obliquamente às linhas de campo", "A velocidade é decomposta em uma parte paralela e outra perpendicular ao campo", "Só a parte perpendicular sofre força, e a carga passa a girar", "Enquanto gira, a carga avança com a parte paralela, que não se altera", "Giro e avanço juntos desenham uma hélice de passo constante"],
    "O giro vem de v·sen θ e o avanço, de v·cos θ. O passo da hélice é o avanço durante um período."),
  cadeia("forca-carga", "Dentro de um espectrômetro de massa",
    ["Os átomos da amostra são ionizados e acelerados por uma tensão", "O seletor deixa passar apenas os íons com velocidade E/B", "Os íons entram perpendicularmente em um campo magnético uniforme", "Cada íon descreve meia circunferência de raio proporcional à sua massa", "Isótopos diferentes atingem o detector em pontos diferentes"],
    "Com a mesma carga e a mesma velocidade, o raio só depende da massa. É assim que se separam isótopos de um mesmo elemento."),
  cadeia("forca-fio", "Por que dois fios paralelos se atraem",
    ["O fio 1 é percorrido por corrente", "Ao redor do fio 1 surge um campo magnético circular", "O fio 2, paralelo, fica mergulhado nesse campo e perpendicular a ele", "A corrente do fio 2 sofre a força B·i·L, dada pela regra do tapa", "Com correntes de mesmo sentido, essa força aponta para o fio 1"],
    "São duas regras em sequência: a da mão direita dá o campo de um fio, e a do tapa dá a força sobre o outro."),
  cadeia("forca-fio", "Como gira um motor elétrico",
    ["A corrente chega à bobina pelas escovas", "Os lados da bobina perpendiculares ao campo sofrem forças opostas", "O binário dessas forças faz a bobina girar meia volta", "O comutador inverte o sentido da corrente na bobina", "O binário conserva o sentido e a bobina continua girando"],
    "Sem o comutador, a bobina pararia depois de meia volta, pois o binário passaria a empurrá-la de volta."),
];

/** Campos magnéticos para os jogos de comparar e de ordenar. `ano` é a intensidade em tesla. */
export const eventos: Evento[] = [
  { ano: 1e-12, rotulo: "≈ 1 pT", texto: "Campo magnético produzido pela atividade do cérebro humano" },
  { ano: 5e-11, rotulo: "≈ 50 pT", texto: "Campo magnético produzido pelos batimentos do coração" },
  { ano: 2e-7, rotulo: "0,2 µT", texto: "Campo a 1 m de um fio percorrido por 1 A" },
  { ano: 5e-5, rotulo: "≈ 50 µT", texto: "Campo magnético da Terra na superfície" },
  { ano: 2e-4, rotulo: "200 µT", texto: "Campo a 1 cm de um fio percorrido por 10 A" },
  { ano: 4e-4, rotulo: "≈ 0,4 mT", texto: "Campo de Júpiter na altura das nuvens, no equador" },
  { ano: 5e-3, rotulo: "≈ 5 mT", texto: "Campo de um ímã de geladeira" },
  { ano: 0.3, rotulo: "≈ 0,3 T", texto: "Campo no interior de uma mancha solar" },
  { ano: 1.3, rotulo: "≈ 1,3 T", texto: "Campo na superfície de um ímã de neodímio" },
  { ano: 3, rotulo: "3 T", texto: "Campo de um aparelho de ressonância magnética de hospital" },
  { ano: 8.3, rotulo: "8,3 T", texto: "Campo dos ímãs que curvam os prótons no acelerador LHC" },
  { ano: 45, rotulo: "45 T", texto: "Maior campo contínuo já mantido em laboratório" },
  { ano: 100, rotulo: "≈ 100 T", texto: "Campo de um ímã pulsado de laboratório, por milésimos de segundo" },
  { ano: 1e8, rotulo: "≈ 10⁸ T", texto: "Campo na superfície de uma estrela de nêutrons" },
  { ano: 1e11, rotulo: "≈ 10¹¹ T", texto: "Campo de um magnetar, o ímã mais forte que se conhece" },
];
