import type { Questao } from "@/lib/tipos";
import { criar } from "../criar";

const f = criar("forca-fio");

const MU = "(Dado: µ₀ = 4π × 10⁻⁷ T·m/A)";

/** Força magnética em condutores retilíneos. A primeira alternativa é a correta. */
export const questoesForcaFio: Questao[] = [
  // ───────── Fácil ─────────
  f("fio-01", "facil", "ENEM", "Um fio retilíneo percorrido por corrente está imerso em um campo magnético uniforme, com a corrente paralela às linhas de campo. A força magnética sobre o fio é:",
    ["nula.", "máxima.", "perpendicular ao fio.", "paralela ao fio."],
    "F = B·i·L·sen θ. Com o fio paralelo ao campo, θ = 0° e sen θ = 0. Não há força.",
    "Fio paralelo ao campo: força zero."),
  f("fio-02", "facil", "Unesp", "A força magnética sobre um fio retilíneo com corrente, em um campo magnético uniforme, é máxima quando o fio está:",
    [
      "perpendicular às linhas de campo.",
      "paralelo às linhas de campo.",
      "inclinado de 45° em relação às linhas de campo.",
      "em qualquer posição, pois a força não depende do ângulo.",
    ],
    "Na expressão F = B·i·L·sen θ, o seno atinge seu valor máximo, 1, para θ = 90°. A força é máxima com o fio perpendicular ao campo.",
    "Fio atravessado no campo: força máxima."),
  f("fio-03", "facil", "UERJ", "Dois fios retilíneos, longos e paralelos, são percorridos por correntes de mesmo sentido. A força magnética entre eles é de:",
    ["atração.", "repulsão.", "atração e depois repulsão.", "intensidade nula."],
    "Cada fio está no campo magnético criado pelo outro. Aplicando a regra da mão direita e depois a do tapa, conclui-se que correntes de mesmo sentido se atraem e correntes de sentidos opostos se repelem.",
    "Correntes: iguais se atraem, opostas se repelem. Ao contrário das cargas."),
  f("fio-04", "facil", "UFPR", "Um fio retilíneo de comprimento L, percorrido por corrente i e perpendicular a um campo magnético uniforme, sofre força de intensidade F. Se a corrente for duplicada, a força passa a valer:",
    ["2F.", "F/2.", "4F.", "F.", "F/4."],
    "F = B·i·L: a força é diretamente proporcional à corrente. Dobrando a corrente, a força dobra.",
    "F = B·i·L: tudo multiplica, tudo é proporcional."),
  f("fio-05", "facil", "Fuvest", "O funcionamento de um motor elétrico de corrente contínua baseia-se no fato de que:",
    [
      "condutores com corrente sofrem força quando estão em um campo magnético.",
      "ímãs em repouso produzem corrente elétrica em fios parados.",
      "cargas em repouso são aceleradas por campos magnéticos.",
      "fios com corrente se aquecem por efeito Joule.",
    ],
    "A bobina do motor, percorrida por corrente e colocada no campo de um ímã, sofre forças em seus lados que a fazem girar. É a conversão de energia elétrica em energia mecânica.",
    "Motor: corrente + campo = força que gira."),

  // ───────── Médio ─────────
  f("fio-06", "medio", "Fuvest", "Um fio retilíneo de 50 cm de comprimento, percorrido por corrente de 5,0 A, é colocado perpendicularmente a um campo magnético uniforme de 0,40 T. A intensidade da força magnética sobre o fio é:",
    ["1,0 N.", "100 N.", "0,10 N.", "4,0 N.", "0,040 N."],
    "F = B·i·L·sen 90° = 0,40 × 5,0 × 0,50 = 1,0 N. O comprimento precisa estar em metros.",
    "F = B·i·L: B em tesla, i em ampère, L em metro."),
  f("fio-07", "medio", "Unicamp", "Um fio retilíneo de 2,0 m, percorrido por corrente de 10 A, forma um ângulo de 30° com as linhas de um campo magnético uniforme de 0,20 T. A intensidade da força magnética sobre ele é:",
    ["2,0 N.", "4,0 N.", "3,5 N.", "1,0 N.", "zero."],
    "F = B·i·L·sen 30° = 0,20 × 10 × 2,0 × 0,50 = 2,0 N. Só a componente do fio perpendicular ao campo contribui para a força.",
    "Fio inclinado: multiplique pelo seno do ângulo com o campo."),
  f("fio-08", "medio", "Unesp", "Um fio retilíneo está no plano desta página e é percorrido por corrente da esquerda para a direita. Ele está em um campo magnético uniforme perpendicular à página, entrando nela. A força magnética sobre o fio aponta para:",
    [
      "cima, no plano da página.",
      "baixo, no plano da página.",
      "dentro da página.",
      "fora da página.",
      "a direita.",
    ],
    "Na regra do tapa, o polegar aponta no sentido convencional da corrente (para a direita) e os dedos, no sentido do campo (entrando na página). A palma fica voltada para cima: esse é o sentido da força. Não se inverte nada, porque a corrente convencional já é a de cargas positivas.",
    "Para fios: polegar na corrente convencional, e o tapa vale direto."),
  f("fio-09", "medio", "UERJ", "Dois fios longos e paralelos conduzem correntes i e 3i. Sendo F a intensidade da força que o fio de corrente i exerce sobre cada metro do outro, a força que o fio de corrente 3i exerce sobre cada metro do primeiro tem intensidade:",
    ["F.", "3F.", "F/3.", "9F.", "zero."],
    "As duas forças formam um par ação-reação e têm sempre a mesma intensidade. Isso também aparece na fórmula F/L = µ₀·i₁·i₂/(2π·d), em que as duas correntes entram simetricamente.",
    "Par ação-reação: forças iguais mesmo com correntes diferentes."),
  f("fio-10", "medio", "UFPR", "Dois fios longos e paralelos, percorridos por correntes constantes, atraem-se com força de intensidade F por unidade de comprimento. Se a distância entre eles for duplicada, a força por unidade de comprimento passa a ser:",
    ["F/2.", "F/4.", "2F.", "F.", "4F."],
    "F/L = µ₀·i₁·i₂/(2π·d): a força é inversamente proporcional à distância, porque o campo de um fio retilíneo cai com 1/d. Dobrando a distância, a força cai à metade, e não a um quarto.",
    "Entre fios paralelos a força cai com 1/d, como o campo do fio."),

  // ───────── Difícil ─────────
  f("fio-11", "dificil", "Fuvest", `Dois fios retilíneos longos e paralelos, separados por 10 cm, são percorridos por correntes de 10 A e 20 A. A intensidade da força magnética que atua em cada metro de um dos fios é:\n${MU}`,
    ["4,0 × 10⁻⁴ N.", "4,0 × 10⁻⁶ N.", "2,0 × 10⁻⁴ N.", "4,0 × 10⁻³ N.", "8,0 × 10⁻⁴ N."],
    "F/L = µ₀·i₁·i₂/(2π·d) = 2 × 10⁻⁷ × 10 × 20/0,10 = 4,0 × 10⁻⁴ N/m. Em um metro de fio, a força é 4,0 × 10⁻⁴ N. É uma força pequena mesmo com correntes altas, e por isso não percebemos fios se atraindo no dia a dia.",
    "Fios paralelos: F/L = 2 × 10⁻⁷ · i₁·i₂/d."),
  f("fio-12", "dificil", "ITA", "Um fio retilíneo horizontal de massa 20 g e comprimento 50 cm é percorrido por corrente e está em um campo magnético uniforme e horizontal de 0,40 T, perpendicular ao fio. Para que o fio fique em equilíbrio sem nenhum apoio, a corrente deve valer:\n(Dado: g = 10 m/s²)",
    ["1,0 A.", "0,10 A.", "10 A.", "2,5 A.", "0,40 A."],
    "A força magnética deve equilibrar o peso: B·i·L = m·g. Então i = m·g/(B·L) = (0,020 × 10)/(0,40 × 0,50) = 0,20/0,20 = 1,0 A. O sentido da corrente deve ser tal que a regra do tapa dê força para cima.",
    "Levitar um fio: B·i·L = m·g."),
  f("fio-13", "dificil", "IME", "Um fio horizontal de peso P está pendurado por dois fios leves e verticais, em uma região de campo magnético uniforme horizontal e perpendicular a ele. Com corrente i em certo sentido, a tração nos fios de sustentação se anula. Invertendo o sentido da corrente, sem alterar sua intensidade, a soma das trações nos dois fios de sustentação passa a ser:",
    ["2P.", "P.", "P/2.", "zero.", "4P."],
    "Se a tração é nula, a força magnética aponta para cima e tem intensidade P. Invertendo a corrente, a força magnética mantém a intensidade P, mas passa a apontar para baixo, somando-se ao peso. Os fios de sustentação precisam equilibrar P + P = 2P.",
    "Inverter a corrente inverte a força, sem mudar a intensidade."),
  f("fio-14", "dificil", "Unicamp", "Uma espira retangular percorrida por corrente é colocada em um campo magnético uniforme, com seu plano paralelo às linhas de campo. Sobre as forças magnéticas que atuam na espira, é correto afirmar que:",
    [
      "a resultante é nula, mas elas formam um binário que tende a girar a espira.",
      "a resultante é nula e a espira permanece em repouso em qualquer situação.",
      "a resultante não é nula e arrasta a espira no sentido do campo.",
      "a resultante não é nula e arrasta a espira perpendicularmente ao campo.",
    ],
    "Os dois lados paralelos ao campo não sofrem força. Os dois lados perpendiculares ao campo conduzem correntes de sentidos opostos e sofrem forças de mesma intensidade e sentidos opostos, aplicadas em linhas diferentes. A soma das forças é zero, mas o torque não: a espira gira. É o princípio do motor elétrico e do galvanômetro.",
    "Espira em campo uniforme: não anda, mas gira."),
  f("fio-15", "dificil", "ITA", "Três fios retilíneos longos, paralelos e coplanares, X, Y e Z, nessa ordem, estão igualmente espaçados de uma distância d. X e Y conduzem correntes i em um mesmo sentido, e Z conduz corrente i no sentido oposto. Sendo F₀ = µ₀·i²/(2π·d), a força por unidade de comprimento sobre o fio central Y tem intensidade:",
    [
      "2F₀, dirigida para X.",
      "2F₀, dirigida para Z.",
      "zero.",
      "F₀, dirigida para X.",
      "F₀/2, dirigida para Z.",
    ],
    "X e Y têm correntes de mesmo sentido e se atraem: Y é puxado para X com F₀. Y e Z têm correntes opostas e se repelem: Y é empurrado para longe de Z, ou seja, também para o lado de X, com F₀. As duas forças têm o mesmo sentido e se somam: 2F₀, para X.",
    "Atraído por um lado e empurrado pelo outro: as forças se somam."),
  f("fio-16", "dificil", "IME", "Três fios retilíneos longos, paralelos e coplanares, igualmente espaçados de uma distância d, conduzem correntes de mesma intensidade i e mesmo sentido. A força por unidade de comprimento que atua em um dos fios das extremidades tem intensidade:",
    ["3µ₀·i²/(4π·d).", "µ₀·i²/(2π·d).", "µ₀·i²/(4π·d).", "µ₀·i²/(π·d).", "zero."],
    "O fio da extremidade é atraído pelo fio central, à distância d, com µ₀·i²/(2π·d), e pelo outro fio da extremidade, à distância 2d, com µ₀·i²/(4π·d). As duas forças apontam para o mesmo lado e se somam: 3µ₀·i²/(4π·d). Já o fio central é puxado igualmente para os dois lados e fica com resultante nula.",
    "Some as forças fio a fio, cada uma com a sua distância."),
  f("fio-17", "dificil", "Unesp", "Um fio retilíneo vertical conduz corrente de baixo para cima em uma região onde existe um campo magnético uniforme horizontal, que aponta para o norte. A força magnética sobre o fio aponta para:",
    ["o oeste.", "o leste.", "o sul.", "cima.", "o norte."],
    "Pela regra do tapa, com o polegar para cima (corrente) e os dedos apontando para o norte (campo), a palma da mão direita fica voltada para oeste. É por isso que a força é horizontal: ela precisa ser perpendicular tanto ao fio, que é vertical, quanto ao campo.",
    "A força é perpendicular ao fio e ao campo, ao mesmo tempo."),
  f("fio-18", "dificil", "Fuvest", `Durante décadas, o ampère foi definido como a corrente que, mantida em dois fios retilíneos, paralelos e muito longos, separados por 1 m no vácuo, produz entre eles determinada força por metro de comprimento. Com correntes de 1 A em cada fio, essa força é:\n${MU}`,
    ["2 × 10⁻⁷ N por metro.", "1 N por metro.", "4π × 10⁻⁷ N por metro.", "1 × 10⁻⁷ N por metro.", "9 × 10⁹ N por metro."],
    "F/L = µ₀·i₁·i₂/(2π·d) = (4π × 10⁻⁷ × 1 × 1)/(2π × 1) = 2 × 10⁻⁷ N/m. Era exatamente esse valor que fixava a definição do ampère, e o valor de µ₀ decorria dela.",
    "1 A, 1 m, 1 m de fio: 2 × 10⁻⁷ N. Era a definição do ampère."),
  f("fio-19", "dificil", "ITA", "Um fio em forma de semicircunferência de raio R, percorrido por corrente i, está contido em um plano perpendicular a um campo magnético uniforme de intensidade B. A intensidade da força magnética resultante sobre o fio é:",
    ["2B·i·R.", "π·B·i·R.", "B·i·R.", "zero.", "π·B·i·R/2."],
    "Em campo uniforme, a força sobre um fio de forma qualquer é igual à que agiria sobre um fio retilíneo ligando as suas extremidades, percorrido pela mesma corrente. As extremidades da semicircunferência estão separadas pelo diâmetro, 2R, perpendicular ao campo. Logo, F = B·i·(2R). Usar o comprimento do arco, π·R, é o erro esperado.",
    "Campo uniforme: vale a reta entre as pontas, não o caminho do fio."),
  f("fio-20", "dificil", "IME", "Uma barra condutora de massa 0,20 kg e comprimento 0,50 m repousa sobre dois trilhos horizontais paralelos, perpendicularmente a eles, em uma região de campo magnético uniforme vertical de 0,40 T. O coeficiente de atrito estático entre a barra e os trilhos é 0,50. A menor corrente que, percorrendo a barra, a coloca em movimento é:\n(Dado: g = 10 m/s²)",
    ["5,0 A.", "10 A.", "2,5 A.", "0,50 A.", "1,0 A."],
    "Com o campo vertical, a força magnética sobre a barra é horizontal e vale B·i·L. Ela precisa vencer o atrito estático máximo, que é 0,50 × m·g = 0,50 × 0,20 × 10 = 1,0 N. Então i = 1,0/(0,40 × 0,50) = 5,0 A.",
    "Campo vertical em barra horizontal: a força empurra de lado."),

  // ───────── Desafio ─────────
  f("fio-21", "desafio", "ITA", "Uma barra condutora de massa m e comprimento L está em equilíbrio, na horizontal, sobre dois trilhos paralelos sem atrito, inclinados de um ângulo θ em relação à horizontal. A região tem campo magnético uniforme vertical de intensidade B, e a barra é perpendicular aos trilhos. A corrente na barra vale:",
    ["m·g·tg θ/(B·L).", "m·g·sen θ/(B·L).", "m·g·cos θ/(B·L).", "m·g/(B·L·tg θ).", "m·g/(B·L)."],
    "A barra é horizontal e o campo é vertical, então a força magnética é horizontal e vale B·i·L. Ao longo do plano inclinado, sua componente é B·i·L·cos θ, que deve equilibrar a componente do peso, m·g·sen θ. Assim, i = m·g·sen θ/(B·L·cos θ) = m·g·tg θ/(B·L). A alternativa com sen θ corresponde a um campo perpendicular ao plano inclinado, e não vertical.",
    "Decomponha as duas forças ao longo do plano: a magnética também inclina."),
  f("fio-22", "desafio", "IME", "Um fio retilíneo muito longo conduz corrente i₁. No mesmo plano há uma espira retangular percorrida por corrente i₂, com dois lados de comprimento L paralelos ao fio, situados às distâncias a e 2a dele. No lado mais próximo, a corrente tem o mesmo sentido de i₁. A força magnética resultante sobre a espira é:",
    [
      "µ₀·i₁·i₂·L/(4π·a), de atração.",
      "µ₀·i₁·i₂·L/(4π·a), de repulsão.",
      "µ₀·i₁·i₂·L/(2π·a), de atração.",
      "3µ₀·i₁·i₂·L/(4π·a), de atração.",
      "zero, pois a espira é um circuito fechado.",
    ],
    "O lado próximo é atraído pelo fio com µ₀·i₁·i₂·L/(2π·a). O lado distante, com corrente no sentido oposto, é repelido com µ₀·i₁·i₂·L/(4π·a). As forças nos dois lados perpendiculares ao fio se cancelam. A resultante é a diferença: µ₀·i₁·i₂·L/(4π·a), de atração. A resultante só seria nula em um campo uniforme, e o campo do fio não é.",
    "Em campo não uniforme, a espira sofre força: vence o lado mais próximo."),
  f("fio-23", "desafio", "ITA", `Um fio retilíneo longo está fixo sobre uma mesa horizontal. Um segundo fio, paralelo ao primeiro, com massa de 5,0 g por metro, flutua em equilíbrio verticalmente acima dele. Os dois conduzem correntes de 50 A em sentidos opostos. A distância entre os fios é:\n${MU}\n(Dado: g = 10 m/s²)`,
    ["1,0 cm.", "1,0 mm.", "10 cm.", "0,50 cm.", "2,0 cm."],
    "A repulsão por unidade de comprimento deve equilibrar o peso por unidade de comprimento: µ₀·i²/(2π·d) = λ·g. Então d = 2 × 10⁻⁷ × 50²/(5,0 × 10⁻³ × 10) = (5,0 × 10⁻⁴)/(5,0 × 10⁻²) = 1,0 × 10⁻² m = 1,0 cm. O equilíbrio é estável na vertical: se o fio desce, a repulsão aumenta e o empurra de volta.",
    "Equilíbrio por metro de fio: força por metro = peso por metro."),
  f("fio-24", "desafio", "IME", "Dois fios retilíneos longos e paralelos, A e B, separados por 30 cm, conduzem correntes de mesmo sentido, i e 4i. Um terceiro fio, paralelo aos dois e no mesmo plano, deve ser colocado de modo que a força magnética resultante sobre ele seja nula. Ele deve ficar:",
    [
      "entre A e B, a 6,0 cm de A, qualquer que seja a sua corrente.",
      "entre A e B, a 6,0 cm de B, qualquer que seja a sua corrente.",
      "entre A e B, a 6,0 cm de A, apenas se sua corrente tiver o sentido das outras.",
      "fora da região entre A e B, a 10 cm de A.",
      "entre A e B, a 10 cm de A, qualquer que seja a sua corrente.",
    ],
    "A força sobre o terceiro fio é nula onde o campo resultante de A e B é nulo. Com correntes de mesmo sentido, isso ocorre entre os fios: i/x = 4i/(30 − x), o que dá 30 − x = 4x e x = 6,0 cm a partir de A. Como o campo ali é zero, a força é nula para qualquer intensidade e qualquer sentido da corrente no terceiro fio.",
    "Força nula no fio = campo nulo naquele lugar."),
  f("fio-25", "desafio", "ITA", "Uma bobina quadrada de 100 espiras e lado 10 cm é percorrida por corrente de 2,0 A e está em um campo magnético uniforme de 0,50 T, com o plano da bobina paralelo às linhas de campo e dois de seus lados perpendiculares a elas. O módulo do torque (momento do binário) das forças magnéticas sobre a bobina é:",
    ["1,0 N·m.", "0,10 N·m.", "10 N·m.", "0,010 N·m.", "0,50 N·m."],
    "Em cada um dos dois lados perpendiculares ao campo, a força é F = N·B·i·L = 100 × 0,50 × 2,0 × 0,10 = 10 N. Essas forças têm sentidos opostos e estão separadas pela largura da bobina, 0,10 m. O torque do binário é F × 0,10 = 1,0 N·m. Em geral, para essa posição, o torque vale N·B·i·A, com A a área da espira.",
    "Torque máximo de uma bobina: N·B·i·A."),
  f("fio-26", "desafio", "IME", "Uma barra condutora horizontal de massa 10 g e comprimento 20 cm está suspensa pelas extremidades por dois fios leves, em uma região de campo magnético uniforme vertical de 0,50 T. Quando passa corrente pela barra, os fios de suspensão se inclinam e ficam em equilíbrio a 45° com a vertical. A corrente na barra é:\n(Dado: g = 10 m/s²)",
    ["1,0 A.", "0,10 A.", "2,0 A.", "0,71 A.", "10 A."],
    "A barra fica sujeita ao peso (vertical), à força magnética (horizontal, pois o campo é vertical) e às trações. No equilíbrio, tg 45° = B·i·L/(m·g). Como tg 45° = 1, B·i·L = m·g e i = (0,010 × 10)/(0,50 × 0,20) = 0,10/0,10 = 1,0 A.",
    "Balanço magnético: tg θ = força magnética ÷ peso."),
  f("fio-27", "desafio", "ITA", "Em um lançador eletromagnético, uma barra condutora de massa 0,10 kg e comprimento 0,20 m desliza sem atrito sobre dois trilhos horizontais paralelos, em um campo magnético uniforme vertical de 0,50 T. Uma fonte mantém na barra corrente constante de 100 A. Partindo do repouso, a velocidade da barra depois de percorrer 1,0 m é, aproximadamente:",
    ["14 m/s.", "10 m/s.", "100 m/s.", "20 m/s.", "4,5 m/s."],
    "A força magnética é constante: F = B·i·L = 0,50 × 100 × 0,20 = 10 N. A aceleração é a = F/m = 100 m/s². Pela equação de Torricelli, v² = 2·a·d = 2 × 100 × 1,0 = 200, de modo que v ≈ 14 m/s. Também se chega lá pelo teorema da energia cinética: F·d = m·v²/2.",
    "Força constante: Torricelli ou trabalho-energia resolvem."),
  f("fio-28", "desafio", "IME", "Três fios retilíneos longos e paralelos passam pelos vértices de um triângulo equilátero de lado a, perpendicularmente ao plano do triângulo, e conduzem correntes de mesma intensidade i e mesmo sentido. A força por unidade de comprimento sobre cada fio tem intensidade:",
    [
      "√3·µ₀·i²/(2π·a), apontando para o centro do triângulo.",
      "√3·µ₀·i²/(2π·a), apontando para fora do triângulo.",
      "µ₀·i²/(π·a), apontando para o centro do triângulo.",
      "µ₀·i²/(2π·a), apontando para o centro do triângulo.",
      "zero, por simetria.",
    ],
    "Cada fio é atraído pelos outros dois com forças de intensidade F₀ = µ₀·i²/(2π·a), dirigidas ao longo dos lados do triângulo, que formam 60° entre si. A resultante vale 2·F₀·cos 30° = √3·F₀ e aponta ao longo da bissetriz, isto é, para o centro do triângulo. Os fios tendem a se juntar, como acontece em um feixe de correntes paralelas.",
    "Duas forças iguais a 60°: resultante √3 vezes cada uma."),
];
