import type { Questao } from "@/lib/tipos";
import { criar } from "../criar";

const m = criar("imas");
const c = criar("campo-corrente");
const q = criar("forca-carga");
const f = criar("forca-fio");

const MU = "(Dado: µ₀ = 4π × 10⁻⁷ T·m/A)";

/** Questões de cálculo em várias etapas, no padrão ITA/IME. A primeira alternativa é a correta. */
export const questoesContas: Questao[] = [
  // ───────── Ímãs e campo da Terra ─────────
  m("ima-31", "desafio", "ITA", "O campo magnético de um ímã em barra, em pontos distantes sobre o seu eixo, é inversamente proporcional ao cubo da distância ao centro do ímã. Um ímã é colocado com o eixo na direção leste-oeste, e uma bússola, sobre esse eixo, a 10 cm do ímã, desvia-se 45° em relação ao norte. Afastando a bússola para 20 cm, sobre o mesmo eixo, o novo desvio θ é tal que:",
    ["tg θ = 1/8.", "tg θ = 1/2.", "tg θ = 1/4.", "θ = 22,5°.", "tg θ = 8."],
    "O campo do ímã é perpendicular ao campo terrestre, então tg θ = B(ímã)/B(Terra). A 10 cm, tg 45° = 1: os dois campos são iguais. Dobrando a distância, o campo do ímã fica 2³ = 8 vezes menor, e tg θ = 1/8, o que dá cerca de 7°. O desvio não cai pela metade: ele despenca.",
    "Campo de ímã distante cai com o cubo: dobrou a distância, dividiu por 8."),
  m("ima-32", "dificil", "IME", "Em certo local, as componentes horizontal e vertical do campo magnético terrestre valem, respectivamente, 2,4 × 10⁻⁵ T e 3,2 × 10⁻⁵ T. A intensidade do campo e a tangente do ângulo de inclinação magnética nesse local são:",
    [
      "4,0 × 10⁻⁵ T e 4/3.",
      "5,6 × 10⁻⁵ T e 4/3.",
      "4,0 × 10⁻⁵ T e 3/4.",
      "2,8 × 10⁻⁵ T e 3/4.",
      "5,6 × 10⁻⁵ T e 3/4.",
    ],
    "As componentes são perpendiculares: B = √(2,4² + 3,2²) × 10⁻⁵ = 4,0 × 10⁻⁵ T (triângulo 3-4-5 multiplicado por 0,8). A inclinação é o ângulo com a horizontal: tg = B(vertical)/B(horizontal) = 3,2/2,4 = 4/3, cerca de 53°.",
    "Inclinação: tg = vertical ÷ horizontal."),
  m("ima-33", "desafio", "ITA", "A frequência das pequenas oscilações de uma agulha de bússola em torno da posição de equilíbrio é proporcional à raiz quadrada da componente horizontal do campo magnético local. Em uma cidade A, onde essa componente vale 3,6 × 10⁻⁵ T, a agulha executa 20 oscilações por minuto. Levada a uma cidade B, a mesma agulha executa 10 oscilações por minuto. A componente horizontal do campo em B é:",
    ["9,0 × 10⁻⁶ T.", "1,8 × 10⁻⁵ T.", "7,2 × 10⁻⁵ T.", "1,4 × 10⁻⁴ T.", "2,5 × 10⁻⁵ T."],
    "Se f é proporcional a √B, então B é proporcional a f². A frequência caiu à metade, logo o campo ficou quatro vezes menor: 3,6 × 10⁻⁵/4 = 9,0 × 10⁻⁶ T. Dividir o campo por 2 é o erro de quem esquece a raiz.",
    "f ∝ √B significa B ∝ f²."),
  m("ima-34", "dificil", "ITA", "Em um local onde a componente horizontal do campo terrestre vale 3,0 × 10⁻⁵ T e aponta para o norte, um ímã cria, na posição de uma bússola, um campo horizontal de 4,0 × 10⁻⁵ T dirigido para leste. A intensidade do campo horizontal resultante e o desvio da agulha em relação ao norte são, aproximadamente:\n(Dados: sen 53° ≈ 0,80 e cos 53° ≈ 0,60)",
    [
      "5,0 × 10⁻⁵ T e 53° para leste.",
      "7,0 × 10⁻⁵ T e 53° para leste.",
      "5,0 × 10⁻⁵ T e 37° para leste.",
      "1,0 × 10⁻⁵ T e 45° para leste.",
      "7,0 × 10⁻⁵ T e 37° para leste.",
    ],
    "Os campos são perpendiculares: B = √(3,0² + 4,0²) × 10⁻⁵ = 5,0 × 10⁻⁵ T. O desvio em relação ao norte tem tg θ = 4,0/3,0, isto é, sen θ = 0,80: θ ≈ 53°. O ângulo de 37° é o que a agulha forma com a direção leste.",
    "O desvio é medido a partir do norte: tg = campo extra ÷ campo da Terra."),
  m("ima-35", "desafio", "IME", "Três ímãs em forma de anel, idênticos e de 50 g cada um, são enfiados em uma haste vertical sem atrito apoiada em uma mesa, com polos de mesmo nome frente a frente entre vizinhos. O de baixo apoia-se na mesa e os outros dois flutuam em equilíbrio. Desprezando a interação entre o primeiro e o terceiro ímãs, a força de repulsão entre o ímã de baixo e o do meio e a força normal da mesa valem, respectivamente:\n(Dado: g = 10 m/s²)",
    ["1,0 N e 1,5 N.", "0,50 N e 1,5 N.", "1,0 N e 0,50 N.", "0,50 N e 1,0 N.", "1,5 N e 1,5 N."],
    "Cada ímã pesa 0,50 N. O de cima é sustentado só pelo do meio: a repulsão entre eles vale 0,50 N. O do meio é empurrado para baixo por essa força e pelo próprio peso, então precisa receber 1,0 N do ímã de baixo. A mesa sustenta o conjunto inteiro: 1,5 N. Por isso, no equilíbrio, os dois ímãs de baixo ficam mais próximos um do outro.",
    "Analise de cima para baixo: cada ímã sustenta tudo o que está acima dele."),
  m("ima-36", "dificil", "Unicamp", "Um barco navega a 20 km/h durante 3,0 h seguindo sempre a direção que a bússola indica como norte, em uma região onde a declinação magnética é de 30° para oeste e o piloto não a corrige. Ao final, o barco está afastado da rota pretendida (rumo ao norte geográfico) de uma distância lateral de:",
    ["30 km, para oeste.", "30 km, para leste.", "52 km, para oeste.", "60 km, para oeste.", "35 km, para leste."],
    "O barco percorre 60 km em uma direção 30° a oeste do norte verdadeiro. O afastamento lateral é 60 × sen 30° = 30 km, para oeste. O avanço na direção norte é 60 × cos 30° ≈ 52 km.",
    "Bússola sem correção: o erro lateral é distância × sen (declinação)."),

  // ───────── Campo das correntes ─────────
  c("cor-29", "desafio", "ITA", `Um fio retilíneo longo e vertical conduz corrente de 10 A, de baixo para cima, em um local onde a componente horizontal do campo terrestre vale 2,0 × 10⁻⁵ T e aponta para o norte. No plano horizontal, o campo magnético horizontal resultante é nulo em um ponto situado:\n${MU}`,
    [
      "10 cm a oeste do fio.",
      "10 cm a leste do fio.",
      "10 cm ao norte do fio.",
      "1,0 cm a oeste do fio.",
      "1,0 cm a leste do fio.",
    ],
    "O campo do fio deve ter a intensidade do campo terrestre: 2 × 10⁻⁷ × 10/d = 2,0 × 10⁻⁵, de onde d = 0,10 m. E deve apontar para o sul. Visto de cima, com a corrente subindo, o campo circula no sentido anti-horário: aponta para o norte a leste do fio e para o sul a oeste dele. O ponto fica 10 cm a oeste.",
    "Campo nulo: mesma intensidade E sentidos opostos. Resolva as duas condições."),
  c("cor-30", "dificil", "IME", `Dois fios retilíneos longos e paralelos, A e B, perpendiculares ao plano da página e separados por 10 cm, conduzem correntes de 3,0 A e 4,0 A. Um ponto P do plano dista 6,0 cm de A e 8,0 cm de B. A intensidade do campo magnético resultante em P é, aproximadamente:\n${MU}`,
    ["1,4 × 10⁻⁵ T.", "2,0 × 10⁻⁵ T.", "1,0 × 10⁻⁵ T.", "zero.", "7,0 × 10⁻⁶ T."],
    "O triângulo de lados 6, 8 e 10 cm é retângulo em P. O campo de A vale 2 × 10⁻⁷ × 3,0/0,060 = 1,0 × 10⁻⁵ T, e o de B, 2 × 10⁻⁷ × 4,0/0,080 = 1,0 × 10⁻⁵ T. Cada campo é perpendicular ao segmento que liga o fio a P; como esses segmentos são perpendiculares entre si, os campos também são. Resultante: √2 × 10⁻⁵ ≈ 1,4 × 10⁻⁵ T, quaisquer que sejam os sentidos das correntes.",
    "Raios perpendiculares, campos perpendiculares: Pitágoras."),
  c("cor-31", "desafio", "ITA", `Uma bobina chata de 50 espiras e raio 10 cm é colocada com seu plano na vertical, contendo a direção norte-sul, e uma pequena bússola é posta em seu centro. A componente horizontal do campo terrestre vale 2,0 × 10⁻⁵ T. A corrente que faz a agulha desviar 45° é, aproximadamente:\n${MU}\n(Use π ≈ 3,14)`,
    ["64 mA.", "3,2 A.", "6,4 mA.", "0,20 A.", "32 mA."],
    "O campo da bobina no centro é perpendicular ao seu plano, portanto na direção leste-oeste, perpendicular ao campo terrestre. Desvio de 45° significa campos iguais: N·µ₀·i/(2R) = 2,0 × 10⁻⁵. Então i = 2R·B/(N·µ₀) = (2 × 0,10 × 2,0 × 10⁻⁵)/(50 × 4π × 10⁻⁷) = 0,20/π ≈ 0,064 A. É a bússola de tangentes, um amperímetro primitivo.",
    "Bússola de tangentes: tg θ = B(bobina)/B(Terra)."),
  c("cor-32", "dificil", "IME", `Um solenoide longo é feito enrolando-se, em uma única camada e com as espiras encostadas umas nas outras, um fio de 0,50 mm de diâmetro (incluído o isolamento). Com corrente de 2,0 A, a intensidade do campo magnético em seu interior é:\n${MU}`,
    ["1,6π × 10⁻³ T.", "4,0π × 10⁻⁴ T.", "1,6π × 10⁻⁶ T.", "8,0π × 10⁻⁴ T.", "1,6π × 10⁻² T."],
    "Com as espiras encostadas, cada uma ocupa 0,50 mm do comprimento: cabem 1/(0,50 × 10⁻³) = 2000 espiras por metro. Assim, B = µ₀·n·i = 4π × 10⁻⁷ × 2000 × 2,0 = 1,6π × 10⁻³ T, cerca de 5,0 × 10⁻³ T. O comprimento total e o raio do solenoide não são necessários.",
    "Espiras encostadas: n = 1 ÷ diâmetro do fio."),
  c("cor-33", "desafio", "IME", "No modelo de Bohr do átomo de hidrogênio, o elétron (carga 1,6 × 10⁻¹⁹ C) percorre uma órbita circular de raio 5,3 × 10⁻¹¹ m com velocidade de 2,2 × 10⁶ m/s. A intensidade do campo magnético que esse movimento produz no centro da órbita é, aproximadamente:\n(Dado: µ₀/4π = 10⁻⁷ T·m/A)",
    ["12,5 T.", "1,25 T.", "125 T.", "0,66 T.", "6,6 × 10⁻³ T."],
    "A corrente equivalente é i = e/T = e·v/(2π·r). O campo no centro de uma espira é B = µ₀·i/(2r) = (µ₀/4π)·e·v/r². Substituindo: B = 10⁻⁷ × 1,6 × 10⁻¹⁹ × 2,2 × 10⁶/(5,3 × 10⁻¹¹)² = 3,52 × 10⁻²⁰/2,81 × 10⁻²¹ ≈ 12,5 T. É um campo enorme, maior que o de um aparelho de ressonância magnética.",
    "Carga em órbita: i = e·v/(2π·r) e B = µ₀·i/(2r)."),
  c("cor-34", "dificil", "ITA", "Duas bobinas chatas, concêntricas e coplanares, têm, respectivamente, 10 espiras de raio 5,0 cm e 25 espiras de raio 20 cm. A primeira é percorrida por corrente de 2,0 A. Para que o campo magnético seja nulo no centro comum, a segunda deve ser percorrida, em sentido oposto, por corrente de:",
    ["3,2 A.", "0,80 A.", "1,6 A.", "5,0 A.", "8,0 A."],
    "O campo de uma bobina chata no centro é N·µ₀·i/(2R). Igualando: N₁·i₁/R₁ = N₂·i₂/R₂, isto é, 10 × 2,0/5,0 = 25 × i₂/20. Daí, 4,0 = 1,25·i₂ e i₂ = 3,2 A. Os raios podem ficar em centímetros, pois só a razão importa.",
    "Bobinas concêntricas: compare N·i/R."),

  // ───────── Força sobre cargas ─────────
  q("car-29", "desafio", "ITA", "Prótons (m/q = 1,0 × 10⁻⁸ kg/C) partem do repouso, são acelerados por uma diferença de potencial de 800 V e penetram perpendicularmente em um campo magnético uniforme de 0,10 T. O raio da trajetória circular é:",
    ["4,0 cm.", "0,40 cm.", "8,0 cm.", "2,8 cm.", "40 cm."],
    "Da aceleração: q·U = m·v²/2, logo v = √(2U·q/m) = √(2 × 800/10⁻⁸) = 4,0 × 10⁵ m/s. No campo: R = (m/q)·v/B = 10⁻⁸ × 4,0 × 10⁵/0,10 = 4,0 × 10⁻² m. Diretamente: R = √(2U·m/q)/B = √(1,6 × 10⁻⁵)/0,10 = 4,0 cm.",
    "Tensão dá a velocidade, campo dá o raio: R = √(2U·m/q)/B."),
  q("car-30", "dificil", "IME", "Um próton (m/q = 1,0 × 10⁻⁸ kg/C) descreve órbitas circulares em um campo magnético uniforme de 0,50 T. O número de voltas que ele completa em 1,0 ms é, aproximadamente:\n(Use π ≈ 3,14)",
    ["8,0 × 10³.", "8,0 × 10⁶.", "1,3 × 10⁴.", "5,0 × 10⁴.", "1,6 × 10³."],
    "O período é T = 2π·(m/q)/B = 2 × 3,14 × 10⁻⁸/0,50 ≈ 1,26 × 10⁻⁷ s, independentemente da velocidade. Em 1,0 × 10⁻³ s cabem 10⁻³/(1,26 × 10⁻⁷) ≈ 8,0 × 10³ voltas. A frequência correspondente, cerca de 8 MHz, é a frequência de cíclotron do próton nesse campo.",
    "Voltas = tempo ÷ período, e o período não depende da velocidade."),
  q("car-31", "desafio", "ITA", "Um próton (m/q = 1,0 × 10⁻⁸ kg/C) penetra com velocidade de 4,0 × 10⁵ m/s em um campo magnético uniforme de 0,20 T, em uma direção que forma 60° com as linhas de campo. O raio e o passo da hélice descrita são, aproximadamente:\n(Use π ≈ 3,14 e sen 60° ≈ 0,87)",
    [
      "1,7 cm e 6,3 cm.",
      "1,0 cm e 11 cm.",
      "2,0 cm e 6,3 cm.",
      "1,7 cm e 13 cm.",
      "1,0 cm e 6,3 cm.",
    ],
    "O giro vem da componente perpendicular ao campo: v·sen 60° ≈ 3,5 × 10⁵ m/s, e R = (m/q)·v·sen 60°/B = 10⁻⁸ × 3,5 × 10⁵/0,20 ≈ 1,7 × 10⁻² m. O avanço vem da componente paralela: v·cos 60° = 2,0 × 10⁵ m/s. O período é T = 2π·(m/q)/B = 3,14 × 10⁻⁷ s, e o passo, 2,0 × 10⁵ × 3,14 × 10⁻⁷ ≈ 6,3 × 10⁻² m.",
    "Raio com v·sen θ, passo com v·cos θ."),
  q("car-32", "dificil", "IME", "Em um espectrômetro de massa, íons de neônio de massas 20 u e 22 u, ambos com carga 1,6 × 10⁻¹⁹ C e velocidade de 1,0 × 10⁵ m/s, entram perpendicularmente em um campo magnético uniforme de 0,10 T e atingem uma chapa após meia volta. A distância entre os pontos de impacto dos dois isótopos é, aproximadamente:\n(Dado: 1 u = 1,66 × 10⁻²⁷ kg)",
    ["4,2 cm.", "2,1 cm.", "0,42 cm.", "8,3 cm.", "42 cm."],
    "Cada íon atinge a chapa a um diâmetro da entrada: 2R = 2m·v/(q·B). A separação é a diferença dos diâmetros: 2·Δm·v/(q·B) = 2 × (2 × 1,66 × 10⁻²⁷) × 1,0 × 10⁵/(1,6 × 10⁻¹⁹ × 0,10) = 6,64 × 10⁻²²/1,6 × 10⁻²⁰ ≈ 4,2 × 10⁻² m. Usar a diferença dos raios, em vez dos diâmetros, daria metade disso.",
    "Na chapa, o que se mede é diâmetro: a separação é 2·Δm·v/(q·B)."),
  q("car-33", "desafio", "IME", "Um cíclotron tem campo magnético de 1,0 T e raio máximo de órbita de 0,50 m. A energia cinética máxima com que saem os prótons (massa 1,6 × 10⁻²⁷ kg e carga 1,6 × 10⁻¹⁹ C) é, aproximadamente:\n(Dado: 1 MeV = 1,6 × 10⁻¹³ J)",
    ["12,5 MeV.", "25 MeV.", "1,25 MeV.", "6,25 MeV.", "50 MeV."],
    "Na órbita de raio máximo, v = q·B·R/m. A energia é K = m·v²/2 = (q·B·R)²/(2m) = (1,6 × 10⁻¹⁹ × 1,0 × 0,50)²/(2 × 1,6 × 10⁻²⁷) = 6,4 × 10⁻³⁹/3,2 × 10⁻²⁷ = 2,0 × 10⁻¹² J. Em MeV: 2,0 × 10⁻¹²/1,6 × 10⁻¹³ = 12,5 MeV.",
    "Cíclotron: K = (q·B·R)²/(2m)."),
  q("car-34", "dificil", "ITA", "Prótons (m/q = 1,0 × 10⁻⁸ kg/C) com velocidade de 2,0 × 10⁶ m/s penetram, perpendicularmente à fronteira, em uma região de 10 cm de largura onde há um campo magnético uniforme de 0,10 T, perpendicular à velocidade. Ao sair pelo lado oposto, a direção do movimento terá sido desviada de:",
    ["30°.", "60°.", "45°.", "90°.", "15°."],
    "O raio da trajetória é R = (m/q)·v/B = 10⁻⁸ × 2,0 × 10⁶/0,10 = 0,20 m, maior que a largura da região, de modo que o próton atravessa. O ângulo de desvio α é o ângulo central do arco percorrido, e a largura é L = R·sen α. Logo, sen α = 0,10/0,20 = 0,50 e α = 30°.",
    "Atravessando uma faixa de campo: sen α = largura ÷ raio."),

  // ───────── Força em fios ─────────
  f("fio-29", "desafio", "ITA", "Uma barra condutora de 0,10 kg e 20 cm de comprimento está em equilíbrio, na horizontal, sobre dois trilhos paralelos sem atrito, inclinados de 30° em relação à horizontal, em uma região de campo magnético uniforme vertical de 0,50 T. A corrente na barra é, aproximadamente:\n(Dados: g = 10 m/s² e tg 30° ≈ 0,58)",
    ["5,8 A.", "5,0 A.", "8,7 A.", "10 A.", "17 A."],
    "Com o campo vertical e a barra horizontal, a força magnética é horizontal: B·i·L. Projetando ao longo do plano: B·i·L·cos 30° = m·g·sen 30°, de onde i = m·g·tg 30°/(B·L) = (0,10 × 10 × 0,58)/(0,50 × 0,20) = 5,8 A. O valor 5,0 A corresponde a um campo perpendicular ao plano inclinado, e 10 A, a ignorar a inclinação.",
    "Campo vertical em plano inclinado: i = m·g·tg θ/(B·L)."),
  f("fio-30", "dificil", "IME", `Um fio retilíneo longo conduz corrente de 20 A. No mesmo plano, uma espira retangular percorrida por 10 A tem dois lados de 30 cm paralelos ao fio, um a 2,0 cm e o outro a 6,0 cm dele. A intensidade da força magnética resultante sobre a espira é:\n${MU}`,
    ["4,0 × 10⁻⁴ N.", "6,0 × 10⁻⁴ N.", "8,0 × 10⁻⁴ N.", "2,0 × 10⁻⁴ N.", "zero."],
    "Lado próximo: F = 2 × 10⁻⁷ × 20 × 10 × 0,30/0,020 = 6,0 × 10⁻⁴ N. Lado distante: 2 × 10⁻⁷ × 20 × 10 × 0,30/0,060 = 2,0 × 10⁻⁴ N. Como as correntes nesses lados têm sentidos opostos, uma força é de atração e a outra de repulsão: resultante de 4,0 × 10⁻⁴ N. As forças nos outros dois lados se cancelam.",
    "Espira perto de fio: subtraia as forças dos dois lados paralelos."),
  f("fio-31", "dificil", "ITA", "Uma barra condutora de 25 cm desliza sem atrito sobre trilhos horizontais e está presa a uma mola de constante elástica 25 N/m, paralela aos trilhos. A região tem campo magnético uniforme vertical de 0,40 T. Quando a barra é percorrida por corrente de 5,0 A, a mola, na nova posição de equilíbrio, fica deformada de:",
    ["2,0 cm.", "0,50 cm.", "20 cm.", "8,0 cm.", "5,0 cm."],
    "A força magnética sobre a barra é horizontal e vale B·i·L = 0,40 × 5,0 × 0,25 = 0,50 N. No equilíbrio ela é igual à força elástica: k·x = 0,50, de onde x = 0,50/25 = 0,020 m = 2,0 cm.",
    "Equilíbrio com mola: k·x = B·i·L."),
  f("fio-32", "desafio", "IME", `Três fios retilíneos longos e paralelos passam pelos vértices de um triângulo equilátero de 10 cm de lado, perpendicularmente ao plano do triângulo, e conduzem correntes de 10 A no mesmo sentido. A força magnética resultante sobre cada metro de qualquer um dos fios tem intensidade aproximada de:\n${MU}\n(Use √3 ≈ 1,7)`,
    ["3,4 × 10⁻⁴ N.", "2,0 × 10⁻⁴ N.", "4,0 × 10⁻⁴ N.", "1,7 × 10⁻⁴ N.", "zero."],
    "Cada par de fios se atrai com F₀ = 2 × 10⁻⁷ × 10 × 10/0,10 = 2,0 × 10⁻⁴ N por metro. Sobre cada fio atuam duas dessas forças, dirigidas ao longo dos lados do triângulo, a 60° uma da outra. A resultante é 2·F₀·cos 30° = √3·F₀ ≈ 3,4 × 10⁻⁴ N por metro, apontando para o centro do triângulo.",
    "Duas forças iguais a 60°: √3 vezes cada uma."),
  f("fio-33", "dificil", "ITA", "A bobina retangular de um motor tem 200 espiras de 5,0 cm por 4,0 cm e gira em um campo magnético uniforme de 0,25 T. Com corrente de 0,50 A, o torque máximo que as forças magnéticas exercem sobre a bobina é:",
    ["0,050 N·m.", "0,50 N·m.", "5,0 × 10⁻³ N·m.", "0,025 N·m.", "2,5 N·m."],
    "O torque é máximo quando o plano da bobina fica paralelo ao campo e vale N·B·i·A. A área é 0,050 × 0,040 = 2,0 × 10⁻³ m². Então o torque é 200 × 0,25 × 0,50 × 2,0 × 10⁻³ = 0,050 N·m. O erro mais comum é deixar a área em cm².",
    "Torque máximo de bobina: N·B·i·A, com a área em m²."),
  f("fio-34", "desafio", "ITA", `Dois fios retilíneos longos e paralelos conduzem correntes de mesma intensidade em sentidos opostos. O de baixo está fixo; o de cima, com massa de 10 g por metro, deve flutuar em equilíbrio 2,0 cm acima dele. A corrente necessária em cada fio é:\n${MU}\n(Dado: g = 10 m/s²)`,
    ["100 A.", "10 A.", "1,0 × 10⁴ A.", "50 A.", "32 A."],
    "Por metro de fio, a repulsão deve equilibrar o peso: 2 × 10⁻⁷·i²/d = λ·g. Então i² = λ·g·d/(2 × 10⁻⁷) = (1,0 × 10⁻² × 10 × 2,0 × 10⁻²)/(2 × 10⁻⁷) = 1,0 × 10⁴, e i = 100 A. O valor 1,0 × 10⁴ é o de quem esquece de extrair a raiz.",
    "Correntes iguais: a força vai com i². Não esqueça a raiz."),
];
