import type { Questao } from "@/lib/tipos";
import { criar } from "../criar";

const q = criar("forca-carga");

/** Força magnética sobre cargas em movimento. A primeira alternativa é a correta. */
export const questoesForcaCarga: Questao[] = [
  // ───────── Fácil ─────────
  q("car-01", "facil", "ENEM", "Uma partícula eletricamente carregada está em repouso em uma região onde existe apenas um campo magnético uniforme. A força magnética sobre ela é:",
    [
      "nula.",
      "paralela ao campo.",
      "perpendicular ao campo.",
      "proporcional à carga da partícula.",
    ],
    "A força magnética vale F = |q|·v·B·sen θ. Com v = 0, a força é zero. Campo magnético só age sobre carga em movimento.",
    "Carga parada não sente campo magnético."),
  q("car-02", "facil", "UERJ", "Um próton é lançado em um campo magnético uniforme com velocidade paralela às linhas de campo. Seu movimento será:",
    ["retilíneo uniforme.", "circular uniforme.", "helicoidal.", "retilíneo uniformemente acelerado."],
    "Com a velocidade paralela ao campo, θ = 0° e sen θ = 0: não há força magnética. Sem força, a partícula segue em linha reta com velocidade constante.",
    "Paralelo ao campo: passa reto (MRU)."),
  q("car-03", "facil", "Unesp", "Um elétron é lançado em um campo magnético uniforme com velocidade perpendicular às linhas de campo. Desprezando outras forças, sua trajetória é:",
    ["uma circunferência.", "uma reta.", "uma parábola.", "uma hélice."],
    "A força magnética é sempre perpendicular à velocidade e, nesse caso, tem módulo constante. Ela atua como resultante centrípeta e o movimento é circular uniforme. Parábola é a trajetória em campo elétrico uniforme, não em campo magnético.",
    "Perpendicular ao campo: gira (MCU)."),
  q("car-04", "facil", "UFPR", "Uma carga é lançada em um campo magnético uniforme com velocidade que forma 30° com as linhas de campo. A trajetória é:",
    ["uma hélice.", "uma circunferência.", "uma reta.", "uma parábola."],
    "A componente da velocidade paralela ao campo não sofre força e se mantém (MRU). A componente perpendicular produz um movimento circular uniforme. A composição dos dois movimentos é uma hélice cilíndrica.",
    "Oblíquo ao campo: gira e avança, como uma mola (hélice)."),
  q("car-05", "facil", "Fuvest", "Em relação aos vetores velocidade e campo magnético, a força magnética que atua sobre uma carga em movimento é sempre:",
    [
      "perpendicular aos dois.",
      "paralela à velocidade.",
      "paralela ao campo.",
      "perpendicular ao campo e paralela à velocidade.",
    ],
    "A força magnética é perpendicular ao plano formado pela velocidade e pelo campo. É isso que a regra do tapa representa: polegar na velocidade, dedos no campo, força saindo da palma.",
    "A força magnética é sempre de lado: perpendicular a v e a B."),

  // ───────── Médio ─────────
  q("car-06", "medio", "Fuvest", "Uma partícula com carga de 2,0 µC move-se a 3,0 × 10⁵ m/s perpendicularmente a um campo magnético uniforme de 0,50 T. A intensidade da força magnética sobre ela é:",
    ["0,30 N.", "3,0 N.", "0,030 N.", "0,15 N.", "0,60 N."],
    "F = |q|·v·B·sen 90° = 2,0 × 10⁻⁶ × 3,0 × 10⁵ × 0,50 = 0,30 N. Lembre que 1 µC = 10⁻⁶ C.",
    "Perpendicular: F = |q|·v·B, sem seno para atrapalhar."),
  q("car-07", "medio", "Unicamp", "Um próton (carga 1,6 × 10⁻¹⁹ C) move-se a 2,0 × 10⁶ m/s em uma direção que forma 30° com um campo magnético uniforme de 0,10 T. A intensidade da força magnética é:",
    ["1,6 × 10⁻¹⁴ N.", "3,2 × 10⁻¹⁴ N.", "2,8 × 10⁻¹⁴ N.", "1,6 × 10⁻¹³ N.", "zero."],
    "F = |q|·v·B·sen 30° = 1,6 × 10⁻¹⁹ × 2,0 × 10⁶ × 0,10 × 0,50 = 1,6 × 10⁻¹⁴ N. Usar cos 30° em vez de sen 30° levaria a 2,8 × 10⁻¹⁴ N, que é o erro clássico.",
    "Na força magnética o ângulo entra com SENO."),
  q("car-08", "medio", "Unesp", "Uma partícula carregada penetra em um campo magnético uniforme e passa a descrever uma trajetória curva. Sob a ação exclusiva da força magnética, sua energia cinética:",
    [
      "permanece constante, pois a força é sempre perpendicular à velocidade.",
      "aumenta, pois a força magnética acelera a partícula.",
      "diminui, pois a partícula gasta energia para fazer a curva.",
      "aumenta se a carga for positiva e diminui se for negativa.",
    ],
    "Uma força perpendicular ao deslocamento não realiza trabalho. Logo, a força magnética muda a direção da velocidade, mas não o seu módulo: a energia cinética se conserva.",
    "Força magnética não realiza trabalho: curva sem acelerar."),
  q("car-09", "medio", "UFPR", "Um elétron move-se para a direita, no plano desta página, em uma região onde o campo magnético uniforme é perpendicular à página e entra nela. A força magnética sobre o elétron aponta para:",
    [
      "baixo, no plano da página.",
      "cima, no plano da página.",
      "dentro da página.",
      "fora da página.",
      "a esquerda.",
    ],
    "Pela regra do tapa, com o polegar para a direita e os dedos entrando na página, a palma fica voltada para cima: esse seria o sentido da força sobre uma carga positiva. Como o elétron é negativo, a força tem sentido oposto: para baixo.",
    "Carga negativa: faça a regra e inverta o resultado."),
  q("car-10", "medio", "UERJ", "Uma partícula carregada descreve movimento circular uniforme de raio R em um campo magnético uniforme. Se a intensidade do campo for duplicada, mantendo-se a velocidade da partícula, o raio da trajetória passa a ser:",
    ["R/2.", "2R.", "R.", "R/4.", "4R."],
    "Igualando a força magnética à resultante centrípeta, |q|·v·B = m·v²/R, obtém-se R = m·v/(|q|·B). O raio é inversamente proporcional ao campo: campo duas vezes maior, raio duas vezes menor.",
    "R = m·v/(|q|·B): campo forte aperta a curva."),

  // ───────── Difícil ─────────
  q("car-11", "dificil", "Fuvest", "Um próton (massa 1,6 × 10⁻²⁷ kg e carga 1,6 × 10⁻¹⁹ C) penetra perpendicularmente em um campo magnético uniforme de 0,20 T com velocidade de 2,0 × 10⁶ m/s. O raio da trajetória circular descrita é:",
    ["10 cm.", "1,0 cm.", "1,0 m.", "20 cm.", "5,0 cm."],
    "R = m·v/(|q|·B) = (1,6 × 10⁻²⁷ × 2,0 × 10⁶)/(1,6 × 10⁻¹⁹ × 0,20) = (2,0 × 10⁶ × 10⁻⁸)/0,20 = 0,10 m = 10 cm.",
    "Raio = quantidade de movimento ÷ (carga × campo)."),
  q("car-12", "dificil", "ITA", "Uma partícula carregada descreve movimento circular uniforme, de período T, em um campo magnético uniforme. Se a mesma partícula for lançada no mesmo campo com velocidade duas vezes maior, também perpendicular a ele, o novo período será:",
    ["T.", "2T.", "T/2.", "4T.", "T/4."],
    "T = 2π·R/v e R = m·v/(|q|·B), logo T = 2π·m/(|q|·B): a velocidade se cancela. Com o dobro da velocidade, o raio dobra e a circunferência fica duas vezes maior, mas é percorrida duas vezes mais depressa. O período só depende da razão m/|q| e do campo.",
    "O período no campo magnético não depende da velocidade."),
  q("car-13", "dificil", "IME", "Um próton e uma partícula alfa (núcleo de hélio, com o dobro da carga e quatro vezes a massa do próton) penetram com a mesma velocidade, perpendicularmente, no mesmo campo magnético uniforme. A razão entre os raios das trajetórias, R(alfa)/R(próton), é:",
    ["2.", "4.", "1/2.", "1.", "8."],
    "R = m·v/(|q|·B). Com a mesma velocidade e o mesmo campo, R é proporcional a m/|q|. Para a partícula alfa, m/q = 4m/(2e) = 2·(m/e): o raio é o dobro do raio do próton.",
    "Mesma velocidade: o raio acompanha m/|q|."),
  q("car-14", "dificil", "ITA", "Um elétron e um próton, com a mesma energia cinética, penetram perpendicularmente no mesmo campo magnético uniforme. Sobre os raios das trajetórias, é correto afirmar que:",
    [
      "o do próton é maior, pois ele tem maior quantidade de movimento.",
      "são iguais, pois as cargas têm o mesmo módulo e as energias são iguais.",
      "o do elétron é maior, pois ele é mais veloz.",
      "o do elétron é maior, pois ele tem menor inércia.",
      "são iguais, pois o raio só depende do campo magnético.",
    ],
    "R = m·v/(|q|·B) = p/(|q|·B). Como a energia cinética é K = p²/(2m), tem-se p = √(2·m·K). Com a mesma energia, a partícula de maior massa tem maior quantidade de movimento. Sendo as cargas iguais em módulo, o próton descreve a circunferência de maior raio, na razão √(m(próton)/m(elétron)), cerca de 43 vezes.",
    "Mesma energia cinética: R é proporcional a √m."),
  q("car-15", "dificil", "Unicamp", "Em um seletor de velocidades, um feixe de íons atravessa uma região onde existem um campo elétrico uniforme de 2,0 × 10⁴ V/m e um campo magnético uniforme de 0,050 T, perpendiculares entre si e à velocidade dos íons. Atravessam a região sem desvio apenas os íons com velocidade de:",
    ["4,0 × 10⁵ m/s.", "1,0 × 10³ m/s.", "2,5 × 10⁻⁶ m/s.", "4,0 × 10³ m/s.", "1,0 × 10⁵ m/s."],
    "O íon não desvia quando a força elétrica e a magnética se equilibram: |q|·E = |q|·v·B, de onde v = E/B = 2,0 × 10⁴/0,050 = 4,0 × 10⁵ m/s. O resultado não depende da carga nem da massa, e por isso o dispositivo seleciona velocidades.",
    "Seletor de velocidades: v = E/B, para qualquer carga e massa."),
  q("car-16", "dificil", "ITA", "Uma partícula de carga positiva move-se no plano desta página, em uma região onde o campo magnético uniforme é perpendicular à página e sai dela, apontando para o leitor. Vista pelo leitor, a partícula descreve uma circunferência no sentido:",
    [
      "horário.",
      "anti-horário.",
      "horário ou anti-horário, conforme o sentido da velocidade inicial.",
      "horário, mas apenas se a velocidade for maior que E/B.",
    ],
    "Tome o instante em que a partícula se move para a direita. Pela regra do tapa (polegar para a direita, dedos saindo da página), a palma fica voltada para baixo: a força aponta para baixo, onde está o centro da curva. Quem vai para a direita passando acima do centro gira no sentido horário. O sentido de giro não depende da velocidade inicial, só do sinal da carga e do sentido do campo.",
    "Carga positiva, campo vindo para você: gira no sentido horário."),
  q("car-17", "dificil", "IME", "Uma partícula carregada é lançada com velocidade de 4,0 × 10⁶ m/s em uma direção que forma 60° com um campo magnético uniforme. O período do movimento circular associado é de 2,0 × 10⁻⁷ s. O passo da hélice descrita, isto é, a distância percorrida ao longo do campo em uma volta, é:",
    ["0,40 m.", "0,80 m.", "0,69 m.", "0,20 m.", "1,6 m."],
    "Só a componente da velocidade paralela ao campo faz a partícula avançar: v(paralela) = v·cos 60° = 2,0 × 10⁶ m/s. Em uma volta, passo = v(paralela)·T = 2,0 × 10⁶ × 2,0 × 10⁻⁷ = 0,40 m. Usar sen 60° daria 0,69 m: essa é a componente que gira, não a que avança.",
    "Hélice: v·cos θ avança, v·sen θ gira."),
  q("car-18", "dificil", "Unesp", "Em um espectrômetro de massa, íons de mesma carga q e mesma velocidade v entram perpendicularmente em um campo magnético uniforme B, descrevem meia circunferência e atingem uma chapa situada no mesmo plano da fenda de entrada. Para um íon de massa m, a distância entre a fenda e o ponto de impacto é:",
    ["2m·v/(|q|·B).", "m·v/(|q|·B).", "π·m·v/(|q|·B).", "m·v/(2|q|·B).", "2π·m/(|q|·B)."],
    "Depois de meia volta, o íon está no ponto diametralmente oposto ao de entrada. A distância é o diâmetro: 2R = 2m·v/(|q|·B). Como ela é proporcional à massa, isótopos diferentes atingem a chapa em pontos diferentes, e é assim que o aparelho os separa.",
    "Meia volta: a distância é o diâmetro, não o raio."),
  q("car-19", "dificil", "Fuvest", "Na fotografia de uma câmara de bolhas imersa em campo magnético uniforme, a trajetória de uma partícula carregada aparece como uma espiral cujo raio diminui progressivamente. A explicação é que a partícula:",
    [
      "perde velocidade ao interagir com o líquido, e o raio é proporcional à velocidade.",
      "ganha velocidade com o campo magnético, e o raio é inversamente proporcional à velocidade.",
      "perde carga elétrica ao longo do caminho, o que reduz o raio.",
      "é atraída pelo polo magnético situado no centro da espiral.",
    ],
    "O campo magnético não altera o módulo da velocidade; quem freia a partícula são as colisões com o líquido da câmara. Como R = m·v/(|q|·B), com B, m e q constantes, o raio diminui junto com a velocidade. Se a carga diminuísse, o raio aumentaria, e não o contrário.",
    "Espiral fechando = partícula perdendo velocidade."),
  q("car-20", "dificil", "ITA", "Uma partícula de massa 2,0 × 10⁻⁶ kg e carga positiva de 4,0 × 10⁻⁶ C move-se horizontalmente, em linha reta e com velocidade constante, em uma região onde há um campo magnético uniforme e horizontal de 0,50 T, perpendicular à velocidade, além do campo gravitacional (g = 10 m/s²). A velocidade da partícula é:",
    ["10 m/s.", "1,0 m/s.", "5,0 m/s.", "20 m/s.", "100 m/s."],
    "Para o movimento ser retilíneo e uniforme, a força magnética deve equilibrar o peso: |q|·v·B = m·g. Então v = m·g/(|q|·B) = (2,0 × 10⁻⁶ × 10)/(4,0 × 10⁻⁶ × 0,50) = 10 m/s. Com velocidade e campo horizontais e perpendiculares entre si, a força magnética é vertical, como precisa ser.",
    "Voo reto na horizontal: força magnética = peso."),

  // ───────── Desafio ─────────
  q("car-21", "desafio", "ITA", "Uma partícula de massa m e carga q, inicialmente em repouso, é acelerada por uma diferença de potencial U e, em seguida, penetra perpendicularmente em um campo magnético uniforme de intensidade B. O raio da trajetória circular é:",
    [
      "(1/B)·√(2m·U/|q|).",
      "(1/B)·√(2|q|·U/m).",
      "2m·U/(|q|·B²).",
      "(1/B)·√(m·U/(2|q|)).",
      "m·U/(|q|·B).",
    ],
    "Na aceleração, |q|·U = m·v²/2, logo v = √(2|q|·U/m). No campo, R = m·v/(|q|·B) = (m/(|q|·B))·√(2|q|·U/m) = (1/B)·√(2m·U/|q|). Íons mais pesados, acelerados pela mesma tensão, descrevem raios maiores: é o princípio do espectrômetro de massa.",
    "Duas etapas: a tensão dá a velocidade (q·U = m·v²/2), o campo dá o raio."),
  q("car-22", "desafio", "IME", "Uma região de campo magnético uniforme B, perpendicular à página, é limitada por dois planos paralelos separados por uma distância L. Uma partícula de massa m e carga q penetra nessa região perpendicularmente ao primeiro plano. A maior velocidade com que ela pode entrar e ainda assim não atravessar a região, retornando pelo mesmo plano, é:",
    ["|q|·B·L/m.", "|q|·B·L/(2m).", "2|q|·B·L/m.", "m/(|q|·B·L).", "|q|·B·L/(π·m)."],
    "Ao entrar perpendicularmente à fronteira, a partícula descreve uma semicircunferência cujo centro está sobre o próprio plano de entrada. A maior profundidade atingida é igual ao raio R. Para não alcançar o segundo plano, R ≤ L, ou seja, m·v/(|q|·B) ≤ L. A velocidade limite é v = |q|·B·L/m.",
    "Entrando de frente, a partícula penetra exatamente um raio."),
  q("car-23", "desafio", "ITA", "Em um cíclotron, prótons de massa m e carga e giram em um campo magnético uniforme B e são extraídos quando o raio da órbita atinge o valor máximo R, limitado pelo tamanho do aparelho. A energia cinética máxima dos prótons é:",
    ["e²·B²·R²/(2m).", "e·B·R/(2m).", "e²·B²·R²/m.", "e·B·R²/(2m).", "m·e²·B²·R²/2."],
    "Da condição R = m·v/(e·B), a velocidade na órbita de raio R é v = e·B·R/m. A energia cinética é K = m·v²/2 = e²·B²·R²/(2m). Por isso, para obter energias maiores é preciso aumentar o campo ou o raio da máquina. A frequência de giro, e·B/(2π·m), é a mesma em todas as órbitas, o que permite acelerar com uma tensão alternada de frequência fixa.",
    "Cíclotron: a energia cresce com (B·R)²."),
  q("car-24", "desafio", "IME", "Dois íons de mesma carga, com massas m e 2m, entram com velocidades v e 3v, respectivamente, em uma região semi-infinita de campo magnético uniforme, ambos perpendicularmente ao plano que limita a região e às linhas de campo. Cada um descreve meia circunferência e sai da região. A razão entre os tempos de permanência no campo, t(2m)/t(m), é:",
    ["2.", "6.", "2/3.", "3.", "1."],
    "Cada íon percorre meia volta, o que leva meio período: t = T/2 = π·m/(|q|·B). Esse tempo não depende da velocidade, apenas da massa (para a mesma carga e o mesmo campo). O íon de massa 2m demora o dobro do tempo, ainda que seja três vezes mais rápido e percorra um arco seis vezes maior.",
    "Meia volta = meio período, e o período ignora a velocidade."),
  q("car-25", "desafio", "ITA", "Uma partícula de massa m e carga q é lançada em um campo magnético uniforme B com velocidade v que forma um ângulo θ com as linhas de campo. O número de voltas completas que ela executa enquanto avança uma distância D ao longo do campo é:",
    [
      "D·|q|·B/(2π·m·v·cos θ).",
      "D·|q|·B/(2π·m·v·sen θ).",
      "2π·m·v·cos θ/(D·|q|·B).",
      "D·|q|·B·cos θ/(2π·m·v).",
      "D·|q|·B/(m·v·cos θ).",
    ],
    "O período de cada volta é T = 2π·m/(|q|·B), independentemente de θ. O avanço por volta (passo) é p = v·cos θ·T = 2π·m·v·cos θ/(|q|·B). O número de voltas é D/p = D·|q|·B/(2π·m·v·cos θ). Quanto mais próximo de 90° for o ângulo, mais apertada a hélice e maior o número de voltas.",
    "Número de voltas = distância ÷ passo."),
  q("car-26", "desafio", "IME", "Uma região de campo magnético uniforme B, perpendicular à página, tem largura L. Uma partícula de massa m e carga q entra perpendicularmente à fronteira com velocidade v suficiente para atravessar a região (m·v/(|q|·B) > L). Ao sair pela fronteira oposta, a direção de sua velocidade terá sido desviada de um ângulo α tal que:",
    [
      "sen α = |q|·B·L/(m·v).",
      "tg α = |q|·B·L/(m·v).",
      "cos α = |q|·B·L/(m·v).",
      "sen α = m·v/(|q|·B·L).",
      "α = |q|·B·L/(m·v), em radianos.",
    ],
    "Dentro da região a trajetória é um arco de raio R = m·v/(|q|·B), com centro sobre a fronteira de entrada. O ângulo de desvio da velocidade é igual ao ângulo central do arco percorrido. Como o arco termina quando a partícula avançou uma profundidade L, tem-se L = R·sen α, isto é, sen α = L/R = |q|·B·L/(m·v).",
    "O desvio da velocidade é o ângulo central do arco: L = R·sen α."),
  q("car-27", "desafio", "ITA", "Em certa região existem um campo elétrico uniforme E e um campo magnético uniforme B, paralelos entre si. Uma partícula de massa m e carga q é lançada perpendicularmente a esses campos. Desprezando a gravidade, o deslocamento da partícula na direção dos campos, ao completar a primeira volta, é:",
    [
      "2π²·m·E/(|q|·B²).",
      "π²·m·E/(|q|·B²).",
      "2π·m·E/(|q|·B).",
      "4π²·m·E/(|q|·B²).",
      "zero, pois a força magnética não realiza trabalho.",
    ],
    "A força magnética age no plano perpendicular aos campos e produz o movimento circular de período T = 2π·m/(|q|·B). A força elétrica age ao longo dos campos e produz aceleração constante a = |q|·E/m, partindo do repouso nessa direção. Em uma volta, o deslocamento é a·T²/2 = (|q|·E/2m)·(4π²·m²/(q²·B²)) = 2π²·m·E/(|q|·B²). A trajetória é uma hélice de passo crescente.",
    "E paralelo a B: gira com período fixo e acelera ao longo do eixo."),
  q("car-28", "desafio", "IME", "Íons atravessam sem desvio um seletor de velocidades, onde existem um campo elétrico E e um campo magnético B₁ cruzados, e em seguida penetram perpendicularmente em um segundo campo magnético B₂, no qual descrevem semicircunferências de raio R. A razão entre a massa e a carga desses íons, m/|q|, é:",
    ["B₁·B₂·R/E.", "E·R/(B₁·B₂).", "B₂·R/(E·B₁).", "E/(B₁·B₂·R).", "B₁·R/(E·B₂)."],
    "No seletor, só passam os íons com v = E/B₁. No segundo campo, R = m·v/(|q|·B₂), de onde m/|q| = B₂·R/v = B₁·B₂·R/E. Medindo o raio, determina-se a razão massa-carga: é o espectrômetro de massa de Bainbridge.",
    "Seletor dá v = E/B₁; a curva dá m/|q| = B₂·R/v."),
];
