import type { Questao } from "@/lib/tipos";
import { criar } from "../criar";

const c = criar("campo-corrente");

const MU = "(Dado: µ₀ = 4π × 10⁻⁷ T·m/A)";

/** Campo magnético gerado por correntes. A primeira alternativa é a correta. */
export const questoesCampoCorrente: Questao[] = [
  // ───────── Fácil ─────────
  c("cor-01", "facil", "ENEM", "Em 1820, Oersted observou que a agulha de uma bússola se desviava quando uma corrente elétrica passava por um fio próximo. A experiência mostrou que:",
    [
      "correntes elétricas criam campo magnético.",
      "ímãs criam corrente elétrica em fios parados.",
      "a agulha da bússola fica eletricamente carregada.",
      "o fio se transforma em ímã permanente.",
    ],
    "A agulha só se desvia enquanto há corrente, e o desvio se inverte quando a corrente é invertida. Cargas em movimento geram campo magnético ao seu redor: é o elo entre eletricidade e magnetismo.",
    "Oersted: corrente passando, bússola girando."),
  c("cor-02", "facil", "Unesp", "As linhas do campo magnético criado por um fio retilíneo longo percorrido por corrente são:",
    [
      "circunferências centradas no fio, em planos perpendiculares a ele.",
      "retas paralelas ao fio.",
      "retas que saem radialmente do fio.",
      "hélices enroladas ao longo do fio.",
    ],
    "O campo de um fio retilíneo circula em torno dele. Em cada ponto, o vetor campo é tangente à circunferência que passa por esse ponto e tem centro no fio, e é perpendicular tanto ao fio quanto ao raio.",
    "O campo abraça o fio em círculos."),
  c("cor-03", "facil", "UERJ", "Na regra da mão direita aplicada a um fio retilíneo, o polegar e os demais dedos indicam, respectivamente:",
    [
      "o sentido da corrente e o sentido das linhas de campo.",
      "o sentido das linhas de campo e o sentido da corrente.",
      "o sentido da força e o sentido da corrente.",
      "o polo norte e o polo sul do fio.",
    ],
    "O polegar aponta no sentido convencional da corrente. Os outros dedos, ao envolver o fio, mostram o sentido em que o campo circula ao redor dele.",
    "Polegar na corrente, dedos abraçando: o abraço é o campo."),
  c("cor-04", "facil", "UFPR", "A intensidade do campo magnético a uma distância d de um fio retilíneo longo vale B. A uma distância 2d do mesmo fio, a intensidade é:",
    ["B/2.", "B/4.", "2B.", "B.", "4B."],
    "Para o fio retilíneo longo, B = µ₀·i/(2π·d): o campo é inversamente proporcional à distância, e não ao quadrado dela. Dobrando a distância, o campo cai à metade.",
    "No fio reto, B cai com 1/d (não com 1/d²)."),
  c("cor-05", "facil", "Fuvest", "No interior de um solenoide longo percorrido por corrente, longe das extremidades, o campo magnético é:",
    [
      "praticamente uniforme e paralelo ao eixo do solenoide.",
      "nulo, pois os campos das espiras se cancelam.",
      "perpendicular ao eixo e variável de ponto a ponto.",
      "circular, em torno do eixo do solenoide.",
    ],
    "Dentro de um solenoide longo, as linhas de campo são retas paralelas ao eixo e igualmente espaçadas: campo uniforme. Fora dele, o campo é muito mais fraco. O solenoide se comporta como um ímã em barra.",
    "Solenoide: por dentro, campo reto e uniforme, como um ímã em barra."),

  // ───────── Médio ─────────
  c("cor-06", "medio", "Fuvest", `Um fio retilíneo muito longo é percorrido por uma corrente de 10 A. A intensidade do campo magnético em um ponto a 2,0 cm do fio é:\n${MU}`,
    ["1,0 × 10⁻⁴ T.", "1,0 × 10⁻⁶ T.", "2,0 × 10⁻⁵ T.", "4,0 × 10⁻⁴ T.", "1,0 × 10⁻² T."],
    "B = µ₀·i/(2π·d) = (4π × 10⁻⁷ × 10)/(2π × 2,0 × 10⁻²) = (2 × 10⁻⁷ × 10)/(2,0 × 10⁻²) = 1,0 × 10⁻⁴ T. O erro mais comum é esquecer de converter centímetros em metros.",
    "Atalho: no fio reto, B = 2 × 10⁻⁷ · i/d."),
  c("cor-07", "medio", "Unicamp", `Uma espira circular de raio 10 cm é percorrida por uma corrente de 5,0 A. A intensidade do campo magnético no centro da espira é:\n${MU}`,
    ["π × 10⁻⁵ T.", "π × 10⁻⁶ T.", "1,0 × 10⁻⁵ T.", "2π × 10⁻⁵ T.", "π × 10⁻⁷ T."],
    "B = µ₀·i/(2R) = (4π × 10⁻⁷ × 5,0)/(2 × 0,10) = (20π × 10⁻⁷)/0,20 = π × 10⁻⁵ T, cerca de 3,1 × 10⁻⁵ T. Na espira não aparece o π no denominador, ao contrário do fio retilíneo.",
    "Espira: µ₀·i/(2R). Fio reto: µ₀·i/(2π·d). O π só mora no fio."),
  c("cor-08", "medio", "Unesp", `Um solenoide de 50 cm de comprimento tem 1000 espiras e é percorrido por uma corrente de 2,0 A. A intensidade do campo magnético em seu interior é:\n${MU}`,
    ["1,6π × 10⁻³ T.", "8,0π × 10⁻⁴ T.", "4,0π × 10⁻⁴ T.", "1,6π × 10⁻⁵ T.", "8,0π × 10⁻³ T."],
    "A densidade de espiras é n = N/L = 1000/0,50 = 2000 espiras/m. Então B = µ₀·n·i = 4π × 10⁻⁷ × 2000 × 2,0 = 1,6π × 10⁻³ T, aproximadamente 5,0 × 10⁻³ T.",
    "Solenoide: o que conta é espira por metro, N/L."),
  c("cor-09", "medio", "UFPR", "Um fio retilíneo é perpendicular ao plano desta página e conduz corrente saindo da página, em direção ao leitor. Vistas pelo leitor, as linhas de campo magnético em torno do fio são circunferências percorridas no sentido:",
    [
      "anti-horário.",
      "horário.",
      "horário acima do fio e anti-horário abaixo dele.",
      "radial, afastando-se do fio.",
    ],
    "Com o polegar da mão direita apontando para o leitor, os demais dedos se curvam no sentido anti-horário. Se a corrente entrasse na página, o campo circularia no sentido horário.",
    "Corrente saindo da página: campo anti-horário. Entrando: horário."),
  c("cor-10", "medio", "UERJ", "Olhando de frente para uma das extremidades de um solenoide, um observador vê a corrente circular nas espiras no sentido anti-horário. Essa extremidade se comporta como:",
    [
      "polo norte, pois as linhas de campo saem por ela.",
      "polo sul, pois as linhas de campo entram por ela.",
      "polo norte, pois as linhas de campo entram por ela.",
      "região neutra, pois o campo só existe no interior.",
    ],
    "Curvando os dedos da mão direita no sentido anti-horário, o polegar aponta para o observador: o campo sai por essa face, que é, portanto, o polo norte. A face em que a corrente circula no sentido horário é o polo sul.",
    "Anti-horário = Norte (as pontas do N giram assim). Horário = Sul."),

  // ───────── Difícil ─────────
  c("cor-11", "dificil", "Fuvest", `Dois fios retilíneos longos e paralelos, separados por 20 cm, conduzem correntes de 10 A em sentidos opostos. A intensidade do campo magnético resultante no ponto médio entre eles é:\n${MU}`,
    ["4,0 × 10⁻⁵ T.", "zero.", "2,0 × 10⁻⁵ T.", "1,0 × 10⁻⁵ T.", "8,0 × 10⁻⁵ T."],
    "Cada fio cria, a 10 cm, B = 2 × 10⁻⁷ × 10/0,10 = 2,0 × 10⁻⁵ T. Com correntes opostas, a regra da mão direita mostra que os dois campos têm o mesmo sentido na região entre os fios, e portanto se somam: 4,0 × 10⁻⁵ T. O campo só se anularia no meio se as correntes tivessem o mesmo sentido.",
    "Entre dois fios: correntes opostas somam os campos; iguais subtraem."),
  c("cor-12", "dificil", "ITA", "Dois fios retilíneos longos e paralelos, A e B, distam 40 cm um do outro e conduzem correntes de mesmo sentido, de 6,0 A e 2,0 A, respectivamente. O campo magnético resultante é nulo em um ponto do plano dos fios situado:",
    [
      "entre os fios, a 30 cm de A.",
      "entre os fios, a 10 cm de A.",
      "fora da região entre os fios, a 20 cm de B.",
      "fora da região entre os fios, a 60 cm de A.",
      "no ponto médio entre os fios.",
    ],
    "Com correntes de mesmo sentido, os campos têm sentidos opostos apenas na região entre os fios. Igualando as intensidades: 6,0/x = 2,0/(40 − x), o que dá 240 − 6x = 2x e x = 30 cm, medidos a partir de A. O ponto fica mais perto do fio de menor corrente.",
    "O ponto de campo nulo fica sempre mais perto da corrente mais fraca."),
  c("cor-13", "dificil", "Unicamp", "Na montagem de Oersted, um fio horizontal é estendido na direção norte-sul, logo acima de uma bússola. Fecha-se o circuito e a corrente passa a percorrer o fio de sul para norte. O polo norte da agulha se desvia para:",
    ["oeste.", "leste.", "cima, saindo do plano horizontal.", "sul, invertendo-se completamente."],
    "Com o polegar apontando para o norte, os dedos da mão direita passam por baixo do fio dirigidos de leste para oeste. Assim, na posição da agulha (abaixo do fio) o campo da corrente aponta para oeste, e o polo norte da agulha é empurrado nesse sentido. Se o fio estivesse abaixo da bússola, o desvio seria para leste.",
    "Corrente para o norte, fio por cima: agulha vai para oeste."),
  c("cor-14", "dificil", "Fuvest", "Para que a experiência de Oersted mostre claramente o efeito da corrente, o fio deve ser colocado paralelamente à agulha da bússola (direção norte-sul), e não perpendicularmente a ela. A razão é que, com o fio na direção leste-oeste:",
    [
      "o campo da corrente, na posição da agulha, fica na própria direção norte-sul e pode não produzir giro algum.",
      "o campo da corrente se anula, pois é cancelado pela rotação da Terra.",
      "a corrente deixa de criar campo magnético abaixo do fio.",
      "a agulha gira tão depressa que o desvio não pode ser observado.",
    ],
    "O campo do fio é perpendicular a ele. Com o fio na direção leste-oeste, o campo abaixo dele aponta para o norte ou para o sul. Se apontar para o norte, apenas reforça o campo terrestre e a agulha não se mexe. Com o fio na direção norte-sul, o campo da corrente é perpendicular ao da Terra, e a agulha gira até a direção do campo resultante.",
    "Para a agulha girar, o campo novo tem de ser atravessado ao campo da Terra."),
  c("cor-15", "dificil", "ITA", `Um fio retilíneo longo e horizontal, na direção norte-sul, passa 5,0 cm acima de uma bússola. Quando se estabelece a corrente, a agulha gira 45° em relação à direção inicial. Sabendo que a componente horizontal do campo terrestre no local vale 2,0 × 10⁻⁵ T, a corrente no fio é:\n${MU}`,
    ["5,0 A.", "2,5 A.", "10 A.", "0,50 A.", "50 A."],
    "O campo do fio é perpendicular ao campo terrestre horizontal. Um desvio de 45° significa tg 45° = B(fio)/B(Terra) = 1, isto é, B(fio) = 2,0 × 10⁻⁵ T. De B = 2 × 10⁻⁷·i/d, vem i = (2,0 × 10⁻⁵ × 5,0 × 10⁻²)/(2 × 10⁻⁷) = 5,0 A.",
    "Desvio de 45° = os dois campos têm a mesma intensidade."),
  c("cor-16", "dificil", "IME", "Duas espiras circulares, concêntricas e coplanares, têm raios R e 2R e são percorridas por correntes de mesma intensidade i, em sentidos opostos. A intensidade do campo magnético no centro comum é:",
    ["µ₀·i/(4R).", "3µ₀·i/(4R).", "zero.", "µ₀·i/(2R).", "µ₀·i/R."],
    "A espira menor cria µ₀·i/(2R) e a maior, µ₀·i/(4R). Como as correntes circulam em sentidos opostos, os campos no centro têm sentidos opostos: B = µ₀·i/(2R) − µ₀·i/(4R) = µ₀·i/(4R), com o sentido do campo da espira menor. Se as correntes tivessem o mesmo sentido, o resultado seria 3µ₀·i/(4R).",
    "Mesma corrente, raio menor, campo maior no centro."),
  c("cor-17", "dificil", "Unesp", "O solenoide X tem N espiras, comprimento L e é percorrido por corrente i. O solenoide Y tem 2N espiras, comprimento 2L, raio duas vezes maior e a mesma corrente i. Sendo ambos longos, a razão entre as intensidades dos campos em seus interiores, B(Y)/B(X), é:",
    ["1.", "2.", "4.", "1/2.", "1/4."],
    "B = µ₀·(N/L)·i. O solenoide Y tem o dobro de espiras no dobro do comprimento, ou seja, a mesma densidade de espiras N/L. O raio não entra na expressão do campo de um solenoide longo. Com a mesma corrente, os campos são iguais.",
    "No solenoide, o raio não importa e o que vale é N/L."),
  c("cor-18", "dificil", "UFPR", "Um fio retilíneo longo é vertical e conduz corrente de baixo para cima. Em um ponto P situado a leste do fio, o campo magnético criado pela corrente aponta para:",
    ["o norte.", "o sul.", "o oeste.", "o leste.", "cima."],
    "Com o polegar da mão direita para cima, os dedos giram no sentido anti-horário para quem olha de cima. Visto de cima, com o norte à frente e o leste à direita, o sentido anti-horário passa pelo lado leste dirigindo-se para o norte. Logo, em P o campo aponta para o norte.",
    "Vista de cima, corrente subindo: campo anti-horário."),
  c("cor-19", "dificil", "ITA", "Dois fios retilíneos longos e isolados entre si coincidem com os eixos x e y de um sistema cartesiano e conduzem correntes de mesma intensidade i, nos sentidos positivos de x e de y. Com o eixo z saindo do plano xy, o campo magnético no ponto P = (a, −a), com a > 0, tem intensidade e sentido:",
    [
      "µ₀·i/(π·a), entrando no plano (−z).",
      "µ₀·i/(π·a), saindo do plano (+z).",
      "zero.",
      "µ₀·i/(2π·a), entrando no plano (−z).",
      "µ₀·i/(2π·a), saindo do plano (+z).",
    ],
    "Cada fio está à distância a de P e cria campo de intensidade µ₀·i/(2π·a). Pela regra da mão direita, o fio sobre o eixo x (corrente para +x) produz campo entrando no plano nos pontos com y < 0; o fio sobre o eixo y (corrente para +y) produz campo entrando no plano nos pontos com x > 0. Em P os dois se somam: µ₀·i/(π·a), entrando. Já no ponto (a, a) eles se cancelariam.",
    "Fios cruzados: em dois quadrantes os campos se somam, nos outros dois se anulam."),
  c("cor-20", "dificil", "IME", "Um fio percorrido por corrente i é formado por dois trechos retilíneos muito longos, alinhados sobre a mesma reta, unidos por uma semicircunferência de raio R cujo centro C está sobre essa reta. A intensidade do campo magnético em C é:",
    ["µ₀·i/(4R).", "µ₀·i/(2R).", "µ₀·i/(2π·R).", "µ₀·i/(4π·R).", "µ₀·i/(4R) + µ₀·i/(2π·R)."],
    "Os trechos retilíneos apontam para C (seus prolongamentos passam por ele), e um trecho de corrente não cria campo em pontos de sua própria reta. Resta a semicircunferência, que produz metade do campo de uma espira completa: (1/2)·µ₀·i/(2R) = µ₀·i/(4R).",
    "Corrente não cria campo sobre a própria reta; meio arco, meio campo."),

  // ───────── Desafio ─────────
  c("cor-21", "desafio", "ITA", "Dois fios retilíneos longos e paralelos, perpendiculares ao plano da página, conduzem correntes de mesma intensidade i e mesmo sentido. Os pontos em que os fios furam a página e um ponto P formam um triângulo equilátero de lado a. A intensidade do campo magnético resultante em P é:",
    ["√3·µ₀·i/(2π·a).", "µ₀·i/(2π·a).", "µ₀·i/(π·a).", "√3·µ₀·i/(4π·a).", "zero."],
    "Cada fio cria em P um campo de intensidade B₀ = µ₀·i/(2π·a), perpendicular ao segmento que liga o fio a P. Como esses segmentos formam 60° entre si e as correntes têm o mesmo sentido, os dois vetores campo também formam 60°. A resultante é 2·B₀·cos 30° = √3·B₀. Com correntes opostas, o ângulo entre os campos seria 120° e a resultante valeria B₀.",
    "O campo é perpendicular ao raio: o ângulo entre os campos é o ângulo entre os raios."),
  c("cor-22", "desafio", "IME", "Um fio retilíneo muito longo, percorrido por corrente i₁, tangencia uma espira circular de raio R, percorrida por corrente i₂, estando ambos no mesmo plano e isolados entre si. Para que o campo magnético seja nulo no centro da espira, com os sentidos das correntes adequados, a razão i₁/i₂ deve ser:",
    ["π.", "1/π.", "2π.", "1.", "2."],
    "O centro da espira está à distância R do fio. Igualando as intensidades: µ₀·i₁/(2π·R) = µ₀·i₂/(2R), o que dá i₁ = π·i₂. O fio precisa de uma corrente cerca de três vezes maior porque, à mesma distância R, um fio reto é menos eficiente que a espira, que envolve o ponto por todos os lados.",
    "À mesma distância, a espira vence o fio reto por um fator π."),
  c("cor-23", "desafio", "ITA", "No modelo de Bohr do átomo de hidrogênio, o elétron (carga de módulo e) descreve órbita circular de raio r com frequência f. Para um observador que vê o elétron girar no sentido anti-horário, o campo magnético produzido no centro da órbita tem intensidade e sentido:",
    [
      "µ₀·e·f/(2r), entrando no plano da órbita.",
      "µ₀·e·f/(2r), saindo do plano da órbita.",
      "µ₀·e·f/(2π·r), entrando no plano da órbita.",
      "µ₀·e/(2r·f), saindo do plano da órbita.",
      "µ₀·e·f/(4r), entrando no plano da órbita.",
    ],
    "A carga e passa f vezes por segundo por um ponto da órbita, o que equivale a uma corrente i = e·f. O campo no centro é o de uma espira: B = µ₀·e·f/(2r). Como o elétron é negativo, a corrente convencional circula no sentido contrário ao do movimento, ou seja, no sentido horário, e a regra da mão direita dá campo entrando no plano.",
    "Carga em órbita é espira: i = q·f. Se a carga é negativa, inverta o sentido."),
  c("cor-24", "desafio", "IME", "Quatro fios retilíneos longos e paralelos passam pelos vértices de um quadrado de lado L, perpendicularmente ao plano do quadrado. Três deles conduzem corrente i em um sentido e o quarto conduz corrente i no sentido oposto. A intensidade do campo magnético no centro do quadrado é:",
    ["√2·µ₀·i/(π·L).", "µ₀·i/(π·L).", "zero.", "2√2·µ₀·i/(π·L).", "µ₀·i/(√2·π·L)."],
    "Cada fio dista L·√2/2 do centro e cria ali um campo B₀ = µ₀·i/(2π·L·√2/2) = µ₀·i/(√2·π·L). Com as quatro correntes iguais e de mesmo sentido, os campos de fios diagonalmente opostos se cancelam e o total é zero. Inverter uma corrente equivale a somar a essa situação duas vezes o campo do fio invertido: B = 2·B₀ = √2·µ₀·i/(π·L).",
    "Superposição: parta do caso simétrico (zero) e some só o que mudou."),
  c("cor-25", "desafio", "ITA", "Um solenoide longo, de comprimento L, é construído enrolando-se um fio de comprimento total ℓ em espiras circulares de raio r, bem juntas e em uma única camada. Quando o fio é percorrido por corrente i, a intensidade do campo magnético no interior do solenoide é:",
    ["µ₀·ℓ·i/(2π·r·L).", "µ₀·ℓ·i/(π·r·L).", "µ₀·ℓ·i/L².", "µ₀·L·i/(2π·r·ℓ).", "µ₀·ℓ·i/(2r·L)."],
    "Cada espira consome um comprimento 2π·r de fio, de modo que o número de espiras é N = ℓ/(2π·r). Substituindo em B = µ₀·(N/L)·i, obtém-se B = µ₀·ℓ·i/(2π·r·L). Note que, com o mesmo fio, espiras de raio menor dão mais voltas e, por isso, campo mais intenso.",
    "Número de espiras = comprimento do fio ÷ comprimento de uma volta."),
  c("cor-26", "desafio", "IME", "Um anel isolante de raio R tem carga elétrica Q distribuída uniformemente e gira em torno do eixo que passa pelo seu centro, perpendicular ao seu plano, com velocidade angular constante ω. A intensidade do campo magnético no centro do anel é:",
    ["µ₀·Q·ω/(4π·R).", "µ₀·Q·ω/(2R).", "µ₀·Q·ω/(2π·R).", "µ₀·Q·ω·R/(4π).", "µ₀·Q/(4π·ω·R)."],
    "A carga Q completa uma volta a cada período T = 2π/ω, o que corresponde a uma corrente i = Q/T = Q·ω/(2π). O anel equivale a uma espira de raio R: B = µ₀·i/(2R) = µ₀·Q·ω/(4π·R).",
    "Carga girando: i = Q/T = Q·ω/(2π)."),
  c("cor-27", "desafio", "ITA", "Dois fios retilíneos longos e paralelos, perpendiculares ao plano da página e separados por uma distância 2a, conduzem correntes de mesma intensidade i em sentidos opostos. Em um ponto P da mediatriz do segmento que une os fios, a uma distância y do ponto médio desse segmento, a intensidade do campo magnético resultante é:",
    [
      "µ₀·i·a/[π·(a² + y²)].",
      "µ₀·i·y/[π·(a² + y²)].",
      "µ₀·i/[π·√(a² + y²)].",
      "µ₀·i·a/[2π·(a² + y²)].",
      "zero, por simetria.",
    ],
    "Cada fio está à distância r = √(a² + y²) de P e cria campo B₀ = µ₀·i/(2π·r), perpendicular a r. Com correntes opostas, as componentes paralelas ao segmento que une os fios se cancelam e as componentes ao longo da mediatriz se somam, valendo B₀·(a/r) cada uma. Assim, B = 2·B₀·a/r = µ₀·i·a/[π·(a² + y²)]. Conferindo: para y = 0, B = µ₀·i/(π·a), o dobro do campo de um fio.",
    "Teste a fórmula no caso que você já conhece: aqui, y = 0."),
  c("cor-28", "desafio", "IME", "No interior de um solenoide longo, com 1000 espiras por metro e corrente de 0,50 A, coloca-se uma bobina chata de 10 espiras e raio 5,0 cm, coaxial com o solenoide e centrada em seu eixo. Para que o campo magnético seja nulo no centro da bobina, ela deve ser percorrida, no sentido contrário ao da corrente do solenoide, por uma corrente de:",
    ["5,0 A.", "0,50 A.", "2,5 A.", "10 A.", "50 A."],
    "O campo do solenoide é µ₀·n·i₁ e o da bobina chata, no centro, é N·µ₀·i₂/(2R). Igualando: n·i₁ = N·i₂/(2R), de onde i₂ = 2R·n·i₁/N = (2 × 5,0 × 10⁻² × 1000 × 0,50)/10 = 5,0 A. A constante µ₀ se cancela.",
    "Bobina chata de N espiras: N vezes o campo de uma espira."),
];
