import type { Questao } from "@/lib/tipos";
import { criar } from "../criar";

const m = criar("imas");

/** Ímãs e campo magnético da Terra. A primeira alternativa é a correta. */
export const questoesImas: Questao[] = [
  // ───────── Fácil ─────────
  m("ima-01", "facil", "ENEM", "Um ímã em forma de barra cai no chão e se parte ao meio. O que se obtém?",
    [
      "Dois ímãs completos, cada um com polo norte e polo sul.",
      "Um pedaço só com polo norte e outro só com polo sul.",
      "Dois pedaços de ferro sem magnetismo algum.",
      "Um ímã com dois polos e um pedaço sem polos.",
    ],
    "Os polos de um ímã são inseparáveis. No ponto da quebra surgem um novo polo sul em um pedaço e um novo polo norte no outro, de modo que cada parte continua sendo um ímã completo.",
    "Quebrou o ímã? Ganhou dois ímãs, nunca um polo solto."),
  m("ima-02", "facil", "UERJ", "Aproximam-se os polos norte de dois ímãs em barra. A interação entre eles é de:",
    ["repulsão.", "atração.", "atração seguida de repulsão.", "nenhuma força, pois os polos são iguais."],
    "Polos de mesmo nome se repelem e polos de nomes opostos se atraem. Norte com norte, ou sul com sul, dá repulsão.",
    "Iguais se repelem, opostos se atraem."),
  m("ima-03", "facil", "Fuvest", "A extremidade norte da agulha de uma bússola aponta, aproximadamente, para o norte geográfico da Terra. Isso indica que, perto do norte geográfico, existe:",
    [
      "um polo sul magnético.",
      "um polo norte magnético.",
      "uma grande jazida de ferro.",
      "uma região sem campo magnético.",
    ],
    "O polo norte da agulha é atraído por um polo de nome oposto. Logo, perto do norte geográfico fica um polo sul magnético da Terra, e perto do sul geográfico, um polo norte magnético.",
    "Norte geográfico = sul magnético. Os nomes são trocados."),
  m("ima-04", "facil", "Unesp", "Na região externa de um ímã em barra, as linhas de campo magnético:",
    [
      "saem do polo norte e entram no polo sul.",
      "saem do polo sul e entram no polo norte.",
      "saem dos dois polos e se perdem no espaço.",
      "são retas paralelas ao comprimento da barra em todo o espaço.",
    ],
    "Por convenção, fora do ímã as linhas de campo vão do polo norte para o polo sul. Dentro do ímã elas continuam, do sul para o norte, formando curvas fechadas.",
    "Fora do ímã: Nasce no Norte, Some no Sul."),
  m("ima-05", "facil", "UFPR", "Os materiais que são fortemente atraídos por ímãs, chamados ferromagnéticos, incluem:",
    ["ferro, níquel e cobalto.", "cobre, prata e ouro.", "alumínio, chumbo e zinco.", "vidro, madeira e borracha."],
    "Ferro, níquel, cobalto e muitas de suas ligas são ferromagnéticos. Cobre, ouro, prata, alumínio e chumbo praticamente não respondem a um ímã comum.",
    "FeNiCo: ferro, níquel e cobalto."),
  m("ima-06", "facil", "Unicamp", "No Sistema Internacional, a intensidade do campo magnético é medida em:",
    ["tesla (T).", "newton (N).", "coulomb (C).", "ampère (A).", "volt (V)."],
    "A unidade de campo magnético no SI é o tesla. Um tesla equivale a um newton por ampère-metro: 1 T = 1 N/(A·m).",
    "Campo magnético se mede em tesla, com T de Tesla."),

  // ───────── Médio ─────────
  m("ima-07", "medio", "Fuvest", "Um prego de ferro, que não é ímã, é aproximado do polo sul de um ímã em barra e depois do polo norte do mesmo ímã. O prego é:",
    [
      "atraído nos dois casos, porque o ímã o imanta por indução.",
      "atraído pelo polo sul e repelido pelo polo norte.",
      "repelido pelo polo sul e atraído pelo polo norte.",
      "repelido nos dois casos, porque não tem polos próprios.",
      "atraído apenas pelo polo que estiver mais próximo do norte geográfico.",
    ],
    "O campo do ímã alinha os domínios magnéticos do prego, que vira um ímã temporário. A extremidade do prego mais próxima fica sempre com polo oposto ao do ímã, então há atração qualquer que seja o polo aproximado.",
    "Ferro comum é atraído por qualquer polo. Só ímã com ímã se repele."),
  m("ima-08", "medio", "Unesp", "Duas linhas de campo magnético nunca se cruzam. A razão é que:",
    [
      "em cada ponto do espaço o campo magnético tem uma única direção e um único sentido.",
      "as linhas de campo se repelem como cargas elétricas de mesmo sinal.",
      "o campo magnético é nulo nos pontos em que as linhas se aproximam.",
      "as linhas só existem dentro do ímã, onde ficam paralelas.",
    ],
    "O vetor campo magnético é tangente à linha de campo em cada ponto. Se duas linhas se cruzassem, haveria duas tangentes naquele ponto, ou seja, dois vetores campo diferentes no mesmo lugar, o que não faz sentido.",
    "Um ponto, um só vetor campo. Por isso as linhas não se cruzam."),
  m("ima-09", "medio", "UFPR", "Uma pequena agulha magnética é colocada em um ponto de um campo magnético e fica livre para girar. Na posição de equilíbrio, a agulha fica:",
    [
      "tangente à linha de campo, com o polo norte no sentido do campo.",
      "perpendicular à linha de campo, com o polo norte para fora.",
      "tangente à linha de campo, com o polo sul no sentido do campo.",
      "em qualquer posição, pois o campo não exerce torque sobre ela.",
    ],
    "É assim que se define o sentido do campo magnético: o sentido para o qual aponta o polo norte de uma agulha de prova. A agulha se alinha com o vetor campo, que é tangente à linha de campo naquele ponto.",
    "A agulha é a seta do campo: o norte dela mostra para onde B aponta."),
  m("ima-10", "medio", "Unicamp", "Um ímã permanente de ferro perde suas propriedades magnéticas quando é aquecido acima de certa temperatura (cerca de 770 °C para o ferro). Isso acontece porque:",
    [
      "a agitação térmica desfaz o alinhamento dos domínios magnéticos.",
      "o calor faz os polos norte e sul se fundirem em um único polo.",
      "o ferro derrete nessa temperatura e deixa de ser metal.",
      "os elétrons livres abandonam o ímã com o aquecimento.",
      "o campo magnético da Terra se anula em altas temperaturas.",
    ],
    "Um ímã é um material com os domínios magnéticos alinhados. Acima da temperatura de Curie, a agitação térmica desorganiza esse alinhamento e o material deixa de ser ferromagnético. O ferro só funde a 1538 °C, bem acima disso.",
    "Ponto de Curie: calor demais bagunça os domínios."),
  m("ima-11", "medio", "UERJ", "Em cartas náuticas aparece o valor da declinação magnética de cada região. Essa grandeza é o ângulo entre:",
    [
      "a direção do norte geográfico e a direção apontada pela bússola.",
      "a agulha da bússola e o plano horizontal.",
      "o eixo de rotação da Terra e o plano da órbita.",
      "o equador geográfico e o equador magnético.",
    ],
    "Os polos magnéticos não coincidem com os geográficos, então a bússola não aponta para o norte verdadeiro. A declinação é o ângulo entre as duas direções, medido no plano horizontal. O ângulo da agulha com a horizontal é outra grandeza, a inclinação magnética.",
    "Declinação: desvio para o lado. Inclinação: mergulho para baixo."),
  m("ima-12", "medio", "Fuvest", "Considerando também o interior de um ímã em barra, as linhas de campo magnético:",
    [
      "são curvas fechadas: dentro do ímã vão do polo sul para o polo norte.",
      "começam no polo norte e terminam no polo sul, sem atravessar o ímã.",
      "são curvas fechadas: dentro do ímã vão do polo norte para o polo sul.",
      "começam no centro do ímã e terminam nos dois polos.",
    ],
    "Fora do ímã as linhas vão do norte para o sul; dentro, completam o percurso do sul para o norte. Linhas de campo magnético não têm início nem fim, o que é outra forma de dizer que não existe polo magnético isolado.",
    "Por fora, do N ao S; por dentro, do S ao N. O circuito fecha."),

  // ───────── Difícil ─────────
  m("ima-13", "dificil", "Fuvest", "Três barras metálicas idênticas na aparência, A, B e C, são testadas. Verifica-se que uma extremidade de A repele uma extremidade de B, e que as duas extremidades de A atraem qualquer extremidade de C. Pode-se concluir que:",
    [
      "A e B são ímãs, e C é de ferro não imantado.",
      "A, B e C são ímãs.",
      "apenas A é ímã; B e C são de ferro não imantado.",
      "A e C são ímãs, e B é de ferro não imantado.",
      "nada se pode afirmar sem uma bússola.",
    ],
    "Repulsão só ocorre entre dois ímãs, logo A e B são ímãs. Se C fosse ímã, alguma combinação de extremidades de A e C daria repulsão. Como A atrai C por qualquer ponta, C é ferro comum, imantado por indução.",
    "A prova de que algo é ímã é a repulsão, nunca a atração."),
  m("ima-14", "dificil", "Unicamp", "Duas barras de aparência idêntica, uma delas imantada e a outra de ferro comum, são dispostas em T: a ponta da barra 1 é encostada no meio da barra 2, e observa-se forte atração. Invertendo os papéis (ponta da barra 2 no meio da barra 1), a atração é quase nula. Conclui-se que:",
    [
      "a barra 1 é o ímã, pois o campo de um ímã é intenso nos polos e fraco no meio.",
      "a barra 2 é o ímã, pois só um ímã pode ser atraído pelo meio.",
      "as duas são ímãs, com polos de mesmo nome nas pontas.",
      "nenhuma é ímã, pois ímãs não atraem pela região central.",
    ],
    "Na região central de um ímã em barra o campo externo é muito fraco; ele se concentra nas extremidades. Quando a ponta do ímã (barra 1) toca o ferro, há atração forte. Quando a ponta do ferro toca o meio do ímã, quase nada acontece.",
    "Teste do T: quem atrai com a ponta é o ímã."),
  m("ima-15", "dificil", "UERJ", "Um ímã em barra é serrado transversalmente em três pedaços. Em seguida, os pedaços são reaproximados na mesma ordem e na mesma orientação em que estavam. As faces que foram separadas pelo corte:",
    [
      "atraem-se, pois em cada corte surgem polos de nomes opostos.",
      "repelem-se, pois em cada corte surgem polos de mesmo nome.",
      "não interagem, pois o pedaço do meio fica sem polos.",
      "atraem-se em um dos cortes e repelem-se no outro.",
    ],
    "Cada pedaço vira um ímã completo com a mesma orientação do original. Assim, em cada corte ficam frente a frente o polo sul de um pedaço e o polo norte do pedaço vizinho, que se atraem. O pedaço do meio também tem os dois polos.",
    "Faces de um mesmo corte são polos opostos: voltam a se grudar."),
  m("ima-16", "dificil", "ITA", "Uma agulha magnética pode girar livremente em um plano vertical que contém a direção norte-sul magnética. Em certo local, ela fica em equilíbrio na vertical, com o polo norte apontando para baixo. Esse local fica:",
    [
      "sobre o polo magnético situado no hemisfério norte geográfico.",
      "sobre o equador magnético.",
      "sobre o polo magnético situado no hemisfério sul geográfico.",
      "em qualquer ponto do equador geográfico.",
      "sobre o polo norte geográfico, exatamente.",
    ],
    "A agulha acompanha a direção do campo terrestre. No equador magnético o campo é horizontal; nos polos magnéticos é vertical. O polo norte da agulha aponta para baixo onde as linhas entram na Terra: no polo sul magnético, que fica no hemisfério norte geográfico.",
    "Inclinação de 90° só nos polos magnéticos; 0° no equador magnético."),
  m("ima-17", "dificil", "Unesp", "Sobre o campo magnético da Terra, analise as afirmativas.\nI. O polo norte geográfico fica próximo de um polo sul magnético.\nII. Os polos magnéticos coincidem exatamente com os polos geográficos.\nIII. A polaridade do campo já se inverteu muitas vezes ao longo do tempo geológico.\nEstá correto o que se afirma em:",
    ["Apenas I e III.", "Apenas I e II.", "Apenas II e III.", "Apenas I.", "I, II e III."],
    "I é verdadeira: é por isso que o norte da bússola aponta para lá. II é falsa: há um afastamento entre eles, que origina a declinação magnética, e os polos magnéticos ainda se deslocam com o tempo. III é verdadeira: rochas antigas registram inversões de polaridade.",
    "Os polos magnéticos não são fixos nem coincidem com os geográficos."),
  m("ima-18", "dificil", "UFPR", "Um campo magnético uniforme é aquele que tem a mesma intensidade, direção e sentido em todos os pontos. Ele é representado por linhas:",
    [
      "retas, paralelas e igualmente espaçadas, como entre os polos de um ímã em U.",
      "circulares e concêntricas, como ao redor do polo de um ímã em barra.",
      "retas que divergem de um ponto, como na ponta de um ímã em barra.",
      "curvas que se fecham sobre si mesmas a distâncias cada vez maiores.",
    ],
    "A direção constante exige linhas retas e paralelas; a intensidade constante exige espaçamento igual, já que a densidade de linhas indica a intensidade do campo. A região entre os polos de um ímã em ferradura é o exemplo clássico de campo aproximadamente uniforme.",
    "Uniforme = linhas retas, paralelas e com o mesmo espaçamento."),
  m("ima-19", "dificil", "Fuvest", "Um ímã em barra está deitado sobre uma mesa, com o polo norte à direita e o polo sul à esquerda. Uma bússola é colocada sobre a mesa em um ponto da mediatriz do ímã, à frente do centro da barra. Desprezando o campo da Terra, a agulha fica:",
    [
      "paralela ao ímã, com o polo norte apontando para a esquerda.",
      "paralela ao ímã, com o polo norte apontando para a direita.",
      "perpendicular ao ímã, com o polo norte apontando para a barra.",
      "perpendicular ao ímã, com o polo norte apontando para longe da barra.",
    ],
    "Fora do ímã, as linhas de campo saem do polo norte (à direita) e voltam para o polo sul (à esquerda). Sobre a mediatriz, a linha passa paralela à barra, no sentido da direita para a esquerda. O norte da agulha segue esse sentido.",
    "Ao lado do ímã, o campo corre do N para o S, na contramão do eixo S→N."),
  m("ima-20", "dificil", "Unicamp", "Uma bússola é colocada sobre o prolongamento do eixo de um ímã em barra, próxima ao polo norte do ímã. Desprezando o campo terrestre, a agulha fica alinhada com o eixo do ímã e:",
    [
      "com o polo sul voltado para o ímã.",
      "com o polo norte voltado para o ímã.",
      "girando continuamente, sem posição de equilíbrio.",
      "com qualquer orientação, pois o campo é nulo nesse ponto.",
    ],
    "Junto ao polo norte, as linhas de campo saem do ímã, de modo que ali o campo aponta para longe da barra. O polo norte da agulha aponta nesse sentido, e o polo sul fica voltado para o ímã, atraído pelo polo norte dele.",
    "Perto do polo N do ímã, o campo aponta para fora: a agulha vira as costas."),
  m("ima-21", "dificil", "Unesp", "O interior da Terra tem temperaturas de milhares de graus Celsius, muito acima do ponto de Curie do ferro. A explicação aceita para a existência do campo magnético terrestre é que ele se deve:",
    [
      "a correntes elétricas no núcleo externo, formado por ferro e níquel líquidos em movimento.",
      "a um enorme ímã permanente de ferro sólido no centro do planeta.",
      "às jazidas de magnetita espalhadas pela crosta terrestre.",
      "à atração gravitacional entre a Terra e a Lua.",
      "ao atrito da atmosfera com a superfície durante a rotação do planeta.",
    ],
    "Acima do ponto de Curie nenhum material permanece imantado, o que descarta a hipótese do ímã permanente. O campo é gerado pelo movimento do metal líquido condutor do núcleo externo, que equivale a correntes elétricas: é o chamado geodínamo.",
    "A Terra não é um ímã de geladeira: é um eletroímã natural."),
  m("ima-22", "dificil", "ENEM", "As auroras polares são luzes que aparecem no céu em altas latitudes. Elas ocorrem quando partículas eletricamente carregadas vindas do Sol atingem a alta atmosfera. O fato de as auroras se concentrarem perto dos polos se explica porque essas partículas:",
    [
      "são guiadas pelas linhas do campo magnético terrestre, que mergulham na atmosfera nas regiões polares.",
      "são atraídas pelo gelo, que é um material ferromagnético.",
      "perdem a carga elétrica ao cruzar a linha do equador.",
      "são mais leves que o ar e sobem em direção aos polos.",
      "só são emitidas pelo Sol na direção dos polos da Terra.",
    ],
    "O campo magnético da Terra desvia as partículas carregadas do vento solar. Elas espiralam em torno das linhas de campo e são conduzidas ao longo delas até as regiões polares, onde as linhas entram na atmosfera e as partículas colidem com os gases, que emitem luz.",
    "O campo da Terra é escudo no equador e funil nos polos."),

  // ───────── Desafio ─────────
  m("ima-23", "desafio", "ITA", "Dois ímãs em barra idênticos são fixados sobre o mesmo eixo, com os polos norte frente a frente e separados por certa distância. No ponto médio do segmento que une esses dois polos, o campo magnético resultante é:",
    [
      "nulo.",
      "o dobro do campo de um só ímã, apontando para a esquerda.",
      "o dobro do campo de um só ímã, apontando para a direita.",
      "igual ao campo de um só ímã, perpendicular ao eixo.",
      "igual ao campo de um só ímã, ao longo do eixo.",
    ],
    "Pela simetria, cada ímã produz no ponto médio um campo de mesma intensidade, dirigido para longe do seu polo norte. Os dois vetores têm a mesma direção e sentidos opostos, e a soma é zero. Se um dos ímãs fosse invertido (norte de frente para sul), os campos se somariam.",
    "Campo é vetor: iguais e opostos se anulam."),
  m("ima-24", "desafio", "Fuvest", "Em um local onde a componente horizontal do campo magnético terrestre vale 2,0 × 10⁻⁵ T e aponta para o norte, um ímã é aproximado e cria, na posição da bússola, um campo horizontal dirigido para leste. A agulha passa a apontar 60° a leste do norte. A intensidade do campo criado pelo ímã nesse ponto é, aproximadamente:\n(Dado: tg 60° ≈ 1,7)",
    ["3,4 × 10⁻⁵ T.", "1,2 × 10⁻⁵ T.", "2,0 × 10⁻⁵ T.", "1,0 × 10⁻⁵ T.", "4,0 × 10⁻⁵ T."],
    "A agulha se alinha com o campo resultante. Como os dois campos são perpendiculares, tg 60° = B(ímã)/B(Terra). Logo, B(ímã) = 1,7 × 2,0 × 10⁻⁵ ≈ 3,4 × 10⁻⁵ T.",
    "Bússola entre dois campos perpendiculares: tg do desvio = campo extra / campo da Terra."),
  m("ima-25", "desafio", "Unicamp", "No fundo dos oceanos, as rochas basálticas dos dois lados de uma dorsal apresentam faixas paralelas com magnetização alternadamente normal e invertida, dispostas de forma simétrica em relação à dorsal. Esse padrão é evidência de que:",
    [
      "o campo terrestre inverteu sua polaridade várias vezes enquanto o assoalho oceânico se expandia.",
      "a água do mar desmagnetiza as rochas em intervalos regulares de tempo.",
      "os polos geográficos trocaram de lugar, invertendo a rotação da Terra.",
      "o basalto é um material que muda de polaridade a cada vez que esfria um pouco.",
    ],
    "O magma que sobe na dorsal contém minerais de ferro. Ao esfriar abaixo do ponto de Curie, eles guardam a orientação do campo terrestre daquele momento. Como o assoalho se afasta para os dois lados, cada inversão do campo fica registrada em um par de faixas simétricas.",
    "Rocha que esfria abaixo do ponto de Curie fotografa o campo da época."),
  m("ima-26", "desafio", "UFPR", "Sobre linhas de campo magnético, analise as afirmativas.\nI. São curvas fechadas, sem ponto de início ou de fim.\nII. O vetor campo magnético é tangente à linha em cada ponto.\nIII. Uma carga elétrica abandonada em repouso em um ponto do campo passa a se mover ao longo da linha que passa por esse ponto.\nEstá correto o que se afirma em:",
    ["Apenas I e II.", "Apenas I e III.", "Apenas II e III.", "Apenas II.", "I, II e III."],
    "I e II são as propriedades básicas das linhas de campo magnético. III é falsa: o campo magnético não exerce força sobre carga em repouso, e, mesmo sobre cargas em movimento, a força é perpendicular ao campo, e não ao longo dele. A linha indica a orientação de uma bússola, não a trajetória de uma carga.",
    "Linha de campo magnético orienta bússola; não é trilho de carga."),
  m("ima-27", "desafio", "UERJ", "Em certa região do oceano, a declinação magnética é de 20° para oeste, isto é, a bússola aponta 20° a oeste do norte geográfico. Para navegar exatamente rumo ao norte geográfico, o piloto deve manter a proa do barco:",
    [
      "20° a leste da direção indicada pela agulha.",
      "20° a oeste da direção indicada pela agulha.",
      "exatamente na direção indicada pela agulha.",
      "40° a leste da direção indicada pela agulha.",
    ],
    "Se a agulha está 20° a oeste do norte verdadeiro, então o norte verdadeiro está 20° a leste da agulha. O piloto precisa compensar a declinação girando a proa esse ângulo para leste em relação à indicação da bússola.",
    "Bússola mostra o norte magnético; o geográfico exige corrigir a declinação."),
  m("ima-28", "desafio", "ITA", "Dois ímãs em forma de anel, idênticos e de massa m cada um, são enfiados em uma haste vertical sem atrito, apoiada sobre uma mesa, com polos de mesmo nome frente a frente. O ímã de baixo fica apoiado na mesa e o de cima flutua em equilíbrio. Sendo g a aceleração da gravidade, a força normal que a mesa exerce sobre o ímã de baixo vale:",
    ["2mg.", "mg.", "zero.", "mg/2.", "3mg."],
    "O ímã de cima está em equilíbrio, então a força magnética de repulsão sobre ele vale mg, para cima. Pela terceira lei de Newton, o ímã de baixo é empurrado para baixo com força mg. Somando o seu próprio peso, a mesa precisa aplicar 2mg. O conjunto pesa 2mg, mesmo com um dos ímãs flutuando.",
    "Flutuar não tira peso da balança: ação e reação continuam valendo."),
  m("ima-29", "desafio", "ITA", "Em certo local, a componente horizontal do campo magnético terrestre vale 2,0 × 10⁻⁵ T e a inclinação magnética é de 60°, isto é, o campo forma 60° com o plano horizontal. A intensidade total do campo terrestre nesse local é:",
    ["4,0 × 10⁻⁵ T.", "2,3 × 10⁻⁵ T.", "3,5 × 10⁻⁵ T.", "1,0 × 10⁻⁵ T.", "2,0 × 10⁻⁵ T."],
    "A componente horizontal é a projeção do campo sobre o plano horizontal: B(horizontal) = B·cos 60°. Logo, B = 2,0 × 10⁻⁵/0,50 = 4,0 × 10⁻⁵ T. O valor 3,5 × 10⁻⁵ T é a componente vertical, B·sen 60°, e não o campo total. A bússola comum só responde à componente horizontal.",
    "Bússola sente só a componente horizontal: B·cos (inclinação)."),
  m("ima-30", "desafio", "IME", "Dois ímãs em barra idênticos são colocados sobre uma mesa, um sobre o eixo x e outro sobre o eixo y, ambos com o polo norte voltado para a origem O e à mesma distância dela. Cada um, sozinho, cria em O um campo de intensidade B. Desprezando o campo da Terra, uma bússola colocada em O indica um campo resultante de intensidade:",
    [
      "√2·B, com a agulha sobre a bissetriz e o polo norte apontando para longe dos dois ímãs.",
      "√2·B, com a agulha sobre a bissetriz e o polo norte apontando para o lado dos ímãs.",
      "2B, com a agulha sobre a bissetriz e o polo norte apontando para longe dos dois ímãs.",
      "zero, pois os campos de polos iguais se cancelam.",
      "B, com a agulha paralela a um dos ímãs.",
    ],
    "Junto ao polo norte de um ímã, o campo aponta para longe dele. Assim, cada ímã cria em O um campo de intensidade B ao longo do próprio eixo, afastando-se do ímã. Os dois vetores são perpendiculares e a resultante, pelo teorema de Pitágoras, vale √2·B, na direção da bissetriz. O polo norte da agulha segue o campo: aponta para longe dos dois ímãs.",
    "Campos perpendiculares: Pitágoras, e a agulha segue a resultante."),
];
