import type { Resumo } from "@/lib/tipos";

/** Resumo de estudo de cada tema, usado no PDF sob medida. A chave é o id do tema; `datas` guarda as fórmulas. */
export const resumos: Record<string, Resumo> = {
  imas: {
    essencial: [
      "Todo ímã tem dois polos, norte e sul. Polos de mesmo nome se repelem e polos de nomes opostos se atraem. Os polos são inseparáveis: ao partir um ímã, cada pedaço volta a ter os dois, porque o magnetismo vem de ímãs elementares (domínios magnéticos) que o corte não divide. Não existe polo magnético isolado.",
      "O campo magnético é representado por linhas de campo. O vetor campo é tangente à linha em cada ponto e tem o sentido para o qual aponta o polo norte de uma agulha de prova. Fora do ímã as linhas vão do norte para o sul; dentro, do sul para o norte. São curvas fechadas, nunca se cruzam e ficam mais próximas onde o campo é mais intenso. Campo uniforme é representado por linhas retas, paralelas e igualmente espaçadas.",
      "Ferro, níquel e cobalto são ferromagnéticos: seus domínios se alinham com um campo externo. Por isso um prego comum é atraído por qualquer polo de um ímã (imantação por indução). A única prova segura de que um corpo é ímã é a repulsão. Aquecimento acima do ponto de Curie (cerca de 770 °C no ferro) e pancadas desalinham os domínios e desmagnetizam o material.",
      "A Terra se comporta como um grande ímã. O polo norte da bússola aponta para o norte geográfico porque lá existe um polo sul magnético; perto do sul geográfico há um polo norte magnético. Os polos magnéticos não coincidem com os geográficos: o ângulo entre o norte verdadeiro e o indicado pela bússola é a declinação magnética. O ângulo da agulha com a horizontal é a inclinação magnética: nula no equador magnético e de 90° nos polos magnéticos.",
      "O campo terrestre é gerado por correntes elétricas no núcleo externo, de ferro e níquel líquidos (geodínamo), e não por um ímã permanente. Sua polaridade já se inverteu muitas vezes, como registram as rochas do fundo oceânico. O campo desvia as partículas carregadas do vento solar, que são guiadas até as regiões polares, onde produzem as auroras.",
    ],
    datas: [
      ["Interação", "Polos iguais se repelem; polos opostos se atraem"],
      ["Linhas, fora", "Do polo norte para o polo sul"],
      ["Linhas, dentro", "Do polo sul para o polo norte (curvas fechadas)"],
      ["Unidade", "Tesla: 1 T = 1 N/(A·m)"],
      ["Campo da Terra", "Cerca de 5 × 10⁻⁵ T na superfície"],
      ["Bússola desviada", "tg θ = B(perpendicular)/B(Terra), com campos perpendiculares"],
    ],
    conceitos: [
      ["Domínio magnético", "Região microscópica do material em que os ímãs atômicos estão alinhados. Em um ímã, os domínios apontam na mesma direção; no ferro comum, em direções ao acaso."],
      ["Imantação por indução", "Alinhamento temporário dos domínios de um material ferromagnético por um campo externo. Faz o ferro comum ser atraído por qualquer polo."],
      ["Ponto de Curie", "Temperatura acima da qual o material deixa de ser ferromagnético. Para o ferro, cerca de 770 °C."],
      ["Declinação magnética", "Ângulo, no plano horizontal, entre o norte geográfico e a direção apontada pela bússola."],
      ["Inclinação magnética", "Ângulo entre o campo terrestre e a horizontal: 0° no equador magnético, 90° nos polos magnéticos."],
      ["Campo uniforme", "Campo de mesma intensidade, direção e sentido em todos os pontos. Linhas retas, paralelas e igualmente espaçadas."],
    ],
    cuidado: [
      "Perto do norte geográfico fica um polo SUL magnético. Os nomes são trocados.",
      "Atração não prova que um corpo é ímã: ferro comum também é atraído. Só a repulsão prova.",
      "As linhas de campo não terminam no polo sul: elas continuam por dentro do ímã e se fecham.",
      "Linha de campo magnético não é trajetória de carga. Carga em repouso nem sequer sofre força magnética.",
      "Declinação é desvio lateral em relação ao norte verdadeiro; inclinação é o mergulho em relação à horizontal.",
      "O campo da Terra não vem de um ímã permanente: o interior do planeta está acima do ponto de Curie.",
    ],
  },
  "campo-corrente": {
    essencial: [
      "Em 1820, Oersted observou que a agulha de uma bússola se desvia quando passa corrente por um fio próximo, e que o desvio se inverte quando a corrente é invertida. Conclusão: cargas em movimento criam campo magnético. Na montagem, o fio deve ficar paralelo à agulha (direção norte-sul), para que o campo da corrente seja perpendicular ao campo terrestre.",
      "O sentido do campo é dado pela regra da mão direita. No fio retilíneo, o polegar aponta no sentido convencional da corrente e os demais dedos, envolvendo o fio, indicam o sentido das linhas, que são circunferências centradas no fio. Com corrente saindo do papel, o campo circula no sentido anti-horário; entrando, no horário.",
      "Na espira circular e no solenoide, curvam-se os dedos no sentido da corrente e o polegar indica o campo no interior. A face por onde as linhas saem é o polo norte: vista de frente, é a face em que a corrente circula no sentido anti-horário.",
      "As intensidades: no fio retilíneo longo, o campo é proporcional à corrente e inversamente proporcional à distância. No centro de uma espira, é proporcional à corrente e inversamente proporcional ao raio; N espiras juntas multiplicam o campo por N. No interior de um solenoide longo, o campo é uniforme, paralelo ao eixo e depende apenas da corrente e do número de espiras por unidade de comprimento.",
      "O campo magnético é um vetor: quando há várias correntes, somam-se vetorialmente os campos de cada uma (superposição). Entre dois fios paralelos, correntes de mesmo sentido produzem campos opostos (que podem se anular) e correntes opostas produzem campos de mesmo sentido (que se somam). Um núcleo de ferro dentro do solenoide multiplica o campo: é o eletroímã.",
    ],
    datas: [
      ["Fio retilíneo", "B = µ₀·i/(2π·d)"],
      ["Espira (centro)", "B = µ₀·i/(2R)"],
      ["N espiras juntas", "B = N·µ₀·i/(2R)"],
      ["Solenoide", "B = µ₀·(N/L)·i"],
      ["Constante", "µ₀ = 4π × 10⁻⁷ T·m/A"],
      ["Atalho do fio", "B = 2 × 10⁻⁷·i/d (SI)"],
      ["Carga em órbita", "Equivale a uma corrente i = q·f = q/T"],
    ],
    conceitos: [
      ["Regra da mão direita", "Polegar no sentido da corrente, dedos envolvendo o fio no sentido do campo. Em espiras e solenoides, dedos na corrente e polegar no campo interno."],
      ["Permeabilidade magnética (µ₀)", "Constante que mede a facilidade com que o vácuo é magnetizado por uma corrente. Vale 4π × 10⁻⁷ T·m/A."],
      ["Solenoide", "Bobina longa de espiras enfileiradas. Campo interno uniforme; por fora, comporta-se como um ímã em barra."],
      ["Eletroímã", "Solenoide com núcleo de ferro doce. O campo é muito mais intenso e desaparece quando a corrente é desligada."],
      ["Superposição", "O campo resultante em um ponto é a soma vetorial dos campos criados por cada corrente."],
    ],
    cuidado: [
      "O π só aparece no denominador da fórmula do fio retilíneo; na espira e no solenoide, não.",
      "No fio, o campo cai com 1/d, e não com 1/d².",
      "No solenoide o que importa é N/L. Dobrar as espiras e o comprimento ao mesmo tempo não muda nada, e o raio não entra.",
      "Entre dois fios, correntes de MESMO sentido dão campos opostos; correntes OPOSTAS dão campos que se somam.",
      "Um trecho reto de corrente não cria campo em pontos do seu próprio prolongamento.",
      "Para um elétron em órbita, a corrente convencional tem sentido contrário ao do movimento.",
      "Converta centímetros para metros antes de substituir na fórmula.",
    ],
  },
  "forca-carga": {
    essencial: [
      "Um campo magnético exerce força sobre uma carga apenas se ela estiver em movimento e se a velocidade não for paralela ao campo. A intensidade é F = |q|·v·B·sen θ, com θ o ângulo entre a velocidade e o campo: nula para θ = 0° ou 180°, máxima para θ = 90°. Partículas neutras não sofrem força magnética.",
      "A força é sempre perpendicular à velocidade e ao campo. O sentido vem da regra do tapa: mão direita espalmada, polegar na velocidade, demais dedos no campo, e a força sobre carga positiva sai da palma. Para carga negativa, a força tem o sentido oposto. A regra da mão esquerda de Fleming leva ao mesmo resultado.",
      "Por ser perpendicular à velocidade, a força magnética não realiza trabalho: altera a direção da velocidade, mas não o seu módulo. A energia cinética se conserva.",
      "Em campo uniforme, a trajetória depende do ângulo de lançamento. Paralelamente ao campo: movimento retilíneo uniforme. Perpendicularmente: movimento circular uniforme, com a força magnética no papel de resultante centrípeta. Obliquamente: movimento helicoidal, composição de um MRU ao longo do campo (com v·cos θ) e de um MCU no plano perpendicular (com v·sen θ).",
      "No movimento circular, o raio é proporcional à quantidade de movimento, e o período não depende da velocidade: partícula mais rápida faz uma volta maior no mesmo tempo. Essas duas propriedades explicam o espectrômetro de massa (o raio separa as massas) e o cíclotron (frequência de giro fixa). No seletor de velocidades, campos elétrico e magnético cruzados deixam passar sem desvio apenas as partículas com v = E/B.",
    ],
    datas: [
      ["Força", "F = |q|·v·B·sen θ"],
      ["Raio", "R = m·v/(|q|·B)"],
      ["Período", "T = 2π·m/(|q|·B)"],
      ["Frequência", "f = |q|·B/(2π·m)"],
      ["Passo da hélice", "p = v·cos θ·T"],
      ["Seletor", "v = E/B"],
      ["Após tensão U", "|q|·U = m·v²/2"],
      ["Cíclotron", "K(máx) = q²·B²·R²/(2m)"],
    ],
    conceitos: [
      ["Regra do tapa", "Mão direita espalmada: polegar em v, dedos em B, força saindo da palma para carga positiva e das costas da mão para carga negativa."],
      ["Resultante centrípeta", "No MCU em campo magnético, é a própria força magnética: |q|·v·B = m·v²/R."],
      ["Movimento helicoidal", "Giro (devido a v·sen θ) combinado com avanço uniforme ao longo do campo (devido a v·cos θ)."],
      ["Seletor de velocidades", "Região com campos E e B perpendiculares. Só passa em linha reta quem tem v = E/B, qualquer que seja a carga ou a massa."],
      ["Espectrômetro de massa", "Íons de mesma velocidade descrevem semicircunferências de raio proporcional a m/|q| e atingem o detector em pontos diferentes."],
      ["Cíclotron", "Acelerador em que as partículas giram em um campo magnético com frequência fixa e ganham energia a cada meia volta."],
    ],
    cuidado: [
      "O ângulo entra com SENO, medido entre a velocidade e o campo. Trocar por cosseno é o erro clássico.",
      "Carga negativa: aplique a regra e inverta o sentido da força.",
      "A força magnética nunca muda o módulo da velocidade nem a energia cinética.",
      "O período não depende da velocidade; o raio depende.",
      "Na hélice, quem avança é v·cos θ e quem gira é v·sen θ.",
      "Trajetória parabólica é coisa de campo elétrico uniforme. Em campo magnético uniforme é reta, circunferência ou hélice.",
      "Depois de meia volta, a partícula está a um diâmetro (2R) do ponto de entrada, e não a um raio.",
      "Mesma velocidade: o raio é proporcional a m/|q|. Mesma energia cinética: é proporcional a √m/|q|.",
    ],
  },
  "forca-fio": {
    essencial: [
      "Um fio com corrente é um conjunto de cargas em movimento; em um campo magnético, a soma das forças sobre essas cargas dá a força sobre o fio. Para um trecho retilíneo de comprimento L, em campo uniforme, F = B·i·L·sen θ, com θ o ângulo entre o fio e o campo. A força é nula com o fio paralelo ao campo e máxima com o fio perpendicular a ele.",
      "O sentido vem da regra do tapa, com o polegar no sentido convencional da corrente no lugar da velocidade. Como a corrente convencional já corresponde a cargas positivas, não se inverte o resultado. A força é perpendicular ao fio e ao campo.",
      "Dois fios paralelos com corrente interagem porque cada um está no campo do outro. A força por unidade de comprimento é proporcional ao produto das correntes e inversamente proporcional à distância. Correntes de mesmo sentido se atraem; de sentidos opostos, se repelem. As forças nos dois fios formam um par ação-reação e têm a mesma intensidade, mesmo com correntes diferentes.",
      "Uma espira com corrente em um campo uniforme sofre força resultante nula, mas as forças em lados opostos podem formar um binário, que a faz girar. É o princípio do motor elétrico, do galvanômetro e do alto-falante. O comutador do motor inverte a corrente a cada meia volta para manter o sentido do giro.",
      "Nos problemas de equilíbrio, a força magnética entra como qualquer outra força: equilibra o peso em um fio que levita, vence o atrito em uma barra sobre trilhos ou inclina um fio suspenso. O primeiro passo é sempre achar a direção da força: com campo vertical e barra horizontal, a força é horizontal.",
    ],
    datas: [
      ["Fio em campo", "F = B·i·L·sen θ"],
      ["Fios paralelos", "F/L = µ₀·i₁·i₂/(2π·d)"],
      ["Atalho", "F/L = 2 × 10⁻⁷·i₁·i₂/d (SI)"],
      ["Levitação", "B·i·L = m·g"],
      ["Fio suspenso", "tg θ = B·i·L/(m·g), com campo vertical"],
      ["Torque na bobina", "Máximo: N·B·i·A"],
      ["Fio curvo", "Em campo uniforme, vale a reta que une as extremidades"],
    ],
    conceitos: [
      ["Sentido convencional da corrente", "O sentido em que se moveriam cargas positivas. É ele que entra na regra do tapa para fios."],
      ["Par ação-reação", "As forças entre dois fios têm a mesma intensidade e sentidos opostos, sejam as correntes iguais ou não."],
      ["Binário", "Par de forças de mesma intensidade e sentidos opostos, em linhas diferentes. Tem resultante nula, mas produz rotação."],
      ["Comutador", "Peça do motor de corrente contínua que inverte o sentido da corrente na bobina a cada meia volta."],
      ["Definição antiga do ampère", "Corrente que, em dois fios paralelos a 1 m de distância, produz força de 2 × 10⁻⁷ N por metro. Valeu até 2019."],
    ],
    cuidado: [
      "Com correntes é o contrário das cargas: mesmo sentido ATRAI, sentidos opostos REPELEM.",
      "Entre fios paralelos a força cai com 1/d, não com 1/d².",
      "As forças nos dois fios são iguais em intensidade, mesmo que uma corrente seja maior.",
      "Para fios, não se inverte o resultado da regra do tapa: a corrente convencional já é de cargas positivas.",
      "Em campo uniforme, a força sobre um fio curvo usa a distância entre as extremidades, e não o comprimento do fio.",
      "Espira em campo uniforme: força resultante nula. Em campo não uniforme (perto de um fio, por exemplo), não é nula.",
      "No plano inclinado com campo vertical, a força magnética é horizontal: decomponha-a também.",
    ],
  },
};
