import type { Questao } from "@/lib/tipos";
import { criar } from "../criar";

const d = criar("dutra");
const v = criar("vargas");
const k = criar("jk");
const j = criar("janio");
const g = criar("jango");

/** Combinações usadas nas questões de análise de afirmativas (I, II e III). */
const I_II = "Apenas I e II.";
const I_III = "Apenas I e III.";
const II_III = "Apenas II e III.";
const SO_I = "Apenas I.";
const SO_II = "Apenas II.";
const TODAS = "I, II e III.";

/** Níveis médio e difícil dos temas de Brasil. A primeira alternativa é a correta. */
export const avancadasBrasil: Questao[] = [
  // ───────── Governo Dutra ─────────
  d("dut-21", "medio", "Fuvest", "Nas eleições de dezembro de 1945, o PCB obteve cerca de 10% dos votos para presidente, elegeu catorze deputados e fez de Luís Carlos Prestes senador pelo Distrito Federal. Esse resultado ajuda a explicar a cassação do partido em 1947 porque:",
    [
      "mostrou que os comunistas tinham força real nas grandes cidades, justamente quando a Guerra Fria começava.",
      "deu ao partido a maior bancada da Assembleia Constituinte, o que lhe permitiria redigir praticamente sozinho a nova Carta.",
      "provou que o PCB havia rompido com Vargas e passado a apoiar a candidatura do brigadeiro Eduardo Gomes, da UDN.",
      "levou o partido a pregar a luta armada imediata, abandonando a linha de união nacional de Prestes.",
      "foi obtido com financiamento soviético comprovado em inquérito do Tribunal Superior Eleitoral.",
    ],
    "O PCB saiu da clandestinidade como o quarto partido do país e o primeiro em algumas capitais. Em 1945–46 sua linha era moderada, de \"união nacional\", e não de luta armada. O que mudou foi o cenário externo: com a Doutrina Truman (1947), o governo Dutra passou a tratar esse peso eleitoral como ameaça.",
    "O PCB não foi cassado por ser fraco, e sim por ter voto."),
  d("dut-22", "medio", "Unicamp", "O Tribunal Superior Eleitoral cassou o registro do PCB, em maio de 1947, apoiando-se num dispositivo da própria Constituição de 1946. Esse dispositivo:",
    [
      "vedava partidos cujo programa ou ação contrariasse o regime democrático, baseado na pluralidade partidária.",
      "proibia a existência de partidos de âmbito nacional, permitindo apenas legendas estaduais.",
      "autorizava o presidente a dissolver agremiações por decreto, ouvido o Conselho de Segurança Nacional, em caso de comoção interna.",
      "exigia que todo partido tivesse representação em pelo menos metade dos estados.",
    ],
    "O artigo 141, § 13, proibia partidos contrários ao regime democrático e à pluralidade partidária. O argumento usado foi o de que o PCB obedecia a orientação estrangeira e defendia o partido único. A decisão foi apertada (3 votos a 2) e não partiu de decreto presidencial. Os partidos de 1945 já eram obrigatoriamente nacionais.",
    "Uma cláusula feita para proteger a democracia serviu para restringi-la."),
  d("dut-23", "medio", "Unesp", "Esgotadas as reservas em dólar, o governo Dutra passou, a partir de 1947–48, a exigir licença prévia para importar, mantendo o cruzeiro valorizado. Um efeito não planejado dessa política foi:",
    [
      "favorecer a indústria, que importava máquinas baratas e ficava protegida da concorrência estrangeira.",
      "arruinar a indústria nacional, que perdeu acesso a equipamentos estrangeiros e teve de reduzir a produção.",
      "estimular as exportações de café, algodão e cacau, que se tornaram mais competitivas no exterior com a moeda forte.",
      "eliminar a inflação, já que o câmbio fixo travou os preços internos até 1951.",
      "atrair capital estrangeiro para o setor de petróleo, até então fechado aos investimentos externos pela Constituição.",
    ],
    "O controle nasceu de uma crise no balanço de pagamentos, não de um projeto industrializante. Mas as licenças priorizavam bens essenciais (máquinas, combustíveis, matérias-primas) e barravam os supérfluos. Com câmbio valorizado, equipamento importado saía barato: um empurrão indireto à substituição de importações. Moeda forte prejudica, e não ajuda, as exportações.",
    "Dutra industrializou \"sem querer\"."),
  d("dut-24", "medio", "UERJ", "A Constituição de 1946 reconheceu o direito de greve, mas, na prática, as paralisações continuaram sendo reprimidas durante o governo Dutra. Isso foi possível porque:",
    [
      "continuou em vigor um decreto-lei de março de 1946, anterior à Carta, que praticamente inviabilizava greves legais.",
      "a Constituição limitava o direito aos trabalhadores rurais.",
      "o Supremo Tribunal Federal declarou o artigo inconstitucional em 1947.",
      "os sindicatos foram extintos em 1946 e substituídos por associações de bairro sem poder de negociação coletiva.",
    ],
    "O Decreto-Lei 9.070, baixado meses antes da promulgação, proibia greves em atividades \"fundamentais\" e submetia as demais à Justiça do Trabalho. Como a Constituição remeteu o tema à lei, o governo seguiu aplicando o decreto. Os sindicatos não foram extintos: sofreram intervenção, o que é diferente.",
    "Direito no papel, decreto na prática."),
  d("dut-25", "medio", "UFRGS", "A Missão Abbink (1948), comissão técnica de brasileiros e norte-americanos, frustrou parte do governo brasileiro porque suas conclusões:",
    [
      "recomendavam que o desenvolvimento se apoiasse no capital privado e na estabilidade monetária, sem prometer financiamento público dos EUA.",
      "propunham estender ao Brasil um programa de doações equivalente ao que a Europa recebia.",
      "defendiam o monopólio estatal do petróleo e da energia elétrica.",
      "sugeriam o rompimento do Brasil com o Fundo Monetário Internacional.",
      "condicionavam qualquer ajuda à legalização do Partido Comunista.",
    ],
    "O Brasil esperava ser recompensado pelo alinhamento na guerra e na Guerra Fria. A resposta americana foi que a América Latina deveria atrair investidores privados; o dinheiro público estava reservado à Europa e à Ásia. Essa frustração atravessa os anos 1950 e reaparece na Operação Pan-Americana de JK.",
    "Alinhamento sem contrapartida."),
  d("dut-26", "medio", "Fuvest", "Sobre o sistema de segurança montado nas Américas no início da Guerra Fria, é correto afirmar que:",
    [
      "o TIAR (1947) veio antes da OEA (1948) e da própria OTAN (1949).",
      "a OEA foi criada em 1945, na Conferência de São Francisco, como braço regional da ONU.",
      "o TIAR foi assinado em Bogotá e previa ajuda econômica aos signatários.",
      "a OTAN serviu de modelo ao TIAR, firmado dois anos depois dela.",
    ],
    "A ordem é: TIAR em 1947 (conferência de Petrópolis, no Rio), OEA em 1948 (Bogotá) e OTAN em 1949. O TIAR é puramente militar, de defesa coletiva, e nada tem de ajuda econômica. Foi ele que antecipou a fórmula depois usada na OTAN, e não o contrário.",
    "47 TIAR · 48 OEA · 49 OTAN."),

  d("dut-31", "dificil", "Unicamp", "Considere as afirmativas sobre a Constituição de 1946.\n\nI. Manteve fora do eleitorado os analfabetos e também os soldados e cabos das Forças Armadas.\nII. Recriou o cargo de vice-presidente da República, a quem cabia presidir o Senado.\nIII. Fixou mandato presidencial de quatro anos, com direito a uma reeleição consecutiva.\n\nEstá correto o que se afirma em:",
    [I_II, SO_I, II_III, I_III, TODAS],
    "I e II estão corretas: o artigo 132 excluía analfabetos e praças de pré, e o vice presidia o Senado (cargo que Jango ocupou duas vezes). III é falsa: o mandato era de cinco anos, sem reeleição imediata. A reeleição só entrou na ordem brasileira em 1997.",
    "1946: cinco anos, sem reeleição."),
  d("dut-32", "dificil", "Fuvest", "Eleito pelo PSD com apoio do PTB, Dutra firmou em 1948 o chamado Acordo Interpartidário com a UDN e o PR. O significado político desse acordo foi:",
    [
      "aproximar o governo da oposição conservadora e isolar o trabalhismo, o que empurrou Vargas a buscar outra aliança para 1950.",
      "consolidar no Congresso a aliança entre PSD e PTB, que sustentaria todos os presidentes eleitos até 1964 e garantiria a posse de JK e de Jango.",
      "permitir a volta do PCB à legalidade em troca de apoio parlamentar ao Plano SALTE.",
      "transferir a chefia do governo à UDN, antecipando um parlamentarismo de fato.",
      "unir os três grandes partidos em torno da candidatura única de Vargas à sucessão.",
    ],
    "Dutra governou com a UDN, o partido que derrotara. O PTB ficou à margem, e Vargas, senador quase ausente, preparou a volta apoiado no PTB e no PSP de Ademar de Barros, enquanto o PSD lançava Cristiano Machado e boa parte de seus chefes o abandonava para votar em Getúlio (a \"cristianização\").",
    "Dutra foi eleito por Vargas e governou com os adversários dele."),
  d("dut-33", "dificil", "UERJ", "Sobre a política econômica do governo Dutra, assinale a afirmativa INCORRETA.",
    [
      "O Plano SALTE foi executado integralmente entre 1946 e 1950, com recursos do Plano Marshall.",
      "Na fase inicial, a liberação das importações dilapidou as divisas acumuladas durante a guerra.",
      "A partir de 1947–48, o controle de importações acabou beneficiando a indústria de bens de consumo.",
      "O combate à inflação foi usado para justificar a contenção de salários e do salário mínimo.",
      "O governo apostava que o alinhamento a Washington traria capitais e empréstimos norte-americanos.",
    ],
    "O SALTE só foi aprovado pelo Congresso em 1950, teve execução parcial e foi abandonado em seguida; e o Plano Marshall não se estendeu à América Latina. O salário mínimo ficou congelado durante todo o governo, perdendo boa parte do poder de compra.",
    "\"INCORRETA\" no enunciado: leia duas vezes."),
  d("dut-34", "dificil", "Unesp", "Historiadores costumam descrever a ordem de 1946 como uma democracia erguida sobre uma estrutura corporativa herdada do Estado Novo. O elemento que melhor sustenta essa leitura é:",
    [
      "a permanência do sindicato único por categoria, do imposto sindical e do poder de intervenção do Ministério do Trabalho.",
      "a manutenção dos interventores federais nomeados para os governos estaduais, que só voltaram a ser eleitos na década seguinte.",
      "a sobrevivência do Departamento de Imprensa e Propaganda, com censura prévia aos jornais, ao rádio e ao cinema até o fim da década.",
      "a continuidade da Constituição de 1937, apenas emendada pela Assembleia.",
      "a proibição de partidos nacionais, substituídos por legendas regionais.",
    ],
    "DIP, interventores e a Carta de 1937 foram extintos na redemocratização. O que atravessou intacto foi a legislação sindical da CLT (1943): unicidade, imposto e tutela ministerial. Foi com esse aparato que Dutra interveio em centenas de sindicatos sem precisar mudar a lei.",
    "Caiu a ditadura, ficou a CLT sindical."),
  d("dut-35", "dificil", "UFPR", "Para ocupar cargos de direção sindical no governo Dutra, o trabalhador precisava apresentar à polícia política o chamado \"atestado de ideologia\". A exigência revela que:",
    [
      "o anticomunismo funcionava como filtro para definir quem podia representar os trabalhadores.",
      "os sindicatos haviam conquistado autonomia e escolhiam seus dirigentes sem interferência da polícia.",
      "o governo estimulava a formação de lideranças independentes do Ministério do Trabalho e dos partidos.",
      "a Justiça Eleitoral passara a organizar as eleições sindicais.",
    ],
    "O atestado, fornecido pelo DOPS, barrava militantes comunistas e independentes e mantinha os \"pelegos\" à frente dos sindicatos. Vargas o aboliu em 1952, o que ajudou a reanimar o movimento operário e abriu caminho para a greve dos 300 mil, em 1953.",
    "Pelego = dirigente que amortece o conflito, como a manta sob a sela."),
  d("dut-36", "dificil", "Fuvest", "O rompimento de relações com a União Soviética (1947) e a cassação dos mandatos comunistas (1948) costumam ser explicados pela Guerra Fria. Um fator interno que também pesou foi:",
    [
      "o interesse do governo e do empresariado em conter a onda de greves de 1945–46 e a influência comunista nos sindicatos.",
      "a pressão da UDN, que ameaçava aliar-se ao PCB nas eleições municipais de 1947 para derrotar os candidatos do governo federal.",
      "a adesão de Prestes à candidatura de Dutra, que tornava o partido dispensável.",
      "a descoberta de um levante militar comunista em preparação nos quartéis do Nordeste, semelhante ao que ocorrera em novembro de 1935.",
      "a exigência do FMI de que o país eliminasse os partidos de esquerda como condição para liberar novos créditos externos.",
    ],
    "O pós-guerra trouxe inflação, salários achatados e muitas greves, com forte presença comunista nas direções sindicais. A repressão ao PCB, as intervenções nos sindicatos e o fechamento da Confederação dos Trabalhadores do Brasil fazem parte do mesmo movimento. Não houve levante armado em 1947.",
    "Guerra Fria por fora, medo de greve por dentro."),

  // ───────── Vargas, populismo, UDN ─────────
  v("var-21", "medio", "Fuvest", "Vargas venceu a eleição de 1950 com 48,7% dos votos. A UDN tentou impedir sua posse alegando que:",
    [
      "a vitória exigiria maioria absoluta, requisito que a Constituição de 1946 não previa.",
      "o candidato governara como ditador até 1945 e, por isso, estaria inelegível pelo prazo de dez anos.",
      "houve fraude comprovada nas urnas do Rio Grande do Sul.",
      "o PTB não tinha registro válido no Tribunal Superior Eleitoral quando a chapa foi inscrita.",
    ],
    "A tese da maioria absoluta não tinha base legal: bastava a maioria simples. O argumento foi reciclado em 1955 contra JK, eleito com 36%. Nos dois casos a UDN buscou anular nos tribunais e nos quartéis o que perdera nas urnas.",
    "Maioria absoluta: tese de 1950 e de 1955, sempre de quem perdeu."),
  v("var-22", "medio", "Unicamp", "Criado em 1952, a partir dos trabalhos da Comissão Mista Brasil–Estados Unidos, o BNDE tinha como função:",
    [
      "financiar a longo prazo projetos de infraestrutura, sobretudo em energia e transportes.",
      "emitir moeda, fixar a taxa de juros e fiscalizar o funcionamento dos bancos comerciais privados.",
      "administrar o monopólio estatal do comércio de café.",
      "conceder crédito agrícola subsidiado aos pequenos produtores do Nordeste atingidos pela seca.",
      "controlar as licenças de importação e organizar os leilões de câmbio para os industriais e comerciantes.",
    ],
    "O Banco Nacional de Desenvolvimento Econômico nasceu para tocar os projetos da Comissão Mista e virou o grande financiador do Plano de Metas. Emissão e fiscalização bancária cabiam à SUMOC e ao Banco do Brasil (o Banco Central é de 1964); as licenças de importação, à CEXIM.",
    "BNDE = banco de obra grande e prazo longo."),
  v("var-23", "medio", "Unesp", "A greve dos 300 mil, em São Paulo (1953), é considerada um marco do segundo governo Vargas porque:",
    [
      "foi organizada por comissões de fábrica, à margem das direções oficiais, e mostrou os limites do controle estatal sobre os trabalhadores.",
      "foi convocada pelo próprio governo para pressionar o Congresso a aprovar a Petrobras.",
      "terminou com a extinção do imposto sindical e o fim da unicidade.",
      "resultou na cassação do PTB pela Justiça Eleitoral.",
    ],
    "Tecelões, metalúrgicos, marceneiros e gráficos pararam por quase um mês contra a carestia, organizados por baixo. O governo reagiu trocando o ministro do Trabalho: entrou João Goulart, encarregado de reaproximar o varguismo dos sindicatos.",
    "Depois da greve, Jango no ministério."),
  v("var-24", "medio", "UERJ", "Em outubro de 1953, a Instrução 70 da SUMOC substituiu as licenças de importação por leilões de câmbio, com taxas diferentes conforme a categoria do produto. A medida:",
    [
      "encareceu os bens supérfluos importados, barateou relativamente os essenciais e gerou receita para o Tesouro.",
      "unificou as taxas de câmbio e eliminou qualquer forma de intervenção do Estado no comércio exterior, como pedia o FMI.",
      "proibiu a importação de máquinas e equipamentos industriais.",
      "congelou o preço do café e reduziu a arrecadação federal.",
      "estabeleceu o monopólio estatal das exportações agrícolas.",
    ],
    "O sistema de câmbios múltiplos, criado na gestão de Oswaldo Aranha na Fazenda, funcionava como tarifa disfarçada: quem queria importar supérfluo pagava um ágio alto, e esse ágio financiava o governo. Foi mais um instrumento de proteção à indústria.",
    "Câmbio múltiplo = protecionismo sem lei de tarifas."),
  v("var-25", "medio", "UFRGS", "No fim de 1951, Vargas denunciou em discurso a \"sangria\" provocada pelas empresas estrangeiras e, em janeiro de 1952, baixou um decreto que:",
    [
      "restringia a remessa de lucros, excluindo os lucros reinvestidos da base de cálculo.",
      "nacionalizava as companhias estrangeiras de energia elétrica e de telefonia que operavam nas capitais.",
      "proibia a entrada de novas empresas estrangeiras nos setores de energia, transportes e comunicações.",
      "confiscava os depósitos de estrangeiros nos bancos brasileiros.",
    ],
    "A lei já fixava um teto percentual para as remessas; o decreto mandou calculá-lo só sobre o capital que entrara de fato no país, sem contar os lucros aqui reinvestidos. Provocou atrito com Washington e com o Banco Mundial e foi abrandado em 1953. O tema volta em 1962, com a Lei de Remessa de Lucros de Jango.",
    "Remessa de lucros: Vargas em 1952, Jango em 1962."),
  v("var-26", "medio", "Fuvest", "A expressão \"República do Galeão\", usada em agosto de 1954, designava:",
    [
      "o inquérito da Aeronáutica sobre o atentado da Rua Tonelero, conduzido com autonomia em relação ao governo.",
      "o governo provisório instalado por Café Filho depois da morte de Vargas, com ministros ligados à Aeronáutica.",
      "o grupo de deputados e senadores da UDN que se reunia no aeroporto do Rio para articular o impeachment do presidente.",
      "a base militar em que Vargas pretendia resistir à deposição.",
      "o acordo entre Exército e Marinha para garantir a posse do vice-presidente.",
    ],
    "Como a vítima fatal era um major da FAB, oficiais instalaram na base aérea do Galeão um inquérito policial-militar que prendia e interrogava por conta própria. Chegaram a Gregório Fortunato e expuseram a corrupção na guarda pessoal: o \"mar de lama\". Era um poder paralelo, sinal de que o presidente perdera o comando.",
    "Galeão: quando o inquérito virou governo."),

  v("var-31", "dificil", "Unicamp", "Considere as afirmativas sobre a criação da Petrobras (Lei 2.004, de 1953).\n\nI. O projeto enviado por Vargas em 1951 previa uma empresa de economia mista, sem estabelecer o monopólio estatal.\nII. O monopólio foi introduzido durante a tramitação no Congresso, com votos de parlamentares da UDN.\nIII. As refinarias privadas que já funcionavam foram encampadas pela mesma lei.\n\nEstá correto o que se afirma em:",
    [I_II, SO_II, TODAS, II_III, SO_I],
    "O projeto original, mais cauteloso, admitia sócios privados. A campanha de rua e uma emenda apresentada por udenistas (que não queriam deixar a bandeira nacionalista com Getúlio) levaram ao monopólio. As refinarias particulares existentes foram preservadas; sua encampação só seria decretada por Jango, em março de 1964.",
    "O monopólio veio do Congresso e da rua, não do projeto de Vargas."),
  v("var-32", "dificil", "Fuvest", "O Manifesto dos Coronéis (fevereiro de 1954), que precipitou a queda do ministro João Goulart, é relevante para a história posterior porque:",
    [
      "reuniu oficiais de patente intermediária, entre eles Golbery do Couto e Silva, que estariam no núcleo do golpe de 1964.",
      "foi redigido pelo general Lott em defesa da legalidade, do aumento do salário mínimo e da permanência do ministro do Trabalho no cargo.",
      "marcou a adesão da oficialidade jovem ao nacionalismo econômico, à campanha do petróleo e à política trabalhista do governo.",
      "pediu a intervenção militar imediata, o fechamento do Congresso e a entrega do governo a uma junta de oficiais-generais.",
      "expressou o apoio da Marinha e da Aeronáutica ao ministro do Trabalho.",
    ],
    "O texto reclamava da deterioração material do Exército e alertava contra a \"subversão\" de um salário mínimo que se aproximaria do soldo de um oficial. Não pedia golpe, mas mostrava uma geração de coronéis ligada à ESG disposta a intervir no debate político. Vargas demitiu Jango e, em 1º de maio, concedeu os 100%.",
    "Os coronéis de 1954 são os generais de 1964."),
  v("var-33", "dificil", "UERJ", "Na Carta-Testamento, Vargas enumera iniciativas que teriam despertado a reação de seus inimigos. NÃO figura entre elas:",
    [
      "a legalização do Partido Comunista e o reatamento com a União Soviética.",
      "a criação da Petrobras.",
      "o projeto da Eletrobras, que diz ter sido obstaculizado.",
      "a lei contra os lucros extraordinários, barrada no Congresso.",
      "a revisão do salário mínimo e a defesa do preço do café no mercado internacional.",
    ],
    "A Carta fala em Petrobras, Eletrobras, lucros extraordinários, salário mínimo e café. O PCB continuou ilegal durante todo o governo, e as relações com a URSS só foram reatadas em 1961. O documento é nacionalista e trabalhista, não de aproximação com o bloco socialista.",
    "Vargas era nacionalista, não comunista: o PCB chegou a fazer oposição a ele."),
  v("var-34", "dificil", "Unesp", "A partir dos anos 1980, historiadores passaram a criticar o uso do conceito de populismo e a preferir o termo trabalhismo. A crítica central é a de que a noção de populismo:",
    [
      "trata os trabalhadores como massa passiva e manipulada, ignorando que eles negociavam, pressionavam e faziam escolhas.",
      "exagera a autonomia dos sindicatos em relação ao Estado.",
      "atribui aos partidos um peso que eles nunca tiveram na política brasileira.",
      "desconsidera o papel do líder carismático e superestima as instituições.",
      "só se aplica a regimes ditatoriais, e o período 1945–1964 foi democrático.",
    ],
    "Na interpretação clássica, o líder engana e a massa, recém-chegada do campo, é enganada. A revisão propõe ver ali um pacto: os trabalhadores trocavam apoio por direitos reais e usavam o discurso oficial para cobrar mais. O termo populismo, aliás, foi difundido pelos adversários do varguismo.",
    "Populismo olha de cima; trabalhismo olha de baixo."),
  v("var-35", "dificil", "Fuvest", "Com a morte de Vargas, o vice Café Filho montou um ministério próximo da UDN, com Eugênio Gudin na Fazenda. Uma medida desse governo que teria enorme efeito no período seguinte foi:",
    [
      "a Instrução 113 da SUMOC, que deixava empresas estrangeiras trazerem máquinas sem cobertura cambial.",
      "a lei que estabeleceu o monopólio estatal da energia elétrica e criou a Eletrobras, proposta por Vargas.",
      "o decreto que duplicou o salário mínimo em todo o país.",
      "a criação da Sudene para coordenar investimentos no Nordeste.",
      "o rompimento com o FMI e a suspensão do pagamento da dívida externa aos bancos privados norte-americanos.",
    ],
    "A Instrução 113 (janeiro de 1955) permitia ao investidor estrangeiro importar equipamentos registrando-os como capital, vantagem que o empresário nacional não tinha. Liberal na origem, foi o grande instrumento de JK para atrair as montadoras. Sudene e rompimento com o FMI são de 1959.",
    "Gudin criou, JK usou."),
  v("var-36", "dificil", "UFPR", "Sobre a sequência da crise de agosto de 1954, é correto afirmar que:",
    [
      "após o atentado, brigadeiros e generais exigiram a renúncia; Vargas aceitou só uma licença e se matou.",
      "Vargas foi deposto por um ultimato do Congresso, que em seguida elegeu indiretamente o seu sucessor para completar o mandato.",
      "o suicídio ocorreu antes de qualquer manifestação militar, o que surpreendeu os comandantes das três Forças.",
      "a UDN assumiu a presidência com Carlos Lacerda, que governou até a eleição de 1955.",
      "os ministros militares fecharam o Congresso e nomearam uma junta provisória, que governou até a posse de JK.",
    ],
    "Tonelero é de 5 de agosto. Nos dias 22 e 23 vieram os manifestos de oficiais-generais exigindo a renúncia. Na madrugada do dia 24, em reunião ministerial, Vargas aceitou licenciar-se; ao saber que os militares exigiam afastamento definitivo, suicidou-se. O Congresso ficou aberto e assumiu o vice.",
    "5: atentado · 22–23: manifestos · 24: o tiro."),

  // ───────── JK ─────────
  k("jk-21", "medio", "Fuvest", "A distribuição dos investimentos previstos no Plano de Metas mostra que:",
    [
      "energia e transportes ficaram com cerca de 70% dos recursos, enquanto educação e alimentação receberam fatias mínimas.",
      "a educação recebeu a maior fatia, por ser considerada condição do desenvolvimento, seguida de perto pelas indústrias de base e pela energia.",
      "os recursos foram repartidos em partes iguais entre os cinco setores.",
      "a agricultura de exportação foi o setor mais beneficiado.",
    ],
    "Energia recebeu algo em torno de 43% e transportes, 30%; indústrias de base, 20%; alimentação e educação, pouco mais de 3% cada. O plano atacava \"pontos de estrangulamento\" da indústria, não os problemas sociais. A meta de educação visava formar pessoal técnico.",
    "Metas: muito kW e asfalto, pouca escola."),
  k("jk-22", "medio", "Unicamp", "O GEIA (Grupo Executivo da Indústria Automobilística), criado em 1956, impunha às montadoras:",
    [
      "índices crescentes de nacionalização, obrigando-as a comprar peças fabricadas no Brasil.",
      "participação majoritária do Estado no capital das fábricas instaladas com incentivos federais.",
      "a instalação das fábricas no Nordeste ou no Centro-Oeste, como contrapartida aos incentivos fiscais.",
      "a venda de toda a produção ao governo federal.",
      "o uso exclusivo de motores movidos a álcool.",
    ],
    "As empresas recebiam facilidades cambiais e fiscais e, em troca, tinham de atingir em poucos anos cerca de 90% do peso do veículo em componentes nacionais. Isso fez surgir a indústria de autopeças, em grande parte de capital brasileiro. As fábricas ficaram no ABC paulista.",
    "Montadora estrangeira, autopeça nacional."),
  k("jk-23", "medio", "UERJ", "No episódio de 11 de novembro de 1955, o presidente em exercício afastado pelo general Lott e seu substituto foram, respectivamente:",
    [
      "Carlos Luz e Nereu Ramos.",
      "Café Filho e Ranieri Mazzilli.",
      "Nereu Ramos e Juscelino Kubitschek.",
      "Carlos Lacerda e João Goulart.",
    ],
    "Café Filho licenciara-se por doença, e o presidente da Câmara, Carlos Luz, assumiu. Suspeito de compactuar com quem queria barrar a posse dos eleitos, foi afastado; entrou Nereu Ramos, vice-presidente do Senado, que governou sob estado de sítio até 31 de janeiro de 1956. Mazzilli é o interino de 1961 e de 1964.",
    "Luz se apaga, Nereu assume."),
  k("jk-24", "medio", "Unesp", "O ISEB (Instituto Superior de Estudos Brasileiros), criado em 1955, tornou-se conhecido por:",
    [
      "formular a ideologia nacional-desenvolvimentista, que via na industrialização o caminho para superar o subdesenvolvimento.",
      "defender o liberalismo econômico e a redução do Estado.",
      "elaborar a doutrina de segurança nacional ensinada aos oficiais.",
      "organizar a oposição empresarial ao governo Goulart, com filmes, publicações e cursos destinados a oficiais e a jovens executivos.",
      "coordenar tecnicamente a construção de Brasília.",
    ],
    "O ISEB reuniu intelectuais como Hélio Jaguaribe, Roland Corbisier e Álvaro Vieira Pinto e dialogava com as teses da CEPAL. Não confunda as siglas: doutrina de segurança é a ESG; oposição empresarial a Jango, o IPES; obra de Brasília, a Novacap. O ISEB foi fechado logo após o golpe de 1964.",
    "ISEB pensa o desenvolvimento · ESG pensa a segurança · IPES conspira."),
  k("jk-25", "medio", "UFRGS", "Em 1958, o ministro Lucas Lopes e Roberto Campos lançaram o Plano de Estabilização Monetária. O destino desse plano foi:",
    [
      "ser abandonado por JK, que não aceitou frear as obras, o que desembocou no rompimento com o FMI em 1959.",
      "reduzir a inflação a zero e ser mantido até o fim do mandato.",
      "ser derrubado pelo Supremo Tribunal Federal a pedido dos sindicatos, que contestavam o congelamento dos salários.",
      "ser substituído, ainda no governo JK, pelo Plano Trienal, que conciliava o combate à inflação com as reformas de base.",
    ],
    "O plano exigia cortar crédito e gastos, o que comprometeria Brasília e as metas. JK escolheu o crescimento, demitiu a equipe e rompeu com o Fundo. O Plano Trienal é de 1963, com Jango e Celso Furtado.",
    "Entre a meta e a moeda, JK ficou com a meta."),
  k("jk-26", "medio", "Fuvest", "A Instrução 113 da SUMOC, herdada do governo Café Filho, foi criticada por empresários nacionais durante o governo JK porque:",
    [
      "dava às empresas estrangeiras uma vantagem cambial na importação de máquinas que as nacionais não tinham.",
      "proibia a importação de equipamentos por empresas de capital brasileiro, obrigadas a comprar máquinas usadas.",
      "estatizava os setores de bens de consumo durável.",
      "obrigava as multinacionais a reinvestir no país todos os lucros obtidos durante os dez primeiros anos de operação.",
      "aumentava os impostos sobre a produção de automóveis e de autopeças, encarecendo o produto final para o consumidor.",
    ],
    "A multinacional trazia o equipamento como investimento, sem comprar dólares no leilão; o industrial brasileiro pagava o câmbio caro. O resultado foi a liderança estrangeira nos setores mais dinâmicos, como automóveis e eletrodomésticos.",
    "Mesma máquina, câmbio diferente."),

  k("jk-31", "dificil", "Unicamp", "Considere as afirmativas sobre o modelo econômico do governo JK.\n\nI. Apoiou-se num tripé formado por empresas estatais, capital privado nacional e capital estrangeiro.\nII. Foi financiado em boa parte por emissão de moeda, na ausência de uma reforma tributária.\nIII. Reduziu a distância econômica entre o Centro-Sul e as demais regiões do país.\n\nEstá correto o que se afirma em:",
    [I_II, TODAS, SO_I, I_III, II_III],
    "I e II descrevem o modelo e seu calcanhar de aquiles: sem base fiscal, o Estado emitia moeda e tomava empréstimos externos. III é falsa: a indústria concentrou-se ainda mais em São Paulo, e foi justamente o agravamento das disparidades (e a seca de 1958) que levou à criação da Sudene.",
    "A Sudene existe porque III é falsa."),
  k("jk-32", "dificil", "Fuvest", "Para executar o Plano de Metas, JK recorreu ao que se chamou de \"administração paralela\". A expressão designa:",
    [
      "grupos executivos e órgãos técnicos, como o BNDE, que decidiam por fora da burocracia tradicional e do clientelismo partidário.",
      "o ministério informal de militares que tutelava o presidente.",
      "a transferência de atribuições federais aos governos estaduais.",
      "a rede de empreiteiras contratadas sem licitação para erguer Brasília.",
      "o conjunto de comissões parlamentares que fiscalizavam cada meta.",
    ],
    "JK não reformou a máquina pública: deixou ministérios e autarquias para a barganha com PSD e PTB e criou ilhas de eficiência (GEIA, grupos executivos, BNDE, Novacap) ligadas diretamente à Presidência. Ganhou velocidade e evitou conflito com o Congresso, ao preço de adiar as reformas.",
    "Não mexeu na casa velha; construiu um anexo."),
  k("jk-33", "dificil", "UERJ", "A Operação Pan-Americana (1958) teve pouca acolhida imediata em Washington. Ainda assim, costuma-se apontar como resultado concreto ligado a ela:",
    [
      "a criação do Banco Interamericano de Desenvolvimento (BID), em 1959.",
      "a extensão do Plano Marshall ao Brasil e à Argentina.",
      "a assinatura do TIAR e a criação da OEA.",
      "a fundação da Comissão Econômica para a América Latina (CEPAL), em Santiago.",
      "a formação do Mercado Comum Centro-Americano sob liderança brasileira.",
    ],
    "A proposta de JK a Eisenhower veio logo depois da viagem em que o vice Nixon foi hostilizado em Lima e Caracas. O BID, antiga reivindicação latino-americana, saiu em 1959. TIAR, OEA e CEPAL são dos anos 1940; a Aliança para o Progresso, herdeira da OPA, é de 1961.",
    "OPA (1958) → BID (1959) → Aliança para o Progresso (1961)."),
  k("jk-34", "dificil", "Unesp", "A aliança PSD–PTB, base do governo JK, apoiava-se num arranjo tácito sobre o mundo rural. Esse arranjo consistia em:",
    [
      "não estender a legislação trabalhista ao campo nem tocar na estrutura fundiária.",
      "realizar a reforma agrária apenas nas terras públicas do Centro-Oeste e da Amazônia, longe dos latifúndios.",
      "entregar ao PTB a organização dos sindicatos rurais.",
      "tributar pesadamente os latifúndios improdutivos.",
    ],
    "O PSD reunia os chefes políticos do interior; o PTB, os trabalhadores das cidades. A convivência dependia de o trabalhismo não atravessar a porteira. Enquanto isso, as Ligas Camponesas surgiam em Pernambuco (Engenho Galileia, 1955). Quando Jango levou as reformas ao campo, o PSD abandonou a aliança.",
    "PTB na cidade, PSD no campo: cada um no seu terreno."),
  k("jk-35", "dificil", "Fuvest", "Sobre o Plano de Metas, todas as afirmativas estão corretas, EXCETO:",
    [
      "Estabeleceu metas quantitativas de desapropriação de terras para a reforma agrária.",
      "Incluiu a construção naval e a mecanização agrícola entre seus objetivos.",
      "Tratou a construção de Brasília como meta-síntese, acrescentada às trinta metas setoriais originais.",
      "Baseou-se em diagnósticos da Comissão Mista Brasil–EUA e do grupo misto BNDE–CEPAL.",
      "Previu a expansão da produção de petróleo e da capacidade de refino.",
    ],
    "O plano tinha trinta metas em cinco setores (energia, transportes, alimentação, indústrias de base e educação), mais Brasília. Na \"alimentação\" entravam armazéns, frigoríficos, tratores e fertilizantes: modernizar a produção sem mexer na propriedade da terra.",
    "Metas de trator, sim; de reforma agrária, não."),
  k("jk-36", "dificil", "UFPR", "Apesar da popularidade, JK não elegeu o sucessor em 1960. A derrota do marechal Lott para Jânio Quadros costuma ser atribuída:",
    [
      "ao desgaste da inflação e das denúncias de corrupção, explorado por um adversário que se dizia acima dos partidos.",
      "ao veto dos ministros militares à candidatura de um oficial da ativa, que obrigou o PSD a trocar de candidato às vésperas.",
      "à divisão do PTB, que lançou João Goulart contra Lott para a presidência.",
      "à decisão de JK de apoiar publicamente Jânio contra o candidato de seu próprio partido, para voltar em 1965 como oposição.",
      "ao apoio dos comunistas a Jânio, por causa de sua política externa.",
    ],
    "Jânio fez campanha contra \"tudo isso que aí está\", com a vassoura e o discurso moralista, e teve quase metade dos votos. Lott era mau orador e candidato pouco empolgante. Jango concorreu a vice na chapa de Lott e venceu; o PCB apoiou Lott.",
    "A conta dos \"50 anos em 5\" chegou em 1960."),

  // ───────── Jânio e a Legalidade ─────────
  j("jan-21", "medio", "Fuvest", "A Instrução 204 da SUMOC (março de 1961), principal medida econômica do governo Jânio Quadros:",
    [
      "desvalorizou o cruzeiro e cortou os subsídios cambiais ao trigo e ao petróleo, encarecendo o custo de vida.",
      "congelou preços, aluguéis e salários por dois anos e criou um órgão federal para fiscalizar o abastecimento.",
      "decretou a moratória da dívida externa e suspendeu as negociações com os credores norte-americanos e europeus.",
      "criou o monopólio estatal do câmbio e proibiu a remessa de lucros das empresas estrangeiras para as matrizes.",
      "restabeleceu os leilões de câmbio abolidos por JK.",
    ],
    "Foi uma reforma ortodoxa, bem recebida pelo FMI e pelos credores, que renegociaram a dívida. Internamente, o pão e o transporte subiram. É a metade \"de direita\" de um governo que, na diplomacia, fazia acenos à esquerda.",
    "204: remédio amargo que agradou ao FMI."),
  j("jan-22", "medio", "Unicamp", "Na Conferência de Punta del Este (janeiro de 1962), já no governo Goulart, a diplomacia brasileira aplicou a política externa independente ao:",
    [
      "abster-se na votação que excluiu Cuba da OEA, invocando a não intervenção e a autodeterminação.",
      "propor a expulsão de Cuba do sistema interamericano e o envio de tropas da OEA à ilha, sob comando brasileiro.",
      "romper relações com os Estados Unidos em solidariedade a Fidel Castro.",
      "retirar o Brasil da Organização dos Estados Americanos.",
    ],
    "O chanceler San Tiago Dantas sustentou que um país não podia ser punido por seu regime interno. O Brasil não votou a favor de Cuba: absteve-se, junto com Argentina, México, Chile, Bolívia e Equador. A posição irritou Washington e os conservadores brasileiros.",
    "Independente não é pró-Cuba: é contra a intervenção."),
  j("jan-23", "medio", "UERJ", "Jânio Quadros ficou famoso por medidas como proibir rinhas de galo, lança-perfume e biquínis em concursos de beleza, e por governar por meio de \"bilhetinhos\". Essas práticas indicam:",
    [
      "um estilo personalista e moralista, que falava direto à opinião pública e passava por cima de partidos e do Congresso.",
      "a força da base parlamentar do presidente, que aprovava com rapidez suas propostas.",
      "a influência decisiva da UDN na definição da agenda do governo.",
      "um programa de modernização dos costumes inspirado nos movimentos juvenis.",
      "a prioridade dada pelo governo às questões econômicas e administrativas.",
    ],
    "Jânio não tinha maioria (o Congresso eleito em 1958 era dominado por PSD e PTB) nem fidelidade a partido algum. Os bilhetinhos aos ministros e as proibições de impacto eram formas de ocupar o noticiário e mostrar autoridade. Era o inverso de base parlamentar forte, e seria fatal em agosto.",
    "Muito bilhete, pouca bancada."),
  j("jan-24", "medio", "Unesp", "Na véspera da renúncia, em 24 de agosto de 1961, Carlos Lacerda foi à televisão para:",
    [
      "denunciar que o ministro da Justiça o sondara para um golpe destinado a ampliar os poderes do presidente.",
      "defender a condecoração de Che Guevara como gesto de soberania e anunciar seu apoio à política externa independente.",
      "anunciar sua adesão à Campanha da Legalidade.",
      "pedir a intervenção das Forças Armadas contra a posse de Jango, que regressava de uma viagem à China comunista.",
    ],
    "Lacerda, que apoiara Jânio em 1960, rompera com ele por causa da política externa e da medalha dada a Che cinco dias antes. Sua denúncia contra o ministro Pedroso Horta reforça a tese de que a renúncia do dia seguinte foi uma manobra. A Legalidade só começa depois, e Lacerda ficou contra ela.",
    "Dia 19: medalha · dia 24: denúncia · dia 25: renúncia."),
  j("jan-25", "medio", "UFRGS", "A emenda constitucional que implantou o parlamentarismo em setembro de 1961 (o Ato Adicional) previa que a manutenção do sistema seria decidida:",
    [
      "em plebiscito a realizar-se no fim do mandato de Goulart, consulta que acabou antecipada para janeiro de 1963.",
      "pelo Congresso Nacional, por maioria de dois terços, logo depois das eleições parlamentares e estaduais de outubro de 1962.",
      "pelos ministros militares, que conservavam poder de veto.",
      "por uma Assembleia Constituinte a ser eleita em 1962, junto com os governadores e a nova Câmara dos Deputados.",
      "pelo Supremo Tribunal Federal, em julgamento sobre a validade da emenda, pedido pelos partidos derrotados na votação.",
    ],
    "A consulta estava marcada para nove meses antes do término do mandato, ou seja, 1965. Com apoio de governadores que queriam disputar uma presidência com poderes plenos, e sob pressão de greves, Jango obteve a antecipação.",
    "Era para 1965; veio em 1963."),
  j("jan-26", "medio", "Fuvest", "Enquanto João Goulart regressava da China, a Presidência da República foi exercida interinamente por:",
    [
      "Ranieri Mazzilli, presidente da Câmara dos Deputados.",
      "Tancredo Neves, indicado primeiro-ministro pelo Congresso.",
      "Odílio Denys, ministro da Guerra.",
      "Auro de Moura Andrade, presidente do Senado.",
      "Leonel Brizola, por aclamação dos governadores reunidos na Rede da Legalidade.",
    ],
    "O vice-presidente da República era, pela Constituição, o presidente do Senado; na sua ausência, o primeiro da linha era o presidente da Câmara. Mazzilli assumiu formalmente, mas quem mandava eram os três ministros militares. Ele voltaria ao cargo, de novo como figurante, em abril de 1964.",
    "Mazzilli: interino em 1961 e em 1964."),

  j("jan-31", "dificil", "Unicamp", "Considere as afirmativas sobre a Campanha da Legalidade (1961).\n\nI. Brizola requisitou uma emissora de rádio e formou uma cadeia que alcançou todo o país.\nII. O governador de Goiás, Mauro Borges, também se levantou em defesa da posse.\nIII. O III Exército aderiu no primeiro dia, cumprindo ordem do ministro da Guerra.\n\nEstá correto o que se afirma em:",
    [I_II, SO_I, TODAS, I_III, SO_II],
    "Brizola requisitou a Rádio Guaíba e instalou os transmissores nos porões do Palácio Piratini. Mauro Borges mobilizou Goiás. O general Machado Lopes só aderiu no dia 28, depois de receber de Brasília a ordem de calar Brizola, se preciso bombardeando o palácio: desobedeceu ao ministro, em vez de cumpri-lo.",
    "O III Exército aderiu desobedecendo."),
  j("jan-32", "dificil", "Fuvest", "Em setembro de 1961, Brizola defendia que Jango rejeitasse o parlamentarismo e marchasse sobre Brasília com o III Exército. Goulart aceitou a emenda porque:",
    [
      "preferiu assumir com poderes reduzidos a arriscar uma guerra civil, contando recuperá-los mais adiante.",
      "considerava o parlamentarismo superior e já o defendia desde o governo JK.",
      "foi obrigado por decisão do Supremo Tribunal Federal.",
      "o III Exército voltou atrás e retirou o apoio à sua posse.",
      "recebeu dos três ministros militares a promessa formal de um plebiscito imediato, a ser realizado ainda em 1961.",
    ],
    "Jango era um conciliador por temperamento e por cálculo. Entrou no país pelo Sul, depois de dias de negociação e de a FAB cogitar interceptar seu avião (a Operação Mosquito). A decisão abriu uma ferida com Brizola e com a esquerda trabalhista, que reapareceria em 1963–64.",
    "Jango negocia; Brizola queria marchar."),
  j("jan-33", "dificil", "UERJ", "A manobra de Jânio falhou, entre outras razões, porque o Congresso se limitou a tomar conhecimento da renúncia. Isso ocorreu porque:",
    [
      "a renúncia é ato unilateral, que dispensa votação, e a maioria PSD–PTB não tinha interesse em pedir a volta do presidente.",
      "a Constituição mandava convocar novas eleições em trinta dias.",
      "os parlamentares da UDN votaram em bloco pela aceitação.",
      "os ministros militares fecharam o Congresso antes de qualquer deliberação.",
      "Jânio retirou a carta no dia seguinte, mas o prazo legal já havia expirado.",
    ],
    "O presidente do Senado, Auro de Moura Andrade, leu a carta e declarou o cargo vago: não havia o que votar. Jânio vinha tratando o Legislativo com desprezo, e os partidos majoritários eram seus adversários. Ele embarcou para Santos esperando um apelo que não veio.",
    "Renúncia não se vota: comunica-se."),
  j("jan-34", "dificil", "Unesp", "Entre as motivações atribuídas à política externa independente de Jânio Quadros, NÃO se inclui:",
    [
      "preparar a adesão do Brasil ao Pacto de Varsóvia.",
      "abrir mercados para as exportações no Leste Europeu, na África e na Ásia.",
      "aumentar o poder de barganha do país diante dos Estados Unidos.",
      "compensar, junto à esquerda, o custo de uma política econômica ortodoxa.",
      "projetar o Brasil entre os países recém-independentes.",
    ],
    "A PEI era pragmática: mais mercados, mais autonomia e algum dividendo interno. Nunca cogitou aliança militar com Moscou, e o Brasil não aderiu sequer ao Movimento dos Não Alinhados (esteve em Belgrado, em 1961, como observador).",
    "Independente ≠ neutro ≠ socialista."),
  j("jan-35", "dificil", "Fuvest", "Sobre a experiência parlamentarista (setembro de 1961 a janeiro de 1963), é correto afirmar que:",
    [
      "teve três gabinetes em dezesseis meses e uma greve geral durante a crise ministerial de julho de 1962.",
      "foi estável, com Tancredo Neves à frente do governo durante todo o período e maioria sólida no Congresso.",
      "só entrou em vigor depois de aprovada pelos eleitores em plebiscito.",
      "foi encerrada por um golpe dos ministros militares.",
      "manteve João Goulart afastado de qualquer decisão política, restrito às funções cerimoniais de chefe de Estado.",
    ],
    "Sucederam-se Tancredo Neves, Brochado da Rocha e Hermes Lima. Em julho de 1962, a Câmara rejeitou San Tiago Dantas, e Auro de Moura Andrade renunciou antes de formar governo; os sindicatos pararam, e dessa mobilização nasceu o CGT. Jango trabalhou o tempo todo para mostrar que o sistema não funcionava.",
    "Tancredo → Brochado → Hermes Lima."),
  j("jan-36", "dificil", "UFPR", "Na carta de renúncia, Jânio fala em \"forças terríveis\" que se levantaram contra ele, ecoando a Carta-Testamento de Vargas. A comparação entre os dois episódios mostra que:",
    [
      "Vargas contava com sindicatos, um partido e a lealdade de milhões; Jânio não tinha organização que saísse às ruas por ele.",
      "nos dois casos a comoção popular impediu a posse do vice-presidente e forçou a convocação de uma nova eleição presidencial.",
      "ambos foram depostos por ultimato militar.",
      "Jânio obteve o que Vargas não conseguiu: voltar ao poder nos braços do povo.",
    ],
    "O gesto de 1954 funcionou porque havia o trabalhismo por trás. Jânio fora eleito por votos de protesto, sem partido próprio, sem sindicatos e já brigado com a UDN. A retórica era a mesma; a base social, nenhuma.",
    "Carisma sem organização não enche a rua."),

  // ───────── Jango e o golpe ─────────
  g("jng-21", "medio", "Fuvest", "O principal obstáculo jurídico à reforma agrária proposta por Jango estava na Constituição de 1946, que:",
    [
      "exigia indenização prévia e em dinheiro para qualquer desapropriação.",
      "proibia a desapropriação de imóveis rurais explorados por seus proprietários.",
      "reservava aos estados, e não à União, a competência para legislar sobre a propriedade da terra.",
      "limitava a reforma agrária às terras devolutas da Amazônia e do Centro-Oeste.",
    ],
    "Pagar à vista e em dinheiro tornava a reforma financeiramente impossível. O governo pedia uma emenda que permitisse indenizar com títulos da dívida pública, e ela precisava de dois terços do Congresso. O PSD recusou, e o impasse levou Jango aos decretos do Comício da Central.",
    "Sem emenda não havia reforma; sem PSD não havia emenda."),
  g("jng-22", "medio", "Unicamp", "A Revolta dos Sargentos, em Brasília (setembro de 1963), foi desencadeada:",
    [
      "pela decisão do Supremo Tribunal Federal que confirmou a inelegibilidade dos sargentos eleitos em 1962.",
      "pela prisão de dirigentes do CGT durante uma greve geral, ordenada por comandantes militares sem aval do presidente.",
      "pelo anúncio da reforma agrária por decreto.",
      "pela demissão do ministro da Guerra, favorável às reformas, e sua substituição por um general ligado a Lacerda.",
      "pela tentativa de Jango de fechar o Congresso.",
    ],
    "Sargentos da Aeronáutica e da Marinha ocuparam prédios e detiveram autoridades por algumas horas. O movimento foi contido, mas a reação branda do governo fez crescer, entre os oficiais, a ideia de que Jango tolerava a quebra da hierarquia. A Revolta dos Marinheiros é outro episódio, de março de 1964.",
    "Sargentos: 1963, Brasília. Marinheiros: 1964, Rio."),
  g("jng-23", "medio", "UERJ", "Em outubro de 1963, Jango pediu ao Congresso a decretação do estado de sítio. O resultado foi:",
    [
      "a rejeição da medida pela direita e pela esquerda, o que obrigou o presidente a retirar o pedido e o deixou mais isolado.",
      "a aprovação do pedido e a prisão de Carlos Lacerda.",
      "o fechamento temporário do Congresso pelos ministros militares, que assumiram o governo até o fim do recesso parlamentar.",
      "a renúncia coletiva do ministério.",
    ],
    "O estopim foi uma entrevista de Lacerda a um jornal americano, atacando o governo e os chefes militares. A direita viu na medida o ensaio de um golpe; a esquerda temeu que servisse contra Miguel Arraes e os sindicatos. Sem apoio de ninguém, Jango recuou em três dias.",
    "Estado de sítio: todos contra, por motivos opostos."),
  g("jng-24", "medio", "Unesp", "O IBAD (Instituto Brasileiro de Ação Democrática) foi investigado por uma CPI e fechado em 1963 porque:",
    [
      "financiou, com dinheiro de origem estrangeira, a campanha de centenas de candidatos contrários a Jango nas eleições de 1962.",
      "organizou a Revolta dos Sargentos em Brasília.",
      "recebia verbas do governo cubano para treinar guerrilheiros.",
      "desviou recursos da Sudene e da Aliança para o Progresso para financiar sindicatos rurais e ligas camponesas no interior do Nordeste.",
      "promoveu atentados contra jornais de oposição.",
    ],
    "O IBAD bancou propaganda e candidatos a deputado e a governador. A CPI apontou recursos de empresas estrangeiras e do governo americano. Seu parceiro, o IPES, reunia empresários e oficiais da reserva, produzia filmes e análises e seguiu ativo até o golpe.",
    "IBAD paga a campanha; IPES pensa a conspiração."),
  g("jng-25", "medio", "UFRGS", "Aprovado em 1963, o Estatuto do Trabalhador Rural é importante porque:",
    [
      "estendeu ao campo direitos como carteira assinada, salário mínimo e férias, e facilitou a sindicalização rural.",
      "desapropriou os latifúndios improdutivos e distribuiu a terra aos trabalhadores sem indenizar os antigos proprietários.",
      "extinguiu as Ligas Camponesas e proibiu sindicatos no campo, em troca da concessão de alguns direitos individuais.",
      "transferiu a questão agrária para a alçada dos estados.",
    ],
    "A CLT, de 1943, valia para os trabalhadores urbanos. O Estatuto levou parte desses direitos ao campo e foi seguido da criação da CONTAG. Não mexia na propriedade da terra: isso era a reforma agrária, que não passou. Para os proprietários, porém, já era uma mudança ameaçadora.",
    "Estatuto dá direitos; reforma agrária daria terra."),
  g("jng-26", "medio", "Fuvest", "No início de 1964, as esquerdas estavam divididas. A Frente de Mobilização Popular, liderada por Brizola, distinguia-se da frente proposta por San Tiago Dantas por:",
    [
      "exigir reformas imediatas, mesmo contra o Congresso, e recusar a conciliação com o PSD.",
      "defender a aliança com o PSD e a negociação parlamentar das reformas, mesmo que saíssem incompletas.",
      "apoiar o Plano Trienal e a política de estabilização como condição prévia para as reformas.",
      "pregar o apoio crítico à UDN contra o governo.",
      "condenar a mobilização de sargentos e marinheiros, por entender que ela unia os oficiais contra o governo.",
    ],
    "San Tiago Dantas falava numa \"esquerda positiva\", capaz de recompor a maioria com o centro. Brizola, com CGT, UNE e parte do PTB, apostava na pressão direta: \"reforma agrária na lei ou na marra\". Jango oscilou e, em março, pendeu para o grupo de Brizola.",
    "Dantas queria ponte; Brizola, pressão."),

  g("jng-31", "dificil", "Unicamp", "Considere as afirmativas sobre a execução do golpe de 1964.\n\nI. O general Mourão Filho saiu de Juiz de Fora antecipando-se aos planos do grupo ligado a Castelo Branco.\nII. O comandante do II Exército, Amaury Kruel, aderiu depois que Jango se recusou a romper com o CGT.\nIII. Jango ordenou a resistência armada, e as tropas legalistas foram batidas em combate no vale do Paraíba.\n\nEstá correto o que se afirma em:",
    [I_II, TODAS, SO_II, II_III, SO_I],
    "Mourão precipitou o movimento, para irritação dos conspiradores \"cerebrais\" do Rio. Kruel, amigo de Jango, telefonou propondo apoiá-lo se ele se afastasse da esquerda sindical; ouviu um não. Não houve combate: as tropas enviadas contra os rebeldes confraternizaram com eles, e o presidente proibiu a resistência.",
    "O golpe venceu sem dar um tiro."),
  g("jng-32", "dificil", "Fuvest", "Uma interpretação influente do golpe de 1964, baseada no estudo do complexo IPES/IBAD, sustenta que ele foi:",
    [
      "uma ação de classe, preparada por empresários ligados ao capital multinacional e por militares, para assumir o controle do Estado.",
      "um ato improvisado de militares isolados, sem articulação prévia com civis.",
      "o resultado inevitável da crise econômica, independentemente das escolhas dos atores.",
      "uma resposta defensiva a um autogolpe comprovadamente marcado por Jango para maio.",
      "um movimento conduzido pelo Congresso, que apenas usou os militares.",
    ],
    "Essa leitura enfatiza a conspiração organizada: financiamento, propaganda e um projeto de governo pronto. Outras interpretações destacam a radicalização dos dois lados e a perda de compromisso de direita e esquerda com as regras democráticas. Saber distinguir as teses é o que as provas mais exigentes cobram.",
    "Há quem explique 1964 pela conspiração e quem o explique pela radicalização."),
  g("jng-33", "dificil", "UERJ", "O preâmbulo do Ato Institucional de 9 de abril de 1964 afirma que a \"revolução vitoriosa se investe no exercício do Poder Constituinte\" e \"se legitima por si mesma\". A passagem significa que:",
    [
      "os militares não derivavam sua autoridade do Congresso; era o Congresso que passava a existir por concessão deles.",
      "o novo regime se submetia integralmente à Constituição de 1946.",
      "o poder seria devolvido de imediato a uma Assembleia Constituinte eleita.",
      "o ato precisava ser ratificado em plebiscito.",
      "a legitimidade do governo vinha da declaração de vacância feita pelo Senado.",
    ],
    "O Ato manteve a Constituição de 1946 e o Congresso, mas só no que não o contrariasse, e autorizou cassações de mandatos e suspensão de direitos políticos por dez anos. Com o Legislativo já expurgado, Castelo Branco foi eleito indiretamente em 11 de abril. É a lógica dos atos institucionais até o AI-5.",
    "O Ato não pede licença: concede."),
  g("jng-34", "dificil", "Unesp", "Em 1963, o governo dos Estados Unidos adotou em relação ao Brasil a política conhecida como \"ilhas de sanidade administrativa\". Ela consistia em:",
    [
      "negar recursos ao governo federal e destiná-los diretamente a governadores de oposição a Jango.",
      "financiar o Plano Trienal em troca da aprovação das Reformas de Base pelo Congresso e de um novo acordo com o FMI.",
      "suspender toda a ajuda ao país até a realização de novas eleições.",
      "apoiar a Sudene como alternativa à radicalização no Nordeste.",
      "condicionar empréstimos à nacionalização das empresas americanas de serviços públicos, com indenização.",
    ],
    "Verbas da Aliança para o Progresso foram para estados como a Guanabara de Lacerda, fortalecendo adversários do presidente. Somada ao dinheiro do IBAD em 1962 e à Operação Brother Sam, a medida mostra que a interferência americana foi muito além da simpatia pelo golpe.",
    "Dinheiro para os governadores, não para o presidente."),
  g("jng-35", "dificil", "Fuvest", "No plebiscito de janeiro de 1963, o presidencialismo venceu por larga margem. O resultado, porém, não resolveu o impasse do governo porque:",
    [
      "o Congresso eleito em 1962 continuava de maioria conservadora, e as reformas dependiam de emendas constitucionais.",
      "o comparecimento foi tão baixo que a consulta acabou anulada pela Justiça Eleitoral, mantendo-se o gabinete de Hermes Lima.",
      "os ministros militares não reconheceram o resultado.",
      "o PTB perdeu a metade de sua bancada nas eleições realizadas no mesmo dia.",
      "a vitória foi interpretada por Jango como rejeição popular às reformas.",
    ],
    "Jango leu os números como mandato pessoal para as reformas. Mas o plebiscito não mudou o Legislativo: em 1962 o PTB crescera muito, sem tirar do PSD e da UDN, somados, o poder de bloquear qualquer emenda. Presidente forte nas urnas, fraco no Congresso.",
    "Ganhou a caneta, não ganhou os votos no Congresso."),
  g("jng-36", "dificil", "UFPR", "A Marcha da Família com Deus pela Liberdade (São Paulo, 19 de março de 1964) teve papel estratégico na preparação do golpe porque:",
    [
      "exibiu, seis dias após o Comício da Central, uma base civil de massa que os militares poderiam invocar.",
      "foi convocada pelos comandantes militares de São Paulo e desfilou sob a proteção ostensiva de tropas do II Exército.",
      "reuniu sobretudo operários sindicalizados, descontentes com a inflação e com o atraso no reajuste do salário mínimo.",
      "pediu a volta do parlamentarismo e a permanência de Jango apenas como chefe de Estado, sem poderes de governo.",
      "ocorreu depois da deposição do presidente, como celebração.",
    ],
    "Organizada por entidades femininas católicas (como a União Cívica Feminina), com apoio do governador Ademar de Barros, de empresários e de parte do clero, reuniu centenas de milhares de pessoas, em maioria de classe média. A marcha posterior ao golpe foi a do Rio, em 2 de abril, a \"Marcha da Vitória\".",
    "13 de março: Central · 19: Marcha · 31: tropas."),
];
