import type { Questao } from "@/lib/tipos";
import { criar } from "./criar";

const f = criar("guerra-fria");
const vt = criar("vietna");
const dc = criar("descolonizacao");
const m = criar("maio68");
const p = criar("figuras");

/** Combinações usadas nas questões de análise de afirmativas (I, II e III). */
const I_II = "Apenas I e II.";
const I_III = "Apenas I e III.";
const II_III = "Apenas II e III.";
const SO_I = "Apenas I.";
const SO_II = "Apenas II.";
const TODAS = "I, II e III.";

/** Níveis médio e difícil dos temas de Mundo e das figuras. A primeira alternativa é a correta. */
export const avancadasMundo: Questao[] = [
  // ───────── Guerra Fria ─────────
  f("gf-21", "medio", "Fuvest", "O bloqueio de Berlim (1948–49), primeira grande crise da Guerra Fria, foi a resposta de Stalin:",
    [
      "à reforma monetária que unificou as zonas ocidentais de ocupação e anunciava um Estado alemão ocidental.",
      "à entrada da Alemanha Ocidental na OTAN e ao seu rearmamento, autorizado pelos aliados apesar dos protestos de Moscou.",
      "à construção do muro que isolou o setor ocidental da cidade e interrompeu a fuga de trabalhadores qualificados.",
      "à criação do Pacto de Varsóvia pelos países do Leste.",
      "ao lançamento do Sputnik pelos norte-americanos.",
    ],
    "A introdução do marco alemão nas zonas americana, britânica e francesa levou a URSS a fechar os acessos terrestres a Berlim Ocidental. Os aliados abasteceram a cidade por uma ponte aérea durante quase um ano. Resultado: duas Alemanhas em 1949. A entrada na OTAN é de 1955, o muro de 1961, e o Sputnik é soviético.",
    "Bloqueio (1948) não é muro (1961)."),
  f("gf-22", "medio", "Unicamp", "O diplomata George Kennan, autor do \"longo telegrama\" (1946) e do artigo assinado como \"X\" (1947), forneceu a base intelectual da política norte-americana de:",
    [
      "contenção: barrar, com firmeza e paciência, a expansão soviética em cada ponto em que ela ocorresse.",
      "reversão: libertar pela força os países já ocupados pelo Exército Vermelho.",
      "isolacionismo: retirar os Estados Unidos dos assuntos europeus.",
      "distensão: reduzir os arsenais por meio de tratados bilaterais.",
    ],
    "Kennan argumentava que o regime soviético era expansionista, mas cauteloso, e recuaria diante de resistência firme. A ideia orientou a Doutrina Truman e o Plano Marshall. \"Reversão\" (rollback) foi um discurso dos anos 1950, pouco praticado; a distensão é dos anos 1970.",
    "Kennan = conter, não invadir."),
  f("gf-23", "medio", "Unesp", "Criado em 1947, o Kominform tinha como finalidade:",
    [
      "coordenar os partidos comunistas europeus sob a orientação de Moscou, na lógica dos \"dois campos\".",
      "organizar a ajuda econômica e as trocas comerciais entre as democracias populares do Leste Europeu.",
      "comandar as forças militares conjuntas do bloco socialista e planejar a defesa das fronteiras ocidentais.",
      "planejar a produção industrial e agrícola soviética em ciclos de cinco anos, com metas para cada república.",
      "representar os países socialistas na Assembleia Geral da ONU.",
    ],
    "O Escritório de Informação dos Partidos Comunistas foi a resposta política ao Plano Marshall; nele se formulou a tese de que o mundo estava dividido em um campo imperialista e um campo democrático. Economia era com o Comecon (1949), e defesa, com o Pacto de Varsóvia (1955).",
    "Kominform = política · Comecon = economia · Varsóvia = armas."),
  f("gf-24", "medio", "UERJ", "Em 1948, a Iugoslávia de Tito foi expulsa do Kominform. O episódio é significativo porque:",
    [
      "mostrou que um país podia ser socialista sem obedecer a Moscou, abrindo caminho para o não alinhamento.",
      "levou a Iugoslávia a restaurar o capitalismo e a aderir à OTAN.",
      "provocou a invasão do país por tropas do Pacto de Varsóvia.",
      "resultou na anexação da Iugoslávia pela União Soviética.",
    ],
    "Tito chegara ao poder com seus próprios guerrilheiros, sem depender do Exército Vermelho, e recusou a tutela de Stalin. Manteve o partido único e a economia socialista, mas com política externa autônoma, e seria um dos fundadores do Movimento dos Não Alinhados. O Pacto de Varsóvia nem existia em 1948.",
    "Tito: comunista, mas não satélite."),
  f("gf-25", "medio", "UFRGS", "Nos Estados Unidos do início dos anos 1950, o macarthismo consistiu:",
    [
      "numa campanha de perseguição a supostos comunistas no serviço público, no cinema e nas universidades.",
      "num programa de ajuda econômica aos aliados asiáticos.",
      "na doutrina militar da retaliação nuclear maciça contra qualquer avanço soviético na Europa ou na Ásia.",
      "no movimento pelos direitos civis da população negra.",
      "na política de boa vizinhança com a América Latina.",
    ],
    "O senador Joseph McCarthy liderou investigações baseadas em acusações quase sempre sem provas; carreiras foram destruídas por \"listas negras\". O clima foi alimentado pela vitória de Mao, pela bomba soviética (1949) e pela Guerra da Coreia. A Guerra Fria teve custo interno também no lado que se dizia o \"mundo livre\".",
    "Macarthismo = caça às bruxas."),
  f("gf-26", "medio", "Fuvest", "O lançamento do Sputnik pela União Soviética, em 1957, teve como efeito nos Estados Unidos:",
    [
      "o temor de inferioridade tecnológica e militar, que levou à criação da NASA e a mais investimento em ciência.",
      "a decisão de abandonar a corrida espacial e concentrar os recursos em armas convencionais e em bases no exterior.",
      "a assinatura imediata de um tratado de desarmamento nuclear, proposto por Eisenhower para congelar a vantagem soviética.",
      "o rompimento de relações diplomáticas com Moscou.",
    ],
    "Um foguete capaz de pôr um satélite em órbita podia levar uma ogiva a outro continente: o território americano deixava de ser inatingível. A reação incluiu a NASA (1958) e reformas no ensino. Os soviéticos ainda poriam o primeiro homem no espaço (Gagarin, 1961) antes de os americanos chegarem à Lua (1969).",
    "Sputnik 57 → NASA 58 → Gagarin 61 → Lua 69."),

  f("gf-31", "dificil", "Unicamp", "Considere as afirmativas sobre a Guerra da Coreia (1950–1953).\n\nI. A intervenção sob a bandeira da ONU foi aprovada porque a União Soviética boicotava o Conselho de Segurança.\nII. A China entrou no conflito quando as tropas lideradas pelos EUA se aproximaram de sua fronteira.\nIII. O armistício de 1953 foi seguido de um tratado de paz que reunificou a península.\n\nEstá correto o que se afirma em:",
    [I_II, SO_II, TODAS, II_III, SO_I],
    "Moscou estava ausente do Conselho em protesto contra a permanência de Taiwan no assento chinês e não pôde vetar. Quando as forças do general MacArthur avançaram rumo ao rio Yalu, centenas de milhares de \"voluntários\" chineses as empurraram de volta. O armistício restabeleceu a divisão perto do paralelo 38; tratado de paz nunca houve.",
    "Coreia: armistício sem paz, até hoje."),
  f("gf-32", "dificil", "Fuvest", "Na crise de Suez (1956), Estados Unidos e União Soviética pressionaram, cada um a seu modo, pela retirada das tropas britânicas, francesas e israelenses do Egito. O episódio demonstrou:",
    [
      "que as antigas potências coloniais europeias já não conseguiam agir sem o aval das superpotências.",
      "a formação de uma aliança militar duradoura entre Washington e Moscou para policiar o Oriente Médio.",
      "a força do Reino Unido, que impôs o controle internacional do canal e manteve suas bases militares no Egito.",
      "o fracasso de Nasser, derrubado logo depois da intervenção por oficiais favoráveis a um acordo com Israel.",
      "a neutralidade dos países árabes diante da Guerra Fria.",
    ],
    "Nasser nacionalizara o canal; Londres, Paris e Tel Aviv atacaram. Washington, que não fora consultada, usou pressão financeira, e Moscou fez ameaças. Os invasores recuaram, e Nasser saiu fortalecido, herói do nacionalismo árabe. Na mesma semana, os tanques soviéticos esmagavam a revolta húngara.",
    "Suez: o enterro do imperialismo franco-britânico."),
  f("gf-33", "dificil", "UERJ", "O rompimento sino-soviético, consolidado nos anos 1960, teve como desdobramento diplomático de maior alcance:",
    [
      "a aproximação entre os Estados Unidos e a China, selada com a visita de Nixon a Pequim em 1972.",
      "a entrada da China no Pacto de Varsóvia, solução encontrada para pôr fim aos incidentes de fronteira.",
      "a reunificação da China continental com Taiwan.",
      "a adesão chinesa à política soviética de coexistência pacífica e ao tratado de proibição de testes nucleares.",
      "o fim do apoio de Pequim e de Moscou ao Vietnã do Norte.",
    ],
    "Divergências sobre Stalin, sobre a coexistência pacífica e sobre a liderança do movimento comunista chegaram a choques armados na fronteira (1969). Washington explorou a rivalidade: reconheceu Pequim como interlocutor e pressionou Moscou. O \"bloco comunista\" nunca foi o monólito que a teoria do dominó supunha.",
    "Dois comunismos rivais, e os EUA no meio."),
  f("gf-34", "dificil", "Unesp", "A distensão (détente) dos anos 1970 NÃO incluiu:",
    [
      "a dissolução simultânea da OTAN e do Pacto de Varsóvia.",
      "os acordos SALT, de limitação das armas nucleares estratégicas.",
      "a Conferência de Helsinque (1975), sobre segurança e cooperação na Europa.",
      "o reconhecimento mútuo entre as duas Alemanhas.",
      "a missão espacial conjunta Apollo–Soyuz.",
    ],
    "A distensão administrou a rivalidade sem extingui-la: limitou arsenais (SALT I, 1972), reconheceu as fronteiras do pós-guerra e abriu canais de cooperação. As alianças continuaram intactas. O período se encerrou com a invasão soviética do Afeganistão (1979) e o rearmamento da era Reagan.",
    "Distensão não é fim: é trégua negociada."),
  f("gf-35", "dificil", "Fuvest", "Formulada para justificar a invasão da Tchecoslováquia em 1968, a Doutrina Brejnev afirmava que:",
    [
      "a soberania de cada país socialista era limitada pelo interesse do conjunto do bloco.",
      "a União Soviética apoiaria qualquer movimento de libertação nacional no Terceiro Mundo.",
      "os países do Leste podiam escolher livremente seu modelo de socialismo.",
      "a URSS só usaria armas nucleares em resposta a um ataque.",
    ],
    "É a tese da \"soberania limitada\": se o socialismo estivesse ameaçado num país, os demais tinham o direito de intervir. Foi a versão soviética da lógica das esferas de influência, como os EUA praticavam na América Latina. Gorbachev a abandonou nos anos 1980, e os regimes do Leste caíram em 1989.",
    "Brejnev: ninguém sai do bloco."),
  f("gf-36", "dificil", "UFPR", "Passada a Crise dos Mísseis, as superpotências tomaram medidas para reduzir o risco de guerra nuclear. Entre elas está:",
    [
      "o tratado de 1963 que proibiu testes nucleares na atmosfera, no espaço e sob a água.",
      "a eliminação completa dos mísseis intercontinentais dos dois lados, sob inspeção mútua.",
      "a transferência do controle de todos os arsenais nucleares ao Conselho de Segurança das Nações Unidas.",
      "o compromisso de retirar todas as tropas estrangeiras da Europa.",
      "a entrega de armas atômicas aos principais aliados, para equilibrar as forças em cada região.",
    ],
    "Além do \"telefone vermelho\", EUA, URSS e Reino Unido assinaram em 1963 o Tratado de Proibição Parcial de Testes (os subterrâneos continuaram). Em 1968 veio o Tratado de Não Proliferação, cujo objetivo era justamente evitar que mais países tivessem a bomba. Os arsenais seguiram crescendo.",
    "Depois do susto: telefone (1963), testes (1963), não proliferação (1968)."),

  // ───────── Guerra do Vietnã ─────────
  vt("vie-21", "medio", "Fuvest", "O Viet Minh, fundado por Ho Chi Minh em 1941, era:",
    [
      "uma frente nacionalista dirigida pelos comunistas, criada para lutar contra os japoneses e os franceses.",
      "o exército regular do Vietnã do Sul, treinado e equipado pelos Estados Unidos a partir dos Acordos de Genebra.",
      "a guerrilha comunista que atuou no Sul durante os anos 1960, conhecida entre os americanos como vietcongue.",
      "o partido único que governou o Camboja depois de 1975.",
    ],
    "A Liga pela Independência do Vietnã reunia vários grupos sob liderança comunista. Tomou Hanói em agosto de 1945, com a rendição japonesa, e combateu a França até 1954. Vietcongue é outro nome e outra época: a Frente Nacional de Libertação, criada no Sul em 1960.",
    "Viet Minh: contra a França. Vietcongue: contra os EUA."),
  vt("vie-22", "medio", "Unicamp", "No início dos anos 1960, o governo Diem e seus assessores norte-americanos implantaram as \"aldeias estratégicas\". O programa:",
    [
      "removia camponeses para povoados fortificados, a fim de isolá-los da guerrilha, e acabou aumentando a hostilidade ao governo.",
      "distribuía as terras dos grandes proprietários, conquistando o apoio rural.",
      "transferia a população do Sul para o Norte, por meio de acordos com Hanói.",
      "criava cooperativas socialistas nos moldes chineses.",
      "instalava bases aéreas dos EUA em áreas desabitadas.",
    ],
    "Arrancadas de suas terras e dos túmulos dos antepassados, as famílias eram confinadas atrás de cercas. A guerrilha se infiltrava mesmo assim, e o ressentimento cresceu. É um exemplo de como a estratégia de contrainsurgência ignorava a sociedade que pretendia \"proteger\".",
    "Cercar o camponês não o conquistou."),
  vt("vie-23", "medio", "Unesp", "A Operação Rolling Thunder (1965–1968) foi:",
    [
      "a campanha de bombardeio aéreo contínuo sobre o Vietnã do Norte.",
      "a ofensiva vietcongue contra as cidades do Sul no ano-novo lunar.",
      "a retirada dos últimos norte-americanos de Saigon, por helicóptero.",
      "a invasão terrestre do Vietnã do Norte por tropas dos EUA.",
      "o desembarque francês que tentou romper o cerco de Dien Bien Phu.",
    ],
    "Lançada por Johnson, a operação pretendia quebrar a vontade de Hanói e interromper o envio de suprimentos. Não conseguiu nem uma coisa nem outra. Os EUA nunca invadiram o Norte por terra, temendo uma intervenção chinesa como a da Coreia. A ofensiva de ano-novo é a do Tet.",
    "Muita bomba, pouco resultado."),
  vt("vie-24", "medio", "UERJ", "A publicação dos Papéis do Pentágono, em 1971, abalou a credibilidade do governo dos Estados Unidos porque os documentos:",
    [
      "mostravam que sucessivos presidentes haviam ocultado do público a real extensão e as perspectivas da guerra.",
      "provavam que a União Soviética e a China haviam enviado tropas regulares para combater ao lado dos norte-vietnamitas.",
      "revelavam a existência de armas nucleares norte-americanas em Saigon.",
      "comprovavam que a imprensa inventara o massacre de My Lai.",
    ],
    "O estudo secreto, vazado pelo analista Daniel Ellsberg ao New York Times, cobria as decisões de Truman a Johnson. O governo Nixon tentou barrar a publicação e perdeu na Suprema Corte, num caso clássico de liberdade de imprensa.",
    "Os Papéis: o governo sabia e não dizia."),
  vt("vie-25", "medio", "UFRGS", "Em maio de 1970, a Guarda Nacional matou quatro estudantes na Universidade de Kent, em Ohio. Eles protestavam contra:",
    [
      "a invasão do Camboja, anunciada por Nixon dias antes.",
      "o envio das primeiras tropas de combate americanas ao Vietnã.",
      "o massacre de My Lai, que a imprensa havia revelado naquela semana.",
      "a assinatura dos Acordos de Paris, vistos como uma rendição.",
      "o assassinato de Martin Luther King.",
    ],
    "Nixon prometera \"vietnamizar\" a guerra e, em vez disso, ampliou-a para o país vizinho, a fim de atingir santuários norte-vietnamitas. A resposta foi uma onda de greves estudantis em centenas de universidades. As primeiras tropas de combate são de 1965; os Acordos de Paris, de 1973.",
    "Kent, 1970: a guerra chega ao campus."),
  vt("vie-26", "medio", "Fuvest", "A extensão da guerra ao Camboja, com bombardeios e a derrubada do príncipe Sihanouk (1970), teve como consequência:",
    [
      "a desestabilização do país e o fortalecimento do Khmer Vermelho, que tomou o poder em 1975.",
      "a derrota definitiva dos comunistas cambojanos, que só voltariam a atuar depois da reunificação do Vietnã.",
      "a neutralidade do Camboja até o fim do conflito, garantida por um acordo entre Washington, Hanói e Pequim.",
      "a anexação do território cambojano pelo Vietnã do Sul.",
    ],
    "O golpe do general Lon Nol, aliado de Washington, e os bombardeios empurraram camponeses para a guerrilha de Pol Pot. No poder, o Khmer Vermelho esvaziou as cidades e matou perto de um quarto da população, até ser derrubado pela invasão vietnamita de 1979.",
    "A guerra transbordou, e o Camboja pagou."),

  vt("vie-31", "dificil", "Unicamp", "Considere as afirmativas sobre os Acordos de Genebra (1954).\n\nI. A linha do paralelo 17 era uma demarcação militar provisória, e não uma fronteira entre Estados.\nII. Previam-se eleições gerais em 1956, sob supervisão de uma comissão internacional.\nIII. Os Estados Unidos e o governo do Vietnã do Sul não subscreveram a declaração final.\n\nEstá correto o que se afirma em:",
    [TODAS, I_II, SO_II, I_III, II_III],
    "As três estão corretas. O texto dizia expressamente que a linha não era fronteira política. Washington apenas \"tomou nota\" dos acordos, e Saigon sentiu-se livre para não realizar a consulta. Do ponto de vista de Hanói, a guerra seguinte não foi invasão de outro país, mas a retomada de uma unificação prometida.",
    "Genebra dividiu \"por enquanto\"; o enquanto durou 21 anos."),
  vt("vie-32", "dificil", "Fuvest", "Depois da Ofensiva do Tet, falou-se num \"abismo de credibilidade\" (credibility gap) nos Estados Unidos. A expressão refere-se:",
    [
      "à distância entre o otimismo dos comunicados oficiais e o que a população via nos noticiários.",
      "à perda de confiança dos aliados europeus na proteção nuclear oferecida pelos Estados Unidos no âmbito da OTAN.",
      "à diferença de poder de fogo entre as tropas dos Estados Unidos e as do Vietnã do Norte, revelada na ofensiva.",
      "à desconfiança crescente dos soldados americanos em relação a seus aliados e oficiais sul-vietnamitas.",
      "ao descrédito da imprensa, acusada de exagerar as baixas.",
    ],
    "Semanas antes, o comando afirmava enxergar \"a luz no fim do túnel\". Ver a embaixada em Saigon atacada desmentiu isso. O âncora Walter Cronkite declarou no ar que a guerra estava num impasse, e em 31 de março Johnson anunciou que não disputaria a reeleição.",
    "Tet: o governo dizia uma coisa, a TV mostrava outra."),
  vt("vie-33", "dificil", "UERJ", "Uma consequência institucional da guerra nos Estados Unidos foi a aprovação, em 1973, da Lei dos Poderes de Guerra, que:",
    [
      "limitou a capacidade do presidente de manter tropas em combate sem autorização do Congresso.",
      "transferiu ao Pentágono e ao Conselho de Segurança Nacional a decisão de declarar guerra a outro país.",
      "tornou permanente o serviço militar obrigatório.",
      "proibiu o envio de forças americanas ao exterior.",
      "deu ao presidente poderes ilimitados para empregar as Forças Armadas no exterior por tempo indeterminado.",
    ],
    "O Congresso reagia ao cheque em branco da Resolução do Golfo de Tonkin (1964), usada por Johnson e Nixon para travar uma guerra nunca declarada. A lei, aprovada sobre o veto de Nixon, fixa prazos para a retirada sem aval legislativo. O alistamento obrigatório, ao contrário, acabou naquele mesmo ano.",
    "Tonkin deu o cheque em branco; 1973 tentou cancelá-lo."),
  vt("vie-34", "dificil", "Unesp", "Em 1979, três anos depois da reunificação, o Vietnã ocupava o Camboja e era atacado pela China. Esses fatos contradizem a teoria do dominó porque mostram que:",
    [
      "os Estados comunistas da região agiam segundo rivalidades nacionais, e não como um bloco que avançava unido.",
      "o comunismo fora derrotado em todo o Sudeste Asiático.",
      "a China havia abandonado o socialismo e se aliado ao Vietnã do Sul.",
      "os Estados Unidos conservavam o controle militar da Indochina.",
      "o Vietnã havia rompido com Moscou para aderir à OTAN.",
    ],
    "Hanói, aliada da URSS, derrubou o Khmer Vermelho, protegido de Pequim; a China respondeu com uma invasão punitiva do norte vietnamita. A premissa americana de um comunismo único, comandado de fora, ignorava nacionalismos e inimizades seculares. Tailândia, Malásia e Indonésia não \"caíram\".",
    "Os dominós brigaram entre si."),
  vt("vie-35", "dificil", "Fuvest", "Nixon dizia buscar uma \"paz com honra\". Sobre o desfecho de sua política para o Vietnã, é correto afirmar que:",
    [
      "combinou a retirada de tropas com bombardeios intensos, como os do Natal de 1972, para forçar o acordo assinado em Paris.",
      "obteve a rendição de Hanói e a preservação definitiva do Vietnã do Sul, garantida por tropas americanas estacionadas em Saigon até os anos 1980.",
      "encerrou a guerra em 1969, cumprindo promessa de campanha.",
      "interrompeu os ataques aéreos assim que as negociações começaram.",
      "garantiu por tratado a permanência de tropas americanas em Saigon.",
    ],
    "A vietnamização reduziu o contingente em terra enquanto a guerra aérea se ampliava. Os negociadores, Henry Kissinger e Le Duc Tho, receberam o Nobel da Paz de 1973; o vietnamita recusou, alegando que não havia paz. Dois anos depois, o Sul caiu.",
    "Saiu do Vietnã bombardeando."),
  vt("vie-36", "dificil", "UFPR", "Os gastos com a Guerra do Vietnã, somados aos programas sociais da \"Grande Sociedade\", tiveram um efeito econômico de alcance mundial:",
    [
      "pressionaram a inflação e o dólar, contribuindo para o fim da conversibilidade em ouro, em 1971.",
      "provocaram a crise de 1929 e a Grande Depressão.",
      "permitiram aos Estados Unidos zerar a dívida pública.",
      "levaram à criação do Fundo Monetário Internacional, encarregado de socorrer o Tesouro norte-americano.",
      "fizeram do dólar, pela primeira vez, a moeda de reserva internacional, no lugar da libra esterlina e do franco.",
    ],
    "Johnson quis \"canhões e manteiga\" sem aumentar impostos. O déficit e a inflação minaram a confiança no dólar, base do sistema de Bretton Woods (1944), e Nixon suspendeu a troca de dólares por ouro. A guerra abalou a hegemonia americana também nas finanças.",
    "Canhões + manteiga = dólar sem ouro."),

  // ───────── Descolonização ─────────
  dc("des-21", "medio", "Fuvest", "Gana, antiga Costa do Ouro, tornou-se independente em 1957 sob a liderança de Kwame Nkrumah. O fato é um marco porque:",
    [
      "foi a primeira independência da África negra no pós-guerra e serviu de referência ao pan-africanismo.",
      "resultou da mais longa guerra colonial travada pelo Reino Unido no continente africano depois da Segunda Guerra.",
      "encerrou o domínio português na África Ocidental.",
      "deu origem ao regime de segregação conhecido como apartheid, adotado pelos colonos brancos após a retirada britânica.",
    ],
    "Nkrumah combinou greves, boicotes e vitórias eleitorais, sem guerra. Defendia que a independência de Gana só faria sentido ligada à libertação de todo o continente, e Acra virou ponto de encontro dos movimentos africanos. Três anos depois viria o \"Ano da África\".",
    "Gana, 1957: a primeira peça."),
  dc("des-22", "medio", "Unicamp", "A crise do Congo (1960–65), logo após a independência da Bélgica, teve como um de seus elementos centrais:",
    [
      "a secessão da província mineradora de Katanga, apoiada por interesses belgas, e o assassinato do primeiro-ministro Patrice Lumumba.",
      "a invasão do país por tropas soviéticas e a instalação de um regime comunista.",
      "a recusa da ONU em enviar qualquer missão ao território.",
      "a anexação do Congo pela vizinha Angola portuguesa.",
      "a volta negociada da administração colonial belga.",
    ],
    "Katanga concentrava cobre e outros minérios. Lumumba, nacionalista que pediu ajuda a Moscou, foi deposto e morto em 1961, com cumplicidade belga e americana. A ONU interveio, e em 1965 o general Mobutu instalou uma longa ditadura pró-ocidental.",
    "Congo: independência política, minério disputado."),
  dc("des-23", "medio", "Unesp", "A guerra da Argélia produziu efeitos profundos na própria França. Entre eles:",
    [
      "a queda da Quarta República e a volta de De Gaulle ao poder, em 1958.",
      "a perda da Alsácia-Lorena para a Alemanha.",
      "a chegada do Partido Comunista ao governo por via eleitoral, em 1956.",
      "a saída da França da recém-criada Comunidade Econômica Europeia, em 1958.",
      "a dissolução imediata de todo o império colonial francês na África e na Ásia.",
    ],
    "Em maio de 1958, militares e colonos sublevaram-se em Argel temendo um acordo com a FLN. De Gaulle foi chamado, fundou a Quinta República, com Executivo forte, e, contrariando quem o levara ao poder, negociou a independência nos Acordos de Évian (1962).",
    "A Argélia derrubou uma república francesa."),
  dc("des-24", "medio", "UERJ", "A Indonésia proclamou sua independência em 1945, mas ela só foi reconhecida em 1949 porque:",
    [
      "a Holanda tentou retomar a colônia pela força e só cedeu sob pressão internacional, inclusive dos Estados Unidos.",
      "o Japão manteve a ocupação do arquipélago até aquele ano.",
      "o Reino Unido reivindicava o território como parte da Malásia e manteve tropas no arquipélago até aquela data, com aval da ONU.",
      "o líder nacionalista Sukarno recusava a separação.",
    ],
    "Sukarno declarou a independência dias depois da rendição japonesa. Os holandeses lançaram duas \"ações policiais\" contra a república; Washington ameaçou cortar a ajuda do Plano Marshall à Holanda. Em 1955 a Indonésia sediaria a Conferência de Bandung.",
    "Nem toda metrópole saiu por vontade própria."),
  dc("des-25", "medio", "UFRGS", "No Quênia dos anos 1950, a revolta dos Mau Mau expressava principalmente:",
    [
      "a reação de camponeses quicuios à perda das melhores terras para os colonos brancos.",
      "um movimento de colonos britânicos pela autonomia em relação a Londres, como o que ocorreria na Rodésia do Sul.",
      "a disputa entre católicos e protestantes pelo controle das missões e das escolas do interior.",
      "a resistência à ocupação italiana do Chifre da África.",
      "o apoio da população local à permanência britânica.",
    ],
    "As \"terras altas\" haviam sido reservadas aos europeus. A repressão britânica foi duríssima, com campos de detenção e milhares de mortos. Derrotada militarmente, a revolta tornou insustentável o domínio colonial: o Quênia ficou independente em 1963, com Jomo Kenyatta.",
    "Onde havia muitos colonos, a saída foi mais violenta."),
  dc("des-26", "medio", "Fuvest", "Criada em 1963, a Organização da Unidade Africana adotou como princípio a intangibilidade das fronteiras herdadas da colonização. A justificativa era:",
    [
      "evitar que a revisão dos limites desencadeasse uma série interminável de guerras entre os novos Estados.",
      "reconhecer que as fronteiras coloniais, apesar de impostas, respeitavam em geral a distribuição dos povos africanos.",
      "atender a uma exigência das antigas metrópoles, que condicionavam a isso o reconhecimento das independências.",
      "preparar a fusão de todos os países num único Estado continental.",
    ],
    "Os líderes sabiam que as fronteiras eram artificiais, mas quase todos os países tinham minorias e vizinhos com reivindicações. Mexer em uma abriria a discussão de todas. O preço foi conservar Estados com fortes tensões internas, como se viu na guerra de Biafra (Nigéria, 1967–70).",
    "Fronteira ruim, mas fixa: o mal menor."),

  dc("des-31", "dificil", "Unicamp", "Considere as afirmativas sobre a independência das colônias portuguesas.\n\nI. Na Guiné-Bissau, o PAIGC, fundado por Amílcar Cabral, proclamou a independência antes da queda da ditadura em Portugal.\nII. Em Angola, três movimentos rivais disputaram o poder, e a guerra civil atraiu tropas cubanas e sul-africanas.\nIII. Moçambique tornou-se independente em 1961, logo no início da luta armada.\n\nEstá correto o que se afirma em:",
    [I_II, SO_I, TODAS, II_III, I_III],
    "O PAIGC declarou a independência em 1973, meses depois do assassinato de Cabral. Em Angola (1975), MPLA, FNLA e UNITA transformaram o país num campo de batalha da Guerra Fria. Moçambique só ficou independente em 1975, com a FRELIMO; 1961 é o início da guerra em Angola.",
    "Colônias portuguesas: guerra desde 1961, independência só em 1973–75."),
  dc("des-32", "dificil", "Fuvest", "Em 1965, Kwame Nkrumah definiu o neocolonialismo como a situação em que um Estado:",
    [
      "possui todos os atributos formais da soberania, mas tem sua economia e sua política dirigidas de fora.",
      "permanece juridicamente como território ultramarino da antiga metrópole, com representação em seu Parlamento.",
      "é ocupado militarmente por uma potência vizinha.",
      "renuncia à independência e pede para ser reincorporado ao império, por não conseguir manter a ordem interna.",
      "adota o socialismo e se alinha à União Soviética, trocando uma tutela europeia por outra, igualmente externa.",
    ],
    "Bandeira, hino e assento na ONU, mas exportando um ou dois produtos primários, com empresas, bancos, moeda e por vezes tropas da ex-metrópole. É o caso de várias ex-colônias francesas, ligadas a Paris por acordos monetários e militares. O conceito ajuda a entender por que independência não significou desenvolvimento.",
    "Independência de direito, dependência de fato."),
  dc("des-33", "dificil", "UERJ", "Em Os Condenados da Terra (1961), o psiquiatra martinicano Frantz Fanon, engajado na luta argelina, defende uma tese oposta à de Gandhi. Para Fanon:",
    [
      "a colonização é em si uma violência, e só a violência do colonizado pode destruí-la e devolver-lhe a dignidade.",
      "a independência deve ser alcançada pela negociação gradual com as elites da metrópole.",
      "a não cooperação pacífica é o único método moralmente aceitável.",
      "os povos colonizados precisam primeiro assimilar a cultura europeia.",
      "a luta anticolonial deve ser dirigida pelo operariado das metrópoles.",
    ],
    "Fanon analisa os efeitos psicológicos do racismo colonial e vê na luta armada um processo de libertação também interior. O livro influenciou movimentos na África, na América Latina e o radicalismo negro nos Estados Unidos. Comparar Fanon e Gandhi é comparar as duas grandes vias da descolonização.",
    "Gandhi: desobedecer. Fanon: enfrentar."),
  dc("des-34", "dificil", "Unesp", "Sobre a Conferência de Bandung (1955) e a de Belgrado (1961), é correto afirmar que:",
    [
      "a primeira reuniu Estados asiáticos e africanos, com a China presente; a segunda fundou o Movimento dos Não Alinhados, com a Iugoslávia de Tito.",
      "ambas foram convocadas pela União Soviética para organizar seus aliados no Terceiro Mundo.",
      "Bandung criou uma aliança militar afro-asiática, dissolvida em Belgrado.",
      "a primeira foi promovida pelos Estados Unidos, e a segunda, pelas antigas metrópoles.",
      "nas duas, os países participantes aderiram a um dos blocos da Guerra Fria.",
    ],
    "Bandung foi afro-asiática: 29 países, incluindo a China de Zhou Enlai, sem as superpotências. Belgrado ampliou o critério para o não alinhamento, o que permitiu a presença de um país europeu. Os nomes a lembrar são Nehru, Nasser, Sukarno e Tito.",
    "Bandung = quem (afro-asiáticos). Belgrado = como (não alinhados)."),
  dc("des-35", "dificil", "Fuvest", "No apartheid, a política dos bantustões (ou \"lares nacionais\") tinha como objetivo:",
    [
      "retirar dos negros a cidadania sul-africana, atribuindo-os a territórios pobres e nominalmente autônomos.",
      "integrar gradualmente a população negra às cidades, com plenos direitos civis, mas sem direito de voto nacional.",
      "devolver às comunidades africanas as terras mais férteis do país.",
      "preparar a divisão da África do Sul em dois Estados de mesma extensão, um para os brancos e outro para os negros.",
      "garantir aos negros representação proporcional no Parlamento.",
    ],
    "Cerca de 13% do território, o menos produtivo, foi reservado à maioria da população. Os negros se tornavam \"estrangeiros\" na África do Sul branca, onde só entravam como mão de obra, portando passes. O massacre de Sharpeville (1960) ocorreu num protesto contra esses passes e levou o CNA, posto na ilegalidade, à luta armada.",
    "Bantustão: independência de fachada para negar cidadania."),
  dc("des-36", "dificil", "UFPR", "A partilha da Índia britânica em 1947 deixou questões em aberto que marcaram as décadas seguintes. Uma delas foi:",
    [
      "a disputa pela Caxemira e a posterior separação do Paquistão Oriental, que se tornou Bangladesh em 1971.",
      "a reunificação pacífica de Índia e Paquistão nos anos 1960.",
      "a ocupação do Ceilão por tropas soviéticas.",
      "a permanência de Goa como colônia francesa até o fim do século, apesar dos protestos de Nova Délhi nas Nações Unidas.",
      "a adoção do islamismo como religião oficial da Índia.",
    ],
    "O Paquistão nasceu em duas partes separadas por mais de 1.500 km de território indiano. Caxemira, de maioria muçulmana e governante hindu, provocou a primeira guerra entre os dois países já em 1947. Goa era portuguesa e foi tomada pela Índia em 1961.",
    "Um Paquistão em dois pedaços não durou."),

  // ───────── Maio de 1968 ─────────
  m("m68-21", "medio", "Fuvest", "O Movimento 22 de Março, origem dos protestos de 1968 na França, surgiu:",
    [
      "na Universidade de Nanterre, tendo Daniel Cohn-Bendit entre seus porta-vozes.",
      "nas fábricas da Renault, a partir de uma greve por salários e redução da jornada.",
      "na direção do Partido Comunista Francês.",
      "entre oficiais descontentes com a perda da Argélia.",
      "na Sorbonne, por iniciativa de professores catedráticos contrários à reforma do ensino.",
    ],
    "Nanterre era um campus novo, na periferia de Paris, superlotado e com regras rígidas (como a proibição de rapazes nos alojamentos femininos). A ocupação da torre administrativa, em 22 de março, deu nome ao grupo. O fechamento da faculdade, em maio, transferiu o conflito para a Sorbonne.",
    "Começou em Nanterre, explodiu na Sorbonne."),
  m("m68-22", "medio", "Unicamp", "Durante a crise de maio, o Partido Comunista Francês e a central sindical CGT adotaram em relação aos estudantes uma postura de:",
    [
      "desconfiança: trataram-nos como aventureiros e procuraram manter a greve no terreno das reivindicações salariais.",
      "liderança: organizaram as barricadas e propuseram a tomada do poder.",
      "indiferença: não participaram das greves nem das negociações.",
      "aliança com De Gaulle, entrando no governo em plena crise.",
    ],
    "Para o PCF, a revolução era assunto da classe operária organizada, não de jovens \"esquerdistas\" de classe média. A CGT fechou os portões das fábricas ocupadas aos estudantes e negociou aumentos. Essa distância entre a velha esquerda e a nova é uma das chaves de 1968.",
    "A velha esquerda não gostou da nova."),
  m("m68-23", "medio", "Unesp", "Os Acordos de Grenelle (27 de maio de 1968), negociados entre governo, patrões e sindicatos:",
    [
      "previam forte aumento do salário mínimo, mas foram rejeitados em assembleias de fábrica, e a greve prosseguiu.",
      "encerraram a greve no mesmo dia, com a volta geral ao trabalho.",
      "entregaram aos trabalhadores a gestão das empresas estatais e de parte das grandes fábricas privadas ocupadas durante a greve.",
      "extinguiram o direito de greve no setor público.",
      "determinaram a renúncia do presidente e novas eleições.",
    ],
    "O mínimo subiria 35% e os demais salários, cerca de 10%. Quando o líder da CGT apresentou o resultado aos operários da Renault, em Billancourt, foi vaiado: muitos queriam mais do que salário. Só em junho, depois da reviravolta política, o trabalho foi retomado.",
    "Grenelle: o sindicato assinou, a base vaiou."),
  m("m68-24", "medio", "UERJ", "A crise francesa virou a favor do governo em 30 de maio de 1968, quando De Gaulle:",
    [
      "anunciou pelo rádio a dissolução da Assembleia e novas eleições, seguido de uma enorme passeata de apoio.",
      "renunciou e entregou o poder ao primeiro-ministro.",
      "decretou o estado de sítio e ordenou que o Exército ocupasse Paris, as universidades e as principais fábricas em greve.",
      "aceitou formar um governo de coalizão com os líderes estudantis e sindicais, sob a chefia de Mendès France.",
    ],
    "Na véspera, o presidente sumira: fora à Alemanha consultar o comandante das tropas francesas. De volta, falou quatro minutos ao rádio. Horas depois, centenas de milhares de pessoas desfilaram pelos Champs-Élysées: era a França que temia a desordem. O Exército não foi usado.",
    "Quatro minutos de rádio viraram o jogo."),
  m("m68-25", "medio", "UFRGS", "Entre as referências intelectuais dos estudantes de 1968 estava Herbert Marcuse, para quem a sociedade industrial avançada:",
    [
      "integra e neutraliza a contestação por meio do consumo, tornando o operariado tradicional pouco revolucionário.",
      "caminha inevitavelmente para a revolução, desde que dirigida por um partido operário disciplinado, nos moldes do leninismo.",
      "realizou o ideal de liberdade defendido pelo liberalismo, ao dar a cada indivíduo o poder de escolher o que consome.",
      "deve ser preservada contra as novas gerações.",
      "só pode ser reformada pela via parlamentar, por partidos de massa capazes de representar a maioria dos assalariados.",
    ],
    "Em O Homem Unidimensional (1964), Marcuse sustenta que o capitalismo de abundância cria necessidades artificiais e absorve a oposição. A esperança de ruptura viria dos que estão à margem: estudantes, minorias, povos do Terceiro Mundo. Daí a crítica simultânea ao consumismo ocidental e à burocracia soviética.",
    "Marcuse: o consumo adormece a revolta."),
  m("m68-26", "medio", "Fuvest", "No México, dez dias antes da abertura dos Jogos Olímpicos de 1968, o movimento estudantil terminou:",
    [
      "com o massacre de manifestantes pelo Exército na praça de Tlatelolco.",
      "com a queda do governo e a convocação de eleições livres para o ano seguinte.",
      "com um acordo que atendeu a parte das reivindicações e adiou os Jogos por um ano.",
      "com a adesão dos atletas mexicanos a um boicote.",
    ],
    "Os estudantes pediam liberdades democráticas num país governado por um só partido havia décadas. Em 2 de outubro, tropas abriram fogo; o número de mortos, na casa das centenas, nunca foi esclarecido. Nos mesmos Jogos, dois velocistas negros norte-americanos ergueram o punho no pódio.",
    "1968 não foi só Paris."),

  m("m68-31", "dificil", "Unicamp", "Considere as afirmativas sobre o desfecho político do Maio francês.\n\nI. As eleições de junho de 1968 deram ao partido gaullista a maioria absoluta na Assembleia.\nII. A esquerda parlamentar saiu fortalecida e formou o governo seguinte.\nIII. De Gaulle deixou a presidência em 1969, ao ser derrotado num referendo.\n\nEstá correto o que se afirma em:",
    [I_III, SO_I, TODAS, I_II, II_III],
    "O voto do medo deu aos gaullistas uma vitória esmagadora, e socialistas e comunistas perderam cadeiras. Menos de um ano depois, De Gaulle submeteu a referendo a reforma do Senado e a regionalização, perdeu e renunciou. A esquerda só chegaria à presidência em 1981, com Mitterrand.",
    "Venceu em junho de 68, caiu em abril de 69."),
  m("m68-32", "dificil", "Fuvest", "No Brasil de 1968, a ordem cronológica correta dos acontecimentos é:",
    [
      "morte de Edson Luís – Passeata dos Cem Mil – congresso de Ibiúna – AI-5.",
      "Passeata dos Cem Mil – morte de Edson Luís – AI-5 – congresso de Ibiúna.",
      "AI-5 – morte de Edson Luís – Passeata dos Cem Mil – congresso de Ibiúna.",
      "congresso de Ibiúna – morte de Edson Luís – AI-5 – Passeata dos Cem Mil.",
      "morte de Edson Luís – AI-5 – Passeata dos Cem Mil – congresso de Ibiúna.",
    ],
    "O estudante foi morto pela polícia em 28 de março, no restaurante Calabouço. A passeata é de 26 de junho. Em outubro, cerca de setecentos estudantes foram presos em Ibiúna (SP). Em 13 de dezembro, depois de a Câmara negar licença para processar o deputado Márcio Moreira Alves, veio o AI-5.",
    "Março, junho, outubro, dezembro."),
  m("m68-33", "dificil", "UERJ", "A invasão da Tchecoslováquia, em agosto de 1968, teve um efeito duradouro sobre a esquerda da Europa Ocidental:",
    [
      "afastou de Moscou partidos comunistas como o italiano, que mais tarde defenderiam um caminho democrático próprio, o eurocomunismo.",
      "reforçou a obediência dos partidos comunistas ocidentais à União Soviética.",
      "levou a social-democracia a abandonar a OTAN.",
      "provocou a dissolução do Partido Comunista Francês.",
      "uniu a nova esquerda estudantil em defesa da intervenção.",
    ],
    "Dubcek não queria sair do bloco, e sim democratizar o socialismo; a resposta com tanques desmoralizou o modelo soviético. Vários partidos ocidentais condenaram a invasão, e, nos anos 1970, italianos, espanhóis e, por algum tempo, franceses afirmaram independência de Moscou e adesão ao pluralismo.",
    "Praga afastou de Moscou a esquerda ocidental."),
  m("m68-34", "dificil", "Unesp", "Autores críticos do legado de 1968 sustentam que o movimento, derrotado como projeto coletivo, acabou por:",
    [
      "favorecer um individualismo que o capitalismo de consumo soube absorver.",
      "restaurar as hierarquias tradicionais na família e na escola.",
      "fortalecer os partidos de massa e os sindicatos centralizados, em prejuízo dos novos movimentos.",
      "interromper as mudanças de costumes que vinham ocorrendo desde o pós-guerra.",
    ],
    "A leitura é a de um paradoxo: slogans contra a sociedade de consumo teriam aberto caminho a uma cultura de realização pessoal, publicidade \"rebelde\" e relações de trabalho flexíveis. Outra corrente destaca o saldo emancipador (direitos das mulheres, das minorias, ecologia). As duas concordam que a herança é cultural.",
    "\"É proibido proibir\" também serve para vender."),
  m("m68-35", "dificil", "Fuvest", "Nos Estados Unidos, o ano de 1968 teve os assassinatos de Martin Luther King e de Robert Kennedy e os confrontos na convenção democrata de Chicago. O resultado eleitoral daquele ano foi:",
    [
      "a vitória do republicano Richard Nixon, com um discurso de \"lei e ordem\".",
      "a reeleição de Lyndon Johnson, com a promessa de negociar a paz imediata com Hanói.",
      "a eleição de um candidato pacifista, que retirou as tropas do Vietnã já em 1969.",
      "a vitória do segregacionista George Wallace na maioria dos estados do país.",
      "a chegada de Robert Kennedy à presidência.",
    ],
    "Como na França, a contestação produziu uma reação conservadora nas urnas. Nixon falava a uma \"maioria silenciosa\", cansada de protestos e de distúrbios urbanos. Johnson desistira de concorrer, Robert Kennedy fora morto em junho e Wallace venceu apenas em estados do Sul profundo.",
    "Paris e Washington: revolta na rua, direita na urna."),
  m("m68-36", "dificil", "UFPR", "Um resultado institucional direto do Maio francês foi a lei de orientação do ensino superior, de novembro de 1968, que:",
    [
      "deu autonomia às universidades e admitiu estudantes e funcionários em seus conselhos.",
      "privatizou as universidades e instituiu mensalidades.",
      "fechou as faculdades de ciências humanas, vistas como focos permanentes de agitação política.",
      "restabeleceu a cátedra vitalícia e o currículo único nacional, abolidos durante as ocupações.",
      "transferiu o ensino superior à Igreja Católica.",
    ],
    "A reforma, conduzida pelo ministro Edgar Faure, desmontou as velhas faculdades, criou universidades pluridisciplinares e introduziu a participação. O governo também criou o centro experimental de Vincennes, aberto a quem não tinha o diploma do secundário.",
    "A universidade foi onde 68 mais mudou a lei."),

  // ───────── Quem foi quem ─────────
  p("fig-21", "medio", "Fuvest", "Antes de liderar a luta no Vietnã, Ho Chi Minh viveu na França, onde, sob o nome de Nguyen Ai Quoc:",
    [
      "pediu direitos para os vietnamitas à Conferência de Paz de 1919 e, ignorado, ajudou a fundar o Partido Comunista Francês.",
      "serviu como oficial do exército colonial na Primeira Guerra.",
      "foi eleito deputado pela Indochina na Assembleia Nacional.",
      "dirigiu a administração colonial em Saigon.",
    ],
    "A petição, inspirada no princípio da autodeterminação defendido pelo presidente Wilson, não teve resposta. Ho concluiu que só os comunistas levavam a sério a questão colonial. É a mesma trajetória de 1945: primeiro ele apela aos valores do Ocidente; rejeitado, volta-se para Moscou.",
    "Ho bateu duas vezes à porta do Ocidente: 1919 e 1945."),
  p("fig-22", "medio", "Unicamp", "Na política interna, Nikita Kruschev ficou associado:",
    [
      "à campanha das Terras Virgens e à aposta no cultivo do milho, de resultados decepcionantes.",
      "à coletivização forçada da agricultura, aos planos quinquenais e aos grandes expurgos no partido e no Exército.",
      "à perestroika e à glasnost.",
      "à Nova Política Econômica, que readmitiu o pequeno comércio e a propriedade camponesa da terra.",
      "à invasão do Afeganistão.",
    ],
    "Kruschev tentou resolver a escassez de alimentos abrindo vastas áreas no Cazaquistão e na Sibéria; depois de boas colheitas iniciais, a produção despencou. Coletivização e expurgos são de Stalin, a NEP é de Lenin, e perestroika e glasnost, de Gorbachev.",
    "Lenin: NEP · Stalin: coletivização · Kruschev: Terras Virgens · Gorbachev: perestroika."),
  p("fig-23", "medio", "Unesp", "Salvador Allende venceu a eleição de 1970 com pouco mais de um terço dos votos. Sua posse dependeu:",
    [
      "da ratificação pelo Congresso, obtida depois que ele assinou um estatuto de garantias democráticas.",
      "de um segundo turno, que venceu com folga.",
      "de um golpe de militares nacionalistas.",
      "da renúncia do candidato democrata-cristão em seu favor, negociada pelo presidente que deixava o cargo.",
    ],
    "Sem maioria absoluta, a Constituição chilena mandava o Congresso escolher entre os dois primeiros. A Democracia Cristã votou em Allende em troca de garantias. Ele governou sempre em minoria parlamentar, embora a nacionalização do cobre tenha sido aprovada por unanimidade. No Chile, o segundo turno só surgiu depois.",
    "Allende: eleito com um terço, governou sem maioria."),
  p("fig-24", "medio", "UERJ", "O fim da ditadura de Augusto Pinochet teve início quando:",
    [
      "o \"não\" venceu o plebiscito de 1988 sobre a sua permanência no poder.",
      "uma insurreição armada tomou a capital em 1986 e forçou o regime a negociar.",
      "o general morreu no exercício do cargo.",
      "tropas argentinas invadiram o sul do país, na disputa pelo canal de Beagle.",
      "a Suprema Corte o destituiu por corrupção e violações de direitos humanos.",
    ],
    "A consulta estava prevista na Constituição que o próprio regime outorgara em 1980. Derrotado, Pinochet passou a presidência em 1990, mas seguiu comandante do Exército até 1998 e depois senador vitalício. Naquele ano foi detido em Londres, a pedido de um juiz espanhol.",
    "Caiu pelo voto, mas saiu protegido."),
  p("fig-25", "medio", "UFRGS", "As ideias de Gandhi sobre a resistência não violenta tomaram forma inicialmente:",
    [
      "na África do Sul, onde viveu por duas décadas e organizou a comunidade indiana contra leis discriminatórias.",
      "na Inglaterra, como deputado trabalhista.",
      "na China, em contato com o movimento camponês.",
      "nos Estados Unidos, onde estudou direito em Chicago e conviveu com os primeiros líderes do movimento negro.",
    ],
    "Advogado formado em Londres, Gandhi chegou à África do Sul em 1893 e lá criou o método da satyagraha (\"força da verdade\"). Voltou à Índia em 1915. Na luta indiana somou a ela o boicote aos tecidos ingleses e a roca de fiar, símbolo da autossuficiência.",
    "Gandhi aprendeu na África do Sul o que aplicou na Índia."),
  p("fig-26", "medio", "Fuvest", "Como presidente (1994–1999), Nelson Mandela apoiou a Comissão da Verdade e Reconciliação, presidida pelo arcebispo Desmond Tutu. Seu princípio era:",
    [
      "oferecer anistia a quem confessasse publicamente e por inteiro os crimes políticos cometidos.",
      "julgar em tribunais especiais e punir com a pena máxima os dirigentes do regime anterior e seus agentes.",
      "proibir qualquer investigação sobre o período do apartheid.",
      "indenizar a minoria branca pelas terras e empresas perdidas com o fim do regime de segregação racial.",
      "expulsar do país os antigos funcionários do Estado.",
    ],
    "A comissão ouviu vítimas e agentes da repressão, e também militantes do CNA, em audiências públicas. A aposta era que a verdade, e não a vingança ou o esquecimento, permitiria a convivência. O modelo inspirou outros países saídos de ditaduras.",
    "Verdade em troca de anistia."),

  p("fig-31", "dificil", "Unicamp", "Considere as afirmativas sobre a China de Mao Tsé-Tung.\n\nI. A Campanha das Cem Flores (1956–57) convidou os intelectuais à crítica e foi seguida de uma onda de repressão.\nII. O Grande Salto para Frente (1958) baseou-se nas comunas populares e resultou numa fome de enormes proporções.\nIII. A Revolução Cultural (1966) foi lançada por Deng Xiaoping contra a liderança de Mao.\n\nEstá correto o que se afirma em:",
    [I_II, TODAS, SO_II, I_III, II_III],
    "\"Que cem flores desabrochem\" deu lugar à campanha antidireitista. O Grande Salto quis industrializar o país à força de mobilização, com fornos de quintal e comunas, e matou de fome dezenas de milhões. A Revolução Cultural foi obra de Mao; Deng foi uma de suas vítimas e só voltou depois.",
    "Cem Flores → Grande Salto → Revolução Cultural."),
  p("fig-32", "dificil", "Fuvest", "No movimento liderado por Martin Luther King, a campanha de Birmingham (1963) e as marchas de Selma (1965) estão ligadas, respectivamente:",
    [
      "à Lei dos Direitos Civis (1964), contra a segregação em locais públicos, e à Lei do Direito de Voto (1965).",
      "à abolição da escravidão e ao fim da Guerra do Vietnã.",
      "à decisão da Suprema Corte contra a segregação nas escolas e ao boicote que acabou com a segregação nos ônibus.",
      "à fundação dos Panteras Negras e à criação da Nação do Islã.",
      "à Lei do Direito de Voto (1964) e, só depois, à Lei dos Direitos Civis (1965), contra a segregação em locais públicos.",
    ],
    "Em Birmingham, as imagens de cães e jatos d'água contra crianças chocaram o país e empurraram Kennedy a propor a lei de 1964. Em Selma, a violência contra quem marchava pelo registro eleitoral levou Johnson à lei de 1965. A decisão sobre as escolas é de 1954, e o boicote, de 1955–56.",
    "Birmingham → 1964 (lugares). Selma → 1965 (voto)."),
  p("fig-33", "dificil", "UERJ", "A imagem de Rosa Parks como uma costureira que apenas estava cansada é contestada pelos historiadores porque ela:",
    [
      "era militante experiente, secretária da seção local da NAACP, e seu caso foi escolhido para contestar a lei.",
      "agiu por ordem direta de Martin Luther King, que já dirigia o movimento na cidade.",
      "pertencia à Nação do Islã e defendia a separação entre negros e brancos.",
      "nunca chegou a ser presa, e a história foi criada depois pela imprensa.",
      "era advogada e apresentou pessoalmente o recurso à Suprema Corte.",
    ],
    "Meses antes, uma adolescente, Claudette Colvin, fora presa pelo mesmo motivo. As lideranças preferiram organizar o boicote em torno de Parks, mulher respeitada e com formação política. King, recém-chegado à cidade, foi escolhido porta-voz depois da prisão dela. Movimentos preparam seus gestos \"espontâneos\".",
    "Não foi cansaço: foi militância."),
  p("fig-34", "dificil", "Unesp", "Fundado em 1966, um ano após o assassinato de Malcolm X, o Partido dos Panteras Negras retomou de suas ideias sobretudo:",
    [
      "o direito à autodefesa armada e a afirmação do orgulho negro, somados a programas comunitários nos guetos.",
      "a estratégia de desobediência civil não violenta e de integração.",
      "o projeto de retorno coletivo dos negros norte-americanos à África.",
      "a recusa a qualquer ação política, em favor da vida religiosa.",
    ],
    "Criados em Oakland por Huey Newton e Bobby Seale, os Panteras patrulhavam a ação da polícia, mantinham cafés da manhã para crianças e clínicas gratuitas. Fazem parte do Black Power, que marca o deslocamento do movimento negro do Sul rural para os guetos do Norte e do Oeste.",
    "De King a Malcolm, de Malcolm aos Panteras."),
  p("fig-35", "dificil", "Fuvest", "Um dado frequentemente lembrado sobre o golpe de 11 de setembro de 1973 no Chile é que Augusto Pinochet:",
    [
      "fora nomeado comandante do Exército por Allende semanas antes, por ser tido como oficial legalista.",
      "liderava no Senado a oposição ao governo desde 1970 e fora o autor do pedido de destituição do presidente.",
      "comandara em junho uma tentativa fracassada de golpe, o \"tanquetazo\", e fora anistiado logo em seguida pelo presidente.",
      "estava exilado e voltou ao país com apoio da Argentina.",
      "era ministro da Economia de Allende e já defendia em segredo o plano neoliberal aplicado depois do golpe.",
    ],
    "O general Carlos Prats, constitucionalista, sufocou o tanquetazo de junho e renunciou em agosto, sob pressão de seus pares, indicando Pinochet como sucessor. Menos de três semanas depois, o Palácio de La Moneda era bombardeado, e Allende morreu lá dentro. O plano econômico foi obra dos \"Chicago Boys\", civis.",
    "Allende nomeou quem o derrubaria."),
  p("fig-36", "dificil", "UFPR", "Em agosto de 1942, em plena Segunda Guerra, Gandhi lançou o movimento \"Deixem a Índia\" (Quit India). A decisão significava:",
    [
      "recusar a colaboração no esforço de guerra enquanto os britânicos não concedessem a independência imediata.",
      "aliar-se ao Japão, que avançava pela Birmânia, para expulsar os britânicos pelas armas com um exército indiano próprio.",
      "aceitar a oferta de autonomia limitada ao fim do conflito.",
      "apoiar a criação do Paquistão proposta pela Liga Muçulmana.",
      "suspender a luta até a derrota do nazismo.",
    ],
    "Londres envolvera a Índia na guerra sem consultar os indianos. Gandhi e toda a direção do Congresso foram presos, e a repressão foi dura. A aliança com o Japão foi a opção de outro líder, Subhas Chandra Bose. A Liga Muçulmana, que não aderiu, saiu fortalecida, o que pesou na partilha de 1947.",
    "\"Façam ou morram\": independência já, não depois da guerra."),
];
