import type { Cadeia, Intruso } from "@/lib/tipos";

const intruso = (tema: string, grupo: string, itens: string[], fora: string, explicacao: string): Intruso => ({
  tema,
  grupo,
  itens,
  intruso: fora,
  explicacao,
});

/** Jogo O intruso: três itens pertencem ao grupo e um não. */
export const intrusos: Intruso[] = [
  intruso("dutra", "medidas do governo Dutra", ["Cassação do registro do PCB", "Rompimento com a União Soviética", "Plano SALTE"], "Criação da Petrobras",
    "A Petrobras é de 1953, no segundo governo Vargas. Dutra chegou a propor o contrário: abrir o petróleo ao capital estrangeiro."),
  intruso("dutra", "regras da Constituição de 1946", ["Voto direto e secreto", "Mandato presidencial de cinco anos", "Pluripartidarismo"], "Voto dos analfabetos",
    "Os analfabetos ficaram fora das urnas em 1946 e só passaram a votar em 1985. Era uma democracia com eleitorado restrito."),
  intruso("dutra", "sinais do alinhamento de Dutra aos Estados Unidos", ["Assinatura do TIAR", "Criação da Escola Superior de Guerra", "Visita de Truman ao Brasil"], "Política externa independente",
    "A política externa independente é de Jânio e Jango (1961–1964) e buscava justamente reduzir o alinhamento automático a Washington."),
  intruso("vargas", "iniciativas do segundo governo Vargas", ["Criação da Petrobras", "Criação do BNDE", "Projeto da Eletrobrás"], "Criação da Sudene",
    "A Sudene foi criada por JK em 1959. A Eletrobrás foi proposta por Vargas em 1954, embora só tenha sido aprovada em 1961."),
  intruso("vargas", "adversários de Vargas em 1954", ["Carlos Lacerda", "A UDN", "Os coronéis do manifesto de fevereiro"], "Samuel Wainer",
    "Wainer era o dono da Última Hora, o único grande jornal que defendia o governo. Por isso mesmo foi alvo de uma CPI movida pela oposição."),
  intruso("vargas", "episódios da crise de agosto de 1954", ["Atentado da Rua Tonelero", "República do Galeão", "Carta-Testamento"], "Campanha da Legalidade",
    "A Campanha da Legalidade é de 1961, na crise da renúncia de Jânio. Os outros três são a sequência que termina no suicídio de Vargas."),
  intruso("jk", "marcas do governo JK", ["Plano de Metas", "Construção de Brasília", "Indústria automobilística"], "Reformas de Base",
    "As Reformas de Base são a bandeira do governo João Goulart. JK evitou mexer na estrutura agrária para manter o apoio do PSD."),
  intruso("jk", "problemas deixados pelo governo JK", ["Inflação em alta", "Dívida externa maior", "Concentração de renda"], "Estagnação da indústria",
    "A indústria cresceu como nunca, sobretudo a de bens duráveis. O problema foi o custo desse crescimento, e não a falta dele."),
  intruso("jk", "iniciativas do governo JK", ["Criação da Sudene", "Operação Pan-Americana", "Rompimento com o FMI"], "Instrução 204 da SUMOC",
    "A Instrução 204 é de Jânio Quadros (1961): desvalorizou a moeda e cortou subsídios, na linha que o FMI pedia e que JK havia recusado."),
  intruso("janio", "lembranças do governo Jânio Quadros", ["A vassoura como símbolo", "Condecoração de Che Guevara", "Proibição do biquíni"], "Comício da Central do Brasil",
    "O Comício da Central é de março de 1964, no governo Jango. Jânio ficou só sete meses no cargo, em 1961."),
  intruso("janio", "forças da Campanha da Legalidade", ["Leonel Brizola", "Uma cadeia de rádios", "O III Exército"], "Carlos Lacerda",
    "Lacerda, governador da Guanabara, apoiou o veto dos ministros militares à posse de Jango e censurou a imprensa em seu estado."),
  intruso("janio", "primeiros-ministros do parlamentarismo (1961–1963)", ["Tancredo Neves", "Brochado da Rocha", "Hermes Lima"], "Ranieri Mazzilli",
    "Mazzilli presidia a Câmara e ocupou a Presidência interinamente em 1961 e de novo em 1964. Nunca foi primeiro-ministro."),
  intruso("jango", "Reformas de Base", ["Reforma agrária", "Reforma urbana", "Reforma bancária"], "Privatização das estatais",
    "As reformas iam no sentido oposto: mais intervenção do Estado, com medidas como a encampação das refinarias particulares."),
  intruso("jango", "apoiadores civis do golpe de 1964", ["Magalhães Pinto", "Carlos Lacerda", "Adhemar de Barros"], "Leonel Brizola",
    "Brizola era cunhado e aliado de Jango, à esquerda dele, e tentou organizar a resistência no Sul. Os outros três eram governadores de Minas, Guanabara e São Paulo."),
  intruso("jango", "acontecimentos de março de 1964", ["Comício da Central do Brasil", "Marcha da Família com Deus pela Liberdade", "Revolta dos marinheiros"], "Plebiscito sobre o presidencialismo",
    "O plebiscito foi em janeiro de 1963 e devolveu a Jango os poderes de presidente. Os outros três são os passos finais antes do golpe."),
  intruso("guerra-fria", "iniciativas dos Estados Unidos", ["Doutrina Truman", "Plano Marshall", "OTAN"], "Comecon",
    "O Comecon foi a resposta soviética ao Plano Marshall: um conselho de ajuda econômica entre os países socialistas, criado em 1949."),
  intruso("guerra-fria", "fatos do período em que Kruschev governou", ["Denúncia dos crimes de Stalin", "Construção do Muro de Berlim", "Crise dos Mísseis"], "Bloqueio de Berlim",
    "O bloqueio de Berlim (1948–49) foi decisão de Stalin. Kruschev só chegou ao comando depois da morte dele, em 1953."),
  intruso("guerra-fria", "guerras por procuração da Guerra Fria", ["Guerra da Coreia", "Guerra do Vietnã", "Guerra do Afeganistão"], "Guerra das Malvinas",
    "A guerra das Malvinas (1982) opôs Argentina e Reino Unido por um território, sem disputa entre os blocos capitalista e socialista."),
  intruso("vietna", "razões da derrota dos Estados Unidos", ["Guerrilha adaptada à selva", "Opinião pública contra a guerra", "Governo impopular em Saigon"], "Falta de armamento moderno",
    "Os Estados Unidos tinham superioridade tecnológica absoluta. A derrota foi política e estratégica, não por falta de armas."),
  intruso("vietna", "acontecimentos de 1968", ["Ofensiva do Tet", "Massacre de My Lai", "Johnson desiste da reeleição"], "Queda de Saigon",
    "Saigon caiu em 30 de abril de 1975, dois anos depois da saída das tropas norte-americanas."),
  intruso("vietna", "nomes ligados ao Vietnã do Norte", ["Ho Chi Minh", "Viet Minh", "Hanói"], "Ngo Dinh Diem",
    "Diem governou o Vietnã do Sul, com apoio dos Estados Unidos, até ser deposto e morto por seus generais em 1963."),
  intruso("descolonizacao", "fatores externos da descolonização", ["Enfraquecimento das metrópoles europeias", "Pressão dos Estados Unidos e da União Soviética", "Carta da ONU e a autodeterminação"], "Movimentos nacionalistas locais",
    "Os movimentos nacionalistas são o principal fator interno. Na prova discursiva, separar os fatores externos dos internos vale ponto."),
  intruso("descolonizacao", "independências conquistadas pela guerra", ["Argélia", "Angola", "Vietnã"], "Gana",
    "Gana (1957) obteve a independência por negociação e pressão política, com Kwame Nkrumah, sem guerra contra os britânicos."),
  intruso("descolonizacao", "ideias da Conferência de Bandung (1955)", ["Não alinhamento", "União dos países afro-asiáticos", "Condenação do colonialismo"], "Criação da OTAN",
    "A OTAN é a aliança militar do bloco capitalista (1949). Bandung reuniu justamente quem não queria se alinhar a nenhum dos blocos."),
  intruso("maio68", "alvos dos estudantes franceses em 1968", ["Universidade autoritária", "Sociedade de consumo", "Governo De Gaulle"], "Guerra da Argélia",
    "A guerra da Argélia havia terminado em 1962. A guerra que mobilizava os estudantes em 1968 era a do Vietnã."),
  intruso("maio68", "acontecimentos de 1968 pelo mundo", ["Primavera de Praga", "Massacre de Tlatelolco", "Passeata dos Cem Mil"], "Queda do Muro de Berlim",
    "O muro caiu em 1989. Em 1968, Praga, Cidade do México e Rio de Janeiro viveram protestos reprimidos por regimes muito diferentes."),
  intruso("maio68", "consequências do Maio de 1968", ["Reforma universitária", "Fortalecimento do feminismo", "Aumentos salariais"], "Tomada do poder pelos estudantes",
    "Politicamente o movimento perdeu: De Gaulle venceu as eleições de junho. A mudança duradoura foi nos costumes."),
  intruso("figuras", "defensores da não violência", ["Mahatma Gandhi", "Martin Luther King", "Rosa Parks"], "Malcolm X",
    "Malcolm X criticava a não violência e defendia a autodefesa \"por todos os meios necessários\"."),
  intruso("figuras", "história do Chile", ["Salvador Allende", "Augusto Pinochet", "Nacionalização do cobre"], "Revolução Cultural",
    "A Revolução Cultural aconteceu na China de Mao, a partir de 1966."),
  intruso("figuras", "trajetória de Mao Tsé-Tung", ["Longa Marcha", "Livro Vermelho", "Grande Salto Adiante"], "Marcha do Sal",
    "A Marcha do Sal (1930) foi liderada por Gandhi, contra o imposto britânico sobre o sal na Índia."),
  intruso("figuras", "luta contra o apartheid", ["Nelson Mandela", "Congresso Nacional Africano", "Massacre de Sharpeville"], "Boicote de Montgomery",
    "O boicote aos ônibus de Montgomery (1955–56) é da luta pelos direitos civis nos Estados Unidos, iniciada com Rosa Parks."),
  intruso("figuras", "líderes ligados ao Vietnã, à China e à União Soviética socialistas", ["Ho Chi Minh", "Mao Tsé-Tung", "Nikita Kruschev"], "Augusto Pinochet",
    "Pinochet era um ditador anticomunista: derrubou o socialista Allende com apoio dos Estados Unidos."),
];

const cadeia = (tema: string, titulo: string, passos: string[], explicacao: string): Cadeia => ({ tema, titulo, passos, explicacao });

/** Jogo Causa e consequência: os passos estão na ordem certa, cada um levando ao seguinte. */
export const cadeias: Cadeia[] = [
  cadeia("dutra", "Das urnas à cassação do PCB",
    ["Fim do Estado Novo e legalização dos partidos", "PCB obtém cerca de 10% dos votos em 1945", "Guerra Fria começa e Dutra se alinha aos Estados Unidos", "TSE cassa o registro do PCB", "Congresso cassa os mandatos dos comunistas"],
    "O partido não foi cassado por ser fraco, e sim por ter voto: a força eleitoral de 1945 virou ameaça quando o mundo se dividiu em dois blocos."),
  cadeia("dutra", "Como Dutra industrializou sem querer",
    ["Brasil acumula reservas durante a Segunda Guerra", "Governo Dutra libera as importações", "Enxurrada de importados esgota os dólares", "Governo passa a exigir licença para importar", "Indústria nacional, protegida, ganha impulso"],
    "O controle de importações nasceu de uma crise cambial, não de um plano. Como priorizava máquinas e barrava supérfluos, acabou favorecendo a indústria."),
  cadeia("vargas", "O caminho até a Petrobras",
    ["Dutra propõe abrir o petróleo ao capital estrangeiro", "Campanha \"O petróleo é nosso\" toma as ruas", "Vargas envia projeto de empresa mista, sem monopólio", "Congresso inclui o monopólio estatal no projeto", "Lei cria a Petrobras em 1953"],
    "O projeto original de Vargas era mais moderado do que a lei aprovada. O monopólio foi resultado da pressão das ruas e do próprio Congresso."),
  cadeia("vargas", "Agosto de 1954",
    ["Lacerda intensifica a campanha contra Vargas", "Atentado da Rua Tonelero mata o major Vaz", "Inquérito da Aeronáutica chega à guarda do presidente", "Generais exigem a renúncia", "Vargas se suicida e a multidão se volta contra a oposição"],
    "O suicídio inverteu o jogo: a comoção popular paralisou os adversários e adiou por dez anos o desfecho que eles buscavam."),
  cadeia("jk", "A posse garantida pela espada",
    ["JK vence a eleição de 1955 sem maioria absoluta", "UDN e parte dos militares contestam o resultado", "Carlos Luz assume no lugar de Café Filho, doente", "General Lott depõe Carlos Luz", "JK toma posse em janeiro de 1956"],
    "É o \"golpe preventivo\" de 11 de novembro: uma intervenção militar feita para garantir, e não para impedir, a posse dos eleitos."),
  cadeia("jk", "A conta dos 50 anos em 5",
    ["Plano de Metas exige investimentos enormes", "Governo emite moeda e toma empréstimos", "Inflação acelera", "FMI exige corte de gastos para liberar crédito", "JK rompe com o FMI em 1959"],
    "Aceitar o FMI significava parar as obras e Brasília. JK preferiu romper, e deixou a inflação e a dívida para os sucessores."),
  cadeia("janio", "Da renúncia à posse de Jango",
    ["Jânio renuncia em 25 de agosto de 1961", "Ministros militares vetam a posse de Jango", "Brizola lança a Campanha da Legalidade", "Congresso aprova o parlamentarismo", "Jango toma posse com poderes reduzidos"],
    "O parlamentarismo foi a saída negociada para evitar a guerra civil: Jango assumia, mas sem governar de fato."),
  cadeia("jango", "Do parlamentarismo ao comício",
    ["Jango assume sob o parlamentarismo", "Plebiscito de 1963 devolve o presidencialismo", "Plano Trienal não consegue conter a inflação", "Jango aposta nas Reformas de Base e na mobilização popular", "Comício da Central do Brasil"],
    "Sem maioria no Congresso e com a economia piorando, Jango trocou a negociação pela pressão das ruas, o que acelerou a reação."),
  cadeia("jango", "Os últimos dezoito dias",
    ["Comício da Central do Brasil", "Marcha da Família com Deus pela Liberdade", "Revolta dos marinheiros e anistia aos rebeldes", "Tropas de Mourão Filho saem de Minas Gerais", "Congresso declara vaga a Presidência"],
    "A marcha deu base civil à conspiração; a anistia aos marinheiros convenceu os oficiais indecisos de que a hierarquia estava em risco."),
  cadeia("guerra-fria", "A Europa partida em dois",
    ["Doutrina Truman promete conter o comunismo", "Plano Marshall financia a Europa Ocidental", "Stalin bloqueia Berlim Ocidental", "Criação da OTAN", "Criação do Pacto de Varsóvia"],
    "Cada passo de um lado provocou resposta do outro. O Pacto de Varsóvia (1955) veio depois da entrada da Alemanha Ocidental na OTAN."),
  cadeia("guerra-fria", "Da desestalinização aos tanques",
    ["Morte de Stalin", "Kruschev denuncia os crimes de Stalin", "Húngaros vão às ruas pedir reformas", "Nagy anuncia a saída do Pacto de Varsóvia", "Tanques soviéticos invadem a Hungria"],
    "A crítica a Stalin abriu espaço para contestação no Leste. O limite ficou claro em 1956: reformar podia, sair do bloco não."),
  cadeia("guerra-fria", "A crise que quase virou guerra nuclear",
    ["Revolução Cubana chega ao poder", "Invasão da Baía dos Porcos fracassa", "União Soviética instala mísseis em Cuba", "Kennedy impõe o bloqueio naval à ilha", "Linha direta entre Washington e Moscou é criada"],
    "A tentativa de derrubar Fidel empurrou Cuba para Moscou. O susto de 1962 levou as superpotências a criar canais para evitar um acidente."),
  cadeia("vietna", "Como a guerra começou",
    ["Viet Minh derrota a França em Dien Bien Phu", "Acordos de Genebra dividem o país no paralelo 17", "Governo do Sul recusa as eleições de reunificação", "Guerrilha vietcongue cresce no Sul", "Incidente do Golfo de Tonkin leva os Estados Unidos à intervenção direta"],
    "A divisão deveria ser provisória. Como Ho Chi Minh venceria as eleições, elas não aconteceram, e a disputa foi para as armas."),
  cadeia("vietna", "Como a guerra terminou",
    ["Ofensiva do Tet abala a opinião pública norte-americana", "Nixon adota a vietnamização da guerra", "Acordos de Paris retiram as tropas dos Estados Unidos", "Vietnã do Norte lança a ofensiva final", "Saigon cai e o país é reunificado"],
    "O Tet foi derrota militar e vitória política dos comunistas: convenceu os norte-americanos de que a guerra não tinha saída."),
  cadeia("descolonizacao", "A independência da Índia",
    ["Gandhi lidera a Marcha do Sal", "Reino Unido sai enfraquecido da Segunda Guerra", "Londres aceita negociar a retirada", "Independência com partilha entre Índia e Paquistão", "Gandhi é assassinado por um extremista hindu"],
    "A desobediência civil desgastou o domínio britânico por décadas; a guerra tirou de Londres a força para mantê-lo. A partilha custou centenas de milhares de vidas."),
  cadeia("descolonizacao", "Do apartheid à presidência de Mandela",
    ["Partido Nacional institui o apartheid", "Polícia mata manifestantes em Sharpeville", "CNA é proibido e adota a luta armada", "Mandela é condenado à prisão perpétua", "Mandela é libertado e eleito presidente"],
    "Sharpeville (1960) fechou a via pacífica. Entre a condenação (1964) e a libertação (1990) passaram-se 26 anos de pressão interna e sanções."),
  cadeia("descolonizacao", "O fim do império português",
    ["Salazar se recusa a negociar com as colônias", "Guerrilhas iniciam a guerra em Angola, Guiné e Moçambique", "Guerra longa desgasta o Exército português", "Revolução dos Cravos derruba a ditadura", "Angola e Moçambique tornam-se independentes"],
    "Foi a guerra colonial que derrubou a ditadura em Portugal, e não o contrário: os capitães que fizeram o 25 de Abril queriam sair da África."),
  cadeia("maio68", "O maio francês",
    ["Estudantes de Nanterre criam o Movimento 22 de Março", "Polícia entra na Sorbonne e surgem as barricadas", "Dez milhões de trabalhadores entram em greve", "De Gaulle dissolve a Assembleia e convoca eleições", "Gaullistas vencem com folga em junho"],
    "A repressão aos estudantes puxou os operários para a rua. Nas urnas, porém, o medo da desordem deu a vitória ao governo."),
  cadeia("figuras", "De um assento de ônibus à lei",
    ["Rosa Parks é presa por não ceder o lugar", "Comunidade negra boicota os ônibus de Montgomery", "Martin Luther King torna-se líder nacional", "Marcha sobre Washington e \"Eu tenho um sonho\"", "Lei dos Direitos Civis proíbe a segregação"],
    "Do boicote (1955) à lei (1964) foram nove anos de campanhas não violentas. King surgiu como líder justamente em Montgomery."),
  cadeia("figuras", "Chile: da eleição ao golpe",
    ["Allende é eleito presidente", "Governo nacionaliza o cobre", "Estados Unidos cortam crédito e a crise se agrava", "Militares bombardeiam o palácio de La Moneda", "Pinochet instala a ditadura"],
    "A via democrática ao socialismo foi sufocada por dentro e por fora: boicote econômico, oposição interna e, por fim, o golpe de 1973."),
];
