import type { Questao } from "@/lib/tipos";
import { criar } from "../criar";

const j = criar("janio");
const g = criar("jango");

const I_II = "Apenas I e II.";
const I_III = "Apenas I e III.";
const II_III = "Apenas II e III.";
const SO_I = "Apenas I.";
const TODAS = "I, II e III.";

/** Segunda leva de Jânio e Jango: níveis difícil e desafio. A primeira alternativa é a correta. */
export const novasBrasil2: Questao[] = [
  // ───────── Jânio e a Legalidade ─────────
  j("jan-41", "dificil", "Fuvest", "Em 19 de agosto de 1961, seis dias antes de renunciar, Jânio Quadros condecorou Ernesto \"Che\" Guevara com a Ordem Nacional do Cruzeiro do Sul. O gesto deve ser entendido como:",
    [
      "afirmação de autonomia diplomática, que agravou o rompimento do presidente com a UDN e com setores militares.",
      "sinal de adesão ao socialismo, confirmado pelo anúncio da saída do Brasil da OEA.",
      "retribuição ao apoio militar cubano prometido para um eventual fechamento do Congresso Nacional pelo presidente.",
      "exigência do PTB para continuar sustentando o governo no Congresso.",
      "homenagem protocolar que passou despercebida, só sendo lembrada após a renúncia.",
    ],
    "Guevara voltava da conferência de Punta del Este, onde se lançara a Aliança para o Progresso. Jânio, conservador na economia, usava a política externa para mostrar independência dos Estados Unidos. Carlos Lacerda respondeu homenageando um líder anticastrista, e oficiais condecorados ameaçaram devolver as medalhas.",
    "Jânio: FMI na economia, Che na vitrine."),
  j("jan-42", "dificil", "Unesp", "Jânio Quadros governava por meio de \"bilhetinhos\" enviados diretamente a ministros e chefes de repartição e instaurou dezenas de comissões de sindicância. Esse estilo de governo:",
    [
      "dispensava a mediação dos partidos e do Congresso, o que o deixou sem aliados quando a crise chegou.",
      "foi imposto pela Constituição de 1946, que proibia o presidente de enviar projetos de lei ao Legislativo.",
      "refletia a força da UDN, que controlava as nomeações.",
      "resultava de um acordo com o PSD e o PTB, que preferiam manter o presidente longe das decisões econômicas.",
    ],
    "Jânio se elegeu contra \"os políticos\" e governou como se pudesse prescindir deles. As sindicâncias atingiam inclusive gente ligada ao vice João Goulart e ao governo anterior, o que indispôs a maioria parlamentar. Quando renunciou, não havia bancada nem partido disposto a pedir que ficasse.",
    "Quem governa sozinho, cai sozinho."),
  j("jan-43", "dificil", "Unicamp", "Jânio Quadros venceu a eleição de 1960 com a maior votação até então registrada no país. No Congresso, porém, sua situação era frágil, pois:",
    [
      "a maioria das cadeiras pertencia ao PSD e ao PTB, eleitos em 1958 e derrotados na disputa presidencial.",
      "a UDN, seu partido de origem, tinha maioria absoluta, mas se recusava a votar as propostas econômicas do governo.",
      "o Legislativo fora renovado junto com a eleição presidencial, com vitória esmagadora do PCB e de seus aliados.",
      "ele dissolvera a Câmara logo após a posse, e o Senado passou a obstruir todas as votações.",
      "os deputados eleitos em sua coligação haviam sido cassados pela Justiça Eleitoral.",
    ],
    "Jânio não era da UDN: concorreu por pequenas legendas, com o apoio udenista. As eleições legislativas não coincidiam com a presidencial, e o Congresso em funções vinha de 1958, com predomínio da aliança PSD–PTB. Presidente forte nas urnas e fraco no plenário: a combinação ajuda a entender a tentação de buscar mais poderes.",
    "Seis milhões de votos, nenhuma maioria."),
  j("jan-44", "dificil", "UERJ", "Quando Jânio renunciou, o vice-presidente João Goulart estava na China, o que serviu de argumento aos ministros militares para vetar sua posse. Essa viagem:",
    [
      "era uma missão oficial de caráter comercial, determinada pelo próprio Jânio.",
      "era particular e clandestina, feita a convite do Partido Comunista Chinês.",
      "fora imposta pelo Congresso, contra a vontade do presidente.",
      "tinha por objetivo negociar a adesão do Brasil ao bloco dos países socialistas.",
    ],
    "Jango chefiava uma delegação enviada pelo governo dentro da política externa independente, que buscava novos mercados. Para muitos historiadores, mandar para tão longe um vice malvisto pelos militares fazia parte do cálculo da renúncia: com o substituto \"inaceitável\" do outro lado do mundo, o país pediria a volta de Jânio.",
    "Jango estava na China a serviço de Jânio."),
  j("jan-45", "dificil", "UFPR", "Durante a crise de agosto de 1961, o marechal Henrique Lott, candidato derrotado por Jânio no ano anterior:",
    [
      "divulgou um manifesto pela posse de Jango e foi preso por ordem do ministro da Guerra.",
      "assumiu o comando do III Exército e marchou sobre Brasília à frente das tropas gaúchas.",
      "apoiou o veto dos ministros militares, por considerar Jango uma ameaça à hierarquia.",
      "foi escolhido primeiro-ministro pelo Congresso, como nome de consenso entre civis e militares.",
      "manteve silêncio, alegando que a reserva o impedia de opinar sobre política.",
    ],
    "Coerente com 1955, Lott pôs-se do lado da Constituição e pagou com a prisão, determinada pelo marechal Odílio Denys. O episódio mostra que as Forças Armadas estavam rachadas: havia legalistas de peso, e foi essa divisão, tornada concreta com a adesão do III Exército, que impediu o golpe naquele momento.",
    "Lott: legalista em 1955 e de novo em 1961."),
  j("jan-46", "dificil", "UFRGS", "A Campanha da Legalidade costuma ser associada apenas ao Rio Grande do Sul de Leonel Brizola. Outro governador que aderiu abertamente ao movimento, organizando a resistência em seu estado, foi:",
    [
      "Mauro Borges, de Goiás.",
      "Carlos Lacerda, da Guanabara.",
      "Magalhães Pinto, de Minas Gerais.",
      "Carvalho Pinto, de São Paulo.",
      "Cid Sampaio, de Pernambuco.",
    ],
    "Mauro Borges, militar e filho de um velho aliado de Vargas, mobilizou Goiânia e a vizinha Brasília. Lacerda, no extremo oposto, apoiou o veto e censurou a imprensa na Guanabara. A posição dos governadores antecipa o mapa de 1964: Lacerda e Magalhães Pinto estariam entre os chefes civis do golpe, e Mauro Borges seria deposto pouco depois.",
    "Legalidade: Brizola no Sul, Mauro Borges no Planalto."),
  j("jan-51", "desafio", "Fuvest", "Em julho de 1962, uma greve geral paralisou diversas capitais em meio à crise aberta pela demissão do gabinete Tancredo Neves. O movimento pressionava:",
    [
      "pela formação de um gabinete nacionalista, após a rejeição do nome indicado por Jango.",
      "pela renúncia de João Goulart, acusado pelas centrais sindicais de ter traído as reformas ao aceitar o parlamentarismo.",
      "pela manutenção do parlamentarismo, ameaçado por um projeto da UDN.",
      "pelo fechamento do Congresso e pela convocação imediata de uma Assembleia Constituinte exclusiva.",
      "pela posse de Leonel Brizola como primeiro-ministro, com o apoio declarado dos ministros militares.",
    ],
    "A crise mostrou o impasse do sistema: o Congresso conservador derrubou o nome de Jango; Jango inviabilizou o nome do Congresso. A greve, puxada pelo comando que logo daria origem ao CGT, ajudou a impor o gaúcho Brochado da Rocha. Foi a primeira demonstração de que os sindicatos podiam agir como força política nacional, o que alarmou empresários e militares.",
    "Três gabinetes em quinze meses: o parlamentarismo de 1961 não funcionou."),
  j("jan-52", "desafio", "Unicamp", "A emenda parlamentarista de 1961 previa que um plebiscito poderia confirmar ou rejeitar o novo sistema perto do fim do mandato de João Goulart, em 1965. A consulta, no entanto, ocorreu em janeiro de 1963 porque:",
    [
      "o Congresso antecipou a data em 1962, sob pressão de greves, de chefes militares e do próprio governo.",
      "o Supremo Tribunal Federal declarou a emenda inconstitucional e mandou consultar o eleitorado.",
      "Jango a convocou por decreto, à revelia do Congresso, o que deu origem ao primeiro pedido de impeachment.",
      "a UDN, arrependida da emenda, propôs a antecipação para ter um presidente forte em 1963.",
      "a emenda estabelecia que a queda do terceiro gabinete tornava a consulta automática.",
    ],
    "A antecipação foi arrancada em setembro de 1962, depois da renúncia do gabinete Brochado da Rocha e de nova ameaça de greve geral. Em 6 de janeiro de 1963, cerca de quatro em cada cinco votantes disseram \"não\" ao parlamentarismo. Jango recuperou os poderes, mas com metade do mandato já consumida e a economia em deterioração.",
    "Previsto para 1965, antecipado para 1963."),
  j("jan-53", "desafio", "Unesp", "\"O tostão contra o milhão\" foi o lema da campanha que projetou Jânio Quadros, em 1953, na disputa pela prefeitura de São Paulo. A frase expressava:",
    [
      "a imagem do candidato sem recursos nem máquina, enfrentando a coligação dos grandes partidos.",
      "a promessa de congelar preços e tarifas, financiando o déficit com emissão de moeda e crédito público.",
      "o programa de austeridade que ele aplicaria na Presidência, com a Instrução 204.",
      "a defesa do pequeno comércio contra as multinacionais.",
      "a crítica dos adversários ao custo de sua campanha, a mais cara até então.",
    ],
    "Professor e vereador de bairros populares, Jânio derrotou um candidato apoiado por quase todas as legendas e pelo governador. Em sete anos foi de prefeito a governador e a presidente, sempre se apresentando como alguém de fora do sistema. A trajetória meteórica explica tanto a força eleitoral quanto a falta de raízes partidárias.",
    "O outsider que venceu todas, e não tinha ninguém ao lado."),
  j("jan-54", "desafio", "UFRGS", "A política externa independente (1961–1964) é frequentemente confundida com neutralismo. A distinção está em que o Brasil:",
    [
      "ampliou relações com países socialistas e afro-asiáticos sem deixar o sistema interamericano.",
      "deixou a OEA e o TIAR e ingressou como membro fundador no Movimento dos Não Alinhados.",
      "passou a votar sistematicamente com a União Soviética na ONU.",
      "rompeu com os Estados Unidos e assinou um tratado de defesa mútua com Cuba.",
      "limitou a mudança ao discurso, sem reatar com a URSS nem alterar votos em organismos internacionais.",
    ],
    "A ideia era universalizar as relações de um país que se via como ocidental e subdesenvolvido ao mesmo tempo: comerciar com todos, defender a autodeterminação (inclusive a de Cuba) e a descolonização. O Brasil mandou observador à conferência de Belgrado (1961), mas não aderiu ao movimento. As relações com Moscou, rompidas em 1947, foram restabelecidas no fim de 1961.",
    "Independente não é neutro: é ocidental com vontade própria."),
  j("jan-55", "desafio", "Fuvest", "Assinale a alternativa que ordena corretamente os acontecimentos da crise de 1961.",
    [
      "Condecoração de Che Guevara; discurso de Lacerda na televisão; renúncia de Jânio; formação da Rede da Legalidade; aprovação da emenda parlamentarista; posse de Jango.",
      "Discurso de Lacerda na televisão; condecoração de Che Guevara; renúncia de Jânio; aprovação da emenda parlamentarista; formação da Rede da Legalidade; posse de Jango.",
      "Condecoração de Che Guevara; renúncia de Jânio; discurso de Lacerda na televisão; formação da Rede da Legalidade; posse de Jango; aprovação da emenda parlamentarista.",
      "Renúncia de Jânio; condecoração de Che Guevara; formação da Rede da Legalidade; discurso de Lacerda na televisão; aprovação da emenda parlamentarista; posse de Jango.",
    ],
    "Che foi condecorado em 19 de agosto; Lacerda denunciou um suposto plano de golpe na noite do dia 24; Jânio renunciou no dia 25; Brizola pôs a Rede da Legalidade no ar nos dias seguintes; o Congresso aprovou a emenda em 2 de setembro; Jango tomou posse no dia 7. A emenda veio antes da posse: foi a condição para que ela acontecesse.",
    "19, 24, 25 de agosto; 2 e 7 de setembro."),
  j("jan-56", "desafio", "UFPR", "Sobre o governo Jânio Quadros (janeiro a agosto de 1961), assinale a afirmativa INCORRETA.",
    [
      "Manteve os subsídios cambiais à importação de trigo e petróleo, para evitar o aumento do pão e dos transportes.",
      "Foi o primeiro presidente a tomar posse em Brasília.",
      "Criou, por decreto, o Parque Nacional do Xingu.",
      "Renegociou a dívida externa e obteve novos créditos depois de adotar medidas apoiadas pelo FMI.",
      "Tomou medidas para restabelecer relações com a União Soviética, concluídas só no governo seguinte, em novembro de 1961.",
    ],
    "A Instrução 204 fez o oposto: desvalorizou o cruzeiro e retirou o \"câmbio de custo\" do trigo e do petróleo, encarecendo pão e passagens. Essa austeridade agradou aos credores e desagradou aos trabalhadores, enquanto a política externa desagradava aos conservadores. As demais afirmativas estão corretas.",
    "Jânio conseguiu irritar a esquerda pela economia e a direita pela diplomacia."),

  // ───────── Jango e o golpe ─────────
  g("jng-41", "dificil", "Fuvest", "No Comício da Central do Brasil, em 13 de março de 1964, João Goulart assinou diante da multidão dois decretos. Eles determinavam:",
    [
      "a desapropriação de terras às margens de rodovias, ferrovias e açudes federais e a encampação das refinarias de petróleo particulares.",
      "a nacionalização dos bancos estrangeiros e a moratória unilateral da dívida externa.",
      "a concessão do voto aos analfabetos e a legalização do Partido Comunista.",
      "o fechamento do Congresso e a convocação de uma Assembleia Constituinte.",
      "o congelamento geral de preços e a estatização das montadoras de automóveis.",
    ],
    "O decreto da SUPRA atingia faixas de terra valorizadas por obras públicas; o outro passava à Petrobras as refinarias privadas. Voto do analfabeto e legalização do PCB dependiam do Congresso e foram apenas defendidos no palanque. O que assustou a oposição foi o método: reformas por decreto, anunciadas em praça pública, ao lado de sindicalistas e de militares fardados.",
    "Central do Brasil: terra na beira da estrada e refinaria para a Petrobras."),
  g("jng-42", "dificil", "Unicamp", "Dois dias depois do Comício da Central, Jango enviou ao Congresso a mensagem presidencial de 1964. Ela propunha, entre outros pontos, o voto dos analfabetos, a elegibilidade de sargentos e praças e a realização de um plebiscito sobre as reformas. A oposição reagiu denunciando:",
    [
      "uma tentativa de alterar as regras para permanecer no poder além de 1965.",
      "a intenção de entregar o comando das Forças Armadas aos governadores.",
      "um acordo secreto com os Estados Unidos para financiar a reforma agrária no Nordeste.",
      "o abandono das reformas de base em troca do apoio do PSD.",
    ],
    "A Constituição proibia a reeleição e tornava inelegíveis os parentes do presidente, caso de Brizola. Qualquer proposta de mudança constitucional era lida, assim, como plano continuísta, e o fantasma de 1937 foi explorado à exaustão. Não há prova de que Jango preparasse um golpe, mas a desconfiança, alimentada também pela esquerda que pedia \"reformas na lei ou na marra\", isolou-o do centro.",
    "Cada proposta de emenda virava \"prova\" de continuísmo."),
  g("jng-43", "dificil", "UERJ", "Criado em 1962, o Comando Geral dos Trabalhadores (CGT) teve grande peso político no governo Goulart. Em relação à estrutura sindical herdada da era Vargas, o CGT:",
    [
      "funcionava à margem da lei, que não admitia centrais reunindo categorias diferentes.",
      "era o órgão máximo previsto na CLT, presidido pelo próprio ministro do Trabalho e Previdência.",
      "substituiu os sindicatos oficiais, extintos por decreto de Jango em 1962.",
      "representava apenas os trabalhadores rurais, até então excluídos da legislação trabalhista.",
      "foi fundado pelo IPES para dividir o movimento operário.",
    ],
    "A CLT organizava os sindicatos por categoria e por município, na vertical, justamente para impedir uma central nacional. O CGT nasceu das greves políticas de 1962 e reunia comunistas e trabalhistas. Sua força vinha sobretudo do setor público e das estatais (ferroviários, portuários, petroleiros), o que facilitou à oposição apresentá-lo como braço do governo: a \"república sindicalista\".",
    "CGT: forte na rua, inexistente na lei."),
  g("jng-44", "dificil", "Unesp", "Em janeiro de 1964, o governo Goulart instituiu o Plano Nacional de Alfabetização, baseado no método de Paulo Freire, testado no ano anterior em Angicos (RN). O plano tinha implicação política direta porque:",
    [
      "os analfabetos não votavam: alfabetizar milhões de adultos significava ampliar e mudar o eleitorado.",
      "era financiado pela Aliança para o Progresso, que exigia em troca o fim das reformas de base.",
      "substituía a rede pública de ensino por escolas mantidas pelos sindicatos.",
      "tornava o ensino religioso obrigatório, selando a aliança de Jango com a Igreja.",
    ],
    "Cerca de quatro em cada dez adultos estavam fora das urnas por não saber ler. O método partia de palavras do cotidiano do aluno (tijolo, enxada, salário) e ligava a leitura à discussão de sua condição social, o que os adversários chamavam de doutrinação. O plano foi extinto nos primeiros dias após o golpe, e Paulo Freire, preso e depois exilado.",
    "Ensinar a ler era, em 1964, fabricar eleitores."),
  g("jng-45", "dificil", "UFPR", "Na noite de 2 de abril de 1964, o presidente dos Estados Unidos, Lyndon Johnson, enviou mensagem de congratulações a Ranieri Mazzilli, empossado horas antes. O detalhe que torna esse reconhecimento politicamente significativo é que:",
    [
      "João Goulart ainda se encontrava em território brasileiro, sem ter renunciado.",
      "o Congresso brasileiro ainda não havia sido informado da movimentação de tropas.",
      "Mazzilli era o chefe militar da conspiração.",
      "os Estados Unidos haviam declarado neutralidade na véspera.",
      "a mensagem condicionava o apoio à convocação de eleições diretas em noventa dias.",
    ],
    "Jango estava em Porto Alegre e só deixaria o país no dia 4. A pressa em reconhecer o novo governo, somada ao que se soube depois sobre a Operação Brother Sam (força naval e combustível postos à disposição dos golpistas), mostra que Washington acompanhava e respaldava o movimento, embora a intervenção direta não tenha sido necessária.",
    "O telegrama chegou antes de Jango sair do país."),
  g("jng-46", "dificil", "Fuvest", "O governo Goulart confiava num \"dispositivo militar\" que garantiria sua permanência. Ele desmoronou em horas, e um momento decisivo foi a adesão ao golpe do general Amaury Kruel, comandante do II Exército e amigo pessoal do presidente. Kruel aderiu depois que Jango:",
    [
      "se recusou a romper com o CGT e a afastar os auxiliares identificados com a esquerda.",
      "ordenou o bombardeio aéreo das tropas rebeldes que desciam de Minas Gerais rumo ao Rio de Janeiro.",
      "anunciou a intenção de nomear Brizola ministro da Guerra.",
      "decretou o fechamento do Congresso Nacional.",
      "pediu asilo à embaixada do Uruguai, deixando o governo acéfalo.",
    ],
    "Por telefone, Kruel ofereceu apoio em troca do rompimento com os sindicatos; Jango respondeu que não abandonaria quem o sustentava. O episódio revela que muitos oficiais não eram conspiradores de primeira hora: decidiram-se no fim, movidos sobretudo pelo temor de quebra da hierarquia depois da revolta dos marinheiros. Jango, por sua vez, não quis resistir para evitar uma guerra civil.",
    "Kruel pediu a cabeça do CGT; Jango disse não."),
  g("jng-51", "desafio", "Unicamp", "Considere as afirmativas sobre as Reformas de Base.\nI. A reforma agrária esbarrava na exigência constitucional de indenização prévia e em dinheiro, daí a proposta de pagar as desapropriações com títulos da dívida pública.\nII. A reforma eleitoral limitava-se a estender o direito de voto às mulheres, ainda excluídas das eleições federais.\nIII. A reforma universitária previa o fim da cátedra vitalícia e a ampliação das vagas no ensino superior.\nEstá correto o que se afirma em:",
    [I_III, I_II, II_III, SO_I, TODAS],
    "As mulheres votavam desde o Código Eleitoral de 1932. A reforma eleitoral tratava do voto dos analfabetos e da elegibilidade de sargentos e praças. A emenda que permitiria pagar a terra com títulos precisava de dois terços do Congresso, onde os proprietários rurais estavam bem representados pelo PSD e pela UDN: é nesse bloqueio que a crise se instala.",
    "Reforma agrária dependia de emenda; emenda dependia de quem tinha terra."),
  g("jng-52", "desafio", "Fuvest", "Em 1962, o Congresso dos Estados Unidos aprovou a chamada Emenda Hickenlooper, que mandava suspender a ajuda econômica a países que expropriassem empresas norte-americanas sem indenização considerada adequada. Um dos episódios que motivaram a emenda ocorreu no Brasil:",
    [
      "a encampação, pelo governador Leonel Brizola, de subsidiárias norte-americanas de telefonia e energia.",
      "a criação da Petrobras, que teria expropriado sem pagamento os campos de petróleo da Standard Oil na Bahia.",
      "a nacionalização das montadoras de automóveis pelo gabinete Tancredo Neves.",
      "o confisco de fazendas de cidadãos norte-americanos pela SUPRA.",
      "a estatização da Light pelo governo João Goulart.",
    ],
    "Brizola encampou a filial da Amforp (energia, 1959) e a da ITT (telefones, 1962), pagando valores simbólicos por considerar os investimentos já amortizados. O caso azedou as relações com Washington no momento em que Jango buscava crédito. O governo federal acabou negociando a compra das empresas da Amforp, o que lhe valeu críticas da esquerda nacionalista.",
    "Brizola encampava no Sul; a conta diplomática chegava a Brasília."),
  g("jng-53", "desafio", "Unesp", "Em análise clássica da crise de 1964, o cientista político Wanderley Guilherme dos Santos falou em \"paralisia decisória\". Com essa expressão, ele sustenta que o golpe foi precedido por:",
    [
      "um sistema político fragmentado e radicalizado, em que nenhuma coalizão conseguia aprovar ou barrar de vez as grandes decisões.",
      "uma conspiração planejada de longa data por empresários, militares e pela embaixada norte-americana, da qual a crise política foi mero pretexto.",
      "uma crise exclusivamente econômica, sem relação com o funcionamento das instituições.",
      "a inércia pessoal do presidente, que se recusava a enviar projetos ao Congresso.",
      "o excesso de poder do Executivo, que governava por decretos e anulava o Legislativo.",
    ],
    "A interpretação desloca o foco dos conspiradores para as instituições: partidos divididos internamente, alianças instáveis e ministérios trocados a cada poucos meses impediam qualquer saída negociada. Ela dialoga com outras duas leituras: a de René Dreifuss, centrada na ação organizada do complexo IPES/IBAD, e a de Argelina Figueiredo, para quem direita e esquerda deixaram de apostar na democracia como regra do jogo.",
    "Três leituras de 1964: conspiração, paralisia, falta de compromisso democrático."),
  g("jng-54", "desafio", "UFRGS", "No fim de 1963, pelo microfone da Rádio Mayrink Veiga, Leonel Brizola conclamou a formação dos \"Grupos dos Onze\". Na prática, essa iniciativa:",
    [
      "teve organização precária, mas foi amplamente usada pela oposição como prova de que a esquerda preparava a luta armada.",
      "constituiu um exército popular treinado e armado por Cuba, que resistiu ao golpe por várias semanas no interior do Rio Grande do Sul.",
      "era um movimento de alfabetização de adultos ligado à Igreja.",
      "foi criada pelo governo federal para substituir as polícias estaduais nas capitais governadas pela oposição, como a Guanabara.",
      "reunia os onze governadores favoráveis às reformas de base.",
    ],
    "A ideia era formar núcleos de onze \"companheiros\", como um time de futebol, para defender as reformas e resistir a um golpe. Houve muitas listas de adesão e quase nenhuma arma. O efeito maior foi sobre o adversário: somados à rebelião dos sargentos e dos marinheiros, os Grupos dos Onze alimentaram o medo que levou oficiais indecisos para o lado da conspiração.",
    "Muito barulho, pouca arma, enorme efeito de propaganda contra."),
  g("jng-55", "desafio", "UERJ", "A Ação Popular (AP), fundada em 1962, foi a principal força do movimento estudantil no governo Goulart, dirigindo a UNE. Sua origem está:",
    [
      "na Juventude Universitária Católica, cujos militantes aderiram ao socialismo.",
      "numa dissidência do PCB favorável à linha chinesa.",
      "na ala jovem do PTB gaúcho, organizada por Brizola.",
      "nos grêmios das escolas militares, mobilizados durante a Campanha da Legalidade de 1961.",
      "no Instituto Superior de Estudos Brasileiros.",
    ],
    "A AP mostra que a Igreja não era um bloco em 1964: enquanto parte do clero e do laicato organizava as Marchas da Família, jovens da Ação Católica, inspirados num cristianismo voltado à transformação social, atuavam na alfabetização popular e no sindicalismo rural. Depois do golpe, a organização se radicalizou e muitos de seus quadros foram perseguidos.",
    "Havia católicos na Marcha da Família e católicos na UNE."),
  g("jng-56", "desafio", "Fuvest", "Assinale a alternativa que ordena corretamente os acontecimentos de março e abril de 1964.",
    [
      "Comício da Central do Brasil; Marcha da Família em São Paulo; revolta dos marinheiros; discurso de Jango no Automóvel Clube; saída das tropas de Minas Gerais; declaração de vacância da Presidência; Ato Institucional.",
      "Marcha da Família em São Paulo; Comício da Central do Brasil; discurso de Jango no Automóvel Clube; revolta dos marinheiros; saída das tropas de Minas Gerais; Ato Institucional; declaração de vacância da Presidência.",
      "Comício da Central do Brasil; revolta dos marinheiros; Marcha da Família em São Paulo; saída das tropas de Minas Gerais; discurso de Jango no Automóvel Clube; declaração de vacância da Presidência; Ato Institucional.",
      "Revolta dos marinheiros; Comício da Central do Brasil; Marcha da Família em São Paulo; discurso de Jango no Automóvel Clube; declaração de vacância da Presidência; saída das tropas de Minas Gerais; Ato Institucional.",
    ],
    "Dia 13, comício; dia 19, marcha; dias 25 a 27, marinheiros; dia 30, Automóvel Clube; dia 31, Mourão Filho; madrugada de 2 de abril, vacância; dia 9, Ato Institucional. A marcha foi resposta ao comício, e o discurso aos sargentos, logo após a anistia aos marinheiros, foi a gota d'água para os oficiais.",
    "13, 19, 25, 30, 31 de março; 2 e 9 de abril."),
];
