import type { Questao } from "@/lib/tipos";
import { criar } from "./criar";

const d = criar("dutra");
const v = criar("vargas");
const k = criar("jk");

const I_II = "Apenas I e II.";
const I_III = "Apenas I e III.";
const II_III = "Apenas II e III.";
const SO_I = "Apenas I.";
const SO_III = "Apenas III.";
const TODAS = "I, II e III.";

/** Segunda leva de Dutra, Vargas e JK: níveis difícil e desafio. A primeira alternativa é a correta. */
export const novasBrasil1: Questao[] = [
  // ───────── Governo Dutra ─────────
  d("dut-41", "dificil", "Fuvest", "Apresentado ao Congresso em 1948, o Plano SALTE costuma ser citado como a primeira tentativa de planejamento global do gasto público no Brasil democrático. Sobre ele, é correto afirmar que:",
    [
      "reunia metas para saúde, alimentação, transporte e energia, mas foi executado só em parte.",
      "foi financiado integralmente pelo Plano Marshall, estendido à América Latina por pressão da diplomacia brasileira.",
      "priorizava a indústria de bens de consumo duráveis, antecipando o modelo de JK.",
      "criou a Petrobras e a Eletrobrás como empresas estatais encarregadas de executar suas metas de energia.",
      "foi rejeitado pelo Congresso, dominado pela UDN, que via nele uma volta ao dirigismo do Estado Novo.",
    ],
    "SALTE é a sigla de Saúde, Alimentação, Transporte e Energia. O plano só foi aprovado em 1950, dependia de verbas orçamentárias incertas e foi abandonado no início dos anos 1950. O Plano Marshall nunca chegou à América Latina, o que frustrou o governo Dutra. Petrobras (1953) e Eletrobrás (1961) são posteriores.",
    "SALTE = Saúde, ALimentação, Transporte, Energia. Muito papel, pouca obra."),
  d("dut-42", "dificil", "UERJ", "Em abril de 1946, um decreto-lei de Dutra proibiu os jogos de azar e fechou os cassinos em todo o país, invocando a \"tradição moral, jurídica e religiosa do povo brasileiro\". A medida é reveladora porque:",
    [
      "mostra o conservadorismo moral do governo, próximo da Igreja Católica.",
      "resultou de uma exigência dos Estados Unidos para liberar empréstimos, já que os cassinos lavavam dinheiro de simpatizantes do Eixo.",
      "foi aprovada pela Assembleia Constituinte como primeiro artigo da nova Carta, antes mesmo da definição do regime de governo.",
      "visava enfraquecer o PCB, que controlava os sindicatos de trabalhadores dos cassinos e deles tirava seu financiamento.",
    ],
    "O decreto-lei 9.215 foi baixado por Dutra quando a Constituinte ainda trabalhava e o presidente legislava sozinho. Atribui-se a decisão ao catolicismo do casal presidencial e à pressão de setores da Igreja. Milhares de músicos, artistas e funcionários perderam o emprego de um dia para o outro.",
    "Democracia nova, costumes vigiados."),
  d("dut-43", "dificil", "Unicamp", "Entre fevereiro e setembro de 1946, enquanto a Assembleia Constituinte redigia a nova Carta, o presidente Dutra governou:",
    [
      "por decretos-lei, com base na Carta de 1937, que continuava formalmente em vigor.",
      "sob a Constituição de 1934, restabelecida por José Linhares logo após a deposição de Vargas.",
      "submetido a um gabinete escolhido pela Constituinte, numa breve experiência parlamentarista.",
      "sem poder legislar, pois a Constituinte acumulava as funções de Congresso ordinário desde a instalação.",
      "com base em atos institucionais editados pelos chefes militares que haviam deposto Vargas.",
    ],
    "A Constituinte decidiu, por maioria do PSD, que só faria a Constituição; até a promulgação valia a Carta do Estado Novo. Foi nesse intervalo que saíram decretos como o que restringia as greves (9.070) e o que fechou os cassinos. A proposta de revogar de imediato a Carta de 1937, defendida por UDN e PCB, foi derrotada.",
    "Sete meses de democracia com as regras do Estado Novo."),
  d("dut-44", "dificil", "Unesp", "O Brasil saiu da Segunda Guerra com reservas internacionais elevadas, e o governo Dutra abriu as importações contando com elas. A aposta fracassou rapidamente, entre outros motivos, porque:",
    [
      "boa parte das reservas estava em ouro e em libras bloqueadas, e os dólares de fato disponíveis eram poucos.",
      "os Estados Unidos confiscaram os depósitos brasileiros para cobrar o material bélico fornecido à FEB.",
      "o Congresso proibiu o uso das reservas para importar bens de consumo.",
      "a Constituição de 1946 obrigava o Tesouro a destinar metade das divisas ao pagamento antecipado da dívida externa.",
      "o preço do café despencou em 1946 e só voltou a subir no governo Juscelino Kubitschek.",
    ],
    "As libras acumuladas com o Reino Unido não podiam ser convertidas em dólares; parte delas acabou usada na compra de ferrovias inglesas já envelhecidas. Como o grosso das importações vinha da área do dólar, a parcela conversível se esgotou em pouco mais de um ano, o que levou ao controle de importações de 1947–48. O café, ao contrário, valorizou-se no fim da década.",
    "Reserva grande no papel, dólar curto no caixa."),
  d("dut-45", "dificil", "UFPR", "Do ponto de vista dos trabalhadores urbanos, um dado resume o governo Dutra: o salário mínimo",
    [
      "não teve nenhum reajuste, permanecendo com o valor fixado em 1943 apesar da inflação.",
      "foi extinto em 1946 e recriado por Vargas em 1951.",
      "passou a ser corrigido automaticamente todo ano, por determinação expressa da Constituição de 1946.",
      "foi unificado em todo o território nacional, acabando com as diferenças regionais.",
    ],
    "O mínimo ficou congelado de dezembro de 1943 até o reajuste concedido por Vargas no fim de 1951, perdendo boa parte do poder de compra. Somado à intervenção nos sindicatos e à repressão às greves, isso explica por que o voto operário voltou em massa para Vargas em 1950. O salário mínimo só seria unificado nacionalmente em 1984.",
    "Oito anos sem aumento: o melhor cabo eleitoral de Vargas."),
  d("dut-46", "dificil", "Fuvest", "Na eleição presidencial de 1950 surgiu o verbo \"cristianizar\", que entrou para o vocabulário político brasileiro. Ele designa a situação em que:",
    [
      "um partido lança um candidato oficial, mas suas bases o abandonam e trabalham por outro.",
      "a Igreja Católica orienta abertamente o voto dos fiéis contra um candidato tido como comunista.",
      "um candidato derrotado se recusa a reconhecer o resultado e apela aos quartéis.",
      "dois partidos rivais se unem em torno de um nome apartidário para evitar a vitória de um terceiro.",
    ],
    "O PSD lançou o mineiro Cristiano Machado, mas boa parte de seus chefes estaduais, ligados a Vargas desde o Estado Novo, fez campanha para o candidato do PTB. Cristiano terminou em terceiro. O episódio mostra que PSD e PTB, ambos criados sob a sombra de Getúlio, eram mais próximos entre si do que as siglas sugeriam.",
    "Cristiano Machado: candidato do PSD, abandonado pelo PSD."),
  d("dut-51", "desafio", "Unicamp", "Considere as afirmativas sobre a política externa do governo Dutra.\nI. O Brasil enviou um batalhão à Guerra da Coreia em 1950, como prova de fidelidade aos Estados Unidos.\nII. A conferência que aprovou o TIAR, em 1947, realizou-se em Petrópolis e foi encerrada com a presença do presidente Truman.\nIII. A esperada ajuda econômica norte-americana em larga escala não veio, pois a prioridade de Washington era a reconstrução da Europa.\nEstá correto o que se afirma em:",
    [II_III, I_II, I_III, SO_III, TODAS],
    "O Brasil não mandou tropas à Coreia: a guerra começou em junho de 1950, e o pedido norte-americano foi recusado já no governo Vargas. A conferência do Hotel Quitandinha (1947) e a visita de Truman são o auge do alinhamento. A frustração com a falta de um \"Plano Marshall para a América Latina\" é o pano de fundo da Missão Abbink e, mais tarde, da Operação Pan-Americana de JK.",
    "Alinhamento total, retorno pequeno."),
  d("dut-52", "desafio", "Fuvest", "O artigo 146 da Constituição de 1946 estabelecia: \"A União poderá, mediante lei especial, intervir no domínio econômico e monopolizar determinada indústria ou atividade\". O dispositivo permite concluir que a Carta de 1946:",
    [
      "era liberal na organização política, mas não consagrava o liberalismo econômico ortodoxo.",
      "proibia a presença de capital estrangeiro em qualquer setor considerado estratégico.",
      "manteve intacta a ordem econômica corporativa de 1937, incluindo os conselhos técnicos com poder de legislar no lugar do Parlamento.",
      "tornava obrigatória a estatização do petróleo, o que fez da Petrobras mera execução de um mandamento constitucional.",
      "subordinava a iniciativa privada a planos quinquenais aprovados pelo Congresso.",
    ],
    "A Constituição condicionava o uso da propriedade ao bem-estar social e autorizava o monopólio estatal por lei. Ela não impunha a estatização: abria a possibilidade. Foi com base nesse artigo que a lei de 1953 instituiu o monopólio do petróleo. O texto mostra como a ideia de Estado interventor, herdada dos anos 1930, sobreviveu à redemocratização.",
    "Liberal na política, intervencionista na economia."),
  d("dut-53", "desafio", "UERJ", "Em 1947, o Clube Militar promoveu um ciclo de conferências sobre o petróleo que opôs dois generais e antecipou o debate nacional dos anos seguintes. Nesse confronto:",
    [
      "Horta Barbosa defendeu o monopólio estatal, e Juarez Távora, a participação do capital estrangeiro.",
      "Juarez Távora defendeu o monopólio estatal, e Horta Barbosa, a entrega da exploração às empresas norte-americanas.",
      "ambos defenderam o monopólio estatal, divergindo apenas sobre a sede da futura empresa.",
      "Góis Monteiro e Eurico Dutra disputaram a presidência do Conselho Nacional do Petróleo.",
    ],
    "Távora argumentava que o país não tinha capital nem técnica e que a segurança continental pedia rapidez; Horta Barbosa, ex-presidente do Conselho Nacional do Petróleo, respondia que petróleo era questão de soberania. Em 1948 Dutra enviou ao Congresso o Estatuto do Petróleo, próximo das teses de Távora; a reação gerou a campanha \"O petróleo é nosso\".",
    "Horta = Estado. Távora = capital de fora."),
  d("dut-54", "desafio", "UFRGS", "Assinale a alternativa que apresenta, em ordem cronológica, acontecimentos do período 1945–1948.",
    [
      "Deposição de Vargas; eleição de Dutra; promulgação da Constituição; cassação do registro do PCB; cassação dos mandatos comunistas.",
      "Eleição de Dutra; deposição de Vargas; cassação do registro do PCB; promulgação da Constituição; cassação dos mandatos comunistas.",
      "Deposição de Vargas; promulgação da Constituição; eleição de Dutra; cassação dos mandatos comunistas; cassação do registro do PCB.",
      "Deposição de Vargas; eleição de Dutra; cassação do registro do PCB; cassação dos mandatos comunistas; promulgação da Constituição.",
    ],
    "Vargas caiu em outubro de 1945; Dutra foi eleito em dezembro; a Constituição saiu em setembro de 1946; o TSE cassou o registro do PCB em maio de 1947; o Congresso cassou os mandatos em janeiro de 1948. A ordem importa: a perseguição aos comunistas aconteceu já sob a Constituição democrática, e não antes dela.",
    "45 cai Vargas e vence Dutra · 46 Carta · 47 registro · 48 mandatos."),
  d("dut-55", "desafio", "Unesp", "Em 1947, Adhemar de Barros elegeu-se governador de São Paulo pelo PSP, legenda que ele próprio fundara, contando inclusive com o apoio do PCB, ainda legal. Essa vitória indica que:",
    [
      "o sistema de 1945 não se reduzia a PSD, UDN e PTB: lideranças pessoais com voto urbano podiam se impor fora deles.",
      "o PSD era hegemônico no eleitorado paulista, pois Adhemar era o candidato oficial do presidente Dutra e de seu ministério.",
      "a UDN conquistara o operariado de São Paulo, base principal da candidatura adhemarista.",
      "os partidos de 1945 eram estaduais, como os da Primeira República.",
      "o PCB havia aderido ao governo Dutra em troca da manutenção de seu registro eleitoral.",
    ],
    "Adhemar construiu em São Paulo uma máquina própria, de apelo popular e fama de \"rouba, mas faz\". Depois de eleito, rompeu com os comunistas. Seu peso foi decisivo em 1950: o apoio do PSP a Vargas custou a vaga de vice, entregue a Café Filho. Os partidos de 1945 eram obrigatoriamente nacionais, mas São Paulo sempre escapou ao trio dominante.",
    "São Paulo era de Adhemar (e depois de Jânio), não de PSD, UDN ou PTB."),
  d("dut-56", "desafio", "Fuvest", "Sobre a transição do Estado Novo para a ordem de 1946, assinale a afirmativa INCORRETA.",
    [
      "Promulgada a Constituição, a Assembleia Constituinte foi dissolvida e convocaram-se novas eleições para o Congresso.",
      "Deposto Vargas, a Presidência foi entregue ao presidente do Supremo Tribunal Federal, José Linhares.",
      "Mesmo afastado do poder, Vargas elegeu-se senador e deputado por vários estados em dezembro de 1945.",
      "Vargas foi derrubado por chefes militares que haviam sustentado o Estado Novo, como os generais Góis Monteiro e Eurico Dutra.",
      "A campanha queremista defendia a convocação de uma Constituinte com Vargas ainda no governo, sob o lema \"Queremos Getúlio\".",
    ],
    "Os constituintes eleitos em 1945 não foram dispensados: concluída a Carta, a Assembleia se dividiu em Câmara e Senado e seguiu como Congresso ordinário. As demais afirmativas estão corretas e mostram o paradoxo da transição: a ditadura foi encerrada por seus próprios generais, e o ditador saiu dela como o político mais votado do país.",
    "Quem derrubou Vargas em 1945 foi a mesma cúpula que o sustentou em 1937."),

  // ───────── Vargas ─────────
  v("var-41", "dificil", "Fuvest", "O Acordo Militar Brasil–Estados Unidos, assinado em 1952, dividiu as Forças Armadas e a base do governo Vargas. Os nacionalistas o criticavam porque ele:",
    [
      "trocava armamento norte-americano pelo fornecimento de minerais estratégicos, como as areias monazíticas.",
      "instalava bases navais norte-americanas permanentes em Natal e em Fernando de Noronha, sob jurisdição de Washington.",
      "obrigava o Brasil a enviar uma divisão para a Guerra da Coreia.",
      "transferia ao Pentágono a formação dos oficiais brasileiros, extinguindo as escolas militares nacionais.",
      "proibia o Brasil de comerciar com qualquer país que mantivesse relações com a União Soviética.",
    ],
    "O acordo garantia equipamento e treinamento em troca de matérias-primas de interesse militar, entre elas minerais usados na indústria nuclear. Para os nacionalistas, era entregar recurso estratégico a preço baixo e prender o país à estratégia norte-americana. A polêmica custou o cargo ao ministro da Guerra, Estillac Leal, e mostra as ambiguidades de Vargas: o mesmo governo que criou a Petrobras assinou o acordo.",
    "Vargas nacionalista em casa, pragmático com Washington."),
  v("var-42", "dificil", "Unesp", "Em 1951, os Estados Unidos solicitaram ao Brasil o envio de tropas para a Guerra da Coreia. A resposta do governo Vargas foi:",
    [
      "não enviar soldados, usando a negociação para tentar obter ajuda econômica e equipamento.",
      "enviar um contingente simbólico de médicos e enfermeiros, sob comando das Nações Unidas.",
      "recusar de imediato e romper o TIAR, por considerar a guerra uma agressão imperialista.",
      "condicionar o envio à entrada da China comunista na ONU.",
      "aceitar o pedido, mas ser impedido pelo Congresso, onde a UDN, isolacionista, vetou o crédito necessário.",
    ],
    "Vargas não disse um \"não\" seco: enviou Góis Monteiro a Washington e arrastou a conversa, tentando repetir a barganha da Segunda Guerra, quando a adesão aos Aliados rendeu Volta Redonda. Desta vez os Estados Unidos tinham menos a oferecer à América Latina, e nenhum soldado brasileiro embarcou. O resultado concreto da negociação foi o Acordo Militar de 1952.",
    "A barganha de 1942 não funcionou em 1951."),
  v("var-43", "dificil", "UFPR", "Na Carta-Testamento, Vargas escreve que \"a Eletrobrás foi obstaculada até o desespero\". O destino do projeto confirma a queixa, pois a empresa:",
    [
      "foi proposta em 1954, mas só teve sua criação aprovada em 1961.",
      "foi criada em 1953, junto com a Petrobras, e privatizada por Café Filho.",
      "nunca saiu do papel: o setor elétrico só passou ao Estado em 1968.",
      "foi rejeitada em plebiscito convocado pela UDN.",
    ],
    "O projeto ficou sete anos no Congresso, combatido pelas concessionárias estrangeiras de energia (como a Light e a Amforp) e por parlamentares contrários à expansão do Estado. A lei foi sancionada em 1961 e a empresa instalada em 1962, no governo João Goulart. O contraste com a Petrobras, aprovada em 1953, mostra que o nacionalismo varguista teve limites impostos pelo Legislativo.",
    "Petrobras passou em 1953; Eletrobrás esperou até 1961."),
  v("var-44", "dificil", "Unicamp", "As eleições para a diretoria do Clube Militar funcionavam, nos anos 1950, como termômetro da política nas Forças Armadas. Entre 1950 e 1952, elas indicaram:",
    [
      "a derrota da chapa nacionalista, vencedora em 1950, para a Cruzada Democrática, antigetulista e pró-Estados Unidos.",
      "o crescimento contínuo dos nacionalistas, que controlaram a entidade até 1964.",
      "a vitória, nos dois pleitos, de oficiais ligados ao PCB, o que levou Vargas a determinar o fechamento do Clube Militar.",
      "a neutralidade dos oficiais, que proibiram debates políticos na entidade.",
      "o predomínio de chapas únicas, negociadas pelo ministro da Guerra para evitar divisões.",
    ],
    "Em 1950 venceu a chapa de Estillac Leal e Horta Barbosa, ligada à campanha do petróleo; Estillac virou ministro da Guerra de Vargas. Em 1952, depois da polêmica sobre a Coreia e o Acordo Militar, ganhou a Cruzada Democrática. A virada antecipa o Manifesto dos Coronéis e o ultimato de 1954: Vargas perdia o Exército dois anos antes de perder o governo.",
    "1950 nacionalistas · 1952 Cruzada Democrática."),
  v("var-45", "dificil", "Fuvest", "O primeiro ministério de Vargas, em 1951, ficou conhecido como \"ministério da experiência\". A reforma ministerial de meados de 1953 alterou esse quadro ao:",
    [
      "levar João Goulart ao Trabalho e Osvaldo Aranha à Fazenda.",
      "entregar todas as pastas ao PTB, rompendo a aliança com o PSD e com os setores conservadores.",
      "nomear Carlos Lacerda para a Justiça, numa tentativa de conciliação com a UDN.",
      "substituir os ministros civis por generais.",
    ],
    "O gabinete de 1951 era conservador, dominado pelo PSD e com um udenista na Agricultura. Depois da greve dos 300 mil e com a inflação em alta, Vargas mudou a equipe: Jango deveria reconquistar os trabalhadores, Aranha deveria conter preços e reorganizar o câmbio. As duas tarefas se chocaram em 1954, quando Jango propôs dobrar o salário mínimo.",
    "1953: Jango para os sindicatos, Aranha para a inflação."),
  v("var-46", "dificil", "UERJ", "Fundado em 1951 por Samuel Wainer, o jornal Última Hora tornou-se alvo de uma CPI em 1953. A oposição o acusava de:",
    [
      "ter sido montado com empréstimos favorecidos do Banco do Brasil para servir de voz ao governo.",
      "ser financiado secretamente pela embaixada soviética.",
      "publicar documentos sigilosos das Forças Armadas sobre o Acordo Militar com os Estados Unidos.",
      "pertencer, por meio de testas de ferro, ao grupo norte-americano Time-Life, o que a Constituição vedava.",
      "incitar a greve geral contra o ministro Osvaldo Aranha.",
    ],
    "Quase toda a grande imprensa era antigetulista; a Última Hora nasceu para romper esse cerco, com linguagem popular e inovações gráficas. Lacerda, na Tribuna da Imprensa, fez da campanha contra Wainer um ensaio da ofensiva de 1954, explorando inclusive a dúvida sobre a nacionalidade do jornalista. O caso Time-Life é outro e envolveu a TV Globo nos anos 1960.",
    "Última Hora: o único grande jornal do lado de Vargas."),
  v("var-51", "desafio", "Unicamp", "Considere as afirmativas sobre a política econômica do segundo governo Vargas.\nI. A Assessoria Econômica da Presidência, chefiada por Rômulo Almeida, preparou projetos como os da Petrobras e da Eletrobrás.\nII. A Comissão Mista Brasil–Estados Unidos foi encerrada em 1953, e o financiamento norte-americano efetivamente liberado ficou muito abaixo do esperado.\nIII. A Instrução 70 da SUMOC unificou o câmbio numa taxa única, definida livremente pelo mercado.\nEstá correto o que se afirma em:",
    [I_II, II_III, I_III, SO_I, TODAS],
    "A Instrução 70 fez o contrário: criou taxas múltiplas, com leilões de câmbio por categoria de importação, encarecendo os supérfluos e barateando o essencial. A Assessoria era o núcleo nacionalista do governo; a Comissão Mista, o canal de cooperação com Washington. Com a posse de Eisenhower, em 1953, esse canal se fechou, o que empurrou Vargas para um discurso mais nacionalista.",
    "Assessoria (nacionalista) e Comissão Mista (cooperação): as duas pernas de Vargas."),
  v("var-52", "desafio", "Fuvest", "Em junho de 1954, a UDN levou à Câmara dos Deputados um pedido de impeachment de Getúlio Vargas. O desfecho da votação e seu significado político foram:",
    [
      "a rejeição por larga maioria, mostrando que a oposição não tinha votos e dependeria dos quartéis para afastar o presidente.",
      "a aprovação na Câmara e a rejeição no Senado, o que manteve Vargas no cargo, mas o deixou sem base parlamentar até o fim do mandato.",
      "a aprovação nas duas casas, suspensa por liminar do Supremo Tribunal Federal.",
      "o arquivamento sem votação, por acordo entre UDN e PSD para preservar as eleições de outubro.",
      "um empate, desfeito a favor de Vargas pelo voto do presidente da Câmara.",
    ],
    "O pedido foi derrotado por 136 votos a 35: PSD e PTB tinham maioria folgada. A UDN perdia nas urnas (1945, 1950) e no Congresso; restava-lhe a pregação de Lacerda e a pressão sobre os militares. É esse o sentido da expressão \"vivandeiras de quartel\", usada mais tarde para os civis que rondavam os generais pedindo intervenção.",
    "Sem voto na urna nem no plenário, a UDN bateu à porta dos quartéis."),
  v("var-53", "desafio", "Unesp", "Em fevereiro de 1954, pressionado pelo Manifesto dos Coronéis, Vargas afastou João Goulart do Ministério do Trabalho. Quanto ao aumento de 100% do salário mínimo, proposto pelo ministro demitido, o presidente:",
    [
      "decretou-o integralmente em 1º de maio de 1954.",
      "arquivou-o, atendendo aos militares e aos industriais paulistas.",
      "reduziu-o à metade, por sugestão de Osvaldo Aranha.",
      "transferiu a decisão ao Congresso, que o rejeitou.",
    ],
    "Vargas cedeu a cabeça do ministro, mas não a medida. No discurso do Dia do Trabalho, anunciou o aumento e disse aos trabalhadores: \"hoje estais com o governo; amanhã sereis o governo\". O gesto contrariava o plano de estabilização de Aranha e irritou empresários e oficiais, que viram nele a confirmação de uma guinada à esquerda.",
    "Caiu Jango, ficou o aumento."),
  v("var-54", "desafio", "UFRGS", "Criado em 1951 e presidido pelo almirante Álvaro Alberto, o Conselho Nacional de Pesquisas (CNPq) esteve no centro da política nuclear do período. A tese das \"compensações específicas\", defendida pelo almirante, sustentava que o Brasil:",
    [
      "só deveria exportar minerais atômicos em troca de tecnologia e equipamentos nucleares.",
      "deveria renunciar à energia nuclear em troca de garantias de defesa dos Estados Unidos.",
      "precisava vender tório e urânio a qualquer comprador, inclusive à União Soviética, para financiar a indústria de base.",
      "deveria entregar a pesquisa nuclear a empresas privadas nacionais.",
      "só poderia desenvolver armas atômicas em conjunto com a Argentina de Perón.",
    ],
    "A ideia era não repetir, com o tório e o urânio, a exportação de matéria-prima bruta. Os Estados Unidos queriam os minerais, mas não a transferência de tecnologia. Álvaro Alberto buscou alternativas na Alemanha e na França; ultracentrífugas encomendadas a cientistas alemães foram apreendidas antes do embarque, e o almirante acabou afastado em 1955, já no governo Café Filho.",
    "Minério só em troca de tecnologia."),
  v("var-55", "desafio", "UFPR", "Na eleição de 1950, Vargas concorreu pelo PTB tendo como vice o potiguar Café Filho. A escolha do vice explica-se:",
    [
      "pelo acordo com Adhemar de Barros, cujo partido, o PSP, exigiu a vaga em troca do apoio em São Paulo.",
      "pela aliança formal com a UDN, que indicou Café Filho como garantia de moderação do futuro governo trabalhista.",
      "pela pressão da Igreja Católica, de quem Café Filho era o candidato preferido.",
      "pela exigência do Exército de ter um militar de carreira na linha sucessória.",
    ],
    "Sem São Paulo não se ganhava a eleição, e São Paulo era de Adhemar. Café Filho, de passado oposicionista ao Estado Novo e fama de esquerdista, chegou a ser vetado pela Liga Eleitoral Católica. A ironia veio em 1954: o vice imposto pela aliança populista montou, ao assumir, um governo próximo dos adversários de Vargas.",
    "O vice veio de Adhemar, e acabou governando com a UDN."),
  v("var-56", "desafio", "Fuvest", "A política de Vargas para o capital estrangeiro, entre 1951 e 1954, é mais bem descrita como:",
    [
      "ambígua: monopólio estatal em setores estratégicos e busca de capital externo.",
      "de ruptura: estatização das empresas estrangeiras e moratória da dívida externa.",
      "de abertura irrestrita, com isenções e garantias que anteciparam em tudo a política de JK.",
      "de indiferença, pois o governo considerava o tema secundário diante do problema agrário.",
      "de alinhamento ao FMI, com câmbio livre e fim de qualquer controle sobre remessas.",
    ],
    "O governo negociou com os Estados Unidos na Comissão Mista, criou o BNDE para aplicar recursos externos e assinou o Acordo Militar; ao mesmo tempo, criou a Petrobras, propôs a Eletrobrás e limitou por decreto as remessas de lucros. O tom nacionalista cresceu a partir de 1953, quando o financiamento norte-americano minguou. Por isso é enganoso opor um Vargas \"contra\" a um JK \"a favor\" do capital estrangeiro sem matizes.",
    "Vargas queria o dólar, mas não abria mão do comando."),

  // ───────── JK ─────────
  k("jk-41", "dificil", "Fuvest", "As revoltas de Jacareacanga (1956) e Aragarças (1959) foram levantes de oficiais, sobretudo da Aeronáutica, contra o governo JK. A resposta do presidente aos dois episódios foi:",
    [
      "sufocar os movimentos e, em seguida, anistiar os envolvidos.",
      "decretar estado de sítio até o fim do mandato e fechar o Clube da Aeronáutica.",
      "expulsar os rebeldes das Forças Armadas e cassar os mandatos dos deputados da UDN que os apoiaram.",
      "negociar a entrada da UDN no ministério em troca da rendição.",
      "renunciar ao projeto de Brasília, apontado pelos rebeldes como causa da inflação.",
    ],
    "Os levantes, pequenos e isolados em bases do interior, eram herdeiros do antigetulismo militar de 1954–55. JK preferiu a conciliação à punição exemplar, estilo que marcou seu governo e ajudou a mantê-lo até o fim. Vários dos anistiados, porém, voltariam à cena na conspiração de 1964.",
    "JK anistiava; os anistiados não esqueceram."),
  k("jk-42", "dificil", "Unicamp", "As Ligas Camponesas ganharam projeção nacional na segunda metade dos anos 1950, a partir do Engenho Galileia, em Pernambuco. Sobre esse movimento, é correto afirmar que:",
    [
      "nasceu de uma associação de foreiros ameaçados de expulsão e passou a pedir reforma agrária.",
      "foi criado pelo Ministério do Trabalho para estender ao campo a estrutura sindical oficial das cidades.",
      "reunia pequenos proprietários do Sul contrários à política de preços mínimos do governo.",
      "defendia a luta armada desde a fundação e foi posto na ilegalidade por JK em 1957.",
      "surgiu após o golpe de 1964, como reação à repressão no campo.",
    ],
    "A sociedade dos foreiros do Galileia (1955) começou com objetivos modestos, como pagar enterros e escolas; a tentativa de despejo a politizou. Em 1959 o engenho foi desapropriado pelo governo estadual. O movimento expunha o que o Plano de Metas deixara de fora: o trabalhador rural não tinha nem os direitos da CLT nem acesso à terra.",
    "Enquanto Brasília subia, o campo continuava no século XIX."),
  k("jk-43", "dificil", "UERJ", "Os operários que ergueram Brasília, os candangos, vieram principalmente do Nordeste, de Goiás e de Minas. Inaugurada a capital, a maioria deles:",
    [
      "foi fixada em cidades-satélites afastadas do Plano Piloto, reservado sobretudo ao funcionalismo.",
      "recebeu apartamentos nas superquadras, como previa o projeto original de Lúcio Costa para a nova capital.",
      "foi obrigada por lei a retornar aos estados de origem.",
      "foi incorporada ao serviço público federal, com estabilidade garantida pela Novacap.",
    ],
    "Taguatinga, criada ainda em 1958 para remover uma ocupação, inaugurou o padrão: quem construiu a cidade modernista foi morar longe dela. A capital planejada para superar as desigualdades das cidades brasileiras reproduziu, no próprio desenho, a separação entre centro e periferia.",
    "Plano Piloto para o funcionário, satélite para o candango."),
  k("jk-44", "dificil", "Unesp", "A peça Eles não usam black-tie, de Gianfrancesco Guarnieri, estreou em 1958 no Teatro de Arena, em São Paulo. Ela é representativa de uma vertente da cultura dos anos JK porque:",
    [
      "pôs em cena operários e uma greve, tratando de forma crítica os conflitos da sociedade que se industrializava.",
      "celebrava sem reservas o Plano de Metas, tendo sido encomendada pelo governo.",
      "retomava o regionalismo rural dos anos 1930, ignorando a vida nas cidades.",
      "adaptava comédias norte-americanas para o público de classe média, como fazia todo o teatro paulista daquela época.",
      "foi proibida pela censura de JK, o que a transformou em símbolo da resistência.",
    ],
    "Ao lado do otimismo da bossa nova e da arquitetura de Brasília, o período viu nascer uma arte que perguntava quem pagava a conta do desenvolvimento: o Arena, o Cinema Novo (Rio, 40 Graus é de 1955) e, pouco depois, os Centros Populares de Cultura. O clima de liberdade do governo JK permitiu as duas coisas ao mesmo tempo.",
    "Os anos dourados também tiveram arte de fábrica e de morro."),
  k("jk-45", "dificil", "Fuvest", "O Plano de Metas apoiou-se em estudos do Grupo Misto BNDE–CEPAL, coordenado por Celso Furtado. Da CEPAL vinha a tese de que os países latino-americanos deveriam industrializar-se porque:",
    [
      "os preços dos produtos primários que exportavam tendiam a cair em relação aos dos manufaturados que importavam.",
      "a agricultura era incompatível com o clima tropical e fadada ao esgotamento dos solos.",
      "a indústria dispensava capital estrangeiro, ao contrário das atividades agrícolas e minerais voltadas à exportação.",
      "o livre-comércio garantiria, por si só, a transferência de tecnologia dos países centrais para os da periferia.",
      "a industrialização permitiria reduzir o papel do Estado na economia.",
    ],
    "É a tese da deterioração dos termos de troca, formulada por Raúl Prebisch: quem vende café e compra máquinas precisa exportar cada vez mais para importar o mesmo. A saída seria substituir importações com planejamento e forte ação do Estado. Essa visão contrariava a teoria das vantagens comparativas, defendida no Brasil por economistas como Eugênio Gudin.",
    "CEPAL: exportar só matéria-prima é empobrecer devagar."),
  k("jk-46", "dificil", "UFRGS", "Enquanto a descolonização avançava na África e na Ásia, a diplomacia do governo JK, nas Nações Unidas, tendeu a:",
    [
      "apoiar as posições de Portugal, com quem o Brasil mantinha um tratado de amizade e consulta.",
      "liderar o bloco afro-asiático, tendo o Brasil participado como membro pleno da Conferência de Bandung.",
      "defender a independência imediata de Angola e Moçambique, rompendo relações com o governo de Salazar.",
      "abster-se de qualquer votação sobre temas coloniais.",
    ],
    "O alinhamento ao Ocidente e os laços com Lisboa pesaram mais que a solidariedade com os novos países. A Operação Pan-Americana mostrava ambição de autonomia, mas voltada às Américas. A mudança só viria com a política externa independente de Jânio e Jango, e mesmo ela hesitou diante das colônias portuguesas.",
    "JK inovou com a OPA, mas na questão colonial ficou com Portugal."),
  k("jk-51", "desafio", "Unicamp", "Considere as afirmativas sobre a crise sucessória de 1955.\nI. Derrotada nas urnas, a UDN voltou a sustentar que só poderia tomar posse o candidato com maioria absoluta dos votos.\nII. A chamada Carta Brandi, divulgada por Carlos Lacerda, atribuía a João Goulart tratativas com peronistas para armar milícias operárias; um inquérito do Exército concluiu que era falsa.\nIII. Recuperado de um problema cardíaco, Café Filho tentou reassumir a Presidência, mas foi declarado impedido pelo Congresso.\nEstá correto o que se afirma em:",
    [TODAS, I_II, I_III, II_III, SO_I],
    "As três estão corretas. JK venceu com cerca de 36% dos votos, e a tese da maioria absoluta, sem amparo na Constituição, já havia sido usada contra Vargas em 1950. A Carta Brandi tentava colar em Jango o rótulo de \"república sindicalista\". Depois do movimento de 11 de novembro, o Congresso afastou Carlos Luz e Café Filho, e Nereu Ramos governou sob estado de sítio até a posse.",
    "1955: tese jurídica, carta falsa e dois presidentes afastados."),
  k("jk-52", "desafio", "Fuvest", "O movimento de 11 de novembro de 1955, liderado pelo general Lott, foi chamado por seus autores de \"retorno aos quadros constitucionais vigentes\" e, por historiadores, de \"golpe preventivo\". O paradoxo que essas expressões registram é o de que:",
    [
      "a posse dos eleitos foi garantida por uma intervenção militar que depôs o presidente em exercício.",
      "o Exército tomou o poder para si e só o devolveu aos civis cinco anos depois.",
      "a intervenção foi feita a pedido da UDN, para impedir a posse de um candidato acusado de fraude eleitoral.",
      "os militares agiram para anular a eleição e convocar outra, sob novas regras.",
      "o movimento, embora vitorioso, foi anulado pelo Supremo, que restituiu o cargo a Carlos Luz.",
    ],
    "Lott agiu contra a própria hierarquia para deter a conspiração que pretendia impedir a posse de JK e Jango. A legalidade saiu preservada, mas por meio das armas, o que reforçou o papel do Exército como árbitro da política. Em 1961, na crise da posse de Jango, os ministros militares tentariam usar esse poder no sentido oposto.",
    "Em 1955 a espada garantiu o voto; o precedente ficou."),
  k("jk-53", "desafio", "Unesp", "O Plano de Metas exigiu um volume de investimentos muito superior à poupança disponível. Entre as formas de financiamento efetivamente utilizadas, NÃO se encontra:",
    [
      "uma reforma tributária que elevou a taxação sobre as grandes rendas e fortunas.",
      "a emissão de moeda para cobrir o déficit do governo.",
      "a entrada de máquinas e equipamentos como investimento direto estrangeiro, sem cobertura cambial.",
      "o endividamento externo de curto prazo, em boa parte com fornecedores.",
      "o uso de fundos vinculados e de recursos do BNDE para energia e transportes.",
    ],
    "JK evitou o confronto com o Congresso e com as elites que uma reforma tributária traria. Financiou o plano pelo caminho de menor resistência política: inflação (que funciona como imposto disfarçado sobre os assalariados), capital estrangeiro pela Instrução 113 e dívida de prazo curto. A fatura chegou nos governos seguintes.",
    "Cinquenta anos em cinco, pagos com inflação e dívida."),
  k("jk-54", "desafio", "UFPR", "O relatório do GTDN (1959), redigido sob a direção de Celso Furtado e base da criação da Sudene, rompeu com a visão tradicional do \"problema do Nordeste\" ao sustentar que:",
    [
      "a pobreza da região vinha de sua estrutura econômica e agrária, e não da seca em si.",
      "a única solução era a transferência da população sertaneja para a Amazônia.",
      "o atraso nordestino decorria da falta de açudes, a ser resolvida ampliando as obras do DNOCS.",
      "a região deveria especializar-se na exportação de açúcar e algodão, onde tinha vantagens naturais.",
      "a industrialização do Centro-Sul beneficiava o Nordeste, dispensando políticas regionais.",
    ],
    "A política anterior, \"hidráulica\", construía açudes que muitas vezes valorizavam terras de grandes proprietários: a chamada indústria da seca. Furtado mostrou que a industrialização concentrada no Centro-Sul agravava a desigualdade, pois o Nordeste comprava caro dali e vendia barato para fora. Daí a proposta de industrializar a região e reorganizar a agricultura, que enfrentou a resistência das oligarquias locais.",
    "O problema não é a seca: é a cerca."),
  k("jk-55", "desafio", "UERJ", "Críticos de JK, como o economista Eugênio Gudin e a UDN, trataram Brasília como um capricho pessoal do presidente. Do ponto de vista jurídico, porém, a transferência da capital para o Planalto Central:",
    [
      "estava prevista desde a Constituição de 1891 e fora mantida na de 1946.",
      "foi autorizada por plebiscito realizado junto com a eleição de 1955.",
      "contrariava a Constituição de 1946, que fixava o Rio de Janeiro como sede definitiva do governo.",
      "dependeu de emenda constitucional aprovada em 1959, sob forte obstrução.",
    ],
    "A primeira Carta republicana já reservava uma área no Planalto para a futura capital, e a Missão Cruls a demarcou nos anos 1890. JK não inventou a ideia: deu-lhe prazo, dinheiro e sentido político, como símbolo da interiorização e do próprio governo. A UDN chegou a pedir uma CPI sobre as contas da Novacap, estatal que tocava a obra.",
    "A ideia era de 1891; a pressa era de JK."),
  k("jk-56", "desafio", "Fuvest", "Costuma-se distinguir o nacional-desenvolvimentismo do segundo governo Vargas do desenvolvimentismo do governo JK. A diferença essencial está em que JK:",
    [
      "manteve a meta da industrialização, mas aceitou a liderança de multinacionais nos setores mais dinâmicos.",
      "abandonou a meta da industrialização em favor da modernização da agricultura de exportação.",
      "estatizou a indústria de bens duráveis, que Vargas havia deixado para a iniciativa privada.",
      "substituiu o planejamento estatal pelo livre jogo do mercado.",
      "rompeu com o capital estrangeiro depois do conflito com o FMI, voltando ao modelo varguista de empresas estatais.",
    ],
    "Fala-se por isso em desenvolvimento \"associado\": o Estado planeja e cuida da infraestrutura, o capital nacional fica com os setores tradicionais e as multinacionais assumem automóveis, eletrodomésticos e química. O nacionalismo passa a se medir pelo resultado (ter fábricas no país), e não por quem é o dono delas. O rompimento com o FMI, em 1959, foi um gesto político que não alterou esse desenho.",
    "Vargas: indústria nossa. JK: indústria aqui."),
];
