import type { Questao } from "@/lib/tipos";
import { criar } from "../criar";

const c = criar("descolonizacao");
const m = criar("maio68");
const p = criar("figuras");

const I_II = "Apenas I e II.";
const I_III = "Apenas I e III.";
const II_III = "Apenas II e III.";
const SO_I = "Apenas I.";
const SO_II = "Apenas II.";
const TODAS = "I, II e III.";

/** Segunda leva de Descolonização, Maio de 1968 e Figuras: níveis difícil e desafio. A primeira alternativa é a correta. */
export const novasMundo2: Questao[] = [
  // ───────── Descolonização ─────────
  c("des-41", "dificil", "Fuvest", "A Carta do Atlântico (1941), assinada por Roosevelt e Churchill, afirmava o direito de todos os povos de escolher a forma de governo sob a qual viveriam. Para os movimentos nacionalistas da Ásia e da África, o documento:",
    [
      "serviu de argumento contra as metrópoles, embora Churchill quisesse limitá-lo à Europa ocupada.",
      "foi irrelevante, pois só se tornou público depois de encerrada a guerra.",
      "representou uma derrota, já que garantia expressamente a manutenção dos impérios coloniais britânico e francês.",
      "fixou um calendário de independências, que as metrópoles cumpriram entre 1945 e 1950.",
      "criou a ONU e seu Conselho de Tutela, encarregado de administrar as colônias.",
    ],
    "A contradição era evidente: lutar contra a dominação de Hitler em nome da liberdade e manter centenas de milhões de pessoas sob domínio colonial. Líderes nacionalistas citaram a Carta contra seus próprios autores. Roosevelt, ao contrário de Churchill, entendia que o princípio era universal, e a posição norte-americana pesou no pós-guerra.",
    "Liberdade para a Europa e não para as colônias? A conta não fechava."),
  c("des-42", "dificil", "Unicamp", "Em 8 de maio de 1945, enquanto a Europa comemorava a rendição da Alemanha, a cidade argelina de Sétif foi palco de um acontecimento que muitos historiadores consideram o prenúncio da guerra de independência. Tratou-se:",
    [
      "da repressão a manifestantes nacionalistas, seguida de represálias francesas que deixaram milhares de argelinos mortos.",
      "da proclamação da República Argelina pela Frente de Libertação Nacional.",
      "do desembarque de tropas norte-americanas em apoio aos nacionalistas.",
      "de uma revolta dos colonos europeus contra o governo de Paris.",
      "da assinatura do acordo que concedeu cidadania francesa plena a todos os muçulmanos.",
    ],
    "Argelinos que haviam lutado no exército francês contra o nazismo saíram às ruas com bandeiras nacionalistas no dia da vitória. A repressão e as represálias que se seguiram, com uso de aviação e marinha, convenceram uma geração de que a via pacífica estava fechada. A FLN só surgiria em 1954, ano em que a guerra começou.",
    "No dia da vitória contra Hitler, a França atirou em Sétif."),
  c("des-43", "dificil", "UERJ", "Em março de 1960, na localidade sul-africana de Sharpeville, a polícia abriu fogo contra uma multidão que protestava contra a lei do passe, matando dezenas de pessoas. Uma consequência direta do massacre foi:",
    [
      "a proibição das organizações negras, o que levou parte de seus dirigentes a optar pela luta armada.",
      "a revogação imediata das leis do apartheid, sob pressão internacional.",
      "a libertação de Nelson Mandela, preso desde 1948.",
      "a independência dos bantustões, reconhecida pela ONU.",
      "a intervenção militar britânica, que afastou o Partido Nacional do governo e convocou eleições multirraciais.",
    ],
    "A lei do passe obrigava os negros a portar um documento para circular nas áreas reservadas aos brancos. Depois de Sharpeville, o governo decretou estado de emergência e baniu o Congresso Nacional Africano e o Congresso Pan-Africanista. Mandela, até então defensor da resistência não violenta, ajudou a criar em 1961 o braço armado do CNA, a \"Lança da Nação\". Foi preso em 1962.",
    "Sharpeville fechou a via pacífica na África do Sul."),
  c("des-44", "dificil", "Unesp", "\"Os ventos da mudança estão soprando por este continente.\" A frase foi dita em 1960, na Cidade do Cabo, pelo primeiro-ministro britânico Harold Macmillan. Ela sinalizava que o Reino Unido:",
    [
      "aceitava a independência de suas colônias africanas como fato inevitável.",
      "apoiaria o apartheid como barreira contra o comunismo.",
      "pretendia unir suas colônias africanas numa federação governada de Londres.",
      "enviaria tropas para conter os movimentos nacionalistas.",
      "transferiria seus territórios africanos à administração dos Estados Unidos.",
    ],
    "O discurso foi feito diante do parlamento sul-africano, dominado pelos defensores do apartheid, e incluía uma crítica a essa política. Depois da humilhação de Suez (1956) e da independência de Gana (1957), Londres preferiu negociar a saída a travar guerras caras como a da França na Argélia. A África do Sul respondeu deixando a Comunidade Britânica em 1961.",
    "Londres leu o vento; Paris e Lisboa demoraram mais."),
  c("des-45", "dificil", "UFPR", "Em 1958, De Gaulle submeteu às colônias francesas da África subsaariana um referendo: permanecer associadas à França numa \"Comunidade\" ou tornar-se independentes de imediato. O único território a votar pela independência imediata foi:",
    [
      "a Guiné, de Sékou Touré, que sofreu a retirada abrupta de técnicos e recursos franceses.",
      "o Senegal, de Léopold Senghor, que rompeu todos os laços com Paris.",
      "a Argélia, que por isso obteve a independência quatro anos antes do previsto nos planos franceses.",
      "a Costa do Marfim, cujo governo se aproximou da União Soviética.",
      "o Congo Belga, liderado por Patrice Lumumba.",
    ],
    "\"Preferimos a pobreza na liberdade à riqueza na escravidão\", teria dito Sékou Touré. A França saiu levando o que pôde, como aviso aos demais. A Guiné buscou então o apoio do bloco socialista. Em 1960, porém, as outras colônias francesas da região também se tornaram independentes, mantendo laços econômicos e militares com Paris. A Argélia estava fora dessa consulta, e o Congo era colônia belga.",
    "Guiné, 1958: o \"não\" que custou caro."),
  c("des-46", "dificil", "Fuvest", "O movimento da negritude, formulado nos anos 1930 por intelectuais como Aimé Césaire e Léopold Senghor, contribuiu para a descolonização principalmente ao:",
    [
      "valorizar a cultura e a história dos povos negros, contestando a ideia de superioridade europeia que justificava o colonialismo.",
      "organizar as primeiras guerrilhas contra a presença francesa na África Ocidental.",
      "defender a assimilação completa dos africanos à cultura francesa.",
      "propor a volta dos descendentes de africanos das Américas ao continente de origem.",
      "rejeitar qualquer contato com a literatura e a língua do colonizador.",
    ],
    "A negritude nasceu em Paris, entre estudantes das Antilhas e da África, e se expressou sobretudo em poesia, escrita em francês. Era uma resposta à política de assimilação, que oferecia ao colonizado tornar-se \"francês\" ao preço de renegar suas origens. Senghor seria o primeiro presidente do Senegal. Críticos como Frantz Fanon consideravam o movimento insuficiente por permanecer no plano cultural.",
    "Antes de expulsar o colonizador da terra, tirá-lo da cabeça."),
  c("des-51", "desafio", "Unicamp", "Considere as afirmativas sobre a guerra da Argélia (1954–1962).\nI. A Argélia era juridicamente parte da França e abrigava cerca de um milhão de colonos de origem europeia, o que tornava a retirada muito mais difícil que em outras colônias.\nII. Na chamada Batalha de Argel, o exército francês recorreu de forma sistemática à tortura, o que provocou intenso debate na metrópole.\nIII. Os Acordos de Évian abriram caminho à independência, seguida da saída em massa dos colonos europeus.\nEstá correto o que se afirma em:",
    [TODAS, I_II, I_III, II_III, SO_I],
    "As três estão corretas. Por ser colônia de povoamento, organizada em departamentos, a Argélia era vista como território nacional: \"a Argélia é a França\". A guerra derrubou a Quarta República, trouxe De Gaulle de volta ao poder e terminou, apesar do terrorismo da OAS, com a independência em 1962. Os colonos, os pieds-noirs, partiram quase todos em poucos meses.",
    "Colônia de povoamento: mais difícil de largar."),
  c("des-52", "desafio", "Fuvest", "Entre 1967 e 1970, a região oriental da Nigéria tentou separar-se sob o nome de Biafra. A guerra, lembrada pelas imagens de crianças famintas, ilustra um dilema dos novos Estados africanos, pois:",
    [
      "a maioria deles apoiou a Nigéria, por temer o efeito de uma secessão sobre outras fronteiras.",
      "a Organização da Unidade Africana reconheceu Biafra, em nome da autodeterminação dos povos.",
      "o conflito opôs diretamente tropas dos Estados Unidos e da União Soviética.",
      "a secessão era estimulada pela antiga metrópole, a Bélgica, interessada em controlar as minas de cobre da região.",
      "a região separatista era a mais pobre do país e dependia do governo central.",
    ],
    "As fronteiras traçadas pelos colonizadores reuniam povos distintos, mas mexer em uma era abrir a porta para rediscutir todas; daí o princípio da intangibilidade, adotado em 1963. Em Biafra, de maioria ibo, estavam as jazidas de petróleo, o que explica tanto a tentativa de separação quanto a determinação do governo em impedi-la. O bloqueio provocou uma fome que matou centenas de milhares de pessoas.",
    "Fronteira colonial ruim, mas mexer nela era pior."),
  c("des-53", "desafio", "UERJ", "Em 1965, a Rodésia do Sul proclamou unilateralmente sua independência do Reino Unido. O caso foge ao padrão da descolonização africana porque:",
    [
      "a independência foi declarada pela minoria branca, justamente para evitar um governo da maioria negra.",
      "foi a única independência africana obtida por meio de plebiscito organizado pela ONU.",
      "o movimento era dirigido por uma guerrilha marxista apoiada pela China.",
      "o Reino Unido reconheceu o novo Estado no mesmo dia, sem negociação.",
      "o país pediu, em seguida, sua anexação pela África do Sul.",
    ],
    "Londres só aceitava conceder a independência com garantia de governo da maioria; os colonos, liderados por Ian Smith, anteciparam-se. O regime não foi reconhecido, sofreu sanções internacionais e enfrentou uma longa guerra de guerrilhas. Em 1980, após negociações, o país tornou-se o Zimbábue, sob governo de maioria negra.",
    "Rodésia: \"independência\" para manter o privilégio."),
  c("des-54", "desafio", "Unesp", "Em junho de 1976, estudantes do bairro negro de Soweto, em Joanesburgo, saíram às ruas e foram recebidos a tiros pela polícia. O estopim do protesto foi:",
    [
      "a imposição do africâner, identificado com o opressor, como língua de ensino nas escolas para negros.",
      "a prisão de Nelson Mandela, ocorrida na semana anterior.",
      "o aumento das passagens de ônibus e trens que ligavam o bairro às fábricas e ao centro de Joanesburgo, decretado dias antes.",
      "a remoção forçada dos moradores para um bantustão.",
      "a proibição do casamento entre pessoas de grupos raciais diferentes, aprovada naquele ano pelo parlamento.",
    ],
    "A geração de 1976 havia sido formada pelo movimento da Consciência Negra, de Steve Biko, que pregava o orgulho e a autonomia dos negros; Biko morreria no ano seguinte, sob custódia policial. A repressão em Soweto, com centenas de mortos, isolou ainda mais o regime, fortaleceu as campanhas de boicote e sanções e levou muitos jovens a deixar o país para ingressar na luta armada.",
    "Sharpeville (1960), Soweto (1976): dois massacres, dois pontos de virada."),
  c("des-55", "desafio", "UFRGS", "O ano de 1948, quando o Partido Nacional venceu as eleições na África do Sul, é tomado como marco inicial do apartheid. A afirmação precisa, porém, de uma ressalva, pois:",
    [
      "a segregação já existia em leis anteriores; o que 1948 inaugura é sua sistematização em todas as esferas da vida.",
      "o apartheid só foi posto em prática depois de 1961, quando o país deixou a Comunidade Britânica e se tornou uma república.",
      "até aquela data, negros e brancos tinham os mesmos direitos políticos.",
      "a segregação foi imposta pelo Reino Unido, e o Partido Nacional limitou-se a herdá-la.",
      "a vitória de 1948 resultou do voto da maioria negra, depois traída pelo partido.",
    ],
    "A lei de terras de 1913 e as leis do passe são anteriores. A partir de 1948, o governo dos africâneres classificou toda a população por raça, proibiu casamentos mistos, separou bairros, escolas, hospitais e praias e, mais tarde, criou os bantustões. A maioria negra não votava. O apartheid foi, assim, o endurecimento e a codificação de uma ordem racial já existente, na contramão do mundo do pós-guerra.",
    "1948 não inventou a segregação: transformou-a em sistema."),
  c("des-56", "desafio", "Fuvest", "A expressão \"Terceiro Mundo\" foi criada em 1952 pelo demógrafo francês Alfred Sauvy. A analogia que lhe deu origem foi com:",
    [
      "o Terceiro Estado da França de 1789: ignorado e explorado, mas desejoso de \"ser alguma coisa\".",
      "a Terceira Internacional, que reunia os partidos comunistas sob a direção de Moscou.",
      "a Terceira República francesa, responsável pela expansão colonial na África.",
      "o terceiro lugar desses países na produção industrial do planeta.",
      "a \"terceira via\" entre capitalismo e socialismo, defendida pela social-democracia europeia do pós-guerra.",
    ],
    "Sauvy parafraseava o panfleto do abade Sieyès sobre o Terceiro Estado às vésperas da Revolução Francesa. O termo designava os países que não pertenciam nem ao bloco capitalista desenvolvido nem ao bloco soviético, em sua maioria ex-colônias pobres. Só depois ganhou o sentido corrente de \"países subdesenvolvidos\". Bandung (1955) deu expressão política a essa ideia.",
    "Terceiro Mundo vem de Terceiro Estado, não de terceiro lugar."),

  // ───────── Maio de 1968 ─────────
  m("m68-41", "dificil", "Fuvest", "\"Somos todos judeus alemães\", gritaram os estudantes franceses nas ruas de Paris em maio de 1968. A palavra de ordem era uma resposta:",
    [
      "aos ataques dirigidos a Daniel Cohn-Bendit, líder estudantil de nacionalidade alemã, impedido de voltar à França.",
      "à decisão do governo de romper relações com Israel depois da Guerra dos Seis Dias.",
      "à presença de tropas francesas na Alemanha Ocidental.",
      "à proibição da entrada de estudantes estrangeiros na Sorbonne.",
      "à invasão da Tchecoslováquia pelas tropas do Pacto de Varsóvia.",
    ],
    "Filho de judeus alemães refugiados do nazismo, Cohn-Bendit, o \"Dany, o Vermelho\", era o rosto mais conhecido do movimento. Foi chamado de \"anarquista alemão\" pelo dirigente comunista Georges Marchais e alvo de insultos da direita; o governo aproveitou uma viagem sua para proibir-lhe o regresso. A frase resume o espírito do movimento: solidariedade acima de nacionalidade e desconfiança de todas as autoridades, inclusive as da esquerda tradicional.",
    "Atacado pela direita e pelo PCF: sinal de que 68 não cabia nos velhos rótulos."),
  m("m68-42", "dificil", "Unicamp", "A \"noite das barricadas\", de 10 para 11 de maio de 1968, no Quartier Latin, foi decisiva para a ampliação do movimento francês porque:",
    [
      "a violência da repressão comoveu a opinião pública e levou as centrais sindicais à greve geral.",
      "os estudantes tomaram o Palácio do Eliseu e obrigaram De Gaulle a deixar o país.",
      "o exército aderiu aos manifestantes, o que precipitou a queda do gabinete.",
      "o governo cedeu de imediato a todas as reivindicações, encerrando os protestos.",
      "o Partido Comunista assumiu a direção do movimento e o conduziu à luta armada contra a Quinta República.",
    ],
    "Rádios transmitiram ao vivo o assalto da polícia às barricadas. No dia 13, estudantes e trabalhadores desfilaram juntos em Paris; nos dias seguintes, as fábricas começaram a ser ocupadas, muitas vezes por iniciativa dos operários mais jovens e à frente dos próprios sindicatos. Uma revolta universitária tornava-se a maior greve da história da França.",
    "Das barricadas (dia 10) à greve geral (dia 13)."),
  m("m68-43", "dificil", "UERJ", "Publicado em 1967, A sociedade do espetáculo, de Guy Debord, circulou entre os estudantes de 1968. A tese central do livro é a de que, no capitalismo avançado:",
    [
      "as relações sociais passam a ser mediadas por imagens, e os indivíduos viram espectadores da própria vida.",
      "a televisão e o cinema são os principais instrumentos de emancipação dos trabalhadores.",
      "a classe operária deve conquistar o Estado por meio de um partido de vanguarda, disciplinado e centralizado, como o bolchevique.",
      "o consumo de massa eliminou a alienação descrita por Marx.",
      "a arte deve servir à propaganda dos partidos de esquerda.",
    ],
    "Debord era a principal figura da Internacional Situacionista, pequeno grupo que misturava marxismo heterodoxo e vanguarda artística. Sua crítica deslocava o alvo: o problema não era só a exploração na fábrica, mas o tédio, a passividade e a colonização do cotidiano pelo consumo. Muitos dos grafites de maio, com seu humor e sua recusa do \"métro, boulot, dodo\" (metrô, trabalho, cama), vêm dessa fonte.",
    "Em 68, a crítica foi da fábrica para a vida inteira."),
  m("m68-44", "dificil", "Unesp", "Em 29 de maio de 1968, no auge da crise, o presidente Charles de Gaulle desapareceu por algumas horas, sem informar nem mesmo o primeiro-ministro. Soube-se depois que ele havia viajado para:",
    [
      "Baden-Baden, na Alemanha, onde se reuniu com o comandante das tropas francesas ali estacionadas.",
      "Londres, de onde pretendia dirigir um governo no exílio, como em 1940.",
      "Moscou, para pedir a Brejnev que contivesse o Partido Comunista Francês.",
      "Argel, para negociar o retorno dos militares afastados em 1961.",
      "Washington, a fim de solicitar apoio militar da OTAN.",
    ],
    "O encontro com o general Massu é interpretado como busca de garantias de lealdade do exército ou como momento de hesitação pessoal; provavelmente foi as duas coisas. No dia seguinte, De Gaulle voltou, falou ao país pelo rádio, dissolveu a Assembleia e convocou eleições. Uma enorme manifestação de apoio tomou a avenida Champs-Élysées, e a maré virou.",
    "Dia 29, sumiço em Baden-Baden; dia 30, o contra-ataque."),
  m("m68-45", "dificil", "UFPR", "\"Sob o calçamento, a praia\", \"É proibido proibir\", \"A imaginação no poder\". Os lemas pintados nos muros de Paris em 1968 indicam que o movimento:",
    [
      "dava mais importância à libertação do cotidiano e do desejo do que a um programa de tomada do Estado.",
      "tinha um plano detalhado de governo, negociado previamente com os partidos de oposição e com as centrais sindicais.",
      "reivindicava sobretudo aumentos salariais e redução da jornada.",
      "defendia o retorno aos valores tradicionais contra a sociedade de consumo.",
      "seguia a orientação cultural do realismo socialista soviético.",
    ],
    "Os paralelepípedos arrancados para as barricadas deixavam à mostra a areia: daí a imagem da praia sob o calçamento, a vida possível sob a ordem. Os cartazes impressos em serigrafia por estudantes de Belas-Artes espalharam essa linguagem. Para os críticos, tanta ênfase na liberdade individual explica por que 1968 mudou os costumes, e não o poder.",
    "68 queria mudar a vida, não só o governo."),
  m("m68-46", "dificil", "UFRGS", "Na Alemanha Ocidental, o movimento estudantil viveu seu momento mais tenso em abril de 1968, quando o líder Rudi Dutschke foi baleado em Berlim. Os estudantes reagiram atacando sobretudo:",
    [
      "o grupo de imprensa Springer, cujos jornais vinham promovendo uma campanha de hostilidade contra o movimento.",
      "as bases militares soviéticas instaladas em Berlim Oriental.",
      "as sedes do Partido Social-Democrata, que estava na oposição.",
      "as fábricas de automóveis, cujos operários apoiavam o atentado.",
      "as igrejas protestantes, acusadas de colaborar com a polícia.",
    ],
    "Os estudantes alemães tinham motivos próprios: a presença de antigos nazistas em altos cargos, o silêncio da geração dos pais sobre o passado, as leis de emergência em votação e uma \"grande coalizão\" que deixava o parlamento quase sem oposição. O atentado contra Dutschke, cometido por um jovem de extrema direita, foi atribuído ao clima criado pelos tabloides. 1968 não foi só francês.",
    "Na Alemanha, 68 foi um acerto de contas com o silêncio dos pais."),
  m("m68-51", "desafio", "Unicamp", "Considere as afirmativas sobre o contexto do Maio de 1968 na França.\nI. O movimento eclodiu durante os \"Trinta Gloriosos\", período de crescimento econômico e baixo desemprego, e não em meio a uma depressão.\nII. O número de estudantes universitários havia mais que dobrado em uma década, sem que as estruturas da universidade se adaptassem.\nIII. A iniciativa e a direção dos protestos couberam ao Partido Comunista Francês, que controlava as entidades estudantis.\nEstá correto o que se afirma em:",
    [I_II, I_III, II_III, SO_II, TODAS],
    "O PCF foi surpreendido e, de início, hostil: tratou os líderes estudantis como aventureiros e trabalhou para canalizar a greve operária para reivindicações salariais. Os dois primeiros itens explicam a novidade de 1968: uma revolta nascida da prosperidade, de jovens numerosos, escolarizados e sem lugar numa sociedade de hierarquias rígidas, e não da miséria.",
    "68 nasceu da abundância, não da fome."),
  m("m68-52", "desafio", "Fuvest", "Em janeiro de 1969, o estudante tcheco Jan Palach ateou fogo ao próprio corpo no centro de Praga. Seu gesto era um protesto contra:",
    [
      "a resignação da sociedade diante da ocupação soviética e do desmonte das reformas da Primavera de Praga.",
      "as reformas liberalizantes de Alexander Dubček, que ele considerava uma traição aos princípios do socialismo.",
      "a adesão da Tchecoslováquia à OTAN.",
      "a Guerra do Vietnã, a exemplo do que haviam feito monges budistas em Saigon.",
      "a separação entre tchecos e eslovacos, decidida naquele mês.",
    ],
    "Cinco meses depois da invasão, a censura voltava e as conquistas de 1968 eram retiradas uma a uma, no processo que o regime chamou de \"normalização\". Palach quis sacudir os compatriotas. Seu funeral virou manifestação de massa; vinte anos mais tarde, a repressão a atos em sua memória ajudou a deflagrar o movimento que derrubou o regime, em 1989.",
    "Palach protestou contra a ocupação e contra o conformismo."),
  m("m68-53", "desafio", "UERJ", "Costuma-se dizer que 1968 foi um fenômeno mundial com alvos diferentes em cada região. Essa ideia está corretamente expressa em:",
    [
      "No Ocidente, o consumo e a guerra; no Leste, a tutela soviética; na América Latina, as ditaduras.",
      "Em toda parte os estudantes reivindicavam a mesma coisa: a adoção do modelo soviético.",
      "No Ocidente o movimento foi operário, e no Leste, exclusivamente religioso.",
      "Os protestos limitaram-se à Europa Ocidental e aos Estados Unidos, sem eco nos países socialistas ou no Terceiro Mundo.",
      "No Leste Europeu pedia-se a volta ao stalinismo, e na América Latina, a intervenção dos Estados Unidos.",
    ],
    "Paris, Berkeley e Berlim Ocidental; Praga e Varsóvia; Cidade do México e Rio de Janeiro. O ponto comum era a recusa da autoridade, fosse ela a do mercado, a do partido ou a dos generais, e a presença de uma juventude numerosa e escolarizada. Daí o resultado desconcertante para a Guerra Fria: nenhum dos dois blocos pôde reivindicar 1968 para si.",
    "Um mesmo ano, três alvos: consumo, burocracia, ditadura."),
  m("m68-54", "desafio", "Unesp", "Entre os desdobramentos do Maio de 1968 na França está o fortalecimento do movimento feminista, que em 1971 divulgou o \"Manifesto das 343\". No documento, as signatárias:",
    [
      "declaravam ter feito um aborto, desafiando a lei que o proibia e exigindo sua legalização.",
      "reivindicavam o direito de voto, ainda negado às francesas.",
      "exigiam o serviço militar obrigatório para as mulheres.",
      "pediam a proibição do divórcio, em defesa da família.",
      "anunciavam a criação de um partido formado apenas por mulheres.",
    ],
    "Entre as signatárias estavam Simone de Beauvoir e a atriz Catherine Deneuve. Muitas militantes vinham dos grupos de 1968, onde haviam constatado que os companheiros falavam em revolução e lhes deixavam o café e o mimeógrafo. A mobilização levou à lei de 1975, que descriminalizou a interrupção da gravidez. As francesas votavam desde 1944.",
    "\"O pessoal é político\": 68 continuou nos anos 1970."),
  m("m68-55", "desafio", "UFRGS", "Em outubro de 1968, a polícia cercou um sítio em Ibiúna, no interior de São Paulo, onde se realizava clandestinamente o congresso da UNE. O episódio teve como resultado:",
    [
      "a prisão de centenas de estudantes, entre eles as principais lideranças do movimento.",
      "a legalização da entidade, em acordo negociado com o governo Costa e Silva.",
      "a morte do estudante Edson Luís, estopim das passeatas daquele ano.",
      "a adesão dos sindicatos operários, que deflagraram uma greve geral.",
      "a renúncia do ministro da Educação e a suspensão da reforma universitária então em debate no Congresso.",
    ],
    "A UNE estava proibida desde 1964 e atuava na clandestinidade. O ano começara com a morte de Edson Luís, em março, e tivera seu auge na Passeata dos Cem Mil, em junho; Ibiúna marca o refluxo. Com o AI-5, em dezembro, fecharam-se os canais de protesto público, e parte dos militantes fichados no congresso seguiu para as organizações de luta armada.",
    "Março, Edson Luís; junho, Cem Mil; outubro, Ibiúna; dezembro, AI-5."),
  m("m68-56", "desafio", "Fuvest", "A greve geral de maio–junho de 1968 é frequentemente comparada à de 1936, na França da Frente Popular. Uma diferença importante entre os dois movimentos é que:",
    [
      "o de 1936 acompanhou a chegada da esquerda ao governo; o de 1968 foi seguido de ampla vitória da direita.",
      "o de 1936 foi derrotado sem nenhuma conquista, e o de 1968 obteve a estatização das grandes empresas industriais e dos bancos.",
      "em 1936 os estudantes dirigiram os operários, ao passo que em 1968 não houve participação estudantil.",
      "em 1968 o número de grevistas foi muito menor que em 1936.",
      "o de 1936 exigia a derrubada do regime, e o de 1968 apoiava o presidente.",
    ],
    "Em 1936, os acordos de Matignon trouxeram férias remuneradas e a semana de 40 horas, sob o governo de Léon Blum. Em 1968, os acordos de Grenelle elevaram bastante o salário mínimo e reconheceram a presença sindical nas empresas, mas os grevistas, cerca de dez milhões, eram mais numerosos que em 1936 e não tinham um governo aliado. Nas urnas, o medo da desordem deu aos gaullistas uma maioria inédita.",
    "1936: greve com governo de esquerda. 1968: greve com vitória da direita."),

  // ───────── Figuras ─────────
  p("fig-41", "dificil", "Fuvest", "No Julgamento de Rivonia (1963–1964), Nelson Mandela, em vez de se defender das acusações, usou o tribunal como tribuna. Sobre esse episódio, é correto afirmar que:",
    [
      "acusado de sabotagem, foi condenado à prisão perpétua depois de dizer que morreria pelo ideal da igualdade.",
      "foi absolvido por falta de provas e partiu para o exílio em Londres.",
      "foi condenado à morte, pena comutada dez anos depois por pressão da ONU e de governos africanos recém-independentes.",
      "renunciou à luta armada em troca de uma pena reduzida.",
      "foi julgado por sua participação no massacre de Sharpeville.",
    ],
    "Rivonia era o subúrbio de Joanesburgo onde a polícia localizou o esconderijo da direção do braço armado do CNA. Os réus corriam risco real de enforcamento; a repercussão internacional do julgamento contribuiu para a pena de prisão perpétua. Mandela passou 27 anos encarcerado, a maior parte na ilha de Robben, e recusou ofertas de liberdade condicionadas à renúncia à luta.",
    "\"Um ideal pelo qual estou disposto a morrer\": Rivonia, 1964."),
  p("fig-42", "dificil", "Unicamp", "A Longa Marcha (1934–1935) é um dos episódios fundadores da trajetória de Mao Tsé-Tung. Ela consistiu:",
    [
      "na retirada do Exército Vermelho, cercado pelos nacionalistas, que consolidou a liderança de Mao.",
      "na ofensiva final dos comunistas sobre Pequim, concluída com a proclamação da República Popular.",
      "na campanha de coletivização que levou milhões de camponeses às comunas populares.",
      "na invasão do Tibete pelas tropas chinesas.",
      "na peregrinação dos Guardas Vermelhos pelo país durante a Revolução Cultural.",
    ],
    "Cercados no sul pelas forças de Chiang Kai-shek, os comunistas romperam o bloqueio e caminharam cerca de um ano até o norte remoto; só uma pequena parte chegou. A derrota militar virou mito de heroísmo, e Mao saiu dela como dirigente principal, com sua estratégia de guerrilha apoiada nos camponeses. A vitória só viria em 1949, depois da guerra contra o Japão e da guerra civil.",
    "Uma retirada que virou epopeia e fez de Mao o líder."),
  p("fig-43", "dificil", "UERJ", "A nacionalização das grandes minas de cobre, em 1971, é a medida mais lembrada do governo Salvador Allende. Um aspecto que a distingue de outras iniciativas da Unidade Popular é que ela:",
    [
      "foi aprovada por unanimidade no Congresso, inclusive com os votos da oposição.",
      "foi imposta por decreto, contra a decisão da Suprema Corte.",
      "indenizou generosamente as empresas norte-americanas, evitando atritos com Washington.",
      "limitou-se às pequenas minas, deixando as grandes com as multinacionais.",
      "foi revertida por completo pela ditadura de Pinochet logo depois do golpe.",
    ],
    "O cobre, o \"salário do Chile\", respondia pela maior parte das exportações, e o controle nacional era consenso entre os partidos. O conflito veio com a indenização: Allende descontou os \"lucros excessivos\" acumulados pelas empresas, o que na prática zerou o pagamento e levou os Estados Unidos a intensificar o cerco financeiro. A grande mineração estatal foi mantida pela ditadura.",
    "No cobre, até a direita chilena votou com Allende."),
  p("fig-44", "dificil", "Unesp", "Na Carta da Prisão de Birmingham (1963), Martin Luther King responde a um grupo de religiosos brancos que consideravam os protestos \"inoportunos\". O principal alvo de sua crítica no texto é:",
    [
      "o branco moderado, que diz concordar com os objetivos, mas pede paciência e prefere a ordem à justiça.",
      "Malcolm X e os defensores da autodefesa armada.",
      "o presidente Kennedy, por ter enviado tropas federais ao Alabama.",
      "os negros que boicotavam o comércio da cidade em vez de recorrer aos tribunais.",
      "as igrejas negras, por se envolverem em política.",
    ],
    "King escreve que o grande obstáculo à liberdade talvez não seja o membro da Ku Klux Klan, e sim o moderado que vive dizendo \"espere\". Defende que há leis justas e injustas e que descumprir abertamente as injustas, aceitando a punição, é a mais alta forma de respeito ao direito. O texto, escrito na cela, tornou-se a exposição clássica da desobediência civil.",
    "\"Espere\" quase sempre quis dizer \"nunca\"."),
  p("fig-45", "dificil", "UFPR", "Em março de 1964, Malcolm X rompeu com a Nação do Islã, organização que o projetara. Entre as razões do rompimento estava:",
    [
      "sua decepção com a conduta pessoal do líder Elijah Muhammad e a punição de silêncio que este lhe impôs.",
      "sua conversão ao cristianismo batista, por influência de Martin Luther King.",
      "a decisão da organização de se aliar ao Partido Democrata.",
      "sua oposição à doutrina de separação racial, que ele nunca havia aceitado nem defendido em seus discursos e entrevistas.",
      "a recusa da organização em apoiar a Guerra do Vietnã.",
    ],
    "Malcolm fora suspenso depois de comentar o assassinato de Kennedy com a frase sobre \"as galinhas voltando ao poleiro\". Fora da Nação, fundou organizações próprias, fez a peregrinação a Meca e passou a tratar o racismo como questão de direitos humanos, a ser levada à ONU. Foi morto em fevereiro de 1965, e integrantes da Nação do Islã foram condenados pelo crime.",
    "Dois Malcolms: antes e depois de 1964."),
  p("fig-46", "dificil", "UFRGS", "Em 1959, numa exposição norte-americana em Moscou, Nikita Kruschev e o vice-presidente Richard Nixon travaram diante das câmeras o chamado \"debate da cozinha\". O episódio é ilustrativo da coexistência pacífica porque:",
    [
      "a disputa entre os sistemas era travada em torno do padrão de vida e dos bens de consumo, e não pelas armas.",
      "os dois assinaram, ali mesmo, o primeiro tratado de limitação de armas nucleares.",
      "Kruschev anunciou a adoção da economia de mercado na União Soviética.",
      "Nixon reconheceu a superioridade do modelo soviético na produção de eletrodomésticos.",
      "a exposição foi fechada em seguida, encerrando a aproximação entre os países.",
    ],
    "Diante de uma cozinha-modelo, Nixon exaltou a máquina de lavar e a liberdade de escolha; Kruschev retrucou que a União Soviética alcançaria e ultrapassaria os Estados Unidos em poucos anos. A competição passava a ser por foguetes, tratores e geladeiras. Meses depois, Kruschev visitaria os Estados Unidos; o clima se desfez em 1960, com a derrubada do avião espião U-2.",
    "Coexistência pacífica: guerra de geladeiras, não de mísseis."),
  p("fig-51", "desafio", "Fuvest", "Em outubro de 1998, Augusto Pinochet foi detido em Londres, a pedido do juiz espanhol Baltasar Garzón. Ainda que ele tenha acabado por regressar ao Chile, o caso é considerado um marco porque:",
    [
      "fortaleceu o princípio de que crimes como a tortura podem ser julgados fora do país onde ocorreram.",
      "foi a primeira condenação de um ex-chefe de Estado pelo Tribunal Penal Internacional, com sede em Haia.",
      "resultou em sua extradição para a Espanha, onde cumpriu pena até a morte.",
      "levou os Estados Unidos a entregar os responsáveis pela Operação Condor.",
      "provocou o rompimento de relações entre o Chile e o Reino Unido.",
    ],
    "Pinochet deixara a Presidência em 1990, mas seguiu como comandante do Exército e depois senador vitalício, protegido pela Constituição que ele mesmo impusera em 1980 e por uma lei de anistia. A justiça britânica negou-lhe imunidade; o governo o liberou por razões de saúde em 2000. De volta ao Chile, enfrentou processos e morreu em 2006 sem ter sido condenado.",
    "Pinochet não foi condenado, mas o precedente ficou."),
  p("fig-52", "desafio", "Unicamp", "Sobre a trajetória de Ho Chi Minh, assinale a alternativa correta.",
    [
      "Morreu em 1969, seis anos antes da reunificação do Vietnã, sem ter visto o fim da guerra.",
      "Comandou pessoalmente a tomada de Saigon, em 1975, e governou o país unificado até o início dos anos 1980.",
      "Assinou os Acordos de Paris, em 1973, ao lado de Henry Kissinger.",
      "Nunca saiu do Vietnã, o que explica sua desconfiança de qualquer aliança externa.",
      "Rompeu com a União Soviética em 1960 e alinhou o país exclusivamente à China de Mao Tsé-Tung.",
    ],
    "Ho viveu três décadas fora do país, na França, na União Soviética e na China, antes de voltar em 1941. Em seus últimos anos, já com a saúde frágil, o comando efetivo do Vietnã do Norte estava com dirigentes como Le Duan; o negociador em Paris foi Le Duc Tho. Hanói equilibrou-se entre Moscou e Pequim, recebendo ajuda das duas. Em 1976, Saigon foi rebatizada com o nome de Ho.",
    "Ho venceu a França, mas não viu o fim da guerra contra os EUA."),
  p("fig-53", "desafio", "UERJ", "Em 1932, preso, Gandhi iniciou um jejum \"até a morte\" contra uma decisão britânica sobre a representação política na Índia. Ele se opunha à criação de:",
    [
      "um eleitorado separado para os chamados \"intocáveis\", que a seu ver dividiria os hindus de modo permanente.",
      "um parlamento indiano com poderes limitados, em vez da independência plena.",
      "um Estado separado para os muçulmanos no noroeste.",
      "um imposto sobre a produção artesanal de tecidos.",
      "um exército indiano destinado a lutar ao lado dos britânicos.",
    ],
    "O líder dos dalits, B. R. Ambedkar, defendia o eleitorado próprio como garantia de que o grupo escolheria de fato seus representantes. Pressionado pelo jejum, aceitou um acordo: nada de eleitorado separado, mas um número maior de cadeiras reservadas. O episódio mostra um Gandhi mais controverso do que o dos manuais: para Ambedkar, ele combatia a intocabilidade sem atacar o sistema de castas.",
    "Gandhi também teve adversários dentro da Índia: Ambedkar e os dalits."),
  p("fig-54", "desafio", "Unesp", "A Revolução Cultural (1966) costuma ser explicada, em parte, pelo desfecho do Grande Salto Adiante (1958–1962). A relação entre os dois processos está em que:",
    [
      "o fracasso do Grande Salto fortaleceu dirigentes pragmáticos, contra os quais Mao mobilizou a juventude.",
      "o êxito do Grande Salto deu a Mao prestígio para afastar o Exército da política.",
      "ambos foram campanhas de abertura ao capital estrangeiro, interrompidas por pressão direta da União Soviética.",
      "a Revolução Cultural foi lançada pelos adversários de Mao para puni-lo pela fome.",
      "o Grande Salto fora uma iniciativa de Deng Xiaoping, a quem Mao decidiu apoiar em 1966.",
    ],
    "O Grande Salto pretendia industrializar o país em poucos anos com comunas populares e fornos de fundo de quintal; desorganizou a agricultura e provocou dezenas de milhões de mortes. Mao recuou para o segundo plano, e Liu Shaoqi e Deng Xiaoping conduziram a recuperação. Ao convocar os Guardas Vermelhos contra os \"seguidores da via capitalista\", Mao retomou o controle; Liu morreu na prisão, e Deng foi afastado.",
    "A Revolução Cultural foi também uma luta pelo poder."),
  p("fig-55", "desafio", "Fuvest", "O boicote aos ônibus de Montgomery durou mais de um ano e terminou em dezembro de 1956. O fim da segregação nos ônibus da cidade resultou:",
    [
      "de uma decisão da Suprema Corte em processo movido por outras passageiras negras.",
      "da falência da empresa de ônibus, que decidiu por conta própria abolir a regra para recuperar os passageiros.",
      "de uma lei aprovada pela assembleia do Alabama, sob pressão dos comerciantes.",
      "do Civil Rights Act, sancionado naquele mesmo mês pelo presidente Eisenhower depois de longa obstrução no Senado.",
      "de um acordo entre Martin Luther King e o governador do estado.",
    ],
    "A ação judicial que chegou à Suprema Corte tinha entre as autoras Claudette Colvin, adolescente presa meses antes de Parks pelo mesmo motivo. Os líderes locais escolheram Rosa Parks como símbolo da campanha por sua reputação e sua militância. O movimento combinou, assim, a pressão das ruas com a estratégia nos tribunais. A lei federal dos direitos civis só viria em 1964.",
    "O boicote pressionou; quem derrubou a regra foi a Suprema Corte."),
  p("fig-56", "desafio", "UFRGS", "Considere as afirmativas sobre a crise do governo Allende.\nI. Em outubro de 1972, uma paralisação de donos de caminhões, apoiada por associações patronais, agravou o desabastecimento no país.\nII. A Unidade Popular dispunha de maioria absoluta no Congresso, o que lhe permitiu aprovar sem negociação todo o seu programa.\nIII. Em agosto de 1973, a Câmara dos Deputados aprovou uma declaração acusando o governo de violar a Constituição, depois invocada pelos golpistas.\nEstá correto o que se afirma em:",
    [I_III, I_II, II_III, SO_II, TODAS],
    "Allende foi eleito com pouco mais de um terço dos votos e sempre governou em minoria no Congresso; por isso recorreu a brechas legais e decretos para ampliar a área estatal, o que acirrou o conflito com a oposição. Documentos norte-americanos mostram que Washington financiou grupos oposicionistas e trabalhou para \"fazer a economia gritar\". Em junho de 1973 houve uma primeira tentativa de golpe, fracassada.",
    "Allende governou em minoria, sob cerco interno e externo."),
];
