import type { Questao } from "@/lib/tipos";
import { criar } from "./criar";

const f = criar("guerra-fria");
const t = criar("vietna");

const I_II = "Apenas I e II.";
const I_III = "Apenas I e III.";
const II_III = "Apenas II e III.";
const SO_II = "Apenas II.";
const SO_III = "Apenas III.";
const TODAS = "I, II e III.";

/** Segunda leva de Guerra Fria e Vietnã: níveis difícil e desafio. A primeira alternativa é a correta. */
export const novasMundo1: Questao[] = [
  // ───────── Guerra Fria ─────────
  f("gf-41", "dificil", "Fuvest", "Na Conferência de Yalta (fevereiro de 1945), Roosevelt, Churchill e Stalin trataram do pós-guerra europeu. Um ponto ali acertado, cujo descumprimento se tornaria uma das primeiras queixas ocidentais contra Moscou, foi:",
    [
      "a promessa de eleições livres nos países libertados do domínio nazista, a começar pela Polônia.",
      "a retirada do Exército Vermelho de todo o Leste Europeu em até um ano.",
      "a entrega de Berlim, por inteiro, à administração norte-americana.",
      "a internacionalização das armas atômicas sob controle da futura ONU.",
      "a divisão da Alemanha em dois Estados independentes, um capitalista e um socialista, com capitais em Bonn e Berlim.",
    ],
    "A Declaração sobre a Europa Libertada previa governos escolhidos pelo voto. Stalin, com suas tropas ocupando a região e decidido a ter vizinhos \"amigos\", instalou governos controlados pelos comunistas. Em Yalta definiram-se zonas de ocupação na Alemanha, não a criação de dois países; a bomba atômica ainda nem havia sido testada.",
    "Yalta prometeu urnas; o Exército Vermelho decidiu o resultado."),
  f("gf-42", "dificil", "Unesp", "\"De Stettin, no Báltico, a Trieste, no Adriático, uma cortina de ferro desceu sobre o continente.\" A frase, de março de 1946, foi pronunciada por:",
    [
      "Winston Churchill, então fora do governo, num discurso nos Estados Unidos ao lado de Truman.",
      "Harry Truman, ao anunciar ao Congresso a ajuda à Grécia e à Turquia.",
      "George Marshall, ao apresentar o plano de reconstrução europeia em Harvard.",
      "Josef Stalin, ao denunciar o cerco capitalista à União Soviética.",
      "Charles de Gaulle, ao defender uma Europa independente das duas superpotências.",
    ],
    "Churchill perdera as eleições de 1945 e falava como líder da oposição britânica, em Fulton, no Missouri. O discurso pedia uma aliança dos povos de língua inglesa diante do avanço soviético e ajudou a preparar a opinião pública norte-americana para a política de contenção, anunciada um ano depois na Doutrina Truman.",
    "Cortina de ferro: Churchill, Fulton, 1946."),
  f("gf-43", "dificil", "Unicamp", "O Muro de Berlim foi erguido em agosto de 1961 pelo governo da Alemanha Oriental, que o chamava de \"muro de proteção antifascista\". Sua função prática era:",
    [
      "estancar a saída de alemães orientais, muitos deles qualificados, rumo ao Ocidente.",
      "impedir a invasão de Berlim Oriental por tropas da OTAN estacionadas no setor ocidental.",
      "isolar Berlim Ocidental do restante da Alemanha Ocidental, repetindo o bloqueio de 1948.",
      "separar as zonas de ocupação soviética e norte-americana, conforme decidido em Potsdam.",
      "proteger a cidade de um ataque nuclear, servindo de abrigo à população civil.",
    ],
    "A fronteira entre as duas Alemanhas já estava fechada; Berlim era a brecha. Entre 1949 e 1961, quase três milhões de pessoas deixaram a RDA, uma sangria de médicos, engenheiros e operários especializados. O muro resolveu o problema econômico do regime ao preço de uma derrota de propaganda: um Estado que precisa murar os cidadãos para que não fujam.",
    "O muro não impedia a entrada: impedia a saída."),
  f("gf-44", "dificil", "UERJ", "Em 1956, o governo húngaro de Imre Nagy foi derrubado por uma intervenção militar soviética. O passo de Nagy que Moscou considerou intolerável foi:",
    [
      "anunciar a saída da Hungria do Pacto de Varsóvia e a neutralidade do país.",
      "pedir o ingresso da Hungria na OTAN e a instalação de bases norte-americanas.",
      "restaurar a monarquia dos Habsburgo.",
      "invadir a Romênia para recuperar a Transilvânia.",
      "nacionalizar as empresas soviéticas instaladas no país.",
    ],
    "A revolta começou com estudantes e operários, animados pela denúncia dos crimes de Stalin. Nagy foi além do que Kruschev aceitava: multipartidarismo e saída da aliança militar. Os tanques entraram em novembro, enquanto o Ocidente estava ocupado com a crise de Suez e não foi além de protestos. O episódio mostrou o limite da desestalinização: reformas, sim; sair do bloco, não.",
    "Desestalinizar podia. Sair do Pacto, não."),
  f("gf-45", "dificil", "UFPR", "A sigla MAD (\"destruição mútua assegurada\") resume a lógica estratégica que se impôs depois que as duas superpotências acumularam arsenais nucleares. Segundo essa lógica, a paz entre elas era mantida:",
    [
      "pela certeza de que quem atacasse primeiro seria igualmente destruído pela resposta do outro.",
      "pela superioridade absoluta dos Estados Unidos, que desencorajava qualquer iniciativa soviética.",
      "por tratados que proibiam o uso de armas nucleares.",
      "pela ação da ONU, cujo Conselho de Segurança controlava os arsenais dos dois países.",
      "pelo desarmamento gradual iniciado logo depois de Hiroshima.",
    ],
    "A União Soviética testou sua bomba em 1949; nos anos 1950 vieram as bombas de hidrogênio e os mísseis intercontinentais. Como nenhum dos lados conseguiria destruir todo o arsenal do outro num primeiro golpe, atacar equivalia a suicidar-se. É o \"equilíbrio do terror\": ele evitou a guerra direta e empurrou o conflito para regiões periféricas.",
    "Ninguém aperta o botão porque o outro também aperta."),
  f("gf-46", "dificil", "Fuvest", "Em 1953, no Irã, e em 1954, na Guatemala, governos foram derrubados com a participação da CIA. Os dois casos têm em comum o fato de que os governantes depostos:",
    [
      "haviam contrariado interesses de grandes empresas estrangeiras, com a nacionalização do petróleo num caso e uma reforma agrária no outro.",
      "haviam assinado alianças militares com a União Soviética e recebido tropas do Pacto de Varsóvia.",
      "eram dirigentes de partidos comunistas que tinham chegado ao poder pela luta armada.",
      "tinham declarado guerra a países vizinhos aliados dos Estados Unidos.",
      "haviam fechado o parlamento e suspendido as eleições.",
    ],
    "Mossadegh nacionalizou a companhia anglo-iraniana de petróleo; Jacobo Arbenz desapropriou terras ociosas da United Fruit. Nenhum dos dois era comunista, e ambos haviam chegado ao governo por vias legais. Na lógica da Guerra Fria, porém, nacionalismo econômico no Terceiro Mundo era lido como porta de entrada para Moscou. A Guatemala virou modelo para as intervenções seguintes na América Latina.",
    "Petróleo no Irã, bananas na Guatemala: nacionalismo tratado como comunismo."),
  f("gf-51", "desafio", "Unicamp", "Considere as afirmativas sobre a Crise dos Mísseis (outubro de 1962).\nI. Kennedy ordenou o bombardeio das bases em Cuba, e só então Kruschev aceitou negociar.\nII. Parte do acordo permaneceu secreta: os Estados Unidos retirariam os mísseis que mantinham na Turquia.\nIII. O governo cubano ficou à margem da negociação final entre Washington e Moscou.\nEstá correto o que se afirma em:",
    [II_III, I_II, I_III, SO_II, TODAS],
    "Kennedy contrariou os militares que queriam o ataque aéreo e optou por um bloqueio naval, chamado de \"quarentena\". O acordo público trocava a retirada dos mísseis soviéticos pela promessa de não invadir Cuba; a retirada dos mísseis Jupiter da Turquia foi combinada em sigilo, o que fez Kruschev parecer o único a ceder. Fidel Castro, não consultado, sentiu-se traído.",
    "Kruschev recuou em público; Kennedy, em segredo."),
  f("gf-52", "desafio", "Fuvest", "O documento NSC-68, elaborado em 1950 pelo Conselho de Segurança Nacional dos Estados Unidos, representou uma mudança em relação à contenção proposta por George Kennan poucos anos antes, pois:",
    [
      "deu à contenção um caráter militar e global, recomendando forte aumento dos gastos com defesa.",
      "propôs o abandono da Europa e a concentração dos esforços norte-americanos na Ásia.",
      "recomendou a guerra preventiva imediata contra a União Soviética, enquanto durasse o monopólio atômico.",
      "defendeu a redução dos arsenais e a negociação direta com Stalin.",
      "limitou o apoio dos Estados Unidos a governos democraticamente eleitos.",
    ],
    "Kennan pensava numa contenção sobretudo política e econômica, aplicada em pontos vitais. O NSC-68, escrito depois da bomba soviética e da vitória de Mao, descrevia um inimigo empenhado em dominar o mundo e pedia rearmamento em larga escala. A Guerra da Coreia, meses depois, deu ao documento a justificativa de que precisava: o orçamento militar norte-americano mais que triplicou.",
    "De Kennan ao NSC-68: da contenção política à corrida armamentista."),
  f("gf-53", "desafio", "UERJ", "O Plano Marshall foi formalmente oferecido a todos os países europeus, inclusive aos do Leste. A reação soviética e seu desdobramento imediato foram:",
    [
      "a recusa, estendida aos vizinhos, e o endurecimento do controle comunista no Leste.",
      "a aceitação parcial, que financiou a reconstrução da Polônia e da Hungria até a morte de Stalin.",
      "a aceitação integral, revogada apenas com a criação da OTAN.",
      "a indiferença, pois a economia soviética saíra fortalecida da guerra e dispensava créditos externos.",
      "o rompimento de relações diplomáticas com os Estados Unidos.",
    ],
    "As condições do plano (abertura de contas, coordenação entre economias) eram incompatíveis com o modelo soviético, e Moscou via nele um instrumento para atrair seus vizinhos. O governo tchecoslovaco chegou a aceitar o convite e foi obrigado a voltar atrás. Em fevereiro de 1948, o Golpe de Praga eliminou o último governo de coalizão do Leste, e a divisão da Europa em dois blocos se completou.",
    "A oferta era para todos; a recusa de Stalin fechou a cortina."),
  f("gf-54", "desafio", "Unesp", "A Ata Final de Helsinque (1975), assinada por 35 países, foi recebida por Moscou como uma vitória diplomática. A longo prazo, porém, um de seus capítulos voltou-se contra os regimes do Leste porque:",
    [
      "comprometia os signatários com o respeito aos direitos humanos, o que deu base a grupos dissidentes para cobrar seus governos.",
      "previa eleições supervisionadas pela ONU em toda a Europa Oriental.",
      "autorizava a intervenção da OTAN em caso de violação das fronteiras.",
      "obrigava a União Soviética a retirar suas tropas da Alemanha Oriental.",
      "estabelecia a livre circulação imediata de pessoas entre os dois blocos.",
    ],
    "O que interessava aos soviéticos era o reconhecimento das fronteiras surgidas da Segunda Guerra. Em troca, aceitaram cláusulas sobre liberdades fundamentais que julgavam inofensivas. Com o texto publicado nos jornais oficiais, surgiram movimentos como a Carta 77, na Tchecoslováquia, e os grupos de monitoramento de Helsinque, que usavam a assinatura do próprio governo como argumento.",
    "Moscou ganhou as fronteiras e, sem perceber, armou os dissidentes."),
  f("gf-55", "desafio", "UFRGS", "A Ostpolitik, conduzida pelo chanceler alemão-ocidental Willy Brandt a partir de 1969, rompeu com a orientação anterior de seu país ao:",
    [
      "reconhecer as fronteiras do pós-guerra e estabelecer relações com a Alemanha Oriental.",
      "retirar a Alemanha Ocidental da OTAN e proclamar a neutralidade.",
      "exigir a devolução dos territórios perdidos para a Polônia em 1945.",
      "propor a reunificação imediata sob regime socialista.",
      "romper relações com os Estados Unidos em protesto contra a Guerra do Vietnã e os bombardeios ao Camboja.",
    ],
    "Até então, Bonn rompia com qualquer país que reconhecesse a RDA (a Doutrina Hallstein). Brandt assinou tratados com Moscou e Varsóvia, aceitando a linha Oder–Neisse, e o Tratado Básico com Berlim Oriental, em 1972. A aposta era a \"mudança pela aproximação\": reduzir a tensão para tornar a divisão mais porosa. Seu gesto de ajoelhar-se no memorial do gueto de Varsóvia tornou-se o símbolo dessa política.",
    "Brandt trocou o isolamento pela aproximação."),
  f("gf-56", "desafio", "Fuvest", "A intervenção soviética no Afeganistão, em dezembro de 1979, costuma ser tomada como o fim da détente. Entre as reações do governo dos Estados Unidos, NÃO esteve:",
    [
      "o envio de tropas norte-americanas para combater diretamente o Exército soviético.",
      "o boicote aos Jogos Olímpicos de Moscou, em 1980.",
      "a suspensão das vendas de cereais à União Soviética.",
      "a retirada do tratado SALT II, de limitação de armas estratégicas, da pauta de ratificação do Senado.",
      "o apoio, com armas e dinheiro, aos guerrilheiros afegãos, por intermédio do Paquistão.",
    ],
    "As superpotências nunca se enfrentaram diretamente, e o Afeganistão não foi exceção: Washington armou a resistência, com a ajuda do Paquistão e da Arábia Saudita, numa guerra por procuração de sinal trocado em relação ao Vietnã. O conflito durou dez anos, desgastou a economia e o prestígio soviéticos e abriu a fase que alguns chamam de \"segunda Guerra Fria\", aprofundada no governo Reagan.",
    "Afeganistão: o Vietnã dos soviéticos."),

  // ───────── Guerra do Vietnã ─────────
  t("vie-41", "dificil", "Fuvest", "Durante a Guerra do Vietnã, aviões norte-americanos despejaram sobre o país milhões de litros de desfolhantes, como o \"agente laranja\". O objetivo militar e uma consequência duradoura dessa prática foram, respectivamente:",
    [
      "destruir a vegetação e as lavouras úteis à guerrilha; solo contaminado e doenças por gerações.",
      "incendiar aldeias suspeitas de abrigar vietcongues; desertificação definitiva de todo o delta do Mekong.",
      "interromper a navegação fluvial entre o Norte e o Sul; extinção da pesca no litoral vietnamita.",
      "marcar alvos para os bombardeiros; aumento da produtividade agrícola no pós-guerra.",
      "forçar a rendição de Hanói pela fome; reunificação antecipada do país.",
    ],
    "Sem floresta, a guerrilha perderia esconderijo; sem arroz, perderia alimento. O produto continha dioxina, substância associada a cânceres e a malformações, que atingiu camponeses vietnamitas e também soldados norte-americanos. Quem incendeia é o napalm, outra arma química do conflito. A guerra contra a natureza tornou-se uma das principais acusações morais feitas aos Estados Unidos.",
    "Agente laranja desfolha; napalm queima."),
  t("vie-42", "dificil", "Unicamp", "A Frente Nacional de Libertação (FNL), fundada em 1960 no Vietnã do Sul, era chamada pelos adversários de \"vietcongue\". Sobre ela, é correto afirmar que:",
    [
      "era dirigida pelos comunistas, mas se apresentava como frente ampla, reunindo também nacionalistas, budistas e camponeses contrários a Diem.",
      "era o nome oficial do exército regular do Vietnã do Norte, que invadiu o Sul em 1960.",
      "foi criada pelos Estados Unidos para combater a guerrilha no delta do Mekong.",
      "reunia os católicos do Norte que haviam migrado para o Sul depois de Genebra.",
      "era um movimento pacifista, que recusava a luta armada e defendia apenas eleições.",
    ],
    "\"Vietcongue\" (comunista vietnamita) era o rótulo pejorativo usado por Saigon e por Washington. A FNL tinha um programa nacionalista e agrário: fim da ditadura de Diem, reforma agrária, reunificação. Essa amplitude explica seu enraizamento entre os camponeses do Sul. O apoio e a direção vinham de Hanói, mas boa parte dos combatentes era gente do próprio Sul.",
    "A guerrilha do Sul era feita, em grande parte, por sulistas."),
  t("vie-43", "dificil", "UERJ", "Em novembro de 1963, o presidente sul-vietnamita Ngo Dinh Diem foi deposto e morto por generais de seu próprio exército, com o conhecimento prévio de Washington. Nos dois anos seguintes, o Vietnã do Sul:",
    [
      "viveu uma sucessão de golpes e juntas militares, o que ampliou sua dependência dos Estados Unidos.",
      "realizou as eleições de reunificação previstas em Genebra, vencidas por Ho Chi Minh com ampla margem de votos.",
      "estabilizou-se sob um governo civil de coalizão com participação da FNL.",
      "foi anexado pelo Vietnã do Norte, encerrando a primeira fase da guerra.",
      "rompeu com os Estados Unidos e aproximou-se da França de De Gaulle.",
    ],
    "Diem era impopular, católico num país budista e incapaz de conter a guerrilha; os Estados Unidos concluíram que com ele a guerra estava perdida. Sem ele, porém, não havia quem governasse. Quanto mais frágil o aliado, maior o envolvimento norte-americano: em 1965 chegaram as primeiras tropas de combate. A guerra ia se tornando uma guerra dos Estados Unidos.",
    "Derrubar Diem foi fácil; substituí-lo, impossível."),
  t("vie-44", "dificil", "Unesp", "O recrutamento obrigatório para o Vietnã previa adiamentos, entre outros casos, para quem cursava universidade. Uma consequência social desse sistema foi:",
    [
      "o peso desproporcional de jovens pobres, operários e negros entre os enviados ao combate.",
      "a convocação preferencial de filhos da elite, o que explica a adesão das universidades à guerra.",
      "a igualdade de sacrifício entre as classes, elogiada pelo movimento dos direitos civis.",
      "a formação de um exército exclusivamente profissional já em 1965.",
      "a dispensa geral da população negra, por pressão de Martin Luther King.",
    ],
    "Quem podia pagar a faculdade ou obter um atestado adiava a convocação; quem não podia, embarcava. Daí a crítica de King de que os pobres lutavam uma guerra que consumia o dinheiro dos programas sociais, e gestos como o do boxeador Muhammad Ali, que se recusou a servir em 1967 e perdeu o título. O serviço obrigatório foi extinto em 1973.",
    "Guerra de rico decidida, guerra de pobre lutada."),
  t("vie-45", "dificil", "UFPR", "A estratégia do general Westmoreland no Vietnã, baseada em operações de \"busca e destruição\", media o sucesso pela \"contagem de corpos\" de inimigos mortos. Um dos efeitos desse critério foi:",
    [
      "estimular números inflados e a inclusão de civis entre os \"inimigos\", sem que isso significasse controle do território.",
      "reduzir as baixas civis, pois cada morte precisava ser confirmada por observadores da ONU.",
      "permitir a ocupação permanente das aldeias conquistadas.",
      "convencer a imprensa e a opinião pública dos Estados Unidos de que a vitória era questão de meses, percepção que se manteve até 1973.",
      "levar o Vietnã do Norte a pedir negociações já em 1965.",
    ],
    "Numa guerra sem frente de batalha, não havia cidades a conquistar; restava contar mortos. As tropas entravam numa área, combatiam e saíam, e a guerrilha voltava. A pressão por resultados incentivava a regra informal de que \"todo vietnamita morto é vietcongue\". O Norte, disposto a perdas enormes, repunha os combatentes; a estatística dizia vitória, e a realidade, impasse.",
    "Contar corpos não é ganhar a guerra."),
  t("vie-46", "dificil", "Fuvest", "Em dezembro de 1972, com as negociações de Paris paralisadas, o governo Nixon ordenou os chamados \"bombardeios de Natal\" sobre Hanói e Haiphong. A ação tinha como finalidade:",
    [
      "forçar o Vietnã do Norte a voltar à mesa e, ao mesmo tempo, tranquilizar o governo de Saigon, que resistia ao acordo.",
      "abrir caminho para a invasão terrestre do Norte por tropas norte-americanas.",
      "destruir os reatores nucleares que a União Soviética instalara em Hanói.",
      "retaliar a Ofensiva do Tet, lançada semanas antes.",
      "impedir a entrada da China na guerra.",
    ],
    "O texto negociado em outubro fora rejeitado pelo presidente sul-vietnamita Thieu, que não aceitava a permanência de tropas do Norte no Sul. Depois de onze dias de ataques com bombardeiros B-52, o acordo assinado em janeiro de 1973 era quase idêntico ao anterior. Os Estados Unidos saíram; a guerra entre vietnamitas continuou até 1975.",
    "Bombas em dezembro, assinatura em janeiro, e o mesmo texto de outubro."),
  t("vie-51", "desafio", "Unicamp", "Considere as afirmativas sobre a Guerra da Indochina (1946–1954).\nI. Depois da rendição japonesa, a França tentou restabelecer o domínio colonial que o Viet Minh declarara extinto em 1945.\nII. Ao final do conflito, os Estados Unidos já arcavam com a maior parte dos custos da guerra francesa.\nIII. A China de Mao manteve-se neutra, recusando armas e treinamento ao Viet Minh para não provocar Washington.\nEstá correto o que se afirma em:",
    [I_II, I_III, II_III, SO_III, TODAS],
    "Depois de 1949, a China comunista forneceu ao Viet Minh artilharia, instrutores e uma retaguarda segura, apoio decisivo em Dien Bien Phu. Do outro lado, Washington, que em 1945 via com maus olhos o colonialismo francês, passou a financiá-lo quando a guerra foi reinterpretada como frente de contenção do comunismo. O envolvimento norte-americano no Vietnã começa aí, antes de qualquer soldado.",
    "Os EUA pagaram a guerra francesa antes de herdar a sua."),
  t("vie-52", "desafio", "Fuvest", "A Resolução do Golfo de Tonkin (agosto de 1964) deu ao presidente Lyndon Johnson autorização para usar a força no Sudeste Asiático. Sobre os fatos que a motivaram, a pesquisa histórica posterior estabeleceu que:",
    [
      "o segundo ataque norte-vietnamita, apresentado como prova da agressão, muito provavelmente não aconteceu.",
      "os navios norte-americanos foram afundados, com centenas de mortos.",
      "os incidentes ocorreram em águas territoriais dos Estados Unidos.",
      "os ataques foram ordenados diretamente por Moscou, e não por Hanói.",
      "o Congresso só aprovou o texto depois de meses de debate e por margem estreita, com forte oposição dos republicanos.",
    ],
    "No dia 2 houve de fato uma escaramuça com o destróier Maddox, que apoiava ações de espionagem na costa do Norte. O \"ataque\" do dia 4 foi fruto de leituras confusas de radar e sonar em noite de mau tempo. Johnson usou o episódio para obter, quase por unanimidade e em poucos dias, um cheque em branco. O Congresso revogou a resolução em 1971.",
    "A guerra ganhou autorização com base num ataque que não houve."),
  t("vie-53", "desafio", "UERJ", "O Laos, oficialmente neutro desde um acordo internacional de 1962, tornou-se, proporcionalmente à população, um dos países mais bombardeados da história. Isso se explica porque:",
    [
      "por seu território passava a Trilha Ho Chi Minh, alvo de bombardeios nunca admitidos em público.",
      "o governo laosiano declarou guerra aos Estados Unidos em 1964.",
      "a capital do Vietnã do Norte foi transferida para o país durante a Operação Rolling Thunder, para escapar dos ataques.",
      "tropas chinesas ocuparam o Laos e instalaram ali mísseis apontados para Saigon.",
      "a França manteve no país suas últimas bases coloniais até 1973.",
    ],
    "A chamada \"guerra secreta\" combinou bombardeios maciços com um exército irregular recrutado pela CIA entre o povo hmong. Não impediu o fluxo de homens e armas para o Sul, nem a vitória comunista no Laos em 1975. Bombas não detonadas continuam matando camponeses décadas depois: um custo da guerra que não aparece nas datas oficiais do conflito.",
    "A guerra do Vietnã não coube no Vietnã."),
  t("vie-54", "desafio", "UFRGS", "Na política externa dos Estados Unidos, a expressão \"síndrome do Vietnã\" passou a designar, a partir de 1975:",
    [
      "a relutância em envolver tropas em guerras longas no exterior, por receio das baixas e da reação da opinião pública.",
      "a disposição de intervir preventivamente, com tropas terrestres, em qualquer país que parecesse ameaçado pelo comunismo.",
      "o trauma dos refugiados vietnamitas que deixaram o país em barcos.",
      "o conjunto de doenças provocadas pelo agente laranja nos veteranos.",
      "a doutrina que proibia o governo de fornecer armas a países aliados.",
    ],
    "A derrota abalou a confiança no poder militar e nos governantes. Nas décadas seguintes, Washington preferiu apoiar aliados e guerrilhas, fazer intervenções rápidas ou só entrar em guerra com objetivos limitados e força esmagadora. No Vietnã reunificado, o pós-guerra foi de campos de \"reeducação\", crise econômica e fuga de centenas de milhares de pessoas pelo mar, os boat people.",
    "Depois de 1975: \"outro Vietnã, não\"."),
  t("vie-55", "desafio", "Unesp", "Para obter uma saída negociada do Vietnã, Nixon e Kissinger procuraram alterar o cenário diplomático em torno de Hanói. O principal recurso utilizado foi:",
    [
      "aproximar-se da China e da União Soviética, as fornecedoras de Hanói, explorando a rivalidade entre elas.",
      "levar o caso ao Conselho de Segurança da ONU, que impôs um cessar-fogo fiscalizado por tropas de países neutros.",
      "oferecer a Hanói o ingresso na OTAN em troca da paz.",
      "transferir o comando da guerra à França, antiga metrópole.",
      "reconhecer oficialmente o governo da FNL em Saigon.",
    ],
    "Em 1972, Nixon visitou Pequim e Moscou. A expectativa era que, interessadas na distensão com Washington, as duas potências comunistas pressionassem o aliado a ceder. O efeito foi limitado, pois nenhuma queria parecer menos solidária que a rival. Nixon também cultivou a imagem de governante imprevisível, capaz de tudo (a \"teoria do louco\"), para intimidar o adversário.",
    "Nixon foi a Pequim e a Moscou pensando em Hanói."),
  t("vie-56", "desafio", "Fuvest", "Em 31 de março de 1968, dois meses depois da Ofensiva do Tet, o presidente Lyndon Johnson fez um pronunciamento na televisão que marcou uma virada na guerra. Nele, anunciou:",
    [
      "a limitação dos bombardeios ao Norte, a disposição de negociar e a desistência de concorrer à reeleição.",
      "a retirada imediata e completa das tropas, ordenada sem consulta prévia ao governo de Saigon e sem qualquer contrapartida do Norte.",
      "o envio de mais 200 mil soldados, pedido por Westmoreland.",
      "a invasão terrestre do Vietnã do Norte.",
      "a renúncia à Presidência, entregue no mesmo dia ao vice Hubert Humphrey.",
    ],
    "O Tet convenceu a cúpula do governo de que a guerra não seria vencida a um custo aceitável; Johnson recusou o reforço solicitado e abriu caminho para as conversações de Paris. Sua desistência mostra o estrago político do conflito: o presidente que aprovara as leis dos direitos civis e os programas da \"Grande Sociedade\" saiu de cena por causa do Vietnã.",
    "O Tet não tomou Saigon, mas derrubou um presidente."),
];
