import type { Nivel, Questao } from "@/lib/tipos";

/**
 * Questões oficiais transcritas dos PDFs das próprias bancas e conferidas com o gabarito oficial:
 * ENEM (download.inep.gov.br, caderno azul), Fuvest (fuvest.br, prova V), Unicamp (comvest.unicamp.br,
 * provas comentadas) e UERJ (vestibular.uerj.br, exames de qualificação).
 * A primeira alternativa é a correta; a explicação é nossa.
 */
const o = (
  banca: string,
  prova: string,
  numero: number,
  tema: string,
  nivel: Nivel,
  enunciado: string,
  alternativas: string[],
  explicacao: string,
  lembre?: string,
): Questao => ({
  id: `${banca}-${prova}-${numero}`.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
  tema,
  nivel,
  estilo: banca,
  oficial: `${banca} ${prova}`,
  enunciado,
  alternativas,
  explicacao,
  lembre,
});

export const oficiaisVestibulares: Questao[] = [
  // ───────── ENEM ─────────
  o("ENEM", "2025", 64, "vargas", "medio",
    "Em toda a sua carreira política, Getúlio Vargas sempre contara com o seu talento pessoal de persuasão e poder de manipulação. Agora, porém, seus amigos começavam a perceber que ele parecia envelhecido e cansado. A principal figura da oposição, concordavam eles, era o belicoso jornalista Carlos Lacerda. Se ao menos pudessem “removê-lo” do cenário político, talvez Vargas se salvasse da situação. Esses seguidores decidiram tomar o assunto em suas próprias mãos com o atentado da Rua Tonelero.\n\nSKIDMORE, T. Brasil: de Getúlio a Castelo. Rio de Janeiro: Paz e Terra, 2003 (adaptado).\n\nNesse contexto, a ação dos aliados de Getúlio Vargas teve como consequência imediata o(a)",
    [
      "intensificação dos ataques do grupo udenista.",
      "intervenção dos sindicatos no conflito partidário.",
      "mobilização da sociedade na defesa do governo.",
      "abandono da censura aos meios de comunicação.",
      "apoio dos parlamentares aos candidatos oposicionistas.",
    ],
    "O atentado de agosto de 1954 feriu Lacerda e matou o major Rubens Vaz. Em vez de calar a oposição, deu a ela a arma que faltava: a UDN e a imprensa redobraram os ataques (o \"mar de lama\") e os militares passaram a exigir a renúncia. A mobilização popular em defesa de Vargas só veio depois, com o suicídio, e por isso não é a consequência imediata do atentado.",
    "Tonelero → UDN ataca mais → militares pressionam → suicídio → aí sim o povo reage."),

  // ───────── Fuvest ─────────
  o("Fuvest", "2024", 44, "jk", "medio",
    "“Industrializar é uma condição de vida, é uma absoluta e imperiosa necessidade, é mesmo um dever de que já não está ao nosso alcance declinar. Nem que o quiséssemos, não poderíamos sobreviver conservando-nos nação pastoril e agrícola, no velho estilo, exportando café e umas poucas matérias-primas [...] Industrializar um país não é uma obra mágica que possa ser feita sem preparo, ao simples sopro de uma aspiração. É necessário que exista uma mentalidade industrial, um estado de espírito propício ao desenvolvimento, é necessário que existam gerações preparadas para a ação.”\n\nOLIVEIRA, Juscelino Kubitschek de. Industrialização: batalha pela própria sobrevivência da nacionalidade. São Paulo: Serviço de Publicações da Federação e Centro das Indústrias do Estado de S. Paulo, 1957. p. 9-10.\n\nA “mentalidade industrial”, proposta pelo então presidente Juscelino Kubitschek, concretiza-se em seu governo (1956-1961) sob a forma",
    [
      "de um projeto desenvolvimentista amparado por incentivos e captação de recursos estrangeiros.",
      "de grandes investimentos na educação básica e na fundação de centros de pesquisa.",
      "de incentivos à diversificação e mecanização da produção agrícola.",
      "da implantação de formas racionais de organização do trabalho.",
      "da ação governamental embasada em concepção nacionalista e trabalhista.",
    ],
    "O Plano de Metas apostou na industrialização acelerada com forte entrada de capital estrangeiro, sobretudo das montadoras de automóveis. A alternativa \"nacionalista e trabalhista\" descreve Vargas, e é a pegadinha: JK era desenvolvimentista, mas aberto às multinacionais. A educação era uma das metas, porém recebeu a menor fatia dos recursos.",
    "Vargas = nacionalista. JK = desenvolvimentista com capital estrangeiro."),
  o("Fuvest", "2024", 76, "guerra-fria", "dificil",
    "“O plano dos Estados Unidos de derrubarem a Revolução já estava esboçado na ocasião em que Mikoyan [vice-líder no governo soviético de Nikita Kruschev] visitou Havana, em fevereiro de 1960 (...). A CIA propunha a sabotagem das refinarias de açúcar de Cuba, a principal fonte de riqueza da ilha. (...) Como prometido, Fidel Castro reagiu contra os Estados Unidos (...). Ele anunciou a nacionalização de todas as propriedades norte-americanas importantes da ilha. (...) Numa frase sinistra (...), Castro salientou que a Cuba revolucionária tinha agora o apoio militar de fora do continente. Cuba ‘aceitaria com gratidão’, disse ele, ‘a ajuda dos foguetes da União Soviética (...)’. Naquele mês, a lenha fora jogada na fogueira, quando Castro chegou a Nova York para falar na Assembleia Geral da ONU, instalando-se no Harlem. (...) Castro ficou no [hotel] Theresa, cercado por um grupo de admiradores (...) e numa tarde memorável foi visitado pelo líder soviético. (...) Kruschev escreveu nas suas memórias que ‘indo a um hotel negro num bairro negro, nós estávamos fazendo uma dupla demonstração contra as políticas discriminatórias dos Estados Unidos em relação aos negros, assim como em relação a Cuba’”.\n\nGOTT, Richard. Cuba: uma nova história. Rio de Janeiro: Zahar, 2006. p. 210-213. Adaptado.\n\nAs tensões políticas abordadas no texto referem-se",
    [
      "ao gradual alinhamento entre Cuba e a URSS e ao aceno dos dois governantes de apoio ao movimento negro norte-americano.",
      "à indecisão de Fidel Castro sobre o alinhamento político de Cuba na Guerra Fria e ao isolamento da ilha em relação a outros debates políticos da época.",
      "às garantias do governo revolucionário em Cuba aos capitais norte-americanos e à salvaguarda dos direitos civis da população negra na ilha.",
      "à aliança entre Cuba e URSS selada na origem da guerrilha em Sierra Maestra e à consequente oposição dos EUA ao movimento insurgente.",
      "à articulação entre os governos da URSS e dos EUA para enfraquecer Fidel Castro e os movimentos sociais no Harlem.",
    ],
    "A palavra-chave é \"gradual\". A Revolução Cubana (1959) não nasceu comunista: a aproximação com a URSS foi acontecendo em 1960, à medida que os EUA hostilizavam o novo governo e Fidel nacionalizava empresas americanas. Por isso está errado dizer que a aliança vinha desde a guerrilha em Sierra Maestra. O encontro de Fidel e Kruschev no Harlem, bairro negro de Nova York, foi um gesto calculado de apoio à luta dos negros norte-americanos. Dois anos depois viria a Crise dos Mísseis.",
    "Cuba: 1959 revolução → 1960 aproxima da URSS → 1962 mísseis."),

  // ───────── Unicamp ─────────
  o("Unicamp", "2018", 55, "jk", "dificil",
    "Vistas em conjunto, as aspirações ruralistas não eram contraditórias ou incompatíveis com o programa desenvolvimentista de Juscelino Kubitschek. A ideia de incompatibilidade entre o projeto nacional-desenvolvimentista e os interesses agrários era uma ficção.\n\n(Adaptado de Vânia Moreira, “Os Anos JK: industrialização e modelo oligárquico de desenvolvimento rural”, em Jorge Ferreira e Lucília Delgado (Orgs.), O Brasil Republicano. v. 3. Rio de Janeiro: Civilização Brasileira, 2003, p. 169-170.)\n\nConsiderando a composição do setor rural nacional e o programa desenvolvimentista do governo JK, é correto afirmar que:",
    [
      "O desenvolvimentismo atendia às ambições da oligarquia rural, em função das políticas de modernização da agricultura, permitindo que ela se beneficiasse da expansão do mercado consumidor, um dos desdobramentos da industrialização.",
      "A \"Marcha para o Oeste\" obteve grande êxito porque, além dos grandes ruralistas, conseguia atender também aos interesses dos pequenos posseiros, trabalhadores sem terra e indígenas.",
      "O Plano de Metas do governo JK fracassou porque os interesses do agronegócio se mostraram posteriormente inconciliáveis com as demandas da velha oligarquia rural das regiões Norte e Centro-Oeste.",
      "Os interesses agrários e o projeto de industrialização do nacional-desenvolvimentismo eram compatíveis porque o Partido Trabalhista Brasileiro era composto principalmente pela oligarquia rural.",
    ],
    "JK industrializou sem mexer na estrutura agrária: não houve reforma agrária, e os grandes proprietários ganharam crédito, estradas e um mercado urbano maior para vender. Isso explica sua estabilidade política, pois seu partido, o PSD, era justamente o das elites rurais. O PTB era o partido dos trabalhadores urbanos, não da oligarquia. A questão da terra só entraria na pauta com Jango.",
    "JK agradou indústria e fazendeiro. PSD = elite rural; PTB = trabalhador urbano."),
  o("Unicamp", "2018", 56, "figuras", "dificil",
    "[A questão traz a fotografia do pódio: os dois atletas norte-americanos, de cabeça baixa, erguem o punho fechado com uma luva preta.]\n\nA foto mostra, da esquerda para a direita, os atletas Peter Norman (australiano), John Carlos e Tommie Smith (norte-americanos), no pódio dos 200 metros rasos das Olimpíadas de 1968, no México.\n\nConsiderando a imagem acima e seus conhecimentos acerca dos Movimentos de Direitos Civis, assinale a alternativa correta.",
    [
      "A fotografia registra a manifestação de atletas defensores dos Panteras Negras e das ações violentas, se necessárias, para a conquista da igualdade racial.",
      "A fotografia registra o ato de resistência de atletas negros que defendiam as propostas de Martin Luther King e a ação pacifista como caminho para a constituição da igualdade racial.",
      "A fotografia registra a manifestação política de três atletas que defendiam a Nação Islã e a implementação da Ku Klux Klan em todo o território nacional.",
      "A fotografia registra a resistência de atletas e do Comitê Olímpico Internacional, que combatiam o sistema de discriminação racial existente nos Estados Unidos da América.",
    ],
    "O punho fechado erguido é a saudação do Black Power, associada aos Panteras Negras, grupo criado em 1966 que defendia a autodefesa armada dos negros, na linha das ideias de Malcolm X. Não é o gesto do movimento pacifista de Luther King. A Ku Klux Klan é uma organização racista branca, e o Comitê Olímpico, longe de apoiar, puniu os dois atletas. A banca quis mostrar que o movimento negro tinha correntes diferentes.",
    "Punho fechado = Black Power / Panteras (linha Malcolm X). Mão estendida = King."),
  o("Unicamp", "2025", 30, "descolonizacao", "dificil",
    "A maioria dos países africanos tornaram-se independentes entre 1950 e 1975. Amílcar Cabral foi uma das lideranças que formularam projetos políticos para criar unidades nacionais no pós-independência. Ele havia nascido na Guiné-Bissau em 1924; depois de seu nascimento, sua família se mudou para Cabo Verde. Em 1945, obteve bolsa para estudar em Portugal; na Europa, entrou, então, em contato com as teorias do movimento da negritude, pan-africanismo e marxismo. De volta à África em 1952, ajudou a fundar o Partido Africano para a Independência de Guiné e Cabo Verde (PAIGC, 1953), iniciando a luta armada contra a metrópole em 1963. Em um discurso, Cabral afirmou: “No nosso Partido ninguém dividiu; pelo contrário, cada dia nos unimos mais. Aqui não há papel, nem fula, nem mandinga, nem filhos de cabo-verdianos, nada disso.”\n\n(Adaptado de MALACCO, F. Unidade nacional e unidade continental: uma discussão acerca dos projetos políticos de Amílcar Cabral e Kwame Nkrumah. Revista Ars Historica, 17, p. 78-100, jul/dez 2018.)\n\nCom base no excerto, marque a alternativa correta sobre o ideário nacional proposto por Amílcar Cabral e pelo movimento por ele liderado.",
    [
      "Defendia, para fortalecer a luta contra a colonização e ideologia portuguesa, as unidades políticas nacionais posicionadas acima da diversidade de etnias africanas.",
      "Almejava, com base nas fronteiras dos reinos africanos que existiam antes da chegada dos europeus, construir nações independentes.",
      "Buscava formar, para o enaltecimento das identidades étnicas que antecediam o colonialismo, uma grande unidade pan-africanista.",
      "Propunha um movimento de descolonização das culturas africanas, o qual demandava a adoção de dialetos locais e a rejeição, como idioma nacional, das línguas europeias.",
    ],
    "No discurso, Cabral diz que no partido não há \"papel, nem fula, nem mandinga\", que são nomes de etnias. A ideia é que a nação vem antes da etnia: dividir os africanos por grupos era uma tática do colonizador, e a união era condição para vencer Portugal. O texto ilustra também os fatores internos da descolonização: uma elite formada na metrópole, em contato com o pan-africanismo e o marxismo, liderando um movimento nacionalista.",
    "Lema do PAIGC: \"Unidade e Luta\"."),

  // ───────── UERJ ─────────
  o("UERJ", "2013 (2º EQ)", 55, "figuras", "facil",
    "O ônibus da história\n\nEm 1º de dezembro de 1955, a costureira Rosa Parks recusou-se a ceder seu assento a um homem branco em um ônibus municipal de Montgomery, no Alabama, conforme determinavam as leis do estado. Informada pelo motorista que acabaria presa, a mulher preferiu ser levada para a cadeia - e, posteriormente, a julgamento. Sua condenação pelo júri levou à formação da Montgomery Improvement Association. A presidência da entidade foi entregue ao pastor Martin Luther King. No dia da condenação de Rosa Parks, King discursou para uma multidão reunida diante da Igreja Batista da Rua Holt: “Quero assegurar a todos que trabalharemos para fazer prevalecer a justiça nos ônibus da cidade. Se estivermos errados, a Suprema Corte desta nação está errada. Se estivermos errados, a Constituição dos Estados Unidos está errada. Se estivermos errados, Deus Todo-Poderoso está errado”.\n\nAdaptado de vejaabril.com.br.\n\nAssassinado em 1968, Martin Luther King iniciou suas atividades políticas em 1956, a partir do episódio relatado na reportagem. O principal resultado das propostas de Martin Luther King para a sociedade norte-americana está diretamente relacionado com:",
    [
      "universalização dos direitos civis",
      "unificação das leis estaduais",
      "expansão da igualdade social",
      "regulação de causas trabalhistas",
    ],
    "A luta de King resultou na Lei dos Direitos Civis (1964), que proibiu a segregação em locais públicos, e na Lei do Direito de Voto (1965). Direitos civis são os de igualdade perante a lei: ir e vir, votar, usar os mesmos espaços. A pegadinha é \"igualdade social\": a desigualdade econômica entre negros e brancos continuou; o que se conquistou foi a igualdade legal.",
    "King conquistou igualdade na LEI (direitos civis), não na renda."),
  o("UERJ", "2014 (1º EQ)", 50, "guerra-fria", "facil",
    "Em 25 de junho de 1950, tropas da Coreia do Norte ultrapassaram o Paralelo 38, que delimitava a fronteira com a Coreia do Sul. Com a aprovação do Conselho de Segurança da ONU, quinze países enviaram tropas em defesa da Coreia do Sul, comandadas pelo general norte-americano Douglas MacArthur. Após três anos de combate, foi assinado um armistício em 27 de julho de 1953, mantendo a divisão entre as Coreias.\n\nAdaptado de cpdoc.fgv.br.\n\nO governo norte-coreano anunciou recentemente que não mais reconheceria o armistício assinado em 1953, o que trouxe novamente ao debate o episódio da Guerra da Coreia. O fator que explica a dimensão assumida por essa guerra na década de 1950 está apresentado em:",
    [
      "bipolaridade das relações políticas internacionais",
      "mundialização do acesso a fontes de energia",
      "hegemonia soviética em países do Terceiro Mundo",
      "criação de multinacionais japonesas no extremo Oriente",
    ],
    "Uma guerra entre as duas metades de um país pequeno virou conflito internacional porque cada lado tinha uma superpotência por trás: o Norte comunista era apoiado por URSS e China, o Sul capitalista pelos EUA. É o modelo de guerra por procuração da Guerra Fria, que se repetiria no Vietnã.",
    "Coreia: paralelo 38. Vietnã: paralelo 17."),
  o("UERJ", "2014 (2º EQ)", 59, "vietna", "facil",
    "[A questão traz o cartaz do Festival de Woodstock.]\n\nNa década de 1960, muitas expressões artísticas representaram uma postura crítica frente a problemas da época, em especial os conflitos da Guerra Fria. Um exemplo é o Festival de Woodstock, ocorrido em 1969 nos E.U.A., em cujo cartaz se lê “Três dias de paz e música”. Nesse contexto da década de 1960, destacava-se a denúncia sobre:",
    [
      "intervenção militar no Vietnã",
      "presença soviética na China",
      "dominação europeia na África do Sul",
      "exploração econômica no Oriente Médio",
    ],
    "Woodstock foi o auge da contracultura hippie, cujo lema \"paz e amor\" era uma resposta direta à Guerra do Vietnã. Em 1969 os EUA tinham mais de meio milhão de soldados no país, e os jovens eram os convocados. O festival reuniu músicos que cantavam contra a guerra, como Jimi Hendrix e Joan Baez.",
    "Paz e amor = contra o Vietnã."),
  o("UERJ", "2014 (1º EQ)", 48, "vietna", "medio",
    "Eu e minha mulher somos de gerações que viveram cada minuto da Guerra do Vietnã (1959-1975), uma das mais sangrentas de todos os tempos. Por isso, nossa visita a esse país teve um sentido muito especial.\n\nO país hoje é um formigueiro em atividade, onde todos correm para recuperar o tempo perdido. A renda per capita ainda é muito baixa: US$ 700 por ano. O salário mínimo também é baixo: US$ 30. Embora todos os preços sejam baixos, esses valores dão uma ideia do tipo de vida, ainda austera, que levam os vietnamitas.\n\nA guerra consumiu gerações inteiras. A maioria esmagadora da população hoje é de jovens, o que talvez explique o predomínio da motocicleta como meio de transporte. Quase não há transporte coletivo, e são poucos os carros. Enxames de motos dominam as ruas. A moto mais barata vem da China e custa US$ 300. Equivale a dez meses de salário mínimo. Em Cidade de Ho Chi Minh, há 4 milhões de motos para 2 milhões de famílias.\n\nBernardo Kucinski. Adaptado de redebrasilatual.com.br, julho de 2010.\n\nNo relato de sua visita ao Vietnã, o autor faz referência a algumas das características atuais daquela sociedade. Essas características se relacionam com a seguinte mudança recente na história do país:",
    [
      "implantação do socialismo de mercado",
      "fim do partido comunista",
      "liberalização do fluxo migratório",
      "flexibilização da moeda nacional",
    ],
    "Depois de vencer a guerra e reunificar o país em 1976, o Vietnã continuou governado pelo Partido Comunista, mas a partir de 1986 abriu a economia à iniciativa privada e ao comércio exterior, num modelo parecido com o da China. Daí o \"formigueiro em atividade\" e as motos importadas. Note que a antiga Saigon aparece no texto com o nome atual: Cidade de Ho Chi Minh.",
    "Vietnã hoje: partido comunista + economia de mercado, como a China."),
  o("UERJ", "2017 (2º EQ)", 52, "vietna", "medio",
    "Era um garoto que como eu amava os Beatles e os Rolling Stones (1967)\n\nEra um garoto / Que como eu / Amava os Beatles / E os Rolling Stones\nGirava o mundo / Sempre a cantar / As coisas lindas / Da América\nCantava viva à liberdade / Mas uma carta sem esperar / Da sua guitarra o separou / Fora chamado na América\nStop! Com Rolling Stones / Stop! Com Beatles songs / Mandado foi ao Vietnã / Lutar com vietcongs\n\nEu te amo, meu Brasil (1970)\n\nAs praias do Brasil ensolaradas / O chão onde o país se elevou / A mão de Deus abençoou / Mulher que nasce aqui tem muito mais amor\nO céu do meu Brasil tem mais estrelas / O sol do meu país mais esplendor / A mão de Deus abençoou / Em terras brasileiras vou plantar amor\nEu te amo, meu Brasil, eu te amo / Meu coração é verde, amarelo, branco, azul anil / Eu te amo, meu Brasil, eu te amo / Ninguém segura a juventude do Brasil\n\nBANDA OS INCRÍVEIS. Adaptado de vagalume.com.br.\n\nA banda brasileira Os Incríveis marcou época ao cantar acontecimentos e ideias que afetavam especialmente a vida dos mais jovens no final da década de 1960, como ilustram as letras citadas. Essas letras estão relacionadas, respectivamente, aos seguintes contextos internacional e brasileiro daquele momento:",
    [
      "bipolaridade da Guerra Fria − nacionalismo ufanista",
      "declínio do liberalismo − patriotismo militarista",
      "apogeu do imperialismo − naturalismo romântico",
      "política da coexistência pacífica − conservadorismo ambiental",
    ],
    "A primeira letra fala do jovem americano convocado para lutar contra os vietcongues: a Guerra do Vietnã é o maior exemplo de conflito gerado pela bipolaridade da Guerra Fria. A segunda é do período do \"milagre econômico\" da ditadura brasileira, quando o governo estimulava um patriotismo exagerado, o ufanismo, o mesmo do slogan \"Brasil: ame-o ou deixe-o\".",
    "Vietcongue = guerrilheiro comunista do Vietnã do Sul."),
  o("UERJ", "2015 (1º EQ)", 56, "jango", "medio",
    "O professor Alcino Salazar, secretário de justiça da Guanabara, declarou a O Globo que a extensão do voto ao analfabeto é perigosa concessão aos inimigos do regime democrático, fundado na verdade e na pureza do princípio da representação.\n\nAdaptado de O Globo, 21/02/1964.\n\nEm sua mensagem ao Congresso Nacional em 15 de março de 1964, o presidente João Goulart escreveu: “Outra discriminação inaceitável atinge milhões de cidadãos que, embora investidos de todas as responsabilidades (...) e integrados à força de trabalho, com seu contingente mais numeroso, são impedidos de votar por serem analfabetos”.\n\nALEIXO, J. C. B; KRAMER, Paulo. Os analfabetos e o voto: da conquista da alistabilidade ao desafio da elegibilidade. Senatus, Brasília, outubro/2000.\n\nAs declarações do professor Alcino Salazar e do presidente João Goulart foram feitas em um momento de polarização na sociedade brasileira, que culminou na instauração do regime autoritário em 31 de março de 1964. Ambas as declarações expressavam, naquele momento, visões antagônicas relacionadas à seguinte dimensão da cidadania:",
    [
      "direitos políticos",
      "reparações étnicas",
      "benefícios sociais",
      "oportunidades econômicas",
    ],
    "Votar é um direito político. O voto do analfabeto fazia parte da reforma eleitoral, uma das Reformas de Base de Jango. Desde a Constituição de 1946 os analfabetos estavam excluídos, e incluí-los ampliaria muito o eleitorado popular, o que assustava os conservadores. O direito só veio em 1985.",
    "Civis = igualdade na lei · Políticos = votar · Sociais = saúde, educação, trabalho."),
  o("UERJ", "2016 (2º EQ)", 52, "jango", "facil",
    "Dirijo-me a todos os brasileiros, não apenas aos que conseguiram adquirir instrução nas escolas, mas também aos milhões de irmãos nossos que dão ao Brasil mais do que recebem, que pagam em sofrimento, em miséria, em privações, o direito de ser brasileiro e de trabalhar sol a sol para a grandeza deste país. Aqui estão os meus amigos trabalhadores, na presença das mais significativas organizações operárias e lideranças populares deste país. Àqueles que reclamam do Presidente da República uma palavra tranquilizadora para a Nação, o que posso dizer-lhes é que só conquistaremos a paz social pela justiça social. A maioria dos brasileiros já não se conforma com uma ordem social imperfeita, injusta e desumana.\n\nJoão Goulart, em comício no Rio de Janeiro, 13/03/1964. Adaptado de jornalggn.com.br.\n\nNo evento conhecido como Comício da Central do Brasil, o Presidente João Goulart proferiu discurso em que reafirmava algumas das propostas de seu governo, atendendo a demandas de organizações sindicais. A proposta desse governo mais diretamente associada à promoção da justiça social foi:",
    [
      "realização da reforma agrária",
      "gratuidade do ensino público",
      "concessão do voto aos analfabetos",
      "introdução dos direitos trabalhistas",
    ],
    "No comício, Jango assinou o decreto que desapropriava terras às margens de rodovias e ferrovias federais: a reforma agrária era a principal das Reformas de Base e a que tocava diretamente na distribuição da riqueza. O voto dos analfabetos também era proposta dele, mas diz respeito a direitos políticos, não à justiça social. Os direitos trabalhistas já existiam desde Vargas.",
    "Central do Brasil, 13 de março de 1964 = decreto da reforma agrária."),
  o("UERJ", "2017 (1º EQ)", 49, "jango", "medio",
    "Antecipando-nos à derrocada das forças subversivas, acionadas por dispositivos governamentais, que visavam à destruição do primado da democracia e à implantação de um regime totalitário, tivemos a lucidez e o patriotismo de alertar os poderes constituídos da República para a defesa da ordem jurídica e da Constituição, tão seriamente ameaçadas. Podemos hoje, erradicado o mal das conjuras comuno-sindicalistas, proclamar que a sobrevivência da Nação Brasileira se processou sob a égide intocável do Estado de Direito.\n\nAdaptado de Ata da Reunião Ordinária do Conselho Federal da Ordem dos Advogados do Brasil – OAB, 07/04/1964.\n\nO apoio da Ordem dos Advogados do Brasil à deposição do presidente João Goulart (1961-1964), como indicado no texto, insere-se no contexto de intensas polarizações de opiniões entre partidos e associações. Essas polarizações expressavam posicionamentos distintos acerca da seguinte proposta do governo João Goulart:",
    [
      "implementação das reformas de base",
      "política de desvalorização monetária",
      "cerceamento da liberdade de imprensa",
      "controle orçamentário dos poderes estaduais",
    ],
    "O país se dividiu em torno das Reformas de Base. Para os apoiadores, eram justiça social; para os opositores, o primeiro passo para o comunismo, daí a expressão \"conjuras comuno-sindicalistas\" na ata. O documento mostra por que o golpe é chamado de civil-militar: entidades respeitadas da sociedade civil, como a OAB, apoiaram a derrubada do presidente em nome da democracia.",
    "Golpe civil-militar: OAB, imprensa, Igreja e empresários apoiaram."),
  o("UERJ", "2018 (2º EQ)", 53, "descolonizacao", "facil",
    "Tínhamos a incumbência de reelaborar nosso passado sombrio, contribuindo assim para tratar um povo traumatizado e ferido. Uma tarefa grandiosa, já que todos os sul-africanos tinham suas lesões. Queríamos obter a unidade da nação e a reconciliação.\n\nDESMOND TUTU. Adaptado de dw.com, 29/10/2008.\n\nO arcebispo Desmond Tutu dirigiu a Comissão da Verdade na África do Sul, entre 1996 e 1998, durante o governo do presidente Nelson Mandela. Ao propor “a unidade da nação e a reconciliação”, o arcebispo buscava enfrentar os problemas causados pela vigência do regime de:",
    [
      "segregação racial",
      "natureza totalitária",
      "ordenamento cultural",
      "disciplinarização social",
    ],
    "O regime era o apartheid (1948–1994), que separava brancos e negros por lei e negava direitos políticos à maioria negra. Eleito em 1994, Mandela escolheu a reconciliação em vez da vingança: a Comissão da Verdade ouvia vítimas e agressores e podia conceder anistia a quem confessasse seus crimes.",
    "Apartheid = \"apartar\". Mandela = reconciliação."),
];
