import type { Evento, Personagem, Questao } from "@/lib/tipos";
import { criar } from "./criar";

export const personagens: Personagem[] = [
  {
    id: "ho-chi-minh",
    nome: "Ho Chi Minh",
    lugar: "Vietnã · 1890–1969",
    quem: "Líder comunista e nacionalista que comandou a independência do Vietnã contra a França e presidiu o Vietnã do Norte na guerra contra os Estados Unidos. Morreu em 1969, antes da vitória; Saigon foi rebatizada com seu nome.",
    gancho: "O nome dele virou trilha e virou cidade: a Trilha Ho Chi Minh abastecia a guerrilha, e Saigon hoje é Cidade de Ho Chi Minh. Se a pergunta fala em Vietnã, a resposta é o \"Tio Ho\".",
    palavras: ["Vietnã do Norte", "Viet Minh", "Dien Bien Phu", "Tio Ho"],
    pistas: [
      "Proclamou a independência de seu país em 1945 citando a Declaração de Independência dos EUA.",
      "Fundou o Viet Minh e derrotou os franceses em 1954.",
      "Uma rede de caminhos na selva que abastecia guerrilheiros levava seu nome.",
      "A antiga Saigon hoje se chama Cidade de…",
    ],
    fato: "Líder da independência do Vietnã e do Vietnã do Norte",
  },
  {
    id: "kruschev",
    nome: "Nikita Kruschev",
    lugar: "União Soviética · 1894–1971",
    quem: "Sucessor de Stalin no comando da URSS (1953–1964). Denunciou os crimes de Stalin em 1956, defendeu a coexistência pacífica com os EUA e esteve no centro da Crise dos Mísseis de Cuba (1962).",
    gancho: "Kruschev \"Krushou\" (quebrou) a imagem de Stalin. É o K contra o K: Kruschev × Kennedy na crise de Cuba.",
    palavras: ["Desestalinização", "Coexistência pacífica", "Crise dos Mísseis", "URSS"],
    pistas: [
      "Fez um discurso secreto em 1956 que chocou os comunistas do mundo todo.",
      "Em seu governo foi construído o Muro de Berlim.",
      "Negociou com Kennedy a retirada dos mísseis de Cuba.",
      "Sucedeu Stalin e defendeu a coexistência pacífica.",
    ],
    fato: "Sucessor de Stalin, defensor da coexistência pacífica",
  },
  {
    id: "allende",
    nome: "Salvador Allende",
    lugar: "Chile · 1908–1973",
    quem: "Médico e político socialista, eleito presidente do Chile em 1970. Tentou chegar ao socialismo pela via democrática, nacionalizou o cobre e foi derrubado pelo golpe militar de 11 de setembro de 1973, morrendo no palácio presidencial de La Moneda.",
    gancho: "Allende foi ELEITO: o socialista que chegou ao poder pelo voto, não pelas armas. A começa antes de P no alfabeto: primeiro Allende, depois Pinochet.",
    palavras: ["Chile", "Via democrática ao socialismo", "Cobre", "11 de setembro de 1973"],
    pistas: [
      "Nacionalizou as minas de cobre de seu país.",
      "Defendia chegar ao socialismo por eleições, sem revolução armada.",
      "Morreu dentro do palácio de La Moneda durante um golpe.",
      "Presidente socialista do Chile derrubado em 1973.",
    ],
    fato: "Socialista eleito no Chile, derrubado em 1973",
  },
  {
    id: "pinochet",
    nome: "Augusto Pinochet",
    lugar: "Chile · 1915–2006",
    quem: "General que liderou o golpe contra Allende em 1973, com apoio dos Estados Unidos, e governou o Chile como ditador até 1990. Seu regime combinou repressão violenta (milhares de mortos, desaparecidos e torturados) com uma política econômica neoliberal.",
    gancho: "Pinochet = P de \"Putsch\" (golpe) e de \"Porrete\". Sempre de farda e óculos escuros. Ele vem depois de Allende, como P vem depois de A.",
    palavras: ["Chile", "Ditadura", "Golpe de 1973", "Neoliberalismo"],
    pistas: [
      "Seu governo aplicou as ideias econômicas dos \"Chicago Boys\".",
      "Deixou o poder depois de perder um plebiscito em 1988.",
      "General que bombardeou o palácio presidencial de seu próprio país.",
      "Ditador do Chile de 1973 a 1990.",
    ],
    fato: "General que deu o golpe no Chile e virou ditador",
  },
  {
    id: "gandhi",
    nome: "Mahatma Gandhi",
    lugar: "Índia · 1869–1948",
    quem: "Principal líder da independência da Índia contra o domínio britânico (1947). Pregava a não violência e a desobediência civil: boicotes, greves de fome e marchas pacíficas, como a Marcha do Sal (1930). Foi assassinado em 1948 por um extremista hindu.",
    gancho: "Gandhi = \"Ganhou\" sem dar um tiro. Imagine o homem magro de pano branco e óculos redondos caminhando até o mar para pegar sal.",
    palavras: ["Índia", "Não violência", "Desobediência civil", "Marcha do Sal"],
    pistas: [
      "Incentivava seu povo a fiar o próprio tecido para boicotar os produtos ingleses.",
      "Caminhou centenas de quilômetros até o mar para protestar contra um imposto sobre o sal.",
      "Seu título significa \"grande alma\".",
      "Líder pacifista da independência da Índia.",
    ],
    fato: "Independência da Índia pela não violência",
  },
  {
    id: "mandela",
    nome: "Nelson Mandela",
    lugar: "África do Sul · 1918–2013",
    quem: "Líder da luta contra o apartheid, o regime de segregação racial sul-africano. Ficou 27 anos preso (1962–1990), ganhou o Nobel da Paz em 1993 e, em 1994, tornou-se o primeiro presidente negro da África do Sul, defendendo a reconciliação.",
    gancho: "Mandela foi \"mandado\" para a cela por 27 anos e saiu para \"mandar\" no país como presidente. Da prisão à presidência.",
    palavras: ["África do Sul", "Apartheid", "27 anos preso", "Primeiro presidente negro"],
    pistas: [
      "Militante do Congresso Nacional Africano, foi condenado à prisão perpétua.",
      "Passou boa parte da pena na ilha de Robben.",
      "Dividiu o Nobel da Paz de 1993 com o presidente que o libertou.",
      "Primeiro presidente negro da África do Sul.",
    ],
    fato: "Combateu o apartheid e presidiu a África do Sul",
  },
  {
    id: "mao",
    nome: "Mao Tsé-Tung",
    lugar: "China · 1893–1976",
    quem: "Líder da Revolução Chinesa, que em 1949 criou a República Popular da China. Baseou a revolução nos camponeses, e não nos operários. Governou até morrer, em 1976, promovendo o Grande Salto para Frente e a Revolução Cultural.",
    gancho: "Mao tinha a China na \"mão\", e na mão de cada chinês estava o Livro Vermelho com suas frases. Revolução com camponeses, 1949.",
    palavras: ["China", "Revolução de 1949", "Camponeses", "Revolução Cultural"],
    pistas: [
      "Liderou a Longa Marcha nos anos 1930.",
      "Seu adversário, Chiang Kai-shek, fugiu para Taiwan.",
      "Suas frases foram reunidas no Livro Vermelho.",
      "Líder comunista que proclamou a República Popular da China em 1949.",
    ],
    fato: "Líder da Revolução Chinesa de 1949",
  },
  {
    id: "rosa-parks",
    nome: "Rosa Parks",
    lugar: "Estados Unidos · 1913–2005",
    quem: "Costureira negra que, em 1955, na cidade de Montgomery (Alabama), recusou-se a ceder seu lugar no ônibus a um homem branco, como exigia a lei de segregação. Sua prisão deu início a um boicote de mais de um ano aos ônibus, que projetou Martin Luther King.",
    gancho: "Rosa ficou sentada para que os outros pudessem se levantar. Rosa Parks \"parou\" os ônibus: Parks → parar.",
    palavras: ["Ônibus", "Montgomery, 1955", "Segregação racial", "Boicote"],
    pistas: [
      "Sua prisão provocou um boicote que durou 381 dias.",
      "O episódio aconteceu em Montgomery, no Alabama, em 1955.",
      "Era costureira e militante da causa negra.",
      "Recusou-se a ceder o lugar no ônibus a um branco.",
    ],
    fato: "Recusou-se a ceder o lugar no ônibus em 1955",
  },
  {
    id: "luther-king",
    nome: "Martin Luther King",
    lugar: "Estados Unidos · 1929–1968",
    quem: "Pastor batista e principal líder do movimento pelos direitos civis dos negros nos EUA. Defendia a não violência, inspirado em Gandhi. Fez o discurso \"Eu tenho um sonho\" na Marcha sobre Washington (1963), recebeu o Nobel da Paz em 1964 e foi assassinado em 1968.",
    gancho: "King é o \"rei\" do sonho: \"I have a dream\". King = Paz, pastor, pacífico. É o Gandhi dos Estados Unidos.",
    palavras: ["Direitos civis", "Não violência", "\"Eu tenho um sonho\"", "Nobel da Paz 1964"],
    pistas: [
      "Liderou o boicote aos ônibus de Montgomery.",
      "Foi assassinado em Memphis, em 1968.",
      "Pastor que se inspirava nos métodos de Gandhi.",
      "Autor do discurso \"Eu tenho um sonho\".",
    ],
    fato: "\"Eu tenho um sonho\": direitos civis sem violência",
  },
  {
    id: "malcolm-x",
    nome: "Malcolm X",
    lugar: "Estados Unidos · 1925–1965",
    quem: "Líder negro norte-americano ligado à Nação do Islã. Defendia o orgulho negro, a autodefesa (\"por todos os meios necessários\") e criticava a estratégia pacífica e integracionista de Luther King. Depois de uma viagem a Meca, moderou suas posições. Foi assassinado em 1965.",
    gancho: "O X substitui o sobrenome que os senhores de escravos deram à sua família: é o nome africano perdido. X também é o oposto do King: King estende a mão, Malcolm fecha o punho.",
    palavras: ["Nação do Islã", "Autodefesa", "Orgulho negro", "\"Por todos os meios necessários\""],
    pistas: [
      "Converteu-se ao islamismo na prisão.",
      "Inspirou movimentos como os Panteras Negras.",
      "Criticava a não violência e defendia a autodefesa dos negros.",
      "Trocou o sobrenome de origem escravista por uma letra.",
    ],
    fato: "Orgulho negro e autodefesa \"por todos os meios\"",
  },
];

const p = criar("figuras");

export const questoesFiguras: Questao[] = [
  p("fig-01", "facil", "Colégio", "Qual desses líderes conduziu a independência da Índia por meio da não violência?",
    ["Mahatma Gandhi", "Mao Tsé-Tung", "Ho Chi Minh", "Nelson Mandela"],
    "Gandhi liderou boicotes, marchas e greves de fome contra o domínio inglês até a independência, em 1947. Mao e Ho Chi Minh chegaram ao poder pela luta armada, e Mandela é da África do Sul.",
    "Gandhi \"ganhou\" sem dar um tiro."),
  p("fig-02", "facil", "Colégio", "Quem ficou 27 anos preso por lutar contra o apartheid e depois foi eleito presidente da África do Sul?",
    ["Nelson Mandela", "Martin Luther King", "Malcolm X", "Mahatma Gandhi"],
    "Mandela foi preso em 1962, libertado em 1990 e eleito em 1994. Luther King e Malcolm X lutaram contra a segregação nos Estados Unidos, não na África.",
    "Mandado para a cela, saiu para mandar no país."),
  p("fig-03", "facil", "Colégio", "Em 1955, uma costureira negra recusou-se a ceder seu lugar no ônibus a um homem branco. Seu nome era:",
    ["Rosa Parks", "Angela Davis", "Coretta King", "Harriet Tubman"],
    "O gesto de Rosa Parks em Montgomery, Alabama, desencadeou um boicote aos ônibus de 381 dias, que terminou com a Justiça declarando ilegal a segregação no transporte.",
    "Rosa Parks \"parou\" os ônibus."),
  p("fig-04", "facil", "Colégio", "O discurso \"Eu tenho um sonho\" (1963) foi feito por:",
    ["Martin Luther King", "Malcolm X", "John Kennedy", "Nelson Mandela"],
    "Luther King falou a cerca de 250 mil pessoas na Marcha sobre Washington, pedindo igualdade entre negros e brancos. No ano seguinte foi aprovada a Lei dos Direitos Civis e ele recebeu o Nobel da Paz.",
    "King = o rei do sonho."),
  p("fig-05", "facil", "Colégio", "Quem liderou a Revolução Chinesa, que criou a República Popular da China em 1949?",
    ["Mao Tsé-Tung", "Ho Chi Minh", "Chiang Kai-shek", "Nikita Kruschev"],
    "Mao comandou os comunistas chineses, apoiado nos camponeses. Chiang Kai-shek era o líder derrotado, que fugiu para Taiwan. Ho Chi Minh é do Vietnã e Kruschev, da URSS."),
  p("fig-06", "facil", "Colégio", "O líder soviético que sucedeu Stalin e defendeu a coexistência pacífica com os EUA foi:",
    ["Nikita Kruschev", "Mikhail Gorbachev", "Vladimir Lenin", "Leon Trotsky"],
    "Kruschev governou de 1953 a 1964. Lenin e Trotsky são da Revolução de 1917; Gorbachev é do fim da URSS, nos anos 1980.",
    "Kruschev \"krushou\" a imagem de Stalin."),
  p("fig-07", "facil", "Colégio", "Salvador Allende e Augusto Pinochet são nomes ligados à história de qual país?",
    ["Chile", "Argentina", "Cuba", "Espanha"],
    "Allende foi o presidente socialista eleito em 1970; Pinochet, o general que o derrubou em 1973 e governou como ditador até 1990.",
    "A antes de P: primeiro Allende, depois Pinochet."),
  p("fig-08", "facil", "Colégio", "Ho Chi Minh foi o principal líder:",
    [
      "da independência do Vietnã e do Vietnã do Norte.",
      "da Revolução Chinesa.",
      "da independência da Coreia.",
      "do Japão na Segunda Guerra Mundial.",
    ],
    "Ho Chi Minh fundou o Viet Minh, derrotou os franceses em 1954 e presidiu o Vietnã do Norte. Morreu em 1969, antes do fim da guerra."),
  p("fig-09", "medio", "ENEM", "Martin Luther King e Malcolm X lutaram contra o racismo nos Estados Unidos nos anos 1960, mas com estratégias diferentes. A diferença central era que:",
    [
      "King defendia a resistência não violenta e a integração; Malcolm X defendia o orgulho negro e o direito à autodefesa.",
      "King defendia a luta armada; Malcolm X defendia as vias judiciais.",
      "King lutava nos EUA; Malcolm X lutava na África do Sul.",
      "King era contra o voto dos negros; Malcolm X era a favor.",
    ],
    "King, pastor cristão inspirado em Gandhi, queria negros e brancos convivendo com direitos iguais, por meio de marchas e boicotes. Malcolm X, muçulmano, desconfiava da integração e dizia que os negros deviam se defender \"por todos os meios necessários\". No fim da vida, as posições dos dois se aproximaram.",
    "King estende a mão, Malcolm fecha o punho."),
  p("fig-10", "medio", "Fuvest", "A experiência de Salvador Allende no Chile (1970–1973) foi acompanhada com atenção no mundo todo porque:",
    [
      "tentava construir o socialismo pela via eleitoral e democrática, sem revolução armada.",
      "foi a primeira revolução comunista da América Latina.",
      "era apoiada pelo governo dos Estados Unidos.",
      "restaurou o livre mercado depois de um período socialista.",
    ],
    "A \"via chilena\" era uma novidade em plena Guerra Fria: um marxista eleito pelo voto, mantendo Congresso, imprensa e partidos. Allende nacionalizou o cobre e os bancos. Enfrentou crise econômica, oposição interna e a hostilidade dos EUA, que ajudaram a desestabilizar o governo. A revolução armada na região foi a cubana (1959)."),
  p("fig-11", "medio", "Unesp", "A ditadura de Augusto Pinochet no Chile caracterizou-se por:",
    [
      "forte repressão política combinada com uma política econômica neoliberal.",
      "estatização da economia e aliança com Cuba.",
      "manutenção do Congresso e das eleições livres.",
      "apoio da União Soviética.",
    ],
    "O regime fechou o Congresso, perseguiu, torturou e matou milhares de opositores. Na economia, aplicou privatizações e abertura de mercado, orientadas por economistas formados em Chicago. Foi um dos primeiros laboratórios do neoliberalismo.",
    "Pinochet: porrete na política, privatização na economia."),
  p("fig-12", "medio", "UERJ", "A Marcha do Sal (1930), liderada por Gandhi, é um exemplo de desobediência civil porque:",
    [
      "os manifestantes descumpriram de forma pública e pacífica uma lei que consideravam injusta.",
      "os indianos atacaram os depósitos de sal do exército inglês.",
      "Gandhi negociou em segredo a redução do imposto.",
      "o protesto foi autorizado pelo governo britânico.",
    ],
    "Os ingleses tinham o monopólio do sal e cobravam imposto sobre ele. Gandhi caminhou quase 400 km até o litoral e recolheu sal do mar, o que era proibido. Milhares o imitaram e foram presos sem reagir. Desobediência civil é isto: violar a lei injusta abertamente e aceitar a punição para expor a injustiça."),
  p("fig-13", "medio", "Unicamp", "Uma particularidade da revolução liderada por Mao Tsé-Tung, em comparação com a Revolução Russa, foi:",
    [
      "ter os camponeses, e não os operários urbanos, como principal força revolucionária.",
      "ter sido feita sem luta armada.",
      "ter mantido a propriedade privada da terra.",
      "ter sido apoiada pelos Estados Unidos.",
    ],
    "A China era um país agrário, com poucos operários. Mao adaptou o marxismo: a revolução viria do campo e cercaria as cidades, numa longa guerra de guerrilhas. Esse modelo inspirou movimentos na Ásia, inclusive no Vietnã."),
  p("fig-14", "medio", "ENEM", "O boicote aos ônibus de Montgomery, iniciado após a prisão de Rosa Parks, mostrou que:",
    [
      "a pressão econômica e a mobilização pacífica podiam derrubar leis de segregação.",
      "a segregação racial não existia no sul dos Estados Unidos.",
      "o movimento negro dependia do uso da força.",
      "as leis de segregação tinham apoio da Suprema Corte até o fim do século.",
    ],
    "Os negros eram a maioria dos passageiros. Sem eles, as empresas de ônibus tiveram enorme prejuízo durante 381 dias. Em 1956, a Suprema Corte declarou inconstitucional a segregação nos ônibus. O boicote revelou um jovem pastor de 26 anos: Martin Luther King."),
  p("fig-15", "dificil", "Fuvest", "Kruschev foi afastado do poder em 1964 por seus próprios companheiros de partido. Entre os motivos estavam:",
    [
      "o desgaste causado pelo recuo na Crise dos Mísseis, o rompimento com a China e os fracassos na agricultura.",
      "sua tentativa de restaurar o capitalismo na União Soviética.",
      "a derrota militar da URSS para os Estados Unidos no Vietnã.",
      "a queda do Muro de Berlim.",
    ],
    "A retirada dos mísseis de Cuba foi vista em Moscou como humilhação; a crítica a Stalin e a coexistência pacífica levaram ao rompimento com Mao; e suas reformas agrícolas não deram resultado. Foi substituído por Leonid Brejnev, que endureceu o regime."),
  p("fig-16", "dificil", "Unicamp", "O golpe de 1973 no Chile insere-se no contexto da Guerra Fria na América Latina porque:",
    [
      "contou com o apoio dos Estados Unidos, que desde a Revolução Cubana agiam para impedir governos de esquerda na região.",
      "foi organizado pela União Soviética para substituir Allende por um líder mais radical.",
      "pôs fim à última ditadura militar sul-americana.",
      "resultou de uma invasão do Chile por tropas argentinas.",
    ],
    "O governo Nixon financiou a oposição e trabalhou para asfixiar a economia chilena. O Chile juntou-se a outras ditaduras militares do Cone Sul, como Brasil (1964), Uruguai (1973) e Argentina (1976), que depois cooperaram na repressão por meio da Operação Condor."),
  p("fig-17", "dificil", "UERJ", "Depois de sua peregrinação a Meca, em 1964, Malcolm X:",
    [
      "rompeu com a Nação do Islã e passou a admitir a cooperação com brancos na luta contra o racismo.",
      "abandonou o islamismo e tornou-se pastor batista.",
      "passou a defender a segregação racial.",
      "mudou-se para a África do Sul para lutar ao lado de Mandela.",
    ],
    "Ao ver muçulmanos de todas as cores rezando juntos, Malcolm reviu a ideia de que todos os brancos eram inimigos. Fundou sua própria organização e passou a tratar o racismo como questão de direitos humanos. Foi assassinado em 1965 por membros da Nação do Islã."),
  p("fig-18", "dificil", "Fuvest", "Em 1967, Martin Luther King passou a criticar publicamente a Guerra do Vietnã. Seu argumento era que:",
    [
      "a guerra consumia recursos que deveriam combater a pobreza e enviava jovens negros para morrer por liberdades que não tinham em casa.",
      "os Estados Unidos deveriam usar armas nucleares para encerrar o conflito.",
      "os negros deveriam se alistar em massa para provar seu patriotismo.",
      "a guerra era necessária para conter o comunismo.",
    ],
    "King ligou racismo, pobreza e guerra, o que lhe custou o apoio do presidente Johnson e de parte da imprensa. A posição mostra como o movimento dos direitos civis e os protestos contra a guerra se cruzaram nos anos 1960. Ele foi assassinado um ano depois, em abril de 1968."),
  p("fig-19", "dificil", "Unicamp", "A Revolução Cultural (1966–1976), lançada por Mao Tsé-Tung, tinha como objetivo declarado:",
    [
      "eliminar os \"resquícios burgueses\" e os adversários de Mao no partido, mobilizando os jovens da Guarda Vermelha.",
      "abrir a economia chinesa ao capital estrangeiro.",
      "aproximar a China da União Soviética.",
      "restaurar as tradições do confucionismo.",
    ],
    "Depois do fracasso do Grande Salto para Frente, que provocou uma fome com milhões de mortos, Mao perdeu espaço. Com a Revolução Cultural retomou o controle: estudantes perseguiram professores, intelectuais e dirigentes, e o culto ao líder chegou ao auge. A abertura econômica só veio após sua morte, com Deng Xiaoping."),
  p("fig-20", "dificil", "UERJ", "O fim do apartheid, no início dos anos 1990, resultou da combinação de:",
    [
      "resistência interna da população negra, sanções e boicotes internacionais e negociação entre Mandela e o governo De Klerk.",
      "invasão militar da África do Sul pelas Nações Unidas.",
      "vitória de uma guerrilha apoiada pelos Estados Unidos.",
      "decisão espontânea da minoria branca, sem pressões.",
    ],
    "Décadas de protestos (como o levante de Soweto, em 1976), o isolamento econômico e esportivo do país e o fim da Guerra Fria tornaram o regime insustentável. Mandela foi libertado em 1990, negociou a transição e venceu as primeiras eleições multirraciais, em 1994."),
];

export const eventos: Evento[] = [
  { ano: 1946, texto: "Promulgada a nova Constituição democrática do Brasil" },
  { ano: 1947, texto: "Cassação do registro do PCB e lançamento do Plano Marshall" },
  { ano: 1949, texto: "Criação da OTAN e vitória de Mao na China" },
  { ano: 1953, texto: "Criação da Petrobras e morte de Stalin" },
  { ano: 1954, texto: "Suicídio de Vargas e derrota francesa em Dien Bien Phu" },
  { ano: 1955, texto: "Rosa Parks é presa em Montgomery; criado o Pacto de Varsóvia" },
  { ano: 1956, texto: "JK toma posse; Kruschev denuncia os crimes de Stalin" },
  { ano: 1960, texto: "Inauguração de Brasília" },
  { ano: 1961, texto: "Renúncia de Jânio e construção do Muro de Berlim" },
  { ano: 1962, texto: "Crise dos Mísseis em Cuba" },
  { ano: 1963, texto: "Plebiscito devolve o presidencialismo; \"Eu tenho um sonho\"" },
  { ano: 1964, texto: "Golpe contra Jango e incidente do Golfo de Tonkin" },
  { ano: 1965, texto: "Assassinato de Malcolm X" },
  { ano: 1968, texto: "Ofensiva do Tet, Maio francês e assassinato de Luther King" },
  { ano: 1969, texto: "Morte de Ho Chi Minh" },
  { ano: 1973, texto: "Acordos de Paris e golpe de Pinochet no Chile" },
  { ano: 1975, texto: "Queda de Saigon e independência de Angola" },
  { ano: 1990, texto: "Mandela é libertado da prisão" },
];
