import type { Questao } from "@/lib/tipos";
import { criar } from "./criar";

const d = criar("dutra");
const v = criar("vargas");
const k = criar("jk");
const j = criar("janio");
const g = criar("jango");

export const questoesBrasil: Questao[] = [
  // ───────── Governo Dutra ─────────
  d("dut-01", "facil", "Colégio", "A política externa do governo Dutra (1946–1951) foi marcada por:",
    [
      "alinhamento aos Estados Unidos, com rompimento de relações com a União Soviética.",
      "neutralidade entre os dois blocos da Guerra Fria.",
      "aproximação comercial e diplomática com os países socialistas.",
      "defesa de uma política externa independente das grandes potências.",
    ],
    "Dutra governou no começo da Guerra Fria e colocou o Brasil ao lado dos Estados Unidos: rompeu relações com a URSS em 1947 e assinou o TIAR no mesmo ano. A \"política externa independente\" só aparece depois, com Jânio Quadros e João Goulart.",
    "Dutra = \"Do lado dos EUA\". Independente é Jânio."),
  d("dut-02", "facil", "Colégio", "A Constituição de 1946 representou:",
    [
      "a volta da democracia liberal, com três poderes independentes e eleições diretas.",
      "a criação do Estado Novo e a concentração de poderes no presidente.",
      "a implantação do parlamentarismo no Brasil.",
      "a extensão do direito de voto aos analfabetos.",
    ],
    "A Constituição de 1946 encerrou juridicamente o Estado Novo: devolveu a independência dos poderes, a autonomia dos estados, o voto direto e secreto e as liberdades civis. O parlamentarismo só veio em 1961, e os analfabetos só votaram a partir de 1985.",
    "1946 = depois da ditadura de Vargas (1937–45), volta a democracia."),
  d("dut-03", "facil", "Colégio", "Em 1947, durante o governo Dutra, qual partido teve o registro cassado pela Justiça Eleitoral?",
    ["Partido Comunista do Brasil (PCB)", "União Democrática Nacional (UDN)", "Partido Trabalhista Brasileiro (PTB)", "Partido Social Democrático (PSD)"],
    "O PCB havia saído forte das eleições de 1945, com um senador (Luís Carlos Prestes) e 14 deputados. No clima anticomunista da Guerra Fria, seu registro foi cassado em 1947 e os parlamentares perderam o mandato em 1948. PSD, PTB e UDN foram os três grandes partidos legais do período.",
    "Guerra Fria + aliado dos EUA = comunistas na ilegalidade."),
  d("dut-04", "facil", "Colégio", "O Plano SALTE, lançado no governo Dutra, tinha como prioridades:",
    [
      "saúde, alimentação, transporte e energia.",
      "segurança, agricultura, lazer, trabalho e educação.",
      "siderurgia, automóveis, laticínios, têxteis e eletrônicos.",
      "a construção de uma nova capital no interior do país.",
    ],
    "SALTE é uma sigla: Saúde, ALimentação, Transporte e Energia. Foi a principal tentativa de planejamento do governo Dutra, mas teve poucos resultados por falta de recursos. A nova capital é obra de JK.",
    "A própria sigla é a resposta: S-AL-T-E."),
  d("dut-05", "facil", "Colégio", "Verdadeiro ou falso: a Constituição de 1946 garantiu o voto aos analfabetos.",
    ["Falso", "Verdadeiro"],
    "Falso. O voto era obrigatório para os maiores de 18 anos alfabetizados. Como grande parte da população era analfabeta, mais da metade dos adultos ficava fora das eleições. O voto do analfabeto só foi permitido em 1985."),
  d("dut-06", "medio", "ENEM", "Embora eleito pelo voto e governando sob uma Constituição democrática, o governo Dutra adotou medidas que limitaram a participação política. Um exemplo dessas medidas foi:",
    [
      "a intervenção em sindicatos e a cassação dos mandatos dos parlamentares comunistas.",
      "o fechamento do Congresso Nacional e a suspensão das eleições.",
      "a censura prévia à imprensa por um departamento de propaganda.",
      "a nomeação de interventores para governar os estados.",
    ],
    "Dutra não fechou o Congresso nem suspendeu eleições, coisas típicas do Estado Novo (assim como o DIP e os interventores). O autoritarismo do seu governo apareceu na repressão ao movimento operário, com intervenção em centenas de sindicatos e restrição das greves, e na cassação do PCB (1947) e de seus parlamentares (1948).",
    "Democracia \"com freio\": tudo funciona, menos para comunistas e grevistas."),
  d("dut-07", "medio", "Fuvest", "No início do governo Dutra, a política econômica caracterizou-se por:",
    [
      "liberalização das importações, que consumiu rapidamente as reservas acumuladas durante a Segunda Guerra.",
      "forte controle estatal do câmbio e monopólio do petróleo.",
      "ruptura com o Fundo Monetário Internacional.",
      "reforma agrária e limitação da remessa de lucros ao exterior.",
    ],
    "O Brasil saiu da guerra com reservas em moeda estrangeira. O governo Dutra, de orientação liberal, abriu as importações e as reservas foram gastas em poucos anos, em boa parte com bens de consumo. Monopólio do petróleo é Vargas (1953), ruptura com o FMI é JK (1959) e remessa de lucros é Jango (1962)."),
  d("dut-08", "medio", "Unesp", "O Tratado Interamericano de Assistência Recíproca (TIAR), assinado em 1947 no Brasil, estabelecia que:",
    [
      "um ataque a qualquer país americano seria considerado um ataque a todos.",
      "os países latino-americanos receberiam ajuda financeira nos moldes do Plano Marshall.",
      "as bases militares dos Estados Unidos seriam retiradas da América Latina.",
      "os países signatários manteriam neutralidade na Guerra Fria.",
    ],
    "O TIAR, ou Tratado do Rio, é um pacto de defesa coletiva: agressão a um é agressão a todos. Na prática, amarrou a América Latina à estratégia militar dos Estados Unidos na Guerra Fria. A ajuda econômica nos moldes do Plano Marshall nunca veio, o que gerou frustração (e mais tarde a Operação Pan-Americana de JK).",
    "TIAR é uma espécie de \"OTAN das Américas\", dois anos antes da OTAN."),
  d("dut-09", "medio", "Unicamp", "Sobre os direitos dos trabalhadores na Constituição de 1946, é correto afirmar que ela:",
    [
      "reconheceu o direito de greve, mas manteve a estrutura sindical atrelada ao Estado.",
      "extinguiu a legislação trabalhista criada no período Vargas.",
      "garantiu total liberdade e autonomia sindical.",
      "estendeu todos os direitos trabalhistas aos trabalhadores rurais.",
    ],
    "A Constituição reconheceu a greve como direito, mas deixou sua regulamentação para a lei, e na prática o governo a restringiu. A estrutura corporativa montada por Vargas (sindicato único, imposto sindical, controle do Ministério do Trabalho) continuou de pé, e a CLT também. Os trabalhadores rurais só ganharam um estatuto próprio em 1963."),
  d("dut-10", "dificil", "Fuvest", "\"A democracia de 1946 nasceu com limites.\" Essa afirmação pode ser justificada pelo fato de que, no governo Dutra:",
    [
      "as instituições liberais conviveram com a exclusão dos analfabetos e com a repressão a comunistas e sindicatos.",
      "os partidos políticos nacionais continuaram proibidos.",
      "o presidente governou por decretos, sem Congresso em funcionamento.",
      "as eleições para presidente passaram a ser indiretas.",
    ],
    "O período 1946–1964 teve partidos nacionais, Congresso aberto e eleições diretas, mas a democracia era restrita: analfabetos não votavam, o PCB foi posto na ilegalidade e o movimento sindical ficou sob controle. É a combinação de forma democrática com práticas autoritárias que a frase aponta."),
  d("dut-11", "dificil", "Unicamp", "Dutra, ex-ministro da Guerra do Estado Novo, foi eleito em 1945 pelo PSD com o apoio decisivo de Getúlio Vargas. Esse dado indica que a redemocratização:",
    [
      "manteve no poder grupos e estruturas vindos do Estado Novo.",
      "significou a vitória da oposição liberal reunida na UDN.",
      "afastou definitivamente Vargas e seus aliados da política.",
      "foi conduzida pelos comunistas e pelos sindicatos independentes.",
    ],
    "Vargas foi deposto em 1945, mas os dois partidos criados à sua sombra, o PSD (interventores e elites rurais) e o PTB (trabalhadores urbanos), venceram a eleição. A UDN e seu candidato, o brigadeiro Eduardo Gomes, foram derrotados. O próprio Vargas elegeu-se senador e voltaria à presidência em 1950.",
    "O slogan da virada foi \"Ele disse: vote em Dutra\". Ele = Getúlio."),
  d("dut-12", "dificil", "UERJ", "Criada em 1949, a Escola Superior de Guerra (ESG) é importante para entender a história política brasileira porque:",
    [
      "difundiu entre militares e civis a doutrina de segurança nacional, que mais tarde embasou o golpe de 1964.",
      "formou os oficiais que defenderam o monopólio estatal do petróleo.",
      "organizou a participação brasileira na Segunda Guerra Mundial.",
      "defendia o afastamento dos militares da vida política.",
    ],
    "Inspirada no National War College dos Estados Unidos, a ESG elaborou a ideia de que o inimigo principal era interno (a \"subversão comunista\") e de que desenvolvimento e segurança andavam juntos. Muitos líderes de 1964, como Castelo Branco e Golbery, passaram por ela. A FEB lutou na Itália em 1944–45, antes da ESG existir."),

  // ───────── Vargas, populismo, UDN ─────────
  v("var-01", "facil", "Colégio", "A principal oposição a Getúlio Vargas no período democrático veio:",
    [
      "da UDN, tendo o jornalista Carlos Lacerda como voz mais conhecida.",
      "do PTB, liderado por João Goulart.",
      "do PSD, liderado por Juscelino Kubitschek.",
      "do PCB, liderado por Leonel Brizola.",
    ],
    "A UDN (União Democrática Nacional) nasceu em 1945 justamente para combater Vargas. Carlos Lacerda atacava o presidente diariamente em seu jornal, a Tribuna da Imprensa. PTB e PSD eram os partidos varguistas, e Brizola era do PTB.",
    "UDN = \"União De Não-getulistas\". Lacerda era chamado de \"o Corvo\"."),
  v("var-02", "facil", "Colégio", "A campanha \"O petróleo é nosso\" resultou, em 1953, na criação:",
    ["da Petrobras.", "da Companhia Siderúrgica Nacional.", "da Sudene.", "da Eletrobras."],
    "A Petrobras foi criada em outubro de 1953, no segundo governo Vargas, com monopólio estatal da pesquisa, extração e refino do petróleo. A CSN é do primeiro governo Vargas (1941), a Sudene é de JK (1959) e a Eletrobras só foi instalada em 1962."),
  v("var-03", "facil", "Colégio", "No debate econômico dos anos 1950, eram chamados de \"entreguistas\" os que defendiam:",
    [
      "a abertura da economia ao capital estrangeiro.",
      "o monopólio do Estado sobre o petróleo.",
      "a entrega de terras aos camponeses.",
      "a estatização dos bancos.",
    ],
    "\"Entreguista\" era o apelido que os nacionalistas davam a quem, na visão deles, queria \"entregar\" as riquezas do país às empresas estrangeiras. Esse grupo preferia menos Estado na economia e alinhamento com os Estados Unidos. Monopólio do petróleo era a bandeira do outro lado, o nacionalista.",
    "Entreguista \"entrega\" para o estrangeiro."),
  v("var-04", "facil", "Colégio", "O segundo governo Vargas terminou em agosto de 1954 com:",
    [
      "o suicídio do presidente.",
      "a renúncia do presidente e sua ida para o exílio.",
      "um golpe militar que fechou o Congresso.",
      "a derrota de Vargas nas eleições.",
    ],
    "Pressionado pelos militares a renunciar depois do atentado da Rua Tonelero, Vargas se matou com um tiro no peito em 24 de agosto de 1954 e deixou a Carta-Testamento. Quem renunciou foi Jânio (1961), e golpe militar com Congresso fechado não ocorreu em 1954.",
    "\"Saio da vida para entrar na História.\""),
  v("var-05", "facil", "Colégio", "Na história política brasileira, o termo populismo se refere a:",
    [
      "um estilo de governo baseado na relação direta entre um líder carismático e as massas urbanas.",
      "um regime em que o povo governa por meio de assembleias, sem representantes.",
      "uma ditadura militar apoiada pelas elites rurais.",
      "um sistema em que só os mais ricos têm direito a voto.",
    ],
    "O populismo descreve líderes que falam diretamente ao povo das cidades, concedem direitos e, ao mesmo tempo, controlam a organização dos trabalhadores. Não é democracia direta, nem ditadura militar, nem voto censitário."),
  v("var-06", "medio", "ENEM", "Uma característica central do populismo brasileiro (1945–1964) foi:",
    [
      "a concessão de direitos trabalhistas combinada com o controle dos sindicatos pelo Estado.",
      "a defesa da luta de classes e da revolução socialista.",
      "a exclusão completa dos trabalhadores urbanos da vida política.",
      "a rejeição da industrialização em favor da agricultura de exportação.",
    ],
    "O líder populista incorpora os trabalhadores urbanos à política, mas de forma tutelada: dá direitos e mantém os sindicatos presos ao Ministério do Trabalho. O discurso é de conciliação entre patrões e empregados em nome da nação, o oposto da luta de classes, e o projeto era industrializador.",
    "Populismo = dá com uma mão (direitos) e segura com a outra (controle)."),
  v("var-07", "medio", "Fuvest", "No início dos anos 1950, os nacionalistas defendiam, em linhas gerais:",
    [
      "industrialização conduzida pelo Estado e controle nacional dos setores estratégicos.",
      "livre entrada de empresas estrangeiras na exploração do petróleo.",
      "redução do papel do Estado e privatização das empresas públicas.",
      "prioridade à agricultura de exportação como base da economia.",
    ],
    "Para os nacionalistas, o Brasil só seria independente de verdade se controlasse petróleo, energia e indústria de base, com o Estado como investidor principal. As outras alternativas descrevem posições liberais, associadas aos adversários que eles chamavam de entreguistas."),
  v("var-08", "medio", "Unesp", "O atentado da Rua Tonelero, em agosto de 1954, teve como consequência imediata:",
    [
      "o agravamento da crise política, com militares exigindo a saída de Vargas.",
      "a cassação do registro da UDN.",
      "a decretação do Estado Novo.",
      "a criação da Petrobras.",
    ],
    "O alvo era Carlos Lacerda, que ficou ferido; o major da Aeronáutica Rubens Vaz morreu. A investigação chegou a Gregório Fortunato, chefe da guarda pessoal de Vargas. A Aeronáutica e depois os generais passaram a exigir a renúncia, e o presidente se matou dias depois. O Estado Novo é de 1937 e a Petrobras já existia desde 1953.",
    "Tonelero → Lacerda ferido → major morto → militares contra Vargas → suicídio."),
  v("var-09", "medio", "UERJ", "Em 1954, o ministro do Trabalho João Goulart propôs um aumento de 100% no salário mínimo. A proposta provocou:",
    [
      "a reação de militares e empresários, expressa no Manifesto dos Coronéis, e a saída do ministro.",
      "o apoio entusiasmado da UDN ao governo Vargas.",
      "o fim das greves operárias no país.",
      "a ruptura entre Vargas e o PTB.",
    ],
    "O aumento assustou empresários e oficiais do Exército, que no Manifesto dos Coronéis reclamaram que um operário passaria a ganhar quase como um oficial. Jango deixou o ministério, mas Vargas concedeu o aumento no 1º de maio de 1954, aproximando-se dos trabalhadores e irritando ainda mais a oposição."),
  v("var-10", "dificil", "Fuvest", "\"Mais uma vez as forças e os interesses contra o povo coordenaram-se e se desencadeiam sobre mim.\" (Carta-Testamento, 1954)\n\nNa Carta-Testamento, Vargas atribui a crise de seu governo:",
    [
      "à pressão de grupos internacionais e de seus aliados internos, contrários à sua política nacionalista e trabalhista.",
      "à radicalização dos sindicatos e do Partido Comunista.",
      "ao fracasso de sua política econômica liberal.",
      "à falta de apoio popular e às greves contra o governo.",
    ],
    "A Carta cita a campanha contra a Petrobras e a Eletrobras, os lucros das empresas estrangeiras e a reação ao aumento do salário mínimo. Vargas se apresenta como vítima de uma aliança entre interesses externos e a oposição interna. O efeito foi enorme: a comoção popular virou-se contra a UDN e os jornais de oposição."),
  v("var-11", "dificil", "Unicamp", "Muitos historiadores afirmam que o suicídio de Vargas \"adiou o golpe por dez anos\". A frase significa que:",
    [
      "a comoção popular enfraqueceu a oposição e impediu, naquele momento, que os grupos antigetulistas tomassem o poder.",
      "os militares desistiram definitivamente de intervir na política.",
      "a UDN venceu as eleições presidenciais seguintes.",
      "o PTB foi extinto e os trabalhistas saíram da cena política.",
    ],
    "Em agosto de 1954, a UDN e setores militares estavam perto de derrubar Vargas. O suicídio inverteu o jogo: multidões atacaram jornais de oposição e Lacerda teve de se esconder. Os herdeiros de Vargas (JK e Jango) venceram em 1955. As mesmas forças voltaram em 1955, em 1961 e, enfim, em 1964."),
  v("var-12", "dificil", "UERJ", "A lei que criou a Petrobras, em 1953, representou uma vitória parcial dos nacionalistas porque:",
    [
      "estabeleceu o monopólio estatal da pesquisa, da lavra e do refino, mas deixou a distribuição aberta a empresas privadas.",
      "proibiu qualquer empresa estrangeira de vender combustíveis no Brasil.",
      "foi aprovada sem nenhum apoio da UDN no Congresso.",
      "entregou a exploração do petróleo a empresas mistas com capital norte-americano.",
    ],
    "O monopólio cobria pesquisa, extração (lavra), refino e transporte, mas a distribuição continuou com empresas privadas, inclusive estrangeiras. Curiosidade que cai em prova: parte da UDN votou a favor do monopólio, numa manobra para não deixar a bandeira nacionalista só com Vargas."),
  v("var-13", "dificil", "Fuvest", "A principal crítica da UDN ao varguismo pode ser resumida como:",
    [
      "denúncia da corrupção e da \"demagogia\" do governo e defesa do liberalismo, ainda que o partido recorresse aos militares para chegar ao poder.",
      "defesa do socialismo e da reforma agrária contra o conservadorismo de Vargas.",
      "exigência de maior intervenção do Estado na economia.",
      "defesa do voto dos analfabetos e da ampliação dos direitos trabalhistas.",
    ],
    "A UDN falava em moralidade (o \"mar de lama\"), liberdades e economia de mercado. Mas, como perdia as eleições presidenciais, apelou várias vezes para a intervenção militar: em 1954, em 1955 (contra a posse de JK) e em 1964. Por isso foi chamada de partido de \"liberais golpistas\"."),

  // ───────── JK ─────────
  k("jk-01", "facil", "Colégio", "O lema do governo Juscelino Kubitschek era:",
    ["\"Cinquenta anos em cinco\".", "\"O petróleo é nosso\".", "\"Varre, varre, vassourinha\".", "\"Brasil: ame-o ou deixe-o\"."],
    "JK prometia fazer o país avançar cinquenta anos em cinco de mandato. \"O petróleo é nosso\" é da campanha da Petrobras, a vassourinha é de Jânio Quadros e \"ame-o ou deixe-o\" é da ditadura militar."),
  k("jk-02", "facil", "Colégio", "A obra mais simbólica do governo JK, inaugurada em 1960, foi:",
    ["a construção de Brasília.", "a criação da Petrobras.", "a rodovia Transamazônica.", "a usina de Itaipu."],
    "Brasília, a nova capital no Planalto Central, foi inaugurada em 21 de abril de 1960, com plano urbanístico de Lúcio Costa e prédios de Oscar Niemeyer. Era a \"meta-síntese\" do Plano de Metas. Transamazônica e Itaipu são da ditadura militar.",
    "21 de abril: dia de Tiradentes e aniversário de Brasília."),
  k("jk-03", "facil", "Colégio", "O programa de desenvolvimento do governo JK chamava-se:",
    ["Plano de Metas.", "Plano SALTE.", "Plano Trienal.", "Reformas de Base."],
    "O Plano de Metas tinha trinta metas em cinco setores, mais Brasília. SALTE é de Dutra, e Plano Trienal e Reformas de Base são do governo Jango.",
    "Dutra = SALTE · JK = Metas · Jango = Trienal e Reformas de Base."),
  k("jk-04", "facil", "Colégio", "Um setor industrial que cresceu muito no governo JK, com a chegada de empresas estrangeiras, foi o:",
    ["automobilístico.", "petrolífero.", "de informática.", "aeroespacial."],
    "JK atraiu montadoras como Volkswagen, Ford e GM, que se instalaram principalmente no ABC paulista. O petróleo era monopólio da Petrobras, e informática e aeroespacial são de décadas depois."),
  k("jk-05", "medio", "ENEM", "O modelo econômico do governo JK baseou-se:",
    [
      "na combinação de investimento do Estado, capital privado nacional e forte entrada de capital estrangeiro.",
      "na estatização de todas as indústrias instaladas no país.",
      "no fechamento da economia às empresas multinacionais.",
      "na prioridade à agricultura familiar e à reforma agrária.",
    ],
    "É o chamado tripé: o Estado cuidava da infraestrutura e da indústria de base, o capital nacional dos bens de consumo comuns e as multinacionais dos bens duráveis, como automóveis e eletrodomésticos. Por isso se diz que JK era desenvolvimentista, mas não nacionalista no sentido de Vargas.",
    "Vargas: desenvolver com capital nacional. JK: desenvolver com quem tiver capital."),
  k("jk-06", "medio", "Fuvest", "Entre as consequências negativas da política econômica de JK estão:",
    [
      "o aumento da inflação e da dívida externa.",
      "a queda da produção industrial.",
      "o esvaziamento das cidades e a volta ao campo.",
      "a diminuição das desigualdades entre as regiões do país.",
    ],
    "Brasília e as metas foram pagas com emissão de moeda e empréstimos, o que gerou inflação e endividamento, herança que pesou sobre Jânio e Jango. A indústria cresceu muito, as cidades incharam com o êxodo rural e a indústria se concentrou ainda mais no Sudeste."),
  k("jk-07", "medio", "Unesp", "Em 1959, o governo JK criou a Sudene com o objetivo de:",
    [
      "promover o desenvolvimento do Nordeste e reduzir as desigualdades regionais.",
      "coordenar a construção de Brasília.",
      "controlar a entrada de capital estrangeiro.",
      "administrar o monopólio estatal do petróleo.",
    ],
    "A Superintendência do Desenvolvimento do Nordeste foi idealizada pelo economista Celso Furtado, depois de uma grande seca em 1958. A ideia era industrializar a região em vez de apenas combater os efeitos da seca. A construção de Brasília ficou com a Novacap."),
  k("jk-08", "medio", "UERJ", "A opção do governo JK pelo transporte rodoviário está ligada:",
    [
      "à implantação da indústria automobilística e à integração do interior com a nova capital.",
      "à falta de petróleo importado no período.",
      "à pressão das companhias ferroviárias inglesas.",
      "à prioridade dada às exportações agrícolas por via marítima.",
    ],
    "Estradas como a Belém–Brasília ligavam a nova capital ao resto do país e criavam mercado para os carros e caminhões fabricados aqui. A escolha deixou as ferrovias em segundo plano e tornou o Brasil dependente de rodovias e de petróleo até hoje."),
  k("jk-09", "medio", "Unicamp", "Em novembro de 1955, o general Henrique Lott liderou um movimento militar que:",
    [
      "garantiu a posse de JK e Jango, eleitos naquele ano, contra uma tentativa de impedi-la.",
      "depôs JK e instaurou uma junta militar.",
      "fechou o Congresso e cancelou as eleições.",
      "levou a UDN à presidência da República.",
    ],
    "JK venceu com cerca de 36% dos votos, e a UDN alegou que ele não tinha maioria absoluta, tentando barrar a posse. O ministro da Guerra, general Lott, deu o chamado \"golpe preventivo\" de 11 de novembro para garantir o resultado das urnas. É um caso raro de intervenção militar para cumprir a Constituição.",
    "Lott = legalista. Interveio para que o eleito tomasse posse."),
  k("jk-10", "dificil", "Fuvest", "Em 1959, JK rompeu as negociações com o Fundo Monetário Internacional (FMI). A razão do rompimento foi:",
    [
      "a recusa do governo em cortar gastos e investimentos, como o Fundo exigia para combater a inflação.",
      "a exigência do FMI de que o Brasil estatizasse as multinacionais.",
      "a aproximação do Brasil com a União Soviética.",
      "a decisão de JK de suspender a construção de Brasília.",
    ],
    "O FMI condicionava novos empréstimos a um plano de austeridade, o que obrigaria a frear o Plano de Metas e as obras de Brasília. JK preferiu romper, gesto que agradou os nacionalistas no fim do mandato. É uma contradição interessante: o presidente que mais abriu o país ao capital estrangeiro brigou com o FMI."),
  k("jk-11", "dificil", "Unicamp", "A Operação Pan-Americana (OPA), proposta por JK ao presidente Eisenhower em 1958, defendia que:",
    [
      "o combate ao subdesenvolvimento na América Latina, com apoio financeiro dos EUA, era a melhor forma de conter o comunismo.",
      "os países latino-americanos rompessem relações com os Estados Unidos.",
      "a América Latina formasse uma aliança militar com a União Soviética.",
      "o Brasil liderasse o movimento dos países não alinhados.",
    ],
    "JK usou a lógica da Guerra Fria a favor do Brasil: a miséria é que alimenta a revolução, logo os EUA deveriam financiar o desenvolvimento da região. A proposta teve pouca resposta até a Revolução Cubana (1959); depois dela, Kennedy lançou a Aliança para o Progresso (1961), com ideias parecidas."),
  k("jk-12", "dificil", "UERJ", "A estabilidade política do governo JK, incomum no período 1946–1964, é geralmente explicada:",
    [
      "pela aliança PSD–PTB no Congresso, pelo crescimento econômico e pela habilidade de conciliar militares e oposição.",
      "pela ausência de qualquer revolta militar durante o mandato.",
      "pela censura à imprensa e pela proibição dos partidos de oposição.",
      "pelo apoio da UDN ao presidente.",
    ],
    "JK tinha maioria com PSD (elites rurais) e PTB (trabalhadores), manteve o legalista Lott no Ministério da Guerra e anistiou os militares rebeldes de Jacareacanga (1956) e Aragarças (1959), duas pequenas revoltas da Aeronáutica. A UDN fez oposição o tempo todo, e a imprensa era livre."),

  // ───────── Jânio e a Legalidade ─────────
  j("jan-01", "facil", "Colégio", "Jânio Quadros renunciou à presidência em:",
    ["agosto de 1961, com menos de sete meses de governo.", "agosto de 1954, após um atentado.", "março de 1964, após um golpe militar.", "dezembro de 1968, após o AI-5."],
    "Jânio tomou posse em janeiro de 1961 e renunciou em 25 de agosto do mesmo ano. Agosto de 1954 é o suicídio de Vargas, e março de 1964 é a queda de Jango.",
    "Agosto é o mês das crises: Vargas (1954) e Jânio (1961)."),
  j("jan-02", "facil", "Colégio", "O símbolo da campanha de Jânio Quadros, que prometia \"varrer a corrupção\", era:",
    ["uma vassoura.", "uma estrela.", "uma enxada.", "um tucano."],
    "\"Varre, varre, vassourinha\" foi o jingle da campanha de 1960. Jânio se apresentava como alguém de fora dos partidos, que moralizaria a política. Venceu com apoio da UDN e votação recorde."),
  j("jan-03", "facil", "Colégio", "Quando Jânio renunciou, o vice-presidente João Goulart estava:",
    ["em viagem oficial à China comunista.", "preso por ordem dos militares.", "exilado no Uruguai.", "em campanha eleitoral no Rio Grande do Sul."],
    "Jango chefiava uma missão comercial à China de Mao. Isso foi usado pelos ministros militares como \"prova\" de sua ligação com o comunismo e como argumento para vetar a posse. O exílio no Uruguai só acontece em 1964."),
  j("jan-04", "facil", "Colégio", "A Campanha da Legalidade, em 1961, foi liderada por:",
    [
      "Leonel Brizola, governador do Rio Grande do Sul.",
      "Carlos Lacerda, governador da Guanabara.",
      "Juscelino Kubitschek, ex-presidente.",
      "Luís Carlos Prestes, líder comunista.",
    ],
    "Brizola, cunhado de Jango, montou no Palácio Piratini a Rede da Legalidade, uma cadeia de rádios que defendia a posse do vice como mandava a Constituição. Lacerda estava do outro lado, contra a posse.",
    "Legalidade = cumprir a lei = dar posse ao vice. Brizola, do RS, pelo rádio."),
  j("jan-05", "facil", "Colégio", "A solução encontrada para a crise de 1961 foi:",
    [
      "adotar o parlamentarismo, permitindo a posse de Jango com poderes reduzidos.",
      "convocar novas eleições presidenciais.",
      "entregar o governo a uma junta militar.",
      "reconduzir Jânio Quadros ao cargo.",
    ],
    "O Congresso aprovou uma emenda que criou o cargo de primeiro-ministro. Jango virou chefe de Estado, e o governo do dia a dia ficou com o primeiro-ministro (o primeiro foi Tancredo Neves). Foi um meio-termo para evitar a guerra civil.",
    "Jango entra, mas \"sem a caneta\"."),
  j("jan-06", "medio", "ENEM", "A política externa independente, iniciada no governo Jânio Quadros, propunha:",
    [
      "manter relações com países dos dois blocos, capitalista e socialista, segundo os interesses do Brasil.",
      "romper relações com os Estados Unidos e aderir ao bloco soviético.",
      "isolar o Brasil do comércio internacional.",
      "apoiar a intervenção militar dos Estados Unidos em Cuba.",
    ],
    "Jânio queria ampliar mercados e autonomia: reatou contatos com o bloco socialista, defendeu a autodeterminação de Cuba e apoiou a descolonização africana. O gesto mais polêmico foi condecorar Che Guevara. Não era adesão ao socialismo; em casa, sua política econômica era conservadora.",
    "Dutra: alinhado. Jânio e Jango: independentes."),
  j("jan-07", "medio", "Fuvest", "O governo Jânio Quadros desagradou a diferentes grupos ao mesmo tempo porque combinou:",
    [
      "uma política econômica de austeridade, que irritou a esquerda, com uma política externa independente, que irritou a direita.",
      "reforma agrária radical com alinhamento total aos Estados Unidos.",
      "estatização de bancos com censura à imprensa de esquerda.",
      "aumento generalizado de salários com rompimento com Cuba.",
    ],
    "Jânio cortou subsídios, desvalorizou a moeda e conteve salários, medidas bem vistas pelo FMI e mal vistas pelos trabalhadores. Ao mesmo tempo, sua diplomacia e a condecoração de Che Guevara revoltaram a UDN e Lacerda, que o haviam apoiado. Sem partido forte e brigado com o Congresso, ficou isolado."),
  j("jan-08", "medio", "Unesp", "A tentativa de impedir a posse de João Goulart em 1961 partiu:",
    [
      "dos três ministros militares, que o associavam ao comunismo e ao sindicalismo.",
      "do Congresso Nacional, que votou seu impeachment.",
      "dos governadores do Nordeste.",
      "do Supremo Tribunal Federal.",
    ],
    "Os ministros da Guerra, da Marinha e da Aeronáutica declararam que a volta de Jango era \"inconveniente\" para a segurança nacional. O Congresso não aceitou o veto, mas negociou a saída parlamentarista. A desconfiança vinha desde 1954, quando Jango era ministro do Trabalho de Vargas."),
  j("jan-09", "medio", "UERJ", "O parlamentarismo implantado em 1961 chegou ao fim quando:",
    [
      "um plebiscito, em janeiro de 1963, decidiu pela volta do presidencialismo.",
      "os militares depuseram o primeiro-ministro.",
      "Jango fechou o Congresso.",
      "a Constituição de 1967 foi promulgada.",
    ],
    "A emenda de 1961 previa uma consulta popular. Jango conseguiu antecipá-la, e em 6 de janeiro de 1963 a grande maioria dos eleitores votou pelo presidencialismo, devolvendo-lhe os plenos poderes.",
    "1961: tiram a caneta. 1963: o povo devolve."),
  j("jan-10", "dificil", "Fuvest", "A interpretação mais aceita pelos historiadores para a renúncia de Jânio Quadros é a de que ele:",
    [
      "tentou um autogolpe: esperava que o Congresso, os militares e o povo recusassem a renúncia e lhe dessem mais poderes.",
      "foi deposto por um movimento militar liderado por Lott.",
      "renunciou por motivo de doença grave.",
      "foi afastado por um processo de impeachment aprovado pela UDN.",
    ],
    "Jânio calculou que ninguém aceitaria a posse de Jango, visto como esquerdista e ainda por cima em viagem à China, e que seria chamado de volta com poderes ampliados. O plano falhou: o Congresso aceitou a renúncia na hora, por se tratar de ato unilateral, e ninguém foi às ruas por ele. Na carta, ele culpou \"forças terríveis\".",
    "Blefou e perdeu: o Congresso disse \"aceito\"."),
  j("jan-11", "dificil", "Unicamp", "A Campanha da Legalidade só teve força para barrar o veto militar porque:",
    [
      "contou com a mobilização popular pelo rádio e com a adesão do III Exército, o que dividiu as Forças Armadas.",
      "recebeu apoio militar dos Estados Unidos.",
      "foi apoiada pela UDN e por Carlos Lacerda.",
      "teve o apoio declarado de Jânio Quadros.",
    ],
    "Quando o comandante do III Exército, general Machado Lopes, aderiu a Brizola, os ministros militares ficaram diante do risco de uma guerra entre unidades do próprio Exército. Essa divisão forçou a negociação. Em 1964 as Forças Armadas agiriam unidas, e por isso o resultado foi outro."),
  j("jan-12", "dificil", "UERJ", "A eleição de 1960 produziu um resultado incomum: presidente e vice de chapas adversárias. Isso foi possível porque:",
    [
      "a Constituição de 1946 previa votação separada para presidente e vice-presidente.",
      "Jânio e Jango pertenciam ao mesmo partido.",
      "o vice era escolhido pelo Congresso Nacional.",
      "Jango foi nomeado pelos ministros militares.",
    ],
    "O eleitor votava separadamente nos dois cargos. Jânio (apoiado pela UDN) venceu para presidente, e Jango (PTB, da chapa do marechal Lott) para vice; houve até comitês \"Jan-Jan\". Assim, a renúncia entregava o governo justamente ao grupo político derrotado, o que explica a gravidade da crise."),

  // ───────── Jango e o golpe ─────────
  g("jng-01", "facil", "Colégio", "O governo de João Goulart terminou em 1964 com:",
    [
      "um golpe civil-militar que o depôs.",
      "sua renúncia voluntária.",
      "o fim normal do mandato.",
      "seu suicídio.",
    ],
    "Jango foi derrubado entre 31 de março e 2 de abril de 1964 por um movimento de militares com apoio de civis. Renúncia é Jânio (1961) e suicídio é Vargas (1954).",
    "Vargas se mata · Jânio renuncia · Jango é deposto."),
  g("jng-02", "facil", "Colégio", "As Reformas de Base defendidas por Jango incluíam:",
    [
      "a reforma agrária.",
      "a privatização das empresas estatais.",
      "o fim das leis trabalhistas.",
      "a volta da monarquia.",
    ],
    "As Reformas de Base eram um conjunto de mudanças estruturais: agrária, urbana, bancária, tributária, educacional e eleitoral (com voto para analfabetos). A agrária era a mais polêmica porque mexia na propriedade da terra."),
  g("jng-03", "facil", "Colégio", "Depois de deposto, João Goulart:",
    ["exilou-se no Uruguai.", "foi preso em Brasília.", "tornou-se senador.", "liderou uma guerrilha no Sul."],
    "Jango foi de Brasília a Porto Alegre e, decidido a não resistir para evitar uma guerra civil, seguiu para o Uruguai. Morreu no exílio, na Argentina, em 1976."),
  g("jng-04", "facil", "Colégio", "O Comício da Central do Brasil, em 13 de março de 1964, ficou conhecido porque nele Jango:",
    [
      "anunciou decretos de reforma, como a desapropriação de terras e a encampação de refinarias.",
      "anunciou sua renúncia.",
      "declarou apoio ao parlamentarismo.",
      "rompeu com os sindicatos.",
    ],
    "Diante de cerca de 150 mil pessoas no Rio de Janeiro, Jango assinou decretos que desapropriavam terras às margens de rodovias e ferrovias federais e encampavam refinarias particulares. O comício foi visto pela oposição como prova de radicalização e acelerou a conspiração.",
    "Dia 13: comício. Dia 19: Marcha. Dia 31: golpe."),
  g("jng-05", "facil", "Colégio", "A Marcha da Família com Deus pela Liberdade, em março de 1964, foi uma manifestação:",
    [
      "de setores conservadores contra o governo Jango.",
      "de camponeses a favor da reforma agrária.",
      "de estudantes contra a ditadura militar.",
      "de sindicatos em apoio às Reformas de Base.",
    ],
    "Organizada em São Paulo por grupos católicos conservadores, entidades femininas, empresários e políticos, reuniu centenas de milhares de pessoas com o discurso de que o país caminhava para o comunismo. Serviu para mostrar aos militares que havia apoio civil para o golpe."),
  g("jng-06", "medio", "ENEM", "O golpe de 1964 é chamado por muitos historiadores de \"civil-militar\" porque:",
    [
      "foi executado pelas Forças Armadas com apoio de empresários, de parte da imprensa, da Igreja e da classe média.",
      "foi executado por civis armados, sem participação do Exército.",
      "levou um presidente civil eleito ao poder.",
      "teve a adesão dos sindicatos e das ligas camponesas.",
    ],
    "As tropas fizeram a derrubada, mas a conspiração envolveu governadores (Lacerda, Magalhães Pinto, Ademar de Barros), empresários reunidos no IPES e no IBAD, grandes jornais e setores da Igreja, além do apoio do governo dos Estados Unidos. Sindicatos e ligas camponesas estavam do lado de Jango."),
  g("jng-07", "medio", "Fuvest", "No contexto da Guerra Fria, o governo dos Estados Unidos em relação ao golpe de 1964:",
    [
      "apoiou os golpistas e chegou a preparar ajuda militar, na operação Brother Sam.",
      "condenou a derrubada de Jango e rompeu relações com o Brasil.",
      "manteve-se neutro e desinformado.",
      "enviou tropas para defender o governo constitucional.",
    ],
    "Depois da Revolução Cubana (1959), Washington temia uma \"nova Cuba\" na América Latina. Os EUA financiaram opositores de Jango e deixaram uma força naval pronta para dar apoio logístico aos golpistas, que não chegou a ser usada porque não houve resistência. O novo governo foi reconhecido imediatamente."),
  g("jng-08", "medio", "Unesp", "O Plano Trienal (1963), elaborado por Celso Furtado, fracassou principalmente porque:",
    [
      "tentou combater a inflação e crescer ao mesmo tempo, sem obter apoio nem dos empresários nem dos trabalhadores.",
      "foi vetado pelos Estados Unidos.",
      "dependia da venda da Petrobras.",
      "propunha o fim da industrialização.",
    ],
    "O plano pedia sacrifícios dos dois lados: contenção de salários e de crédito. Os sindicatos recusaram o arrocho, os empresários recusaram o aperto, e o governo abandonou o plano em poucos meses. Sem controle da inflação, Jango apostou cada vez mais nas Reformas de Base."),
  g("jng-09", "medio", "UERJ", "Entre as reformas de base, a reforma eleitoral previa:",
    [
      "o direito de voto para os analfabetos e para os militares de baixa patente.",
      "o fim do voto secreto.",
      "eleições indiretas para presidente.",
      "a extinção dos partidos políticos.",
    ],
    "Estender o voto a analfabetos e a praças (sargentos, cabos, soldados) ampliaria muito o eleitorado popular, em tese favorável ao PTB. Por isso a proposta assustava os conservadores tanto quanto a reforma agrária."),
  g("jng-10", "medio", "Unicamp", "A Lei de Remessa de Lucros (1962) provocou forte reação porque:",
    [
      "limitava o envio ao exterior dos lucros das empresas estrangeiras instaladas no Brasil.",
      "proibia a exportação de café.",
      "acabava com o imposto de renda.",
      "liberava a entrada de capital estrangeiro sem controle.",
    ],
    "A lei fixava um teto para o lucro que as multinacionais podiam mandar para suas matrizes. Agradou os nacionalistas e contrariou empresas estrangeiras e o governo norte-americano, alimentando a oposição externa a Jango."),
  g("jng-11", "dificil", "Fuvest", "Nos dias que antecederam o golpe, a Revolta dos Marinheiros e o discurso de Jango no Automóvel Clube foram decisivos porque:",
    [
      "convenceram oficiais até então legalistas de que o presidente apoiava a quebra da hierarquia e da disciplina militar.",
      "mostraram que as Forças Armadas estavam unidas em defesa do governo.",
      "provocaram a renúncia dos ministros militares em apoio às reformas.",
      "levaram a UDN a apoiar as Reformas de Base.",
    ],
    "Jango anistiou marinheiros rebelados e discursou para sargentos em 30 de março. Para a oficialidade, hierarquia é sagrada: muitos generais que hesitavam em derrubar um presidente constitucional passaram para o lado dos conspiradores. No dia seguinte, o general Mourão Filho pôs as tropas na estrada em Juiz de Fora.",
    "Mexer na hierarquia foi a gota d'água para os oficiais."),
  g("jng-12", "dificil", "Unicamp", "Na madrugada de 2 de abril de 1964, o presidente do Senado declarou vaga a Presidência da República. O ato é considerado ilegal porque:",
    [
      "João Goulart ainda estava em território brasileiro e não havia renunciado.",
      "o Congresso estava fechado pelos militares.",
      "Jango já havia transferido o cargo ao vice-presidente.",
      "a Constituição proibia o Senado de se reunir à noite.",
    ],
    "Jango estava em Porto Alegre quando Auro de Moura Andrade declarou a vacância. Pela Constituição, o cargo só ficaria vago se o presidente deixasse o país sem autorização. O ato deu aparência de legalidade ao golpe: Ranieri Mazzilli assumiu interinamente, e dias depois o AI-1 abriu caminho para o general Castelo Branco."),
  g("jng-13", "dificil", "UERJ", "A radicalização política no governo Jango pode ser descrita como:",
    [
      "polarização entre esquerdas que exigiam as reformas \"na lei ou na marra\" e direitas que denunciavam uma ameaça comunista, esvaziando o centro.",
      "consenso entre os partidos em torno das Reformas de Base.",
      "disputa restrita ao Congresso, sem participação de movimentos sociais.",
      "conflito entre o presidente e os sindicatos, que apoiavam a UDN.",
    ],
    "De um lado, CGT, UNE, Ligas Camponesas e a ala de Brizola pressionavam por reformas imediatas; de outro, IPES, IBAD, UDN, parte da Igreja e dos militares mobilizavam o medo do comunismo. O PSD, partido de centro que sustentava o governo no Congresso, afastou-se, e Jango ficou sem base para negociar."),
];
