import type { Questao } from "@/lib/tipos";
import { criar } from "./criar";

const d = criar("dutra");
const v = criar("vargas");
const k = criar("jk");
const j = criar("janio");
const g = criar("jango");

export const questoesBrasil: Questao[] = [
  // ───────── Governo Dutra ─────────
  d("dut-06", "facil", "ENEM", "Embora eleito pelo voto e governando sob uma Constituição democrática, o governo Dutra adotou medidas que limitaram a participação política. Um exemplo dessas medidas foi:",
    [
      "a intervenção em sindicatos e a cassação dos mandatos dos parlamentares comunistas.",
      "o fechamento do Congresso Nacional e a suspensão das eleições estaduais e municipais até 1950.",
      "a censura prévia à imprensa e ao rádio, exercida por um departamento federal de propaganda ligado à Presidência.",
      "a nomeação de interventores para governar os estados.",
    ],
    "Dutra não fechou o Congresso nem suspendeu eleições, coisas típicas do Estado Novo (assim como o DIP e os interventores). O autoritarismo do seu governo apareceu na repressão ao movimento operário, com intervenção em centenas de sindicatos e restrição das greves, e na cassação do PCB (1947) e de seus parlamentares (1948).",
    "Democracia \"com freio\": tudo funciona, menos para comunistas e grevistas."),
  d("dut-07", "facil", "Fuvest", "No início do governo Dutra, a política econômica caracterizou-se por:",
    [
      "liberalização das importações, que consumiu rapidamente as reservas acumuladas durante a Segunda Guerra.",
      "forte controle estatal do câmbio desde a posse, combinado ao monopólio do petróleo e à restrição ao capital estrangeiro.",
      "ruptura com o Fundo Monetário Internacional.",
      "reforma agrária e limitação da remessa de lucros ao exterior.",
    ],
    "O Brasil saiu da guerra com reservas em moeda estrangeira. O governo Dutra, de orientação liberal, abriu as importações e as reservas foram gastas em poucos anos, em boa parte com bens de consumo. Monopólio do petróleo é Vargas (1953), ruptura com o FMI é JK (1959) e remessa de lucros é Jango (1962)."),
  d("dut-08", "facil", "Unesp", "O Tratado Interamericano de Assistência Recíproca (TIAR), assinado em 1947 no Brasil, estabelecia que:",
    [
      "um ataque a qualquer país americano seria considerado um ataque a todos.",
      "os países latino-americanos receberiam ajuda financeira nos moldes do Plano Marshall.",
      "as bases militares dos Estados Unidos seriam retiradas da América Latina.",
      "os países signatários manteriam neutralidade na Guerra Fria.",
    ],
    "O TIAR, ou Tratado do Rio, é um pacto de defesa coletiva: agressão a um é agressão a todos. Na prática, amarrou a América Latina à estratégia militar dos Estados Unidos na Guerra Fria. A ajuda econômica nos moldes do Plano Marshall nunca veio, o que gerou frustração (e mais tarde a Operação Pan-Americana de JK).",
    "TIAR é uma espécie de \"OTAN das Américas\", dois anos antes da OTAN."),
  d("dut-09", "facil", "Unicamp", "Sobre os direitos dos trabalhadores na Constituição de 1946, é correto afirmar que ela:",
    [
      "reconheceu o direito de greve, mas manteve a estrutura sindical atrelada ao Estado.",
      "extinguiu a legislação trabalhista do período Vargas, substituída pela livre negociação entre patrões e empregados.",
      "garantiu total liberdade e autonomia sindical.",
      "estendeu aos trabalhadores rurais os direitos previstos na CLT, inclusive a sindicalização e o salário mínimo.",
    ],
    "A Constituição reconheceu a greve como direito, mas deixou sua regulamentação para a lei, e na prática o governo a restringiu. A estrutura corporativa montada por Vargas (sindicato único, imposto sindical, controle do Ministério do Trabalho) continuou de pé, e a CLT também. Os trabalhadores rurais só ganharam um estatuto próprio em 1963."),
  d("dut-10", "facil", "Fuvest", "\"A democracia de 1946 nasceu com limites.\" Essa afirmação pode ser justificada pelo fato de que, no governo Dutra:",
    [
      "as instituições liberais conviveram com a exclusão dos analfabetos e com a repressão a comunistas e sindicatos.",
      "os partidos nacionais continuaram proibidos, e só eram admitidas legendas estaduais controladas pelos antigos interventores.",
      "o presidente governou por decretos-leis até 1950, pois o Congresso eleito só voltou a funcionar plenamente no governo seguinte.",
      "as eleições para presidente e governador passaram a ser indiretas, feitas pelo Congresso e pelas assembleias estaduais.",
    ],
    "O período 1946–1964 teve partidos nacionais, Congresso aberto e eleições diretas, mas a democracia era restrita: analfabetos não votavam, o PCB foi posto na ilegalidade e o movimento sindical ficou sob controle. É a combinação de forma democrática com práticas autoritárias que a frase aponta."),
  d("dut-11", "facil", "Unicamp", "Dutra, ex-ministro da Guerra do Estado Novo, foi eleito em 1945 pelo PSD com o apoio decisivo de Getúlio Vargas. Esse dado indica que a redemocratização:",
    [
      "manteve no poder grupos e estruturas vindos do Estado Novo.",
      "significou a vitória da oposição liberal reunida na UDN.",
      "afastou definitivamente Vargas e seus aliados da política.",
      "foi conduzida pelos comunistas e pelos sindicatos independentes.",
    ],
    "Vargas foi deposto em 1945, mas os dois partidos criados à sua sombra, o PSD (interventores e elites rurais) e o PTB (trabalhadores urbanos), venceram a eleição. A UDN e seu candidato, o brigadeiro Eduardo Gomes, foram derrotados. O próprio Vargas elegeu-se senador e voltaria à presidência em 1950.",
    "O slogan da virada foi \"Ele disse: vote em Dutra\". Ele = Getúlio."),
  d("dut-12", "facil", "UERJ", "Criada em 1949, a Escola Superior de Guerra (ESG) é importante para entender a história política brasileira porque:",
    [
      "difundiu entre militares e civis a doutrina de segurança nacional, que mais tarde embasou o golpe de 1964.",
      "formou os oficiais nacionalistas que, nos anos seguintes, lideraram a campanha pelo monopólio estatal do petróleo.",
      "organizou a participação brasileira na Segunda Guerra Mundial e o treinamento da Força Expedicionária enviada à Itália.",
      "defendia o afastamento dos militares da vida política.",
    ],
    "Inspirada no National War College dos Estados Unidos, a ESG elaborou a ideia de que o inimigo principal era interno (a \"subversão comunista\") e de que desenvolvimento e segurança andavam juntos. Muitos líderes de 1964, como Castelo Branco e Golbery, passaram por ela. A FEB lutou na Itália em 1944–45, antes da ESG existir."),

  // ───────── Vargas, populismo, UDN ─────────
  v("var-06", "facil", "ENEM", "Uma característica central do populismo brasileiro (1945–1964) foi:",
    [
      "a concessão de direitos trabalhistas combinada com o controle dos sindicatos pelo Estado.",
      "a defesa da luta de classes e da revolução socialista como caminho para a emancipação dos trabalhadores urbanos.",
      "a exclusão completa dos trabalhadores urbanos da vida política.",
      "a rejeição da industrialização em favor da agricultura de exportação.",
    ],
    "O líder populista incorpora os trabalhadores urbanos à política, mas de forma tutelada: dá direitos e mantém os sindicatos presos ao Ministério do Trabalho. O discurso é de conciliação entre patrões e empregados em nome da nação, o oposto da luta de classes, e o projeto era industrializador.",
    "Populismo = dá com uma mão (direitos) e segura com a outra (controle)."),
  v("var-07", "facil", "Fuvest", "No início dos anos 1950, os nacionalistas defendiam, em linhas gerais:",
    [
      "industrialização conduzida pelo Estado e controle nacional dos setores estratégicos.",
      "livre entrada de empresas estrangeiras na pesquisa e na exploração do petróleo e dos minérios.",
      "redução do papel do Estado, privatização das empresas públicas e equilíbrio rigoroso do orçamento federal.",
      "prioridade à agricultura de exportação como base da economia, deixando a indústria ao mercado.",
    ],
    "Para os nacionalistas, o Brasil só seria independente de verdade se controlasse petróleo, energia e indústria de base, com o Estado como investidor principal. As outras alternativas descrevem posições liberais, associadas aos adversários que eles chamavam de entreguistas."),
  v("var-08", "facil", "Unesp", "O atentado da Rua Tonelero, em agosto de 1954, teve como consequência imediata:",
    [
      "o agravamento da crise política, com militares exigindo a saída de Vargas.",
      "a cassação do registro da UDN e a prisão de Carlos Lacerda, acusado de forjar o atentado.",
      "a decretação do Estado Novo.",
      "a criação da Petrobras, apresentada como resposta nacionalista à ofensiva da oposição.",
    ],
    "O alvo era Carlos Lacerda, que ficou ferido; o major da Aeronáutica Rubens Vaz morreu. A investigação chegou a Gregório Fortunato, chefe da guarda pessoal de Vargas. A Aeronáutica e depois os generais passaram a exigir a renúncia, e o presidente se matou dias depois. O Estado Novo é de 1937 e a Petrobras já existia desde 1953.",
    "Tonelero → Lacerda ferido → major morto → militares contra Vargas → suicídio."),
  v("var-09", "facil", "UERJ", "Em 1954, o ministro do Trabalho João Goulart propôs um aumento de 100% no salário mínimo. A proposta provocou:",
    [
      "a reação de militares e empresários, expressa no Manifesto dos Coronéis, e a saída do ministro.",
      "o apoio entusiasmado da UDN ao governo Vargas.",
      "o fim das greves operárias no país.",
      "a ruptura definitiva entre Vargas e o PTB, que passou a fazer oposição ao governo no Congresso até agosto.",
    ],
    "O aumento assustou empresários e oficiais do Exército, que no Manifesto dos Coronéis reclamaram que um operário passaria a ganhar quase como um oficial. Jango deixou o ministério, mas Vargas concedeu o aumento no 1º de maio de 1954, aproximando-se dos trabalhadores e irritando ainda mais a oposição."),
  v("var-10", "facil", "Fuvest", "\"Mais uma vez as forças e os interesses contra o povo coordenaram-se e se desencadeiam sobre mim.\" (Carta-Testamento, 1954)\n\nNa Carta-Testamento, Vargas atribui a crise de seu governo:",
    [
      "à pressão de grupos internacionais e de seus aliados internos, contrários à sua política nacionalista e trabalhista.",
      "à radicalização dos sindicatos e do Partido Comunista, que teriam sabotado sua política de conciliação entre patrões e empregados.",
      "ao fracasso de sua política econômica liberal, que teria aberto o país às importações e arruinado a indústria nacional.",
      "à falta de apoio popular e às greves contra o governo, que teriam paralisado o país nos meses anteriores ao atentado.",
    ],
    "A Carta cita a campanha contra a Petrobras e a Eletrobras, os lucros das empresas estrangeiras e a reação ao aumento do salário mínimo. Vargas se apresenta como vítima de uma aliança entre interesses externos e a oposição interna. O efeito foi enorme: a comoção popular virou-se contra a UDN e os jornais de oposição."),
  v("var-11", "facil", "Unicamp", "Muitos historiadores afirmam que o suicídio de Vargas \"adiou o golpe por dez anos\". A frase significa que:",
    [
      "a comoção popular enfraqueceu a oposição e impediu, naquele momento, que os grupos antigetulistas tomassem o poder.",
      "os militares desistiram definitivamente de intervir na política e passaram a defender a posse de todos os presidentes eleitos.",
      "a UDN venceu as eleições presidenciais seguintes.",
      "o PTB foi extinto pela Justiça Eleitoral, e os trabalhistas ficaram fora da cena política até a eleição de Jânio Quadros.",
    ],
    "Em agosto de 1954, a UDN e setores militares estavam perto de derrubar Vargas. O suicídio inverteu o jogo: multidões atacaram jornais de oposição e Lacerda teve de se esconder. Os herdeiros de Vargas (JK e Jango) venceram em 1955. As mesmas forças voltaram em 1955, em 1961 e, enfim, em 1964."),
  v("var-12", "facil", "UERJ", "A lei que criou a Petrobras, em 1953, representou uma vitória parcial dos nacionalistas porque:",
    [
      "estabeleceu o monopólio estatal da pesquisa, da lavra e do refino, mas deixou a distribuição aberta a empresas privadas.",
      "proibiu qualquer empresa estrangeira de vender combustíveis no Brasil.",
      "foi aprovada sem nenhum apoio da UDN no Congresso.",
      "entregou a exploração a empresas mistas com capital norte-americano, reservando ao Estado apenas a fiscalização e a cobrança de impostos.",
    ],
    "O monopólio cobria pesquisa, extração (lavra), refino e transporte, mas a distribuição continuou com empresas privadas, inclusive estrangeiras. Curiosidade que cai em prova: parte da UDN votou a favor do monopólio, numa manobra para não deixar a bandeira nacionalista só com Vargas."),
  v("var-13", "facil", "Fuvest", "A principal crítica da UDN ao varguismo pode ser resumida como:",
    [
      "denúncia da corrupção e da \"demagogia\" do governo e defesa do liberalismo, ainda que o partido recorresse aos militares para chegar ao poder.",
      "defesa do socialismo e da reforma agrária contra o conservadorismo de Vargas.",
      "exigência de maior intervenção do Estado na economia.",
      "defesa do voto dos analfabetos e da ampliação dos direitos trabalhistas.",
    ],
    "A UDN falava em moralidade (o \"mar de lama\"), liberdades e economia de mercado. Mas, como perdia as eleições presidenciais, apelou várias vezes para a intervenção militar: em 1954, em 1955 (contra a posse de JK) e em 1964. Por isso foi chamada de partido de \"liberais golpistas\"."),

  // ───────── JK ─────────
  k("jk-05", "facil", "ENEM", "O modelo econômico do governo JK baseou-se:",
    [
      "na combinação de investimento do Estado, capital privado nacional e forte entrada de capital estrangeiro.",
      "na estatização de todas as indústrias de base e de bens duráveis instaladas no país a partir de 1956, sem sócios privados.",
      "no fechamento da economia às empresas multinacionais, vistas como ameaça à soberania e à indústria de capital brasileiro.",
      "na prioridade à agricultura familiar e à reforma agrária, entendidas como base para a criação de um mercado interno.",
    ],
    "É o chamado tripé: o Estado cuidava da infraestrutura e da indústria de base, o capital nacional dos bens de consumo comuns e as multinacionais dos bens duráveis, como automóveis e eletrodomésticos. Por isso se diz que JK era desenvolvimentista, mas não nacionalista no sentido de Vargas.",
    "Vargas: desenvolver com capital nacional. JK: desenvolver com quem tiver capital."),
  k("jk-06", "facil", "Fuvest", "Entre as consequências negativas da política econômica de JK estão:",
    [
      "o aumento da inflação e da dívida externa.",
      "a queda da produção industrial.",
      "o esvaziamento das cidades e a volta ao campo.",
      "a diminuição das desigualdades entre as regiões do país.",
    ],
    "Brasília e as metas foram pagas com emissão de moeda e empréstimos, o que gerou inflação e endividamento, herança que pesou sobre Jânio e Jango. A indústria cresceu muito, as cidades incharam com o êxodo rural e a indústria se concentrou ainda mais no Sudeste."),
  k("jk-07", "facil", "Unesp", "Em 1959, o governo JK criou a Sudene com o objetivo de:",
    [
      "promover o desenvolvimento do Nordeste e reduzir as desigualdades regionais.",
      "coordenar a construção de Brasília e a transferência dos órgãos federais para o Planalto.",
      "controlar a entrada de capital estrangeiro e fiscalizar a remessa de lucros das multinacionais.",
      "administrar o monopólio estatal do petróleo.",
    ],
    "A Superintendência do Desenvolvimento do Nordeste foi idealizada pelo economista Celso Furtado, depois de uma grande seca em 1958. A ideia era industrializar a região em vez de apenas combater os efeitos da seca. A construção de Brasília ficou com a Novacap."),
  k("jk-08", "facil", "UERJ", "A opção do governo JK pelo transporte rodoviário está ligada:",
    [
      "à implantação da indústria automobilística e à integração do interior com a nova capital.",
      "à falta de petróleo importado no período.",
      "à pressão das companhias ferroviárias inglesas.",
      "à prioridade dada às exportações agrícolas por via marítima, que dispensavam ligações terrestres com o interior.",
    ],
    "Estradas como a Belém–Brasília ligavam a nova capital ao resto do país e criavam mercado para os carros e caminhões fabricados aqui. A escolha deixou as ferrovias em segundo plano e tornou o Brasil dependente de rodovias e de petróleo até hoje."),
  k("jk-09", "facil", "Unicamp", "Em novembro de 1955, o general Henrique Lott liderou um movimento militar que:",
    [
      "garantiu a posse de JK e Jango, eleitos naquele ano, contra uma tentativa de impedi-la.",
      "depôs JK logo após a posse e instaurou uma junta militar, dissolvida meses depois pelo Congresso.",
      "fechou o Congresso, cancelou as eleições de 1955 e prorrogou o mandato do presidente em exercício.",
      "levou a UDN à presidência da República, com a posse do general Juarez Távora, segundo colocado.",
    ],
    "JK venceu com cerca de 36% dos votos, e a UDN alegou que ele não tinha maioria absoluta, tentando barrar a posse. O ministro da Guerra, general Lott, deu o chamado \"golpe preventivo\" de 11 de novembro para garantir o resultado das urnas. É um caso raro de intervenção militar para cumprir a Constituição.",
    "Lott = legalista. Interveio para que o eleito tomasse posse."),
  k("jk-10", "facil", "Fuvest", "Em 1959, JK rompeu as negociações com o Fundo Monetário Internacional (FMI). A razão do rompimento foi:",
    [
      "a recusa do governo em cortar gastos e investimentos, como o Fundo exigia para combater a inflação.",
      "a exigência do FMI de que o Brasil estatizasse as multinacionais do setor automobilístico e limitasse a remessa de lucros.",
      "a aproximação diplomática do Brasil com a União Soviética, vista pelo Fundo como risco para os credores.",
      "a decisão de JK de suspender a construção de Brasília.",
    ],
    "O FMI condicionava novos empréstimos a um plano de austeridade, o que obrigaria a frear o Plano de Metas e as obras de Brasília. JK preferiu romper, gesto que agradou os nacionalistas no fim do mandato. É uma contradição interessante: o presidente que mais abriu o país ao capital estrangeiro brigou com o FMI."),
  k("jk-11", "facil", "Unicamp", "A Operação Pan-Americana (OPA), proposta por JK ao presidente Eisenhower em 1958, defendia que:",
    [
      "o combate ao subdesenvolvimento na América Latina, com apoio financeiro dos EUA, era a melhor forma de conter o comunismo.",
      "os países latino-americanos rompessem relações com os Estados Unidos.",
      "a América Latina formasse uma aliança militar com a União Soviética.",
      "o Brasil liderasse o movimento dos países não alinhados.",
    ],
    "JK usou a lógica da Guerra Fria a favor do Brasil: a miséria é que alimenta a revolução, logo os EUA deveriam financiar o desenvolvimento da região. A proposta teve pouca resposta até a Revolução Cubana (1959); depois dela, Kennedy lançou a Aliança para o Progresso (1961), com ideias parecidas."),
  k("jk-12", "facil", "UERJ", "A estabilidade política do governo JK, incomum no período 1946–1964, é geralmente explicada:",
    [
      "pela aliança PSD–PTB no Congresso, pelo crescimento econômico e pela habilidade de conciliar militares e oposição.",
      "pela ausência de qualquer contestação militar durante o mandato, resultado do afastamento das Forças Armadas da política.",
      "pela censura à imprensa e pela proibição dos partidos de oposição.",
      "pelo apoio da UDN ao presidente, selado num acordo de governo que lhe deu ministérios e a liderança na Câmara.",
    ],
    "JK tinha maioria com PSD (elites rurais) e PTB (trabalhadores), manteve o legalista Lott no Ministério da Guerra e anistiou os militares rebeldes de Jacareacanga (1956) e Aragarças (1959), duas pequenas revoltas da Aeronáutica. A UDN fez oposição o tempo todo, e a imprensa era livre."),

  // ───────── Jânio e a Legalidade ─────────
  j("jan-06", "facil", "ENEM", "A política externa independente, iniciada no governo Jânio Quadros, propunha:",
    [
      "manter relações com países dos dois blocos, capitalista e socialista, segundo os interesses do Brasil.",
      "romper relações com os Estados Unidos e aderir ao bloco soviético, em troca de ajuda econômica e militar.",
      "isolar o Brasil do comércio internacional.",
      "apoiar a intervenção militar dos Estados Unidos em Cuba.",
    ],
    "Jânio queria ampliar mercados e autonomia: reatou contatos com o bloco socialista, defendeu a autodeterminação de Cuba e apoiou a descolonização africana. O gesto mais polêmico foi condecorar Che Guevara. Não era adesão ao socialismo; em casa, sua política econômica era conservadora.",
    "Dutra: alinhado. Jânio e Jango: independentes."),
  j("jan-07", "facil", "Fuvest", "O governo Jânio Quadros desagradou a diferentes grupos ao mesmo tempo porque combinou:",
    [
      "uma política econômica de austeridade, que irritou a esquerda, com uma política externa independente, que irritou a direita.",
      "reforma agrária radical com alinhamento total aos Estados Unidos.",
      "estatização de bancos com censura à imprensa de esquerda.",
      "aumento generalizado de salários com rompimento com Cuba.",
    ],
    "Jânio cortou subsídios, desvalorizou a moeda e conteve salários, medidas bem vistas pelo FMI e mal vistas pelos trabalhadores. Ao mesmo tempo, sua diplomacia e a condecoração de Che Guevara revoltaram a UDN e Lacerda, que o haviam apoiado. Sem partido forte e brigado com o Congresso, ficou isolado."),
  j("jan-08", "facil", "Unesp", "A tentativa de impedir a posse de João Goulart em 1961 partiu:",
    [
      "dos três ministros militares, que o associavam ao comunismo e ao sindicalismo.",
      "do Congresso Nacional, que aprovou seu impeachment por larga maioria antes mesmo de ele voltar ao país.",
      "dos governadores do Nordeste, que temiam a aplicação da reforma agrária em seus estados.",
      "do Supremo Tribunal Federal, que considerou irregular a eleição separada do vice-presidente.",
    ],
    "Os ministros da Guerra, da Marinha e da Aeronáutica declararam que a volta de Jango era \"inconveniente\" para a segurança nacional. O Congresso não aceitou o veto, mas negociou a saída parlamentarista. A desconfiança vinha desde 1954, quando Jango era ministro do Trabalho de Vargas."),
  j("jan-09", "facil", "UERJ", "O parlamentarismo implantado em 1961 chegou ao fim quando:",
    [
      "um plebiscito, em janeiro de 1963, decidiu pela volta do presidencialismo.",
      "os militares depuseram o primeiro-ministro e devolveram os poderes ao presidente, em 1962.",
      "Jango fechou o Congresso e convocou uma Assembleia Constituinte, no início de 1964.",
      "a Constituição de 1967 foi promulgada.",
    ],
    "A emenda de 1961 previa uma consulta popular. Jango conseguiu antecipá-la, e em 6 de janeiro de 1963 a grande maioria dos eleitores votou pelo presidencialismo, devolvendo-lhe os plenos poderes.",
    "1961: tiram a caneta. 1963: o povo devolve."),
  j("jan-10", "facil", "Fuvest", "A interpretação mais aceita pelos historiadores para a renúncia de Jânio Quadros é a de que ele:",
    [
      "tentou um autogolpe: esperava que o Congresso, os militares e o povo recusassem a renúncia e lhe dessem mais poderes.",
      "foi deposto por um movimento militar liderado por Lott.",
      "renunciou por motivo de doença grave.",
      "foi afastado por um processo de impeachment aprovado pela UDN, depois da condecoração de Che Guevara e da ruptura com Lacerda.",
    ],
    "Jânio calculou que ninguém aceitaria a posse de Jango, visto como esquerdista e ainda por cima em viagem à China, e que seria chamado de volta com poderes ampliados. O plano falhou: o Congresso aceitou a renúncia na hora, por se tratar de ato unilateral, e ninguém foi às ruas por ele. Na carta, ele culpou \"forças terríveis\".",
    "Blefou e perdeu: o Congresso disse \"aceito\"."),
  j("jan-11", "facil", "Unicamp", "A Campanha da Legalidade só teve força para barrar o veto militar porque:",
    [
      "contou com a mobilização popular pelo rádio e com a adesão do III Exército, o que dividiu as Forças Armadas.",
      "recebeu apoio militar e diplomático dos Estados Unidos, interessados em preservar a ordem constitucional no continente.",
      "foi apoiada pela UDN e por Carlos Lacerda, que colocaram a polícia da Guanabara a serviço da posse do vice-presidente.",
      "teve o apoio declarado de Jânio Quadros, que do exílio pediu aos militares o respeito à ordem de sucessão constitucional.",
    ],
    "Quando o comandante do III Exército, general Machado Lopes, aderiu a Brizola, os ministros militares ficaram diante do risco de uma guerra entre unidades do próprio Exército. Essa divisão forçou a negociação. Em 1964 as Forças Armadas agiriam unidas, e por isso o resultado foi outro."),
  j("jan-12", "facil", "UERJ", "A eleição de 1960 produziu um resultado incomum: presidente e vice de chapas adversárias. Isso foi possível porque:",
    [
      "a Constituição de 1946 previa votação separada para presidente e vice-presidente.",
      "Jânio e Jango pertenciam ao mesmo partido.",
      "o vice era escolhido pelo Congresso Nacional, onde o PTB e o PSD formavam a maioria desde 1958.",
      "Jango foi nomeado pelos ministros militares, como forma de equilibrar o governo de um presidente sem partido.",
    ],
    "O eleitor votava separadamente nos dois cargos. Jânio (apoiado pela UDN) venceu para presidente, e Jango (PTB, da chapa do marechal Lott) para vice; houve até comitês \"Jan-Jan\". Assim, a renúncia entregava o governo justamente ao grupo político derrotado, o que explica a gravidade da crise."),

  // ───────── Jango e o golpe ─────────
  g("jng-06", "facil", "ENEM", "O golpe de 1964 é chamado por muitos historiadores de \"civil-militar\" porque:",
    [
      "foi executado pelas Forças Armadas com apoio de empresários, de parte da imprensa, da Igreja e da classe média.",
      "foi executado por civis armados, sem participação do Exército.",
      "levou imediatamente ao poder um presidente civil escolhido por eleição direta, ainda que sob a tutela dos chefes militares.",
      "teve a adesão dos sindicatos e das ligas camponesas.",
    ],
    "As tropas fizeram a derrubada, mas a conspiração envolveu governadores (Lacerda, Magalhães Pinto, Ademar de Barros), empresários reunidos no IPES e no IBAD, grandes jornais e setores da Igreja, além do apoio do governo dos Estados Unidos. Sindicatos e ligas camponesas estavam do lado de Jango."),
  g("jng-07", "facil", "Fuvest", "No contexto da Guerra Fria, o governo dos Estados Unidos em relação ao golpe de 1964:",
    [
      "apoiou os golpistas e chegou a preparar ajuda militar, na operação Brother Sam.",
      "condenou publicamente a derrubada de Jango e suspendeu a ajuda econômica ao Brasil até a eleição de 1966.",
      "manteve-se neutro e só soube do movimento pelos jornais, pois a embaixada não acompanhava a crise.",
      "enviou uma força naval para defender o governo constitucional, a pedido do presidente deposto.",
    ],
    "Depois da Revolução Cubana (1959), Washington temia uma \"nova Cuba\" na América Latina. Os EUA financiaram opositores de Jango e deixaram uma força naval pronta para dar apoio logístico aos golpistas, que não chegou a ser usada porque não houve resistência. O novo governo foi reconhecido imediatamente."),
  g("jng-08", "facil", "Unesp", "O Plano Trienal (1963), elaborado por Celso Furtado, fracassou principalmente porque:",
    [
      "tentou combater a inflação e crescer ao mesmo tempo, sem obter apoio nem dos empresários nem dos trabalhadores.",
      "foi vetado pelos Estados Unidos.",
      "dependia da venda da Petrobras.",
      "propunha o fim da industrialização.",
    ],
    "O plano pedia sacrifícios dos dois lados: contenção de salários e de crédito. Os sindicatos recusaram o arrocho, os empresários recusaram o aperto, e o governo abandonou o plano em poucos meses. Sem controle da inflação, Jango apostou cada vez mais nas Reformas de Base."),
  g("jng-09", "facil", "UERJ", "Entre as reformas de base, a reforma eleitoral previa:",
    [
      "o direito de voto para os analfabetos e para os militares de baixa patente.",
      "o fim do voto secreto.",
      "eleições indiretas para presidente, a cargo de um colégio formado por deputados e governadores.",
      "a extinção dos partidos políticos existentes e a criação de apenas duas legendas.",
    ],
    "Estender o voto a analfabetos e a praças (sargentos, cabos, soldados) ampliaria muito o eleitorado popular, em tese favorável ao PTB. Por isso a proposta assustava os conservadores tanto quanto a reforma agrária."),
  g("jng-10", "facil", "Unicamp", "A Lei de Remessa de Lucros (1962) provocou forte reação porque:",
    [
      "limitava o envio ao exterior dos lucros das empresas estrangeiras instaladas no Brasil.",
      "proibia a exportação de café.",
      "acabava com o imposto de renda.",
      "liberava a entrada de capital estrangeiro sem controle e isentava de impostos os lucros reinvestidos.",
    ],
    "A lei fixava um teto para o lucro que as multinacionais podiam mandar para suas matrizes. Agradou os nacionalistas e contrariou empresas estrangeiras e o governo norte-americano, alimentando a oposição externa a Jango."),
  g("jng-11", "facil", "Fuvest", "Nos dias que antecederam o golpe, a Revolta dos Marinheiros e o discurso de Jango no Automóvel Clube foram decisivos porque:",
    [
      "convenceram oficiais até então legalistas de que o presidente apoiava a quebra da hierarquia e da disciplina militar.",
      "mostraram que as Forças Armadas estavam unidas em defesa do governo, o que levou os conspiradores a adiar o movimento.",
      "provocaram a renúncia coletiva dos três ministros militares, em sinal de apoio às reformas e aos direitos políticos dos praças.",
      "levaram a UDN a apoiar as Reformas de Base.",
    ],
    "Jango anistiou marinheiros rebelados e discursou para sargentos em 30 de março. Para a oficialidade, hierarquia é sagrada: muitos generais que hesitavam em derrubar um presidente constitucional passaram para o lado dos conspiradores. No dia seguinte, o general Mourão Filho pôs as tropas na estrada em Juiz de Fora.",
    "Mexer na hierarquia foi a gota d'água para os oficiais."),
  g("jng-12", "facil", "Unicamp", "Na madrugada de 2 de abril de 1964, o presidente do Senado declarou vaga a Presidência da República. O ato é considerado ilegal porque:",
    [
      "João Goulart ainda estava em território brasileiro e não havia renunciado.",
      "o Congresso estava fechado pelos militares desde a véspera e não poderia deliberar.",
      "Jango já havia transferido o cargo ao presidente da Câmara, antes de embarcar para o Sul.",
      "a Constituição exigia que a vacância fosse declarada pelo Supremo Tribunal Federal.",
    ],
    "Jango estava em Porto Alegre quando Auro de Moura Andrade declarou a vacância. Pela Constituição, o cargo só ficaria vago se o presidente deixasse o país sem autorização. O ato deu aparência de legalidade ao golpe: Ranieri Mazzilli assumiu interinamente, e dias depois o AI-1 abriu caminho para o general Castelo Branco."),
  g("jng-13", "facil", "UERJ", "A radicalização política no governo Jango pode ser descrita como:",
    [
      "polarização entre esquerdas que exigiam as reformas \"na lei ou na marra\" e direitas que denunciavam uma ameaça comunista, esvaziando o centro.",
      "consenso entre os partidos em torno das Reformas de Base.",
      "disputa restrita ao Congresso, sem participação de movimentos sociais.",
      "conflito entre o presidente e os sindicatos, que apoiavam a UDN.",
    ],
    "De um lado, CGT, UNE, Ligas Camponesas e a ala de Brizola pressionavam por reformas imediatas; de outro, IPES, IBAD, UDN, parte da Igreja e dos militares mobilizavam o medo do comunismo. O PSD, partido de centro que sustentava o governo no Congresso, afastou-se, e Jango ficou sem base para negociar."),
];
