import type { Questao } from "@/lib/tipos";
import { criar } from "../criar";

const f = criar("guerra-fria");
const vt = criar("vietna");
const dc = criar("descolonizacao");
const m = criar("maio68");

export const questoesMundo: Questao[] = [
  // ───────── Guerra Fria ─────────
  f("gf-06", "facil", "ENEM", "A Doutrina Truman (1947) estabeleceu que os Estados Unidos deveriam:",
    [
      "apoiar com recursos e armas os governos ameaçados pelo avanço do comunismo.",
      "retirar suas tropas da Europa e voltar ao isolacionismo.",
      "dividir com a União Soviética o controle das armas nucleares, por meio de uma agência da ONU.",
      "apoiar os movimentos de independência das colônias europeias na Ásia e na África.",
    ],
    "A Doutrina Truman inaugurou a política de contenção: impedir que o comunismo se expandisse para além de onde já estava. Começou com ajuda à Grécia e à Turquia. O Plano Marshall foi seu braço econômico.",
    "Truman = \"trava\" o comunismo (contenção)."),
  f("gf-07", "facil", "Fuvest", "Além de reconstruir a Europa, o Plano Marshall tinha como objetivo político:",
    [
      "evitar que a miséria do pós-guerra fortalecesse os partidos comunistas na Europa Ocidental.",
      "financiar a reconstrução da União Soviética.",
      "punir a Alemanha com pesadas indenizações de guerra, para impedir de vez seu reerguimento industrial e militar.",
      "criar uma moeda única europeia.",
    ],
    "Os EUA entendiam que fome e desemprego abriam espaço para o comunismo, forte na França e na Itália. A ajuda também garantia compradores para a indústria americana. A URSS recusou o plano e proibiu os países do Leste de aceitá-lo. Punir a Alemanha foi o erro de 1919, que os EUA quiseram evitar."),
  f("gf-08", "facil", "Unesp", "A resposta soviética ao Plano Marshall, criada em 1949 para integrar as economias do bloco socialista, foi o:",
    ["Comecon.", "Kominform.", "Pacto de Varsóvia.", "Plano Quinquenal."],
    "O Comecon (Conselho de Assistência Econômica Mútua) organizava a ajuda e o comércio entre os países socialistas. O Kominform coordenava os partidos comunistas (política), o Pacto de Varsóvia era militar e os planos quinquenais eram o planejamento interno da URSS.",
    "ECOnomia = ComECOn."),
  f("gf-09", "facil", "UERJ", "A política de coexistência pacífica, defendida por Nikita Kruschev, partia da ideia de que:",
    [
      "capitalismo e socialismo poderiam competir sem recorrer à guerra, já que um conflito nuclear destruiria os dois lados.",
      "a União Soviética deveria abandonar o socialismo.",
      "os dois blocos deveriam se unir em um único governo mundial.",
      "a URSS deveria atacar primeiro, antes que os EUA se armassem.",
    ],
    "Depois da morte de Stalin (1953), Kruschev propôs que a disputa continuasse em outros campos: economia, ciência, esporte, conquista do espaço. Não era o fim da rivalidade, e sim uma mudança de método."),
  f("gf-10", "facil", "Unicamp", "O Pacto de Varsóvia foi criado em 1955 como reação direta:",
    [
      "à entrada da Alemanha Ocidental na OTAN.",
      "à vitória da Revolução Cubana e à sua aproximação com Moscou.",
      "à construção do Muro de Berlim pela Alemanha Oriental.",
      "à intervenção dos Estados Unidos na Guerra do Vietnã.",
    ],
    "A OTAN é de 1949; quando a Alemanha Ocidental foi admitida e rearmada, em 1955, a URSS formalizou sua própria aliança com os países do Leste Europeu. Repare na ordem: a OTAN vem seis anos antes.",
    "OTAN 1949 → Varsóvia 1955."),
  f("gf-11", "facil", "Fuvest", "A Crise dos Mísseis (1962) é considerada o momento mais tenso da Guerra Fria. Ela foi resolvida quando:",
    [
      "a URSS retirou os mísseis de Cuba em troca do compromisso dos EUA de não invadir a ilha e da retirada de mísseis americanos da Turquia.",
      "os Estados Unidos invadiram Cuba e derrubaram Fidel Castro.",
      "a ONU assumiu o controle das armas nucleares dos dois países.",
      "Cuba rompeu com a União Soviética e voltou ao bloco capitalista.",
    ],
    "Durante treze dias, Kennedy e Kruschev estiveram à beira da guerra nuclear. O acordo foi uma troca: mísseis fora de Cuba, garantia de não invasão e, em segredo, mísseis americanos fora da Turquia. Depois da crise foi instalada a linha direta entre Washington e Moscou (o \"telefone vermelho\")."),
  f("gf-12", "facil", "Unicamp", "A coexistência pacífica não significou o fim das tensões. Uma evidência disso, ocorrida no próprio governo Kruschev, foi:",
    [
      "a invasão da Hungria por tropas soviéticas em 1956, para esmagar uma revolta contra o regime.",
      "a queda do Muro de Berlim.",
      "a dissolução do Pacto de Varsóvia depois da saída da Hungria e da Tchecoslováquia da aliança militar.",
      "a retirada das tropas soviéticas do Afeganistão, depois de quase dez anos de guerra contra a guerrilha.",
    ],
    "No mesmo ano em que denunciou os crimes de Stalin, Kruschev mandou tanques a Budapeste: abrir o diálogo com o Ocidente não incluía deixar um país sair do bloco. Entram na mesma lista o Muro de Berlim (1961) e a Crise dos Mísseis (1962). As outras alternativas são do fim da Guerra Fria (1989–1991)."),
  f("gf-13", "facil", "UERJ", "No XX Congresso do Partido Comunista da URSS (1956), Kruschev fez um discurso que abalou o mundo socialista porque:",
    [
      "denunciou os crimes, as perseguições e o culto à personalidade de Stalin.",
      "anunciou o abandono do socialismo e a abertura da economia soviética ao capital estrangeiro.",
      "rompeu com a China de Mao Tsé-Tung e anunciou o fim da ajuda técnica e militar a Pequim.",
      "propôs a dissolução do Pacto de Varsóvia e a entrada da União Soviética na OTAN.",
    ],
    "O \"relatório secreto\" deu início à desestalinização. Uma consequência importante: a China de Mao discordou da crítica a Stalin e da coexistência pacífica, o que levou ao rompimento entre os dois gigantes comunistas no começo dos anos 1960."),
  f("gf-14", "facil", "Fuvest", "A Guerra da Coreia (1950–1953) e a Guerra do Vietnã são exemplos de um traço típico da Guerra Fria:",
    [
      "conflitos regionais em que as superpotências apoiavam lados opostos, sem se enfrentarem diretamente.",
      "guerras entre países capitalistas pela posse de colônias.",
      "confrontos diretos entre os exércitos dos EUA e da URSS.",
      "guerras religiosas e étnicas sem relação com a disputa entre os blocos, apesar da presença de tropas estrangeiras.",
    ],
    "São as chamadas guerras por procuração. Em ambas, um país foi dividido em Norte comunista e Sul capitalista: a Coreia no paralelo 38 (e continua dividida), o Vietnã no paralelo 17 (reunificado em 1976).",
    "Coreia 38, Vietnã 17."),

  // ───────── Guerra do Vietnã ─────────
  vt("vie-07", "facil", "ENEM", "A batalha de Dien Bien Phu (1954) foi importante porque:",
    [
      "marcou a derrota definitiva da França na Indochina, abrindo caminho para os Acordos de Genebra.",
      "foi a primeira grande vitória dos Estados Unidos contra os vietcongues, o que os animou a ampliar a intervenção.",
      "resultou na reunificação imediata do Vietnã.",
      "provocou a entrada direta da União Soviética na guerra, com o envio de divisões ao norte do país.",
    ],
    "As tropas do Viet Minh, comandadas pelo general Giap, cercaram e renderam a base francesa. Foi uma derrota humilhante de uma potência europeia para um exército colonial, que animou outros movimentos de independência, como o da Argélia.",
    "Dien Bien Phu = \"fim\" da França no Vietnã."),
  vt("vie-08", "facil", "Fuvest", "Os Acordos de Genebra previam eleições para reunificar o Vietnã em 1956. Elas não ocorreram porque:",
    [
      "o governo do Vietnã do Sul, apoiado pelos EUA, recusou-se a realizá-las, temendo a vitória de Ho Chi Minh.",
      "o Vietnã do Norte invadiu o Sul antes da data marcada, o que levou a comissão internacional a cancelar a consulta.",
      "a França voltou a ocupar o país em 1955, com apoio britânico, e suspendeu a aplicação de tudo o que fora acordado.",
      "a ONU declarou a divisão permanente e admitiu os dois Vietnãs como Estados-membros distintos, tal como fizera com a Coreia.",
    ],
    "Ho Chi Minh era o herói da independência e venceria com folga. Ngo Dinh Diem, que governava o Sul com apoio americano, cancelou a consulta. A divisão, que era provisória, se tornou permanente, e a luta armada recomeçou no Sul."),
  vt("vie-09", "facil", "Unesp", "O incidente do Golfo de Tonkin (1964) teve como consequência:",
    [
      "a autorização do Congresso dos EUA para o presidente Lyndon Johnson ampliar a intervenção militar no Vietnã.",
      "a retirada das tropas norte-americanas da Ásia, decidida pelo Congresso diante do risco de um confronto com a China.",
      "a assinatura de um acordo de paz em Paris.",
      "a entrada da França na guerra ao lado do Vietnã do Norte.",
    ],
    "Os EUA alegaram que navios seus foram atacados por lanchas norte-vietnamitas. A Resolução do Golfo de Tonkin deu a Johnson carta branca para usar a força, sem declaração formal de guerra. Mais tarde se soube que o segundo ataque nunca aconteceu.",
    "Tonkin = o \"pretexto\" para a escalada."),
  vt("vie-10", "facil", "UERJ", "A Trilha Ho Chi Minh era:",
    [
      "uma rede de caminhos pela selva, passando por Laos e Camboja, que levava soldados e suprimentos do Norte para os guerrilheiros no Sul.",
      "a linha de fronteira entre o Vietnã do Norte e o do Sul.",
      "a rota de fuga dos refugiados para os Estados Unidos.",
      "uma ferrovia construída pelos franceses.",
    ],
    "Por atravessar países vizinhos, a trilha era difícil de bloquear. Tentando cortá-la, os EUA bombardearam maciçamente o Laos e o Camboja, espalhando a guerra por toda a Indochina. A fronteira entre Norte e Sul era o paralelo 17."),
  vt("vie-11", "facil", "Unicamp", "A Guerra do Vietnã ficou conhecida como a primeira \"guerra televisionada\". Isso foi importante porque:",
    [
      "as imagens de mortos, aldeias queimadas e civis feridos chegavam às casas americanas e alimentavam a oposição à guerra.",
      "a televisão garantiu apoio quase unânime da população dos EUA às tropas, ao exibir diariamente as vitórias no campo de batalha.",
      "o governo norte-vietnamita fornecia as imagens às emissoras americanas, que as exibiam sem verificar a origem ou o contexto.",
      "os combates eram encenados para a propaganda oficial.",
    ],
    "Pela primeira vez, a população via a guerra quase em tempo real, sem o filtro da censura militar. Imagens como a da menina Kim Phuc queimada por napalm (1972) tiveram enorme impacto e fortaleceram os protestos de estudantes, do movimento negro e dos hippies."),
  vt("vie-12", "facil", "ENEM", "A política de \"vietnamização\" da guerra, adotada pelo presidente Richard Nixon, consistia em:",
    [
      "retirar aos poucos os soldados americanos e transferir o combate ao exército do Vietnã do Sul.",
      "enviar mais meio milhão de soldados americanos ao país, para vencer a guerra antes das eleições de 1972.",
      "entregar o Vietnã do Sul ao governo de Hanói em troca da libertação dos prisioneiros de guerra americanos.",
      "convidar a China a ocupar o Vietnã do Norte, em troca do reconhecimento diplomático de Pequim pelos Estados Unidos.",
    ],
    "Com a guerra impopular em casa, Nixon queria sair sem admitir derrota: os americanos forneceriam armas, treinamento e bombardeios aéreos, e os sul-vietnamitas lutariam em terra. Sem as tropas dos EUA, o Sul não resistiu e caiu em 1975."),
  vt("vie-13", "facil", "Fuvest", "A Ofensiva do Tet (1968) costuma ser descrita como uma derrota militar e uma vitória política dos comunistas. Isso porque:",
    [
      "os ataques foram repelidos com grandes perdas, mas mostraram ao público americano que a guerra estava longe de ser vencida.",
      "os vietcongues conquistaram Saigon e a mantiveram por alguns meses, mas com isso perderam o apoio da população camponesa do Sul do país.",
      "os EUA venceram a guerra, mas tiveram de pagar indenizações.",
      "o Vietnã do Norte se rendeu, mas manteve seu governo.",
    ],
    "No feriado do ano-novo lunar (Tet), vietcongues e norte-vietnamitas atacaram de surpresa mais de cem cidades, chegando à embaixada americana em Saigon. Foram rechaçados, mas o governo dos EUA vinha dizendo que a vitória estava próxima. A confiança do público desabou, e Johnson desistiu de disputar a reeleição.",
    "Tet: perderam a batalha, ganharam a opinião pública."),
  vt("vie-14", "facil", "Unicamp", "O massacre de My Lai (1968), revelado à imprensa no ano seguinte, consistiu:",
    [
      "no assassinato de centenas de civis desarmados, incluindo mulheres, crianças e idosos, por soldados norte-americanos.",
      "na execução de centenas de prisioneiros americanos por vietcongues, em represália aos bombardeios sobre o Vietnã do Norte.",
      "no bombardeio de Hanói pela aviação dos EUA.",
      "na morte de estudantes americanos atingidos pela Guarda Nacional em um protesto contra a guerra numa universidade de Ohio.",
    ],
    "Uma companhia do exército americano matou entre 350 e 500 moradores de uma aldeia. O caso foi encoberto por mais de um ano e, quando veio a público, abalou a imagem dos EUA como defensores da liberdade. A morte de estudantes num protesto é outro episódio: a Universidade de Kent, em 1970."),
  vt("vie-15", "facil", "UERJ", "Entre os fatores que explicam a derrota dos Estados Unidos no Vietnã, NÃO se pode incluir:",
    [
      "a inferioridade tecnológica e de armamentos das forças norte-americanas.",
      "a tática de guerrilha em terreno de selva, com túneis e apoio da população.",
      "a pressão da opinião pública americana e internacional contra a guerra.",
      "a impopularidade e a corrupção do governo do Vietnã do Sul.",
    ],
    "Os EUA tinham superioridade tecnológica esmagadora: helicópteros, bombardeiros, napalm. Perderam porque isso valia pouco contra uma guerrilha que se confundia com a população, porque defendiam um governo sem apoio e porque a sociedade americana deixou de aceitar o custo da guerra.",
    "Cuidado com o \"NÃO\" no enunciado: pegadinha clássica de vestibular."),
  vt("vie-16", "facil", "Fuvest", "Em 2 de setembro de 1945, Ho Chi Minh proclamou a independência do Vietnã citando a Declaração de Independência dos Estados Unidos. O episódio revela que:",
    [
      "o movimento vietnamita era, antes de tudo, nacionalista e anticolonial, e buscou inicialmente o reconhecimento dos próprios EUA.",
      "Ho Chi Minh defendia o capitalismo liberal para o Vietnã.",
      "os Estados Unidos apoiaram a independência vietnamita desde o início.",
      "a França já havia abandonado a Indochina.",
    ],
    "Ho Chi Minh era comunista, mas sua prioridade era expulsar o colonizador. Os EUA, porém, preferiram apoiar a França, sua aliada na Europa, e passaram a enxergar o conflito apenas pela lente da Guerra Fria. Muitos historiadores veem aí a raiz do erro americano."),
  vt("vie-17", "facil", "Unicamp", "Em 1963, monges budistas atearam fogo ao próprio corpo nas ruas de Saigon. Os protestos dirigiam-se contra:",
    [
      "o governo de Ngo Dinh Diem, católico e autoritário, que perseguia a maioria budista do Vietnã do Sul.",
      "a presença de tropas chinesas no Vietnã do Norte, vista pelos religiosos como ameaça à independência do país.",
      "a reforma agrária promovida por Ho Chi Minh no Norte, que havia confiscado todas as terras dos mosteiros budistas.",
      "a retirada das tropas francesas.",
    ],
    "Diem, o aliado escolhido pelos EUA, governava com a família, fraudava eleições e discriminava os budistas. As imagens dos monges em chamas correram o mundo. Semanas depois, Diem foi derrubado e morto num golpe de generais, com o conhecimento de Washington. A instabilidade no Sul só aumentou."),
  vt("vie-18", "facil", "UERJ", "Os Acordos de Paris (1973) determinaram:",
    [
      "o cessar-fogo e a retirada das tropas norte-americanas, sem resolver a disputa entre o Norte e o Sul.",
      "a rendição do Vietnã do Norte e o reconhecimento, por Hanói, da independência definitiva do Vietnã do Sul.",
      "a reunificação imediata do país sob governo comunista, com a transferência da capital de Saigon para Hanói.",
      "a divisão do Vietnã em três Estados, um deles neutro e administrado provisoriamente pelas Nações Unidas.",
    ],
    "Os EUA saíram e recuperaram seus prisioneiros, mas as tropas do Norte permaneceram em território do Sul. A guerra entre vietnamitas continuou por mais dois anos, até a queda de Saigon em 1975. Ordem para guardar: Genebra (1954) divide, Paris (1973) tira os EUA, Saigon cai (1975).",
    "Genebra abre, Paris fecha (para os EUA)."),
  vt("vie-19", "facil", "Fuvest", "Dentro dos Estados Unidos, a Guerra do Vietnã teve como um de seus principais efeitos:",
    [
      "o crescimento de movimentos de contestação, que uniram pacifistas, estudantes e a luta pelos direitos civis dos negros.",
      "o fortalecimento duradouro do apoio popular às intervenções militares do país no exterior, confirmado nas eleições de 1968 e de 1972.",
      "o fim do serviço militar para as mulheres.",
      "a aprovação de leis que proibiam protestos de rua.",
    ],
    "O alistamento obrigatório recaía de forma desproporcional sobre jovens pobres e negros. Martin Luther King criticou a guerra em 1967, o boxeador Muhammad Ali recusou-se a servir, e os campi universitários viraram centros de protesto. Depois da derrota, o país ficou relutante em novas intervenções, a chamada \"síndrome do Vietnã\"."),

  // ───────── Descolonização ─────────
  dc("des-05", "facil", "ENEM", "A Conferência de Bandung (1955), na Indonésia, reuniu países recém-independentes da Ásia e da África que defenderam:",
    [
      "o não alinhamento a nenhum dos dois blocos da Guerra Fria e a condenação do colonialismo.",
      "a adesão conjunta ao bloco soviético, visto como aliado natural dos povos que haviam sido colonizados.",
      "a volta ao domínio das antigas metrópoles.",
      "a criação de uma aliança militar com os Estados Unidos, nos moldes da que protegia a Europa Ocidental.",
    ],
    "Bandung deu origem à ideia de Terceiro Mundo como uma terceira posição, nem capitalista nem socialista, e ao Movimento dos Países Não Alinhados. Entre os líderes estavam Nehru (Índia), Nasser (Egito) e Sukarno (Indonésia).",
    "Bandung = a \"banda\" dos que não querem escolher lado."),
  dc("des-06", "facil", "Fuvest", "Entre os fatores internos da descolonização afro-asiática, destaca-se:",
    [
      "a formação de movimentos nacionalistas liderados por elites locais, muitas vezes educadas nas metrópoles.",
      "a crise econômica das potências europeias, endividadas e sem recursos para manter exércitos coloniais no ultramar.",
      "a pressão diplomática dos Estados Unidos, interessados em abrir os mercados coloniais às suas empresas e bancos.",
      "a criação da Organização das Nações Unidas, cuja Carta consagrou o princípio da autodeterminação dos povos.",
    ],
    "Fatores internos são os que nascem dentro das colônias: lideranças como Gandhi, Nehru, Ho Chi Minh e Nkrumah, partidos nacionalistas, revolta contra a exploração e o racismo. As outras três alternativas são fatores externos."),
  dc("des-07", "facil", "Unesp", "A independência da Argélia (1962) diferenciou-se da indiana porque:",
    [
      "foi conquistada após uma longa e violenta guerra contra a França.",
      "ocorreu de forma pacífica, por meio de um plebiscito organizado pela ONU.",
      "resultou da retirada voluntária dos colonos franceses.",
      "foi negociada por Gandhi.",
    ],
    "A Argélia tinha cerca de um milhão de colonos franceses e era tratada como parte da França. A guerra (1954–1962), conduzida pela Frente de Libertação Nacional, teve tortura e terrorismo dos dois lados e provocou uma grave crise política na França."),
  dc("des-08", "facil", "UERJ", "As colônias portuguesas na África, como Angola e Moçambique, só se tornaram independentes em 1975 porque:",
    [
      "a ditadura salazarista se recusava a negociar, e foi preciso que a Revolução dos Cravos (1974) a derrubasse.",
      "eram as colônias mais ricas e industrializadas do continente.",
      "não havia movimentos de libertação nesses territórios.",
      "a ONU proibia a independência de colônias portuguesas.",
    ],
    "Portugal travou longas guerras coloniais desde 1961. O desgaste dessas guerras levou os próprios militares portugueses a derrubar a ditadura em 25 de abril de 1974, e o novo governo reconheceu as independências.",
    "Últimas a sair: as colônias de Portugal, só depois dos Cravos."),
  dc("des-09", "facil", "Unicamp", "A independência da Índia foi acompanhada, em 1947, pela:",
    [
      "divisão do território em dois países, Índia (maioria hindu) e Paquistão (maioria muçulmana).",
      "adesão do país ao bloco soviético.",
      "manutenção de um governador-geral inglês com poder de veto sobre as leis do novo Parlamento indiano.",
      "unificação com a China.",
    ],
    "A partilha provocou a migração forçada de milhões de pessoas e centenas de milhares de mortes em conflitos religiosos. Gandhi era contra a divisão e foi assassinado em 1948 por um extremista hindu que o considerava tolerante demais com os muçulmanos."),
  dc("des-10", "facil", "Fuvest", "EUA e URSS apoiaram, em geral, o fim dos impérios coloniais europeus. Esse apoio se explica porque:",
    [
      "ambos viam nos novos países a oportunidade de ampliar suas áreas de influência econômica e política.",
      "ambos pretendiam abandonar a disputa por áreas de influência e transferir à ONU a tutela dos novos países.",
      "os dois países possuíam extensos impérios coloniais na África e queriam trocá-los por acordos comerciais vantajosos.",
      "a descolonização enfraquecia os dois blocos igualmente.",
    ],
    "Os EUA queriam mercados abertos, sem o monopólio das metrópoles; a URSS apresentava-se como aliada dos povos oprimidos contra o imperialismo. O resultado é que a Guerra Fria entrou nos novos países, como se viu no Vietnã, no Congo e em Angola."),
  dc("des-11", "facil", "Unicamp", "Muitos países africanos enfrentaram guerras civis logo depois da independência. Uma causa estrutural desses conflitos foi:",
    [
      "a manutenção das fronteiras traçadas pelos colonizadores, que reuniam povos rivais e separavam grupos de mesma origem.",
      "a ausência de recursos naturais no continente.",
      "a recusa dos novos governos em participar da ONU.",
      "a decisão de abolir todas as línguas europeias.",
    ],
    "As fronteiras foram desenhadas na Europa, a partir da Conferência de Berlim (1884–85), sem respeitar etnias, línguas e reinos existentes. Os novos Estados herdaram essas linhas, além de economias voltadas à exportação de um ou dois produtos. Somou-se a isso a interferência das superpotências."),
  dc("des-12", "facil", "UERJ", "O ano de 1960 ficou conhecido como \"Ano da África\" porque:",
    [
      "dezessete países africanos conquistaram a independência, a maioria colônias francesas.",
      "terminou o regime do apartheid na África do Sul, com a libertação dos presos políticos do CNA.",
      "foi criada a Organização da Unidade Africana, que reuniu os Estados independentes do continente.",
      "as potências europeias reuniram-se em Berlim para rever a divisão do continente feita no século XIX.",
    ],
    "Em um único ano, países como Senegal, Nigéria, Congo e Costa do Marfim tornaram-se independentes. No mesmo ano, na África do Sul, ocorreu o massacre de Sharpeville, em que a polícia matou dezenas de manifestantes negros: o apartheid estava longe do fim, que só veio em 1994."),

  // ───────── Maio de 1968 ─────────
  m("m68-04", "facil", "ENEM", "Os estudantes franceses de 1968 contestavam principalmente:",
    [
      "o autoritarismo nas universidades e na sociedade, os costumes conservadores e a sociedade de consumo.",
      "a falta de vagas no serviço militar.",
      "o excesso de liberdade sexual na França.",
      "a independência das colônias africanas.",
    ],
    "As reivindicações começaram com questões universitárias (currículos, hierarquia, regras dos alojamentos) e se ampliaram para uma crítica geral: à família tradicional, à moral sexual, ao consumismo, ao governo e à Guerra do Vietnã."),
  m("m68-05", "facil", "Fuvest", "O Maio de 1968 se diferencia de outros protestos estudantis da época porque, na França:",
    [
      "cerca de dez milhões de trabalhadores entraram em greve geral, paralisando o país.",
      "os estudantes tomaram o poder e governaram por alguns meses, até a intervenção do Exército.",
      "o exército aderiu aos manifestantes.",
      "o movimento foi organizado e dirigido desde o início pelo Partido Comunista Francês e pela CGT.",
    ],
    "Foi a união, ainda que breve, entre estudantes e operários que transformou um protesto universitário em crise nacional. O Partido Comunista e os grandes sindicatos, aliás, desconfiaram dos estudantes e preferiram negociar aumentos salariais."),
  m("m68-06", "facil", "Unesp", "Do ponto de vista político imediato, o resultado do Maio de 1968 na França foi:",
    [
      "a vitória do partido de De Gaulle nas eleições de junho, convocadas para encerrar a crise.",
      "a queda do governo e a instalação de um regime socialista apoiado por estudantes e sindicatos.",
      "uma guerra civil que durou dois anos.",
      "a volta da monarquia.",
    ],
    "De Gaulle dissolveu a Assembleia e convocou eleições; a maioria dos franceses, assustada com a desordem, votou a favor do governo. Por isso se diz que 1968 foi uma derrota política e uma vitória cultural. De Gaulle renunciou no ano seguinte, após perder um referendo.",
    "Perdeu na urna, ganhou nos costumes."),
  m("m68-07", "facil", "UERJ", "Entre as consequências duradouras do Maio de 1968 está:",
    [
      "o fortalecimento de movimentos como o feminista, o ambientalista e o de defesa da liberdade sexual.",
      "o fim das universidades públicas na França, substituídas por instituições privadas e confessionais.",
      "a proibição das greves operárias e a dissolução das centrais sindicais que haviam paralisado o país.",
      "o aumento do poder da Igreja sobre a educação, como reação conservadora à agitação estudantil daquele ano.",
    ],
    "O legado de 1968 está na mudança de mentalidade: relações menos autoritárias na escola e na família, novas pautas políticas (mulheres, minorias, meio ambiente) e a reforma das universidades. Os trabalhadores também obtiveram aumentos salariais nos Acordos de Grenelle."),
  m("m68-08", "facil", "Fuvest", "O ano de 1968 foi de contestação em vários países. No Brasil, ele ficou marcado:",
    [
      "pela Passeata dos Cem Mil contra a ditadura e, em dezembro, pelo AI-5, que endureceu o regime.",
      "pelo golpe que derrubou João Goulart e pela edição do primeiro Ato Institucional pelos militares.",
      "pela campanha das Diretas Já, que levou milhões às ruas pelo voto direto para presidente da República.",
      "pela renúncia de Jânio Quadros.",
    ],
    "Após a morte do estudante Edson Luís pela polícia, o movimento estudantil liderou grandes protestos no Rio de Janeiro. A resposta do regime foi o Ato Institucional nº 5, que fechou o Congresso e suspendeu garantias individuais. O golpe é de 1964, a renúncia de 1961 e as Diretas de 1984."),
  m("m68-09", "facil", "Unicamp", "Também em 1968, a Primavera de Praga mostrou que a contestação atingia o bloco socialista. O movimento:",
    [
      "tentou criar um \"socialismo de face humana\" na Tchecoslováquia e foi esmagado por tropas do Pacto de Varsóvia.",
      "derrubou o governo comunista, convocou eleições livres e levou o país a pedir ingresso na OTAN e na Comunidade Europeia.",
      "foi apoiado militarmente pelos Estados Unidos.",
      "defendia a volta do stalinismo.",
    ],
    "O governo de Alexander Dubcek propôs liberdade de imprensa e de opinião sem abandonar o socialismo. Em agosto, tanques soviéticos ocuparam Praga. Assim, 1968 questionou os dois lados da Guerra Fria: o capitalismo de consumo e o socialismo autoritário."),
  m("m68-10", "facil", "UERJ", "\"Sejam realistas, exijam o impossível.\" A frase resume uma novidade do Maio de 1968 em relação aos movimentos de esquerda tradicionais:",
    [
      "a crítica não se limitava à economia e ao poder do Estado; alcançava o cotidiano, a cultura e as relações pessoais.",
      "a defesa da tomada do poder por um partido único e disciplinado.",
      "a prioridade absoluta dada às reivindicações salariais.",
      "o apoio incondicional à União Soviética.",
    ],
    "Os jovens de 1968 criticavam tanto o capitalismo quanto o comunismo burocrático soviético. Não queriam apenas mudar o governo, mas mudar a vida: a escola, a família, o trabalho, a sexualidade. Por isso o movimento é visto como a origem dos chamados \"novos movimentos sociais\"."),
];
