import type { Resumo } from "@/lib/tipos";

/** Resumo de estudo de cada tema, usado no PDF sob medida. A chave é o id do tema. */
export const resumos: Record<string, Resumo> = {
  dutra: {
    essencial: [
      "Eurico Gaspar Dutra, ex-ministro da Guerra do Estado Novo, foi eleito em dezembro de 1945 pelo PSD, com o apoio decisivo de Vargas na reta final. Seu governo inaugura a experiência democrática de 1946 a 1964, mas é uma democracia com limites claros.",
      "A Constituição de 1946 restabeleceu os três poderes independentes, o federalismo, o voto direto e secreto, o pluripartidarismo e o mandato de cinco anos. Reconheceu o direito de greve, porém manteve os sindicatos atrelados ao Estado. Os analfabetos, quase metade dos adultos, continuaram sem votar.",
      "O lado autoritário apareceu cedo. Em 1947 o TSE cassou o registro do PCB, que tivera cerca de 10% dos votos em 1945; em 1948 os parlamentares comunistas perderam os mandatos. O governo interveio em centenas de sindicatos, reprimiu greves com base num decreto anterior à Constituição e manteve o salário mínimo congelado durante todo o mandato.",
      "Na política externa, o alinhamento aos Estados Unidos foi automático: rompimento com a União Soviética (1947), assinatura do TIAR no Rio de Janeiro (1947), visita de Truman e criação da Escola Superior de Guerra (1949). A ajuda econômica esperada em troca não veio, porque a prioridade de Washington era a Europa.",
      "Na economia, o governo começou liberal: abriu as importações e queimou em pouco mais de um ano as reservas acumuladas na guerra. A partir de 1947–48 passou a exigir licença para importar, o que acabou protegendo a indústria nacional. O Plano SALTE (saúde, alimentação, transporte e energia) foi a tentativa de planejamento do período e saiu pouco do papel.",
    ],
    datas: [
      ["1945", "Deposição de Vargas (outubro) e eleição de Dutra (dezembro)"],
      ["1946", "Promulgação da Constituição (setembro)"],
      ["1947", "Cassação do registro do PCB; rompimento com a URSS; TIAR"],
      ["1948", "Cassação dos mandatos comunistas; Plano SALTE enviado ao Congresso"],
      ["1949", "Criação da Escola Superior de Guerra"],
      ["1950", "Vargas vence a eleição presidencial"],
    ],
    conceitos: [
      ["TIAR", "Tratado Interamericano de Assistência Recíproca: um ataque a um país americano seria considerado ataque a todos. É o braço militar do alinhamento aos Estados Unidos."],
      ["PSD, UDN e PTB", "Os três grandes partidos de 1945. PSD e PTB nasceram ligados a Vargas (elites estaduais e sindicatos); a UDN reunia os antigetulistas liberais."],
      ["Democracia limitada", "Expressão usada para a ordem de 1946: eleições e liberdades formais convivendo com exclusão dos analfabetos, sindicatos tutelados e perseguição aos comunistas."],
      ["Plano SALTE", "Plano de gastos públicos em Saúde, Alimentação, Transporte e Energia. Primeira tentativa de planejamento do período, com execução parcial."],
    ],
    cuidado: [
      "A cassação do PCB aconteceu já sob a Constituição democrática de 1946, e não antes dela.",
      "Petrobras, BNDE e Eletrobrás não são de Dutra: são do segundo governo Vargas.",
      "O direito de greve estava na Constituição, mas na prática as greves seguiram reprimidas.",
    ],
  },
  vargas: {
    essencial: [
      "Vargas voltou ao poder em 1951, agora eleito pelo voto direto, pelo PTB e com o apoio do PSP de Adhemar de Barros. Governou sob oposição cerrada da UDN e de boa parte da imprensa, num país dividido sobre o caminho do desenvolvimento.",
      "A disputa central era entre nacionalistas e os chamados \"entreguistas\". Os primeiros queriam industrialização comandada pelo Estado e controle nacional de setores estratégicos; os segundos defendiam abertura ao capital estrangeiro e menos intervenção. O símbolo da vitória nacionalista é a Petrobras (1953), criada com monopólio estatal depois da campanha \"O petróleo é nosso\". O BNDE (1952) e o projeto da Eletrobrás (1954) completam o quadro.",
      "Vargas não foi um nacionalista sem ambiguidades: negociou financiamento com os Estados Unidos e assinou o Acordo Militar de 1952. O discurso endureceu a partir de 1953, quando o crédito norte-americano minguou e a inflação e as greves cresceram (greve dos 300 mil, em São Paulo).",
      "A crise final começa em 1954. O ministro do Trabalho, João Goulart, propõe aumento de 100% no salário mínimo; o Manifesto dos Coronéis força sua saída, mas Vargas concede o aumento em 1º de maio. Em agosto, o atentado da Rua Tonelero contra Carlos Lacerda mata o major Rubens Vaz, e as investigações chegam à guarda pessoal do presidente. Pressionado pelos generais a renunciar, Vargas se suicida em 24 de agosto.",
      "A Carta-Testamento acusa grupos internacionais e nacionais de bloquear suas medidas em favor do povo. A comoção popular voltou-se contra a oposição e, na leitura de muitos historiadores, adiou por dez anos o golpe que se desenhava.",
    ],
    datas: [
      ["1950", "Vargas é eleito presidente"],
      ["1952", "Criação do BNDE; Acordo Militar Brasil–Estados Unidos"],
      ["1953", "Greve dos 300 mil; criação da Petrobras; Jango no Ministério do Trabalho"],
      ["Fev. 1954", "Manifesto dos Coronéis e saída de Jango"],
      ["1º maio 1954", "Aumento de 100% do salário mínimo"],
      ["Ago. 1954", "Atentado da Rua Tonelero (dia 5) e suicídio de Vargas (dia 24)"],
    ],
    conceitos: [
      ["Populismo", "Estilo político em que um líder carismático fala diretamente às massas urbanas, concede direitos e mantém os trabalhadores sob controle, buscando conciliar classes em nome da nação. No Brasil, designa o período 1945–1964."],
      ["Nacional-desenvolvimentismo", "Projeto de industrializar o país com forte ação do Estado e controle nacional dos setores estratégicos."],
      ["UDN", "União Democrática Nacional: partido liberal e antigetulista, de classe média urbana e setores das elites. Sua voz mais agressiva era Carlos Lacerda."],
      ["Carta-Testamento", "Documento deixado por Vargas, que transforma o suicídio em ato político e culpa interesses estrangeiros e seus aliados internos."],
    ],
    cuidado: [
      "A Petrobras é de 1953 (lei de Vargas), não de Dutra nem de JK.",
      "Lacerda sobreviveu ao atentado: quem morreu foi o major Rubens Vaz, da Aeronáutica.",
      "\"Entreguista\" era o apelido dado pelos adversários; ninguém se chamava assim.",
    ],
  },
  jk: {
    essencial: [
      "Juscelino Kubitschek venceu em 1955 com cerca de 36% dos votos, e sua posse só foi garantida pelo \"golpe preventivo\" do general Lott, em 11 de novembro. Governou de 1956 a 1961 com rara estabilidade, apoiado na aliança PSD–PTB e num estilo conciliador, que incluiu anistiar os militares rebeldes de Jacareacanga e Aragarças.",
      "O lema era \"50 anos em 5\". O Plano de Metas reuniu trinta metas em cinco setores (energia, transportes, indústria de base, alimentação e educação), com a maior parte dos recursos em energia e transportes. A meta-síntese foi Brasília, inaugurada em 21 de abril de 1960.",
      "O modelo combinava Estado, capital privado nacional e capital estrangeiro. As multinacionais assumiram os setores mais dinâmicos, sobretudo a indústria automobilística, instalada no ABC paulista; o Estado cuidou da infraestrutura. O país optou pelas rodovias em detrimento das ferrovias.",
      "A Sudene (1959), idealizada por Celso Furtado, tentou enfrentar a desigualdade regional industrializando o Nordeste. Na política externa, a Operação Pan-Americana (1958) pediu aos Estados Unidos um programa de desenvolvimento para a América Latina.",
      "O custo foi alto: inflação crescente, dívida externa maior, concentração de renda e desequilíbrio regional. Em 1959, JK rompeu com o FMI, que exigia corte de gastos, para não interromper as obras. O campo ficou fora do plano, e as Ligas Camponesas ganharam força no Nordeste. Foi também um período de otimismo cultural: bossa nova, Cinema Novo e a Copa de 1958.",
    ],
    datas: [
      ["1955", "Eleição de JK; movimento de 11 de novembro (general Lott)"],
      ["1956", "Posse; Plano de Metas; GEIA e indústria automobilística"],
      ["1958", "Operação Pan-Americana"],
      ["1959", "Criação da Sudene; rompimento com o FMI"],
      ["1960", "Inauguração de Brasília; eleição de Jânio Quadros"],
    ],
    conceitos: [
      ["Plano de Metas", "Programa de investimentos em cinco setores, executado por grupos de trabalho ligados diretamente à Presidência."],
      ["Desenvolvimentismo associado", "Industrialização como meta nacional, mas com as multinacionais liderando os setores mais modernos."],
      ["Substituição de importações", "Produzir no país o que antes vinha de fora. Com JK, passa dos bens de consumo simples para os duráveis (carros, eletrodomésticos)."],
      ["Sudene", "Superintendência do Desenvolvimento do Nordeste: resposta à seca de 1958 e ao atraso regional."],
    ],
    cuidado: [
      "JK não era contra o capital estrangeiro: ele o atraiu. O atrito foi com o FMI, não com as empresas.",
      "Brasília não estava entre as trinta metas originais: era a \"meta-síntese\".",
      "A prioridade foi rodovia e automóvel, não ferrovia.",
    ],
  },
  janio: {
    essencial: [
      "Jânio Quadros elegeu-se em 1960 com votação recorde, usando a vassoura como símbolo do combate à corrupção. Vinha de pequenos partidos, com o apoio da UDN, e seu vice era João Goulart, eleito por outra chapa, já que presidente e vice eram votados separadamente.",
      "Em sete meses desagradou a todos. Na economia foi ortodoxo: desvalorizou a moeda e cortou subsídios ao trigo e ao petróleo (Instrução 204), encarecendo pão e transporte. Na diplomacia adotou a política externa independente: relações com países socialistas, defesa da autodeterminação de Cuba e condecoração de Che Guevara, o que enfureceu a UDN e os militares. Ficou conhecido ainda por proibições moralistas, como a do biquíni e das brigas de galo.",
      "Em 25 de agosto de 1961, um dia depois de Carlos Lacerda denunciar na televisão um suposto plano de golpe, Jânio renunciou, falando em \"forças terríveis\". A interpretação mais aceita é a de uma manobra: esperava voltar nos braços do povo, com mais poderes. O Congresso simplesmente aceitou a renúncia.",
      "Jango estava em missão oficial na China. Os três ministros militares vetaram sua posse, alegando ligação com a esquerda. O governador gaúcho Leonel Brizola reagiu com a Campanha da Legalidade: pela Rede da Legalidade, no rádio, exigiu o cumprimento da Constituição e obteve a adesão do III Exército.",
      "Para evitar a guerra civil, o Congresso aprovou uma emenda que implantou o parlamentarismo. Jango tomou posse em 7 de setembro de 1961, com poderes reduzidos e Tancredo Neves como primeiro-ministro. O sistema funcionou mal, com três gabinetes em quinze meses, e foi derrubado no plebiscito de janeiro de 1963.",
    ],
    datas: [
      ["Jan. 1961", "Posse de Jânio, a primeira em Brasília"],
      ["19 ago. 1961", "Condecoração de Che Guevara"],
      ["25 ago. 1961", "Renúncia"],
      ["Fim de ago. 1961", "Veto militar e Campanha da Legalidade"],
      ["2 set. 1961", "Congresso aprova o parlamentarismo"],
      ["7 set. 1961", "Posse de João Goulart"],
      ["Jan. 1963", "Plebiscito restabelece o presidencialismo"],
    ],
    conceitos: [
      ["Política externa independente", "Relações com todos os países, sem alinhamento automático aos Estados Unidos, mas sem sair do bloco ocidental."],
      ["Campanha da Legalidade", "Movimento liderado por Brizola pela posse do vice, como mandava a Constituição."],
      ["Parlamentarismo de 1961", "Solução de compromisso: o presidente vira chefe de Estado e o governo fica com um primeiro-ministro aprovado pelo Congresso."],
    ],
    cuidado: [
      "Jânio não foi deposto: renunciou. Quem tentou um golpe foram os ministros militares, contra o vice.",
      "A emenda parlamentarista veio antes da posse de Jango: foi a condição para ela.",
      "Jânio era conservador na economia e \"independente\" só na política externa.",
    ],
  },
  jango: {
    essencial: [
      "João Goulart, herdeiro político de Vargas e líder do PTB, governou primeiro sob o parlamentarismo (1961–1963) e depois como presidente pleno, após o plebiscito de janeiro de 1963. Encontrou inflação alta, crescimento em queda e um país politicamente radicalizado.",
      "O Plano Trienal, de Celso Furtado, tentou combinar combate à inflação e crescimento; foi abandonado em meses, sem apoio de sindicatos nem de empresários. Jango passou então a apostar nas Reformas de Base: agrária (com indenização em títulos, o que exigia mudar a Constituição), urbana, bancária, universitária e eleitoral (voto dos analfabetos e elegibilidade de sargentos). A Lei de Remessa de Lucros limitou os ganhos enviados ao exterior pelas empresas estrangeiras.",
      "A sociedade se dividiu. De um lado, CGT, UNE, Ligas Camponesas, parte do PTB e Brizola, pedindo reformas \"na lei ou na marra\". De outro, UDN, grande parte do PSD, empresários reunidos no IPES e no IBAD, a maior parte da imprensa, setores da Igreja e da classe média e a cúpula militar, com apoio do governo dos Estados Unidos.",
      "Março de 1964 concentrou a crise: no dia 13, o Comício da Central do Brasil, com decretos de desapropriação de terras e encampação de refinarias; no dia 19, a Marcha da Família com Deus pela Liberdade, em São Paulo; entre os dias 25 e 27, a revolta dos marinheiros, anistiados pelo governo; no dia 30, o discurso de Jango a sargentos no Automóvel Clube. Para os oficiais, a hierarquia militar estava sendo quebrada.",
      "Em 31 de março, tropas do general Mourão Filho saíram de Minas Gerais. Jango não resistiu, para evitar a guerra civil, e seguiu para o Uruguai. Na madrugada de 2 de abril, o Congresso declarou vaga a Presidência com o presidente ainda no país. O Ato Institucional de 9 de abril iniciou as cassações, e a ditadura durou até 1985. Fala-se em golpe civil-militar pelo apoio decisivo de setores civis.",
    ],
    datas: [
      ["Jan. 1963", "Plebiscito devolve o presidencialismo"],
      ["1963", "Plano Trienal; revolta dos sargentos em Brasília (setembro)"],
      ["13 mar. 1964", "Comício da Central do Brasil"],
      ["19 mar. 1964", "Marcha da Família com Deus pela Liberdade"],
      ["25–27 mar. 1964", "Revolta dos marinheiros"],
      ["31 mar. 1964", "Tropas saem de Minas Gerais"],
      ["9 abr. 1964", "Ato Institucional"],
    ],
    conceitos: [
      ["Reformas de Base", "Conjunto de mudanças estruturais (agrária, urbana, bancária, universitária, eleitoral) defendidas por Jango e pelas esquerdas."],
      ["Golpe civil-militar", "Derrubada executada por militares com apoio ativo de empresários, políticos, imprensa e parte da Igreja e da classe média."],
      ["IPES e IBAD", "Institutos financiados por empresários que fizeram propaganda e articulação contra o governo."],
      ["CGT", "Comando Geral dos Trabalhadores: central sindical que apoiava as reformas, forte nas greves políticas."],
    ],
    cuidado: [
      "A Marcha da Família foi uma resposta ao comício: comício no dia 13, marcha no dia 19.",
      "Jango não renunciou nem foi afastado por impeachment: a Presidência foi declarada vaga com ele no Brasil.",
      "O Plano Trienal é de Celso Furtado, no governo Jango; o Plano de Metas é de JK.",
    ],
  },
  "guerra-fria": {
    essencial: [
      "Guerra Fria é a disputa política, ideológica, econômica e militar entre Estados Unidos (capitalismo) e União Soviética (socialismo), de 1947 a 1991. É \"fria\" porque as duas potências, ambas com armas nucleares, nunca se enfrentaram diretamente: o confronto se deu por corrida armamentista, propaganda, espionagem e guerras em terceiros países. O resultado é o mundo bipolar, dividido em dois blocos.",
      "Do lado norte-americano, a Doutrina Truman (1947) prometeu ajuda a qualquer país ameaçado pelo comunismo, e o Plano Marshall (1947) financiou a reconstrução da Europa Ocidental, contendo a influência soviética e garantindo mercados. A resposta soviética foi o Comecon (1949), conselho de ajuda econômica entre os países socialistas.",
      "Os blocos ganharam alianças militares: a OTAN (1949), liderada pelos Estados Unidos, e o Pacto de Varsóvia (1955), liderado pela União Soviética. A Alemanha foi dividida em duas, e Berlim tornou-se o ponto mais sensível, do bloqueio de 1948–49 à construção do muro em 1961.",
      "Depois da morte de Stalin (1953), Kruschev denunciou seus crimes no XX Congresso (1956) e defendeu a coexistência pacífica: os dois sistemas poderiam competir sem guerra, na economia, na ciência e no espaço. A ideia nasceu do medo da destruição mútua, mas não acabou com as tensões: Hungria (1956), Muro de Berlim (1961) e Crise dos Mísseis em Cuba (1962).",
      "A Crise dos Mísseis foi o momento de maior risco. Terminou com a retirada dos mísseis soviéticos em troca da promessa de não invadir Cuba e da retirada, em segredo, de mísseis norte-americanos da Turquia. Nos anos 1970 veio a distensão (détente), com acordos de limitação de armas; a invasão soviética do Afeganistão (1979) reacendeu o conflito, que terminou com a queda do Muro (1989) e o fim da União Soviética (1991).",
    ],
    datas: [
      ["1947", "Doutrina Truman e Plano Marshall"],
      ["1948–49", "Bloqueio de Berlim"],
      ["1949", "OTAN; Comecon; bomba atômica soviética; revolução na China"],
      ["1950–53", "Guerra da Coreia"],
      ["1955", "Pacto de Varsóvia"],
      ["1956", "Discurso de Kruschev; invasão da Hungria"],
      ["1961", "Muro de Berlim"],
      ["1962", "Crise dos Mísseis"],
    ],
    conceitos: [
      ["Mundo bipolar", "Ordem internacional com dois polos de poder, cada um liderando um bloco de países."],
      ["Contenção", "Estratégia norte-americana de impedir a expansão do comunismo, sem atacar diretamente a União Soviética."],
      ["Coexistência pacífica", "Tese de Kruschev: capitalismo e socialismo podem conviver sem guerra, competindo por outros meios."],
      ["Guerra por procuração", "Conflito local em que cada superpotência apoia um dos lados, sem se enfrentar diretamente (Coreia, Vietnã, Afeganistão)."],
      ["Corrida armamentista e espacial", "Competição por armas nucleares e por feitos no espaço (Sputnik, 1957; chegada à Lua, 1969)."],
    ],
    cuidado: [
      "Plano Marshall é econômico e OTAN é militar; do outro lado, Comecon é econômico e Pacto de Varsóvia é militar.",
      "O Pacto de Varsóvia (1955) veio seis anos depois da OTAN (1949).",
      "Coexistência pacífica não significou fim das crises: o Muro e os mísseis de Cuba são desse período.",
    ],
  },
  vietna: {
    essencial: [
      "O Vietnã fazia parte da Indochina francesa. Liderado por Ho Chi Minh, o Viet Minh, movimento ao mesmo tempo nacionalista e comunista, proclamou a independência em 1945 e derrotou a França na batalha de Dien Bien Phu, em 1954.",
      "Os Acordos de Genebra (1954) dividiram o país provisoriamente no paralelo 17: Norte socialista, com capital em Hanói, e Sul capitalista, com capital em Saigon. Eleições de reunificação estavam marcadas para 1956, mas o governo do Sul, de Ngo Dinh Diem, apoiado pelos Estados Unidos, recusou-se a realizá-las, pois Ho Chi Minh venceria. No Sul surgiu então a guerrilha da Frente Nacional de Libertação, o vietcongue, apoiada pelo Norte.",
      "Os Estados Unidos entraram movidos pela teoria do dominó: se o Vietnã caísse, os vizinhos cairiam em seguida. O incidente do Golfo de Tonkin (1964) serviu de justificativa para a intervenção direta, e o país chegou a ter mais de 500 mil soldados no Vietnã, além de bombardeios maciços, napalm e desfolhantes como o agente laranja.",
      "A guerra virou em 1968. A Ofensiva do Tet, ataque simultâneo a dezenas de cidades do Sul, foi uma derrota militar e uma vitória política dos comunistas: mostrou aos norte-americanos que o fim estava longe. Somaram-se as imagens na televisão, o massacre de My Lai, o alistamento obrigatório e os protestos nas universidades.",
      "Os Estados Unidos perderam porque enfrentavam uma guerrilha que conhecia o terreno, tinha apoio da população, túneis e a Trilha Ho Chi Minh; porque sustentavam um governo impopular; e porque perderam o apoio interno. Nixon adotou a vietnamização (passar a guerra ao exército do Sul), assinou os Acordos de Paris (1973) e retirou as tropas. Saigon caiu em 30 de abril de 1975, e o país foi reunificado sob regime comunista.",
    ],
    datas: [
      ["1945", "Ho Chi Minh proclama a independência"],
      ["1954", "Dien Bien Phu e Acordos de Genebra"],
      ["1964", "Incidente do Golfo de Tonkin"],
      ["1968", "Ofensiva do Tet e massacre de My Lai"],
      ["1973", "Acordos de Paris e saída das tropas dos EUA"],
      ["1975", "Queda de Saigon (30 de abril)"],
    ],
    conceitos: [
      ["Teoria do dominó", "Ideia de que a queda de um país para o comunismo derrubaria os vizinhos em sequência."],
      ["Vietcongue", "Nome dado pelos adversários à guerrilha comunista do Sul (Frente Nacional de Libertação)."],
      ["Trilha Ho Chi Minh", "Rede de caminhos pela selva, passando por Laos e Camboja, que levava homens e armas do Norte ao Sul."],
      ["Vietnamização", "Política de Nixon de retirar as tropas norte-americanas e transferir o combate ao exército sul-vietnamita."],
      ["Guerra televisionada", "Primeira guerra acompanhada diariamente pela TV, o que voltou a opinião pública contra o conflito."],
    ],
    cuidado: [
      "A França perdeu em 1954; os Estados Unidos saíram em 1973; Saigon caiu em 1975. São três momentos diferentes.",
      "O Tet foi derrota militar dos comunistas, mas vitória política.",
      "Viet Minh é o movimento de Ho Chi Minh contra a França; vietcongue é a guerrilha do Sul contra Saigon e os Estados Unidos.",
    ],
  },
  descolonizacao: {
    essencial: [
      "Entre 1945 e 1975, quase todas as colônias europeias da Ásia e da África tornaram-se independentes. O processo resulta da combinação de fatores externos e internos, distinção que a prova costuma cobrar.",
      "Fatores externos: o enfraquecimento econômico e militar das metrópoles depois da Segunda Guerra; a pressão das duas superpotências, contrárias ao velho colonialismo e interessadas em novas áreas de influência; a Carta da ONU, que afirmava a autodeterminação dos povos; e a contradição de ter combatido o nazismo em nome da liberdade mantendo colônias.",
      "Fatores internos: o crescimento dos movimentos nacionalistas, dirigidos muitas vezes por elites formadas na Europa; a experiência de soldados coloniais nas duas guerras mundiais; a exploração e o racismo do sistema colonial; e ideias como o pan-africanismo e a negritude.",
      "Os caminhos variaram. A Índia chegou à independência em 1947 pela desobediência civil de Gandhi, mas com a partilha entre Índia e Paquistão. Gana (1957) abriu a onda africana por negociação. Onde havia muitos colonos ou a metrópole se recusou a sair, houve guerra: Indochina, Argélia (1954–1962) e as colônias portuguesas, que só se libertaram em 1975, depois da Revolução dos Cravos. 1960 é o \"Ano da África\", com dezessete independências.",
      "A Conferência de Bandung (1955) reuniu países afro-asiáticos, condenou o colonialismo e lançou as ideias de Terceiro Mundo e de não alinhamento. A independência política não trouxe autonomia econômica (neocolonialismo), e as fronteiras artificiais herdadas dos colonizadores alimentaram guerras civis. Na África do Sul, o apartheid, regime de segregação racial instituído em 1948, só terminou no início dos anos 1990.",
    ],
    datas: [
      ["1947", "Independência e partilha da Índia"],
      ["1954–62", "Guerra da Argélia"],
      ["1955", "Conferência de Bandung"],
      ["1957", "Independência de Gana"],
      ["1960", "Ano da África; massacre de Sharpeville"],
      ["1975", "Independência de Angola e Moçambique"],
      ["1994", "Mandela é eleito presidente da África do Sul"],
    ],
    conceitos: [
      ["Autodeterminação dos povos", "Direito de cada povo de escolher seu próprio governo. Princípio da Carta da ONU usado contra as metrópoles."],
      ["Terceiro Mundo", "Países que não pertenciam nem ao bloco capitalista desenvolvido nem ao socialista, em geral ex-colônias pobres."],
      ["Não alinhamento", "Recusa de aderir automaticamente a qualquer um dos blocos da Guerra Fria."],
      ["Neocolonialismo", "Dependência econômica que persiste depois da independência política."],
      ["Apartheid", "Segregação racial transformada em lei na África do Sul (1948–1994)."],
      ["Pan-africanismo", "Ideia de unidade e solidariedade entre os povos africanos e seus descendentes."],
    ],
    cuidado: [
      "Movimentos nacionalistas são fator interno; enfraquecimento das metrópoles e pressão das superpotências são fatores externos.",
      "Nem toda independência foi violenta: Índia e Gana foram negociadas; Argélia, Vietnã e Angola tiveram guerra.",
      "As colônias portuguesas foram as últimas: só em 1975.",
    ],
  },
  maio68: {
    essencial: [
      "O Maio de 1968 foi uma onda de protestos iniciada por estudantes franceses, primeiro na Universidade de Nanterre e depois na Sorbonne, em Paris. O contexto não era de crise econômica: a França vivia décadas de crescimento, e o número de universitários havia disparado sem que a universidade mudasse.",
      "Os estudantes contestavam a estrutura autoritária do ensino, o conservadorismo dos costumes, a sociedade de consumo, o governo do general De Gaulle e a Guerra do Vietnã. As palavras de ordem (\"É proibido proibir\", \"A imaginação no poder\") mostram um movimento mais interessado em mudar a vida do que em tomar o Estado.",
      "A repressão policial e as barricadas no Quartier Latin, na noite de 10 de maio, despertaram a solidariedade dos trabalhadores. Seguiu-se uma greve geral de cerca de dez milhões de pessoas, a maior da história francesa, com ocupação de fábricas. O Partido Comunista e a central sindical CGT, surpreendidos, tentaram conduzir a greve para reivindicações salariais.",
      "O governo negociou os Acordos de Grenelle, com aumentos de salário. No fim de maio, De Gaulle dissolveu a Assembleia e convocou eleições, vencidas com folga por seus partidários em junho. Politicamente, portanto, o movimento não tomou o poder; De Gaulle só deixaria o governo em 1969.",
      "As consequências duradouras foram culturais: reforma universitária, fortalecimento do feminismo, da liberdade sexual, do ambientalismo e da contracultura, e relações menos hierárquicas na família, na escola e no trabalho. O ano de 1968 foi de contestação em vários países: Primavera de Praga, na Tchecoslováquia; massacre de Tlatelolco, no México; protestos contra a guerra nos Estados Unidos; e, no Brasil, a Passeata dos Cem Mil, seguida do AI-5 em dezembro.",
    ],
    datas: [
      ["22 mar. 1968", "Ocupação em Nanterre"],
      ["10–11 mai. 1968", "Noite das barricadas"],
      ["13 mai. 1968", "Começo da greve geral"],
      ["27 mai. 1968", "Acordos de Grenelle"],
      ["30 mai. 1968", "De Gaulle dissolve a Assembleia"],
      ["Jun. 1968", "Vitória gaullista nas eleições"],
    ],
    conceitos: [
      ["Contracultura", "Recusa dos valores dominantes (consumo, autoridade, moral tradicional) por parte da juventude dos anos 1960."],
      ["Sociedade de consumo", "Alvo dos estudantes: uma vida organizada em torno de trabalhar para comprar."],
      ["Acordos de Grenelle", "Negociação entre governo, patrões e sindicatos que concedeu aumentos salariais durante a greve."],
      ["Primavera de Praga", "Tentativa de reformar o socialismo na Tchecoslováquia, esmagada pela invasão soviética em agosto de 1968."],
    ],
    cuidado: [
      "O movimento não derrubou De Gaulle em 1968: ele venceu as eleições de junho.",
      "O Partido Comunista Francês não liderou os estudantes; de início foi hostil a eles.",
      "A principal mudança foi nos costumes, não no governo.",
    ],
  },
  figuras: {
    essencial: [
      "Vietnã e União Soviética. Ho Chi Minh liderou a independência do Vietnã contra a França e o Vietnã do Norte contra os Estados Unidos; morreu em 1969, antes da vitória. Nikita Kruschev sucedeu Stalin, denunciou seus crimes em 1956, defendeu a coexistência pacífica e enfrentou Kennedy na Crise dos Mísseis; foi afastado em 1964.",
      "Chile. Salvador Allende, médico socialista, foi eleito em 1970 e tentou a \"via chilena ao socialismo\", por eleições e dentro da lei; nacionalizou o cobre. Foi derrubado em 11 de setembro de 1973 pelo general Augusto Pinochet, com apoio dos Estados Unidos, e morreu no palácio de La Moneda. Pinochet governou como ditador até 1990, combinando repressão violenta e política econômica neoliberal.",
      "Índia e África do Sul. Mahatma Gandhi conduziu a independência da Índia (1947) pela não violência e pela desobediência civil, como na Marcha do Sal (1930); foi assassinado em 1948. Nelson Mandela combateu o apartheid, ficou 27 anos preso, saiu em 1990 e tornou-se, em 1994, o primeiro presidente negro da África do Sul, defendendo a reconciliação.",
      "China. Mao Tsé-Tung liderou a revolução que criou a República Popular da China em 1949, apoiada nos camponeses e não nos operários. Governou até 1976, com o Grande Salto Adiante, que provocou uma fome devastadora, e a Revolução Cultural (a partir de 1966).",
      "Estados Unidos. Rosa Parks recusou-se a ceder o lugar no ônibus a um branco em Montgomery (1955), dando início a um boicote de mais de um ano. Martin Luther King, pastor inspirado em Gandhi, liderou a luta não violenta pelos direitos civis, fez o discurso \"Eu tenho um sonho\" (1963), recebeu o Nobel da Paz (1964) e foi assassinado em 1968. Malcolm X, ligado à Nação do Islã, defendia o orgulho negro e a autodefesa \"por todos os meios necessários\"; depois da viagem a Meca, moderou suas posições e foi assassinado em 1965.",
    ],
    datas: [
      ["1930", "Marcha do Sal (Gandhi)"],
      ["1949", "Revolução Chinesa (Mao)"],
      ["1955", "Rosa Parks e o boicote de Montgomery"],
      ["1963", "\"Eu tenho um sonho\" (Luther King)"],
      ["1965", "Assassinato de Malcolm X"],
      ["1973", "Golpe no Chile: cai Allende, sobe Pinochet"],
      ["1994", "Mandela presidente"],
    ],
    conceitos: [
      ["Desobediência civil", "Descumprir abertamente uma lei injusta, sem violência e aceitando a punição, para pressionar por sua mudança."],
      ["Via chilena ao socialismo", "Projeto de Allende: chegar ao socialismo pelo voto e pelas instituições, sem revolução armada."],
      ["Direitos civis", "Luta da população negra dos Estados Unidos contra a segregação legal e pelo direito de voto."],
      ["Apartheid", "Regime de segregação racial da África do Sul, combatido por Mandela."],
    ],
    cuidado: [
      "Allende foi eleito e veio antes; Pinochet deu o golpe e veio depois.",
      "Luther King defendia a integração e a não violência; Malcolm X, o orgulho negro e a autodefesa.",
      "Gandhi atuou na Índia; Mandela, na África do Sul. Gandhi viveu na África do Sul na juventude, o que confunde.",
    ],
  },
};
